### ISSUE TITLE
"Error: failed to provision VM: Process exited with: 1. Reason was: ()"

### ISSUE THREAD

**Issue by stwomack** [vmware-archive/pcfdev#102]
Same issue as [79](https://github.com/pivotal-cf/pcfdev/issues/79#issuecomment-233331643)
- [[ 9 -lt 50 ]]
- counter=80
- [[ 20 = 0 ]]
- sleep 1
  ++ started_service_count
  ++ started_services
  ++ monit_summary
  ++ grep -E '(running|accessible|Timestamp changed|PID changed)'
  ++ wc -l
  ++ tr -d \'
  ++ awk '{print $2}'
  +++ /var/vcap/bosh/bin/monit summary
  ++ output='The Monit daemon 5.2.5 uptime: 2m

Process '\''pcfdev-nginx'\''              running
Process '\''mariadb_ctrl'\''              running
Process '\''galera-healthcheck'\''        running
Process '\''gra-log-purger-executable'\'' running
Process '\''garden'\''                    running
Process '\''etcd'\''                      running
Process '\''auctioneer'\''                running
Process '\''cc_uploader'\''               running
Process '\''converger'\''                 running
Process '\''file_server'\''               running
Process '\''nsync_listener'\''            running
Process '\''nsync_bulker'\''              running
Process '\''rep'\''                       running
Process '\''route_emitter'\''             running
Process '\''ssh_proxy'\''                 running
Process '\''stager'\''                    running
Process '\''tps_listener'\''              running
Process '\''tps_watcher'\''               running
Process '\''bbs'\''                       running
Process '\''syslog_drain_binder'\''       running
Process '\''consul_agent'\''              running
Process '\''blobstore_nginx'\''           running
Process '\''blobstore_url_signer'\''      running
Process '\''metron_agent'\''              running
Process '\''nats'\''                      running
Process '\''route_registrar'\''           running
Process '\''cloud_controller_clock'\''    running
Process '\''cloud_controller_ng'\''       running
Process '\''cloud_controller_worker_local_1'\'' running
Process '\''cloud_controller_worker_local_2'\'' running
Process '\''nginx_cc'\''                  running
Process '\''cloud_controller_migration'\'' running
Process '\''cloud_controller_worker_1'\'' running
Process '\''uaa'\''                       running
Process '\''doppler'\''                   running
Process '\''gorouter'\''                  running
Process '\''loggregator_trafficcontroller'\'' running
Process '\''syslog-configurator'\''       running
Process '\''process-watcher'\''           running
Process '\''cf-redis-broker'\''           running
Process '\''broker-nginx'\''              running
Process '\''cf-redis-route-registrar'\''  running
Process '\''cf-mysql-broker'\''           running
Process '\''cf-mysql-route-registrar'\''  running
Process '\''quota-enforcer'\''            running
Process '\''rabbitmq-broker'\''           running
Process '\''rabbitmq-broker-route-registrar'\'' running
Process '\''rabbitmq-management-route-registrar'\'' running
Process '\''rabbitmq-server'\''           running
System '\''system_localhost'\''           running'
++ [[ The Monit daemon 5.2.5 uptime: 2m

Process 'pcfdev-nginx'              running
Process 'mariadb_ctrl'              running
Process 'galera-healthcheck'        running
Process 'gra-log-purger-executable' running
Process 'garden'                    running
Process 'etcd'                      running
Process 'auctioneer'                running
Process 'cc_uploader'               running
Process 'converger'                 running
Process 'file_server'               running
Process 'nsync_listener'            running
Process 'nsync_bulker'              running
Process 'rep'                       running
Process 'route_emitter'             running
Process 'ssh_proxy'                 running
Process 'stager'                    running
Process 'tps_listener'              running
Process 'tps_watcher'               running
Process 'bbs'                       running
Process 'syslog_drain_binder'       running
Process 'consul_agent'              running
Process 'blobstore_nginx'           running
Process 'blobstore_url_signer'      running
Process 'metron_agent'              running
Process 'nats'                      running
Process 'route_registrar'           running
Process 'cloud_controller_clock'    running
Process 'cloud_controller_ng'       running
Process 'cloud_controller_worker_local_1' running
Process 'cloud_controller_worker_local_2' running
Process 'nginx_cc'                  running
Process 'cloud_controller_migration' running
Process 'cloud_controller_worker_1' running
Process 'uaa'                       running
Process 'doppler'                   running
Process 'gorouter'                  running
Process 'loggregator_trafficcontroller' running
Process 'syslog-configurator'       running
Process 'process-watcher'           running
Process 'cf-redis-broker'           running
Process 'broker-nginx'              running
Process 'cf-redis-route-registrar'  running
Process 'cf-mysql-broker'           running
Process 'cf-mysql-route-registrar'  running
Process 'quota-enforcer'            running
Process 'rabbitmq-broker'           running
Process 'rabbitmq-broker-route-registrar' running
Process 'rabbitmq-management-route-registrar' running
Process 'rabbitmq-server'           running
System 'system_localhost'           running = _\e\r\r\o\r\ \c\o\n\n\e\c\t\i\n\g\ \t\o\ \t\h\e\ \m\o\n\i\t\ \d\a\e\m\o\n_ ]]
++ echo 'The Monit daemon 5.2.5 uptime: 2m

Process '\''pcfdev-nginx'\''              running
Process '\''mariadb_ctrl'\''              running
Process '\''galera-healthcheck'\''        running
Process '\''gra-log-purger-executable'\'' running
Process '\''garden'\''                    running
Process '\''etcd'\''                      running
Process '\''auctioneer'\''                running
Process '\''cc_uploader'\''               running
Process '\''converger'\''                 running
Process '\''file_server'\''               running
Process '\''nsync_listener'\''            running
Process '\''nsync_bulker'\''              running
Process '\''rep'\''                       running
Process '\''route_emitter'\''             running
Process '\''ssh_proxy'\''                 running
Process '\''stager'\''                    running
Process '\''tps_listener'\''              running
Process '\''tps_watcher'\''               running
Process '\''bbs'\''                       running
Process '\''syslog_drain_binder'\''       running
Process '\''consul_agent'\''              running
Process '\''blobstore_nginx'\''           running
Process '\''blobstore_url_signer'\''      running
Process '\''metron_agent'\''              running
Process '\''nats'\''                      running
Process '\''route_registrar'\''           running
Process '\''cloud_controller_clock'\''    running
Process '\''cloud_controller_ng'\''       running
Process '\''cloud_controller_worker_local_1'\'' running
Process '\''cloud_controller_worker_local_2'\'' running
Process '\''nginx_cc'\''                  running
Process '\''cloud_controller_migration'\'' running
Process '\''cloud_controller_worker_1'\'' running
Process '\''uaa'\''                       running
Process '\''doppler'\''                   running
Process '\''gorouter'\''                  running
Process '\''loggregator_trafficcontroller'\'' running
Process '\''syslog-configurator'\''       running
Process '\''process-watcher'\''           running
Process '\''cf-redis-broker'\''           running
Process '\''broker-nginx'\''              running
Process '\''cf-redis-route-registrar'\''  running
Process '\''cf-mysql-broker'\''           running
Process '\''cf-mysql-route-registrar'\''  running
Process '\''quota-enforcer'\''            running
Process '\''rabbitmq-broker'\''           running
Process '\''rabbitmq-broker-route-registrar'\'' running
Process '\''rabbitmq-management-route-registrar'\'' running
Process '\''rabbitmq-server'\''           running
System '\''system_localhost'\''           running'
- started=50
- [[ 50 -lt 50 ]]
- echo '50 out of 50 running'
  ++ cc_status_code local.pcfdev.io
  ++ curl -s -I -o /dev/null -w '%{http_code}' -H 'Host: api.local.pcfdev.io' http://localhost/v2/info
- [[ 200 != 200 ]]
  ++ uaa_response local.pcfdev.io
  ++ curl -s -H 'Host: login.local.pcfdev.io' http://localhost/healthz
- [[ ok != \o\k ]]
- cf api https://api.local.pcfdev.io --skip-ssl-validation
  Setting api endpoint to https://api.local.pcfdev.io...
  OK

API endpoint:   https://api.local.pcfdev.io (API version: 2.54.0)
Not logged in. Use 'cf login' to log in.
- cf auth admin admin
  API endpoint: https://api.local.pcfdev.io
  Authenticating...
  OK
  Use 'cf target' to view or set your target org and space
- cf create-org pcfdev-org
  Creating org pcfdev-org as admin...
  OK
  Org pcfdev-org already exists
- cf create-space pcfdev-space -o pcfdev-org
  Creating space pcfdev-space in org pcfdev-org as admin...
  OK
  Assigning role SpaceManager to user admin in org pcfdev-org / space pcfdev-space as admin...
  FAILED
  Error performing request: Put https://api.local.pcfdev.io/v2/spaces/ba7114ec-fd46-499a-9903-4ab26d05b8a9/managers/381ddd50-078d-40b3-884f-726828c91493: dial tcp: i/o timeout
  TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

**Comment by sclevine** [comment]
Sorry for the delay.

Even though you aren't behind a proxy, your issue does seem similar to #79 with the sporadic `i/o timeout`s in the `run.log`. Can you try using the `--natdnshostresolver1` fix described in that issue?

The next release (which should be cut in the next few days) will also include this fix.

**Comment by sclevine** [comment]
Hi @stwomack,

Can you let us know if 0.18.0 fixes your issue?

**Comment by stwomack** [comment]
Traveling today; let you know asap 

Steve Womack

**Comment by stwomack** [comment]
Fixed ! 👍
