### ISSUE TITLE
pcfdev on azure

### ISSUE THREAD

**Issue by vcherukuri** [vmware-archive/pcfdev#106]
Is it possible to install pcfdev on Microsoft Azure VM. I tried deploying pcfdev on Azure VM, when tried 
cf dev start , it shows that the VM is running but doesnt show up any services are running on the VM.
and i could not login to pcfdev 
cf login -a api.local.pcfdev.io

**Comment by sclevine** [comment]
Hi @vcherukuri,

Let's address this in #105.
