### ISSUE TITLE
Controlling the name of the pcfdev VM

### ISSUE THREAD

**Issue by luckyabhishek** [vmware-archive/pcfdev#107]
Can we have a way to control the name of the pcfdev VM. Right now I can only start one VM in my box by using 

`cf dev start`

I need 2 VMs since I work behind a proxy while in corporate network while I work without a proxy sometimes to figure out if the issues is because of the proxy. 

Would be nice to have something like

`cf dev start nameofvm`

**Comment by sclevine** [comment]
This is on the roadmap, with exactly the syntax you describe. I expect it to be released in a month or two.
