### ISSUE TITLE
Inconsistent Defaults Between Documentation and Online Help

### ISSUE THREAD

**Issue by mcowger** [vmware-archive/pcfdev#108]
The online help for pcfdev-18 states the default services are:

`Default: redis, rabbitmq`

whereas the [release notes](https://github.com/pivotal-cf/pcfdev/releases/tag/v0.18.0) state that:

> By default, MySQL, Redis, and RabbitMQ are started.

In fact, the documentation is correct....the online cf dev help should the updated to be correct.

**Comment by sclevine** [comment]
Hi @mcowger,

Sorry for the confusion! The MySQL service is now part of the OSS build of PCF Dev, and it cannot be disabled in the commercial version. Internal VM components require MySQL, so disabling the service broker doesn't result in significant memory savings.

I will update the `cf dev help` text in the next release to reduce confusion.

Thanks for pointing this out,
Stephen
