### ISSUE TITLE
Missing word on "services" page of Apps Manager

### ISSUE THREAD

**Issue by rseroter** [vmware-archive/pcfdev#110]
![pcfdev](https://cloud.githubusercontent.com/assets/1229614/17158355/8d27a82c-534a-11e6-9ed5-64a7ed6d0cb5.png)

There appears to be a missing word at the end of this sentence.

Reproduce: Go to Apps Manager, view space, hit "services" sub tab.

**Comment by paulc4** [comment]
Also an icon is missing in the top-left hand corner?

![screen shot 2016-07-29 at 3 44 54 pm](https://cloud.githubusercontent.com/assets/1644418/17238959/99ed1bd6-55a3-11e6-9661-b60aac930f04.png)

**Comment by ekcasey** [comment]
@rseroter Thanks for the report! We found the configuration error and it should be fixed in the next release.

@paulc4 Which version of pcfdev are you running?

**Comment by sclevine** [comment]
Fixed in 0.20.0.

**Comment by sclevine** [comment]
(Also worth noting that you can use `cf dev trust` or `cf dev start -k` to remove the browser SSL warnings.)
