### ISSUE TITLE
Unable to start 0.18.0 pcfdev

### ISSUE THREAD

**Issue by rnadler** [vmware-archive/pcfdev#111]
OS: Windows 10
Virtualbox Version 5.1.2 r108956
PCF Dev version 0.18.0 (CLI: 5c9e186, OVA: 0.219.0)

```
>cf dev start
Using existing image.
Allocating 4096 MB out of 32725 MB total system memory (19640 MB free).
Importing VM...
FAILED
PCF Dev is in an invalid state. Please run 'cf dev destroy'.

>
```

There are no Virtualbox logs created which indicates it is never even getting to the VM startup..  Adding the -v (CF_TRACE) command line arg does not provide any additional diagnostics. Are there any cf logs that would indicate the root cause of the startup failure?

Note: Works fine with Virtualbox-5.1.2 on Win7-Enterprise-SP1. 

Thanks!

BTW: The resulting VM has the configuration issue shown below but starts OK manually.
![image](https://cloud.githubusercontent.com/assets/948978/17160900/92c71688-535d-11e6-9b25-7b353cd9f228.png)

**Comment by sclevine** [comment]
Hi @rnadler,

Thanks for the report! Sorry that you're having trouble. I have a few questions for you:
1. Do you have enough free disk space for Virtualbox to import the OVA?
2. Can you run other 64-bit VMs in Virtualbox on Windows 10?
3. Are you running Windows 10 in a VM?
4. Do you know if you have the Windows 10 native hypervisor (Hyper-V) enabled?

-Stephen

**Comment by rnadler** [comment]
Hi Stephen,
1. Yes, plenty. As noted, I can start the VM manually after the import completes. See screenshot below.
2. Yes. I typically have 2 or 3 other 64-bit VMs running. As an experiment I tried starting pcfdev with no other VMs running -- same failed result.
3. No, Win10 is on bare metal.
4. Yes, hypervisor is enabled.

What conditions would cause the "FAILED" response?

Thanks,

![image](https://cloud.githubusercontent.com/assets/948978/17197303/8077ae52-5420-11e6-887a-7939ff1f90f7.png)

**Comment by clfsoft** [comment]
you can ssh to the vm (local.pcfdev.io or 192.168.11.11) using vagrant/vagrant
and check the log file ( /var/pcfdev/run.log ) for the details

i got the same error and  found the failure cause is the (post-run)
solved by  rerun the  (/var/pcfdev/post-run) with the parameter in the logfile

**Comment by RawSanj** [comment]
@rnadler I faced the same issue when upgraded from previous PFC Dev version (which used Powershell script and vagrant).

The problem was with the Network Adapter. Like you I was also able to run VM from Virtualbox but not able to run from `cf dev start`.

To fix this:
1. Remove all existing Host only network adapters, try [this](http://stackoverflow.com/a/32093978/5702727).
2. Destory your previous vm by running `cf dev destroy` and create again by `cf dev start`.This will create VM along with new `VirtualBox Host-Only Ethernet Adapter #Number`.
3. Once you can run VM with below setting (refer screenshot) from  VirtualBox then you'd be able to run `cf dev start` as well. In case you cannot, repeat step 1-2.

![image](https://cloud.githubusercontent.com/assets/13738294/17432382/7eee231a-5b1c-11e6-9d9a-cdae8c5b6b19.png)

**Comment by rnadler** [comment]
Updated to: PCF Dev version 0.19.0 (CLI: 27d4cda, OVA: 0.234.0)

Now seeing this:
...
Importing VM...
FAILED
**Error: 192.168.59.31 is not one of the allowed PCF Dev ips.**
...

@RawSanj, is this the problem your solution resolved?

Thanks.

**Comment by RawSanj** [comment]
@rnadler I didn't get this **Error: 192.168.59.31 is not one of the allowed PCF Dev ips.** specific error.

But have you tried the above solution?

**Comment by ekcasey** [comment]
What is the IP address of the hostonly interface attached to the pcfdev vm? If you run

```
VBoxManage showvminfo pcfdev-v0.234.0
```

Then find the name of the attached hostonly network interface (i.e VirtualBox Host-Only Ethernet Adapter #1). Then run 

```
VBoxManage list hostonlyifs
```

This should allow you to see the IP range of this network.

**Comment by rnadler** [comment]
Problem solved. 

Had two virtual network interfaces with the same name but different IP addresses. Removed the extraneous interface per @RawSanj's instructions (hostonlyif remove) and pcfdev now starts up correctly.

Thanks everybody!

FYI: Now running Windows 10 Anniversary Addition (Version 10.0.14393 Build 14393)

**Comment by psadineni** [comment]
I am getting file system issues while downloading the VM's by default it is storing in /home/...
Can we change the filesystem path and mention our own FS path to download the VM's
