### ISSUE TITLE
Is it possible to change the path to the config file?

### ISSUE THREAD

**Issue by raptus93** [vmware-archive/pcfdev#114]
Hey guys,

if I try changing CF_HOME to my path, it works for the cf cli, but pcfdev still seems to try to go to the oldpath/plugins/config.json. Is there a way to change the path? May it be a good idea, to refer to the same variable?

Regards,
P

**Comment by sclevine** [comment]
The PCF Dev cf CLI plugin doesn't have any control over where it's installed. Executing the plugin directly just issues a `cf install-plugin` on itself for convenience. The cf CLI is responsible for reading `CF_HOME` and placing the plugin in the location specified.

**Comment by raptus93** [comment]
Ok, I see. I did observe some strange behavior, but I think this is not the right spot for this issue. Sorry and out!

**Comment by mdelillo** [comment]
FYI you can change where plugins are installed by setting [CF_PLUGIN_HOME](https://docs.cloudfoundry.org/cf-cli/use-cli-plugins.html#plugin-directory)
