### ISSUE TITLE
Issue in installing pcfdev1.8 for windows

### ISSUE THREAD

**Issue by suchakra012** [vmware-archive/pcfdev#115]
Hi,

I am installing the pcfdev-v0.18.0 for windows 7. However , on executing the command ->
./pcfdev-v0.18.0+PCF1.7.0-windows.exe

I got the following error 

**Installing plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2**

I have cf install & running. I also tried running with the command  cf install-plugin <.exe file>, but the result is same.

Could , some one please guide where I am making wrong?

Thanks.

**Comment by mssh2001** [comment]
same failure  as mine. 
commands used as follows 

PS C:\CloudFoundry> $PSVersionTable

Name                           Value

---

PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18444
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

PS C:\CloudFoundry> vagrant --version
Vagrant 1.8.5
PS C:\CloudFoundry> vboxmanage --version
5.1.2r108956
PS C:\CloudFoundry> cf --version
cf version 6.20.0+25b1961-2016-06-29
PS C:\CloudFoundry> .\pcfdev-v0.18.0+PCF1.7.0-windows.exe
Installing plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2
PS C:\CloudFoundry>

**Comment by sclevine** [comment]
Could each of you provide the output of `cf install-plugin ./pcfdev-v0.18.0+PCF1.7.0-windows.exe`?

Also, can you confirm that you can install other cf CLI plugins?

**Comment by suchakra012** [comment]
Hello sclevine ,

Please find the o/p : ->

$ cf install-plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at you           r own risk.**

Do you want to install the plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe? (y or n)> y

Installing plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2

Also, cf CLI plugins are working perfectly, though I haven't installed any plugin.

$ cf plugins
Listing Installed Plugins...
OK

Plugin Name   Version   Command Name   Command Help

Is their any bug on the 0.18 release ..

Regards,
Suman

**Comment by sclevine** [comment]
It seems like there was a regression in the cf CLI related to plugins that they fixed in 6.20.0. As @mssh2001 is running 6.20.0, I wonder if this fix actually ended up breaking compatibility with our plugin. Could each of you install cf CLI 6.19.0 and 6.21.0 and see if it works with either of them?

**Comment by suchakra012** [comment]
I will install CLI 6.19.0 /6.21.0 & will let you know the result.

**Comment by suchakra012** [comment]
Hi,

I tried installing with CF CLI version 6.16.1. But getting the same error:
cf -v
cf version 6.16.1+924508c-2016-02-26

C:\pcfdev-v0.18.0+PCF1.7.0-windows.exe
Installing plugin C:\Users\ECTYSAN\Documents\pcfdev\pcfdev-v0.18.0+PCF1.7.0-wind
ows.exe...
FAILED
exit status 2

I think the issue might not be with the CLI version.

**Comment by mssh2001** [comment]
let me update my installations with cf version going through from v6.17 to v6.21 . it means it does not work with the same failed information as follows 
PS C:\pcfdev> cf version
cf version 6.21.0+dff2cf8-2016-07-27
PS C:\pcfdev> .\pcfdev-v0.18.0+PCF1.7.0-windows.exe
Installing plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2
PS C:\pcfdev> cf install-plugin .\pcfdev-v0.18.0+PCF1.7.0-windows.exe

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin .\pcfdev-v0.18.0+PCF1.7.0-windows.exe? (y or n)> y

Installing plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2
PS C:\pcfdev> cf version
cf version 6.19.0+b29b4e0-2016-06-08
PS C:\pcfdev> cf install-plugin .\pcfdev-v0.18.0+PCF1.7.0-windows.exe

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin .\pcfdev-v0.18.0+PCF1.7.0-windows.exe? (y or n)> y

Installing plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2
PS C:\pcfdev> .\pcfdev-v0.18.0+PCF1.7.0-windows.exe
Installing plugin pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2
PS C:\pcfdev> cf version
cf version 6.18.0+b22884b-2016-05-10
PS C:\pcfdev> cf install-plugin .\pcfdev-v0.18.0+PCF1.7.0-windows.exe

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin .\pcfdev-v0.18.0+PCF1.7.0-windows.exe? (y or n)> y

Installing plugin ./pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2
PS C:\pcfdev> cf version
cf version 6.17.1+2ca614d-2016-05-02
PS C:\pcfdev> cf install-plugin .\pcfdev-v0.18.0+PCF1.7.0-windows.exe

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin .\pcfdev-v0.18.0+PCF1.7.0-windows.exe? (y or n)> y

Installing plugin ./pcfdev-v0.18.0+PCF1.7.0-windows.exe...
FAILED
exit status 2
PS C:\pcfdev>

**Comment by mssh2001** [comment]
and we did not find what the error code "exit status 2 " means in google :)

**Comment by suchakra012** [comment]
Any update on this issue ? It seems it is persistent across every other CLI versions.

I also tried with pcfdev-v0.17.0 release, but getting the same error.

**Comment by sclevine** [comment]
I am not able to replicate this issue in any version of Windows. Can you see if you experience this issue while installing [other cf CLI plugins](https://plugins.cloudfoundry.org/)? (Install the plugins from your disk, not from the plugin repository.)

**Comment by suchakra012** [comment]
Which cf version are you using here??

Get Outlook for Androidhttps://aka.ms/ghei36

On Mon, Aug 1, 2016 at 9:54 PM +0530, "Stephen Levine" <notifications@github.com<mailto:notifications@github.com>> wrote:

Could each of you provide the output of cf install-plugin ./pcfdev-v0.18.0+PCF1.7.0-windows.exe?

Also, can you confirm that you can install other cf CLI plugins?

##

**Comment by suchakra012** [comment]
I am trying multiple times with the pcf version on Windows, but getting same error with Exit status 2.

Even I tried with latest pcf version, but no result :(

C:\workspace>".\pcfdev-v0.19.0+PCF1.7.12-windows.exe"
Installing plugin pcfdev-v0.19.0+PCF1.7.12-windows.exe...
FAILED
exit status 2

C:\workspace>cf install-plugin "pcfdev-v0.19.0+PCF1.7.12-windows.exe"

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin pcfdev-v0.19.0+PCF1.7.12-windows.exe? (y or n)> y

Installing plugin pcfdev-v0.19.0+PCF1.7.12-windows.exe...
FAILED
exit status 2

I am using latest CF version 

C:\Users\ECTYSAN>cf -v  
cf version 6.21.0+dff2cf8-2016-07-27

**Comment by mdelillo** [comment]
@suchakra012 We were able to reproduce when we tried to install the plugin as a non-admin user and fix it by installing as an admin user. Is your user an administrator?

We've added a story to allow the plugin to be installed by non-admin users.

**Comment by suchakra012** [comment]
@mdelillo .. Tried with administrator in command prompt & run the .exe file . But it is throwing the same error.

**Comment by mdelillo** [comment]
@suchakra012 Ok, we've added a story to the top of our backlog to investigate this some more. Hopefully fixing the issue we discovered will also fix the issue you are experiencing.

**Comment by traelrawls** [comment]
@suchakra012 We've investigated the issue and discovered that the command:

`wmic computersystem get numberofprocessors`

will deny access without proper permissions. If you run the command and it outputs access denied, then you can attempt to get proper permissions on your account. Otherwise it will be fixed in the next release.

**Comment by sclevine** [comment]
Note that the plugin runs that command to get the number of host CPU cores. Apparently access to that information can be denied by restrictive user account settings on the host. If that command fails, the next release (0.20.0) will install successfully, but you will have to set the number of cores manually with `-c` if you want the PCF Dev VM to take advantage of more than a single processor core.

**Comment by sclevine** [comment]
Fixed in 0.20.0. Please re-open if you continue to experience this issue.
