### ISSUE TITLE
pcf dev doesn't delete apps-manager-venerable app after restart

### ISSUE THREAD

**Issue by clfsoft** [vmware-archive/pcfdev#118]
when you restart the vm by cf dev stop & cf dev start
you always see the apps-manager-venerable  even you delete the app before cf dev stop.

**Comment by mdelillo** [comment]
Thanks for reporting this, we created a story to address this. We will let you know when this change comes out in a future release.

**Comment by sclevine** [comment]
Fix released with 0.20.0.
