### ISSUE TITLE
Issue connecting after disconnecting from VPN

### ISSUE THREAD

**Issue by Jackman3005** [vmware-archive/pcfdev#120]
It appears that connecting to our client's VPN and disconnecting prevents any further connection with PCF DEV.  `cf dev status` reports that the VM is running and it looks like that in VirtualBox as well. When we are on the VPN our client's security settings prevent us from viewing the local.pcfdev.io url and it appears any 192.\* url in general. Not exactly sure if there is a problem with PCF DEV, the VPN software, or something specific with our client's setup, but I thought I'd provide a data point. A full restart of our workstation does appear to fix the issue until the next VPN connection.  I also believe that we had been on and off the VPN before initially installing and it worked upon initial install with the VPN disconnected. 

Software used:
Cisco AnyConnect Secure Mobility Client Version 3.1.05187
VirtualBox version 5.1.2 r108956
PCF Dev version 0.19.0 (CLI: 27d4cda, OVA: 0.234.0)

**Comment by sclevine** [comment]
Can you configure your VPN client to prevent connections to the 192.168.11.0 subnet from going through the VPN?

If your VPN client adjusts your route table to route 192.168.11.0 packets through the VPN, those packets will never reach the PCF Dev VM, by design.

**Comment by Jackman3005** [comment]
I cannot, we must use the client provided machines which do not give us any settings to modify for the VPN. Also, I was more interested in why this remains a problem AFTER disconnecting from the VPN. Since it should no longer have an effect...

**Comment by Jackman3005** [comment]
A few more notes: If the VPN software is completely closed it does not change the behavior. If I stop and restart the PCF DEV instance after this problem is exhibited it does not fix the behavior. So far, just the clean restart fixes.

**Comment by sclevine** [comment]
Your VPN client may leave your route table in a bad state. If `cf dev destroy && cf dev start` doesn't fix the issue, then there probably isn't much we can do about this. I suspect that all Virtualbox VMs with host-only interfaces would have this issue.

**Comment by Jackman3005** [comment]
Steps I just tried with results:
1. Start the computer fresh
2. Connect to the VPN
3. Disconnect from the VPN and close the client
4. `cf dev start`
   
   _This works_ and I can connect to my app on *.local.pcfdev.io
5. `cf dev stop`
6. Connect to VPN, visit app url (which is currently off)
7. Disconnect from VPN and close the client
8. `cf dev start`
   
   This does NOT work.

I'm starting to suspect that this could be a Cisco & Virtualbox bug and unrelated to PCF DEV. If I were to try this again I would make sure virtual box is completely closed before connecting to the VPN the second time. Anyway, if you're feeling good that this isn't relevant to PCF DEV then feel free to close it.

Thanks for the thoughts! Cheers,
Jack

**Comment by sclevine** [comment]
https://forums.virtualbox.org/viewtopic.php?f=6&t=61882
