### ISSUE TITLE
Issue connecting to PCF DEV

### ISSUE THREAD

**Issue by benwilcock** [vmware-archive/pcfdev#121]
When I try to login to PCF DEV locally on my Mac I get:-

**FAILED**
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp: lookup api.local.pcfdev.io: no such host

Here's what I did....

_$ cf dev start_
Please retrieve your Pivotal Network API from:
https://network.pivotal.io/users/dashboard/edit-profile

API token> 
Downloading VM...
Progress: |====================>| 100%
VM downloaded.
Allocating 4096 MB out of 16384 MB total system memory (9678 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
9 out of 50 running
50 out of 50 running

[PCFDEV ASCII ART]

is now running.
To begin using PCF Dev, please run:
    cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass

_$ cf login -a https://api.local.pcfdev.io --skip-ssl-validation_
API endpoint: https://api.local.pcfdev.io
**FAILED**
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp: lookup api.local.pcfdev.io: no such host

The versions of software I'm using are:-
- Mac osX 10.11.6 (El Capitan)
- Virtualbox Version 5.0.26 r108824 (latest)
- cf version 6.21.1+6fd3c9f-2016-08-10 (latest)
- PCF Dev version 0.19.0 (CLI: 27d4cda, OVA: 0.234.0) (latest)

Has anyone else experienced this issue? How did they resolve it?

**Comment by benwilcock** [comment]
I've got further info - the issue seems to resolve itself when I join a different wireless network. Unfortunately, this isn't terribly convenient although it does point to some sort of issue with my networking setup between my host and VirtualBox. This is the first application I've spotted an issue with. I have 'Docker for Mac' running locally for example and so far I haven't experienced any similar issues. 

Networking isn't a strong suit of mine, and help would be very much appreciated.

**Comment by sclevine** [comment]
The `api.local.pcfdev.io` DNS record is a public DNS record (`*.local.pcfdev.io` -> `192.168.11.11`). If you can't resolve `api.local.pcfdev.io` on your host, it's possible that your host DNS server has trouble with wildcard addresses, or prevents resolution of DNS records to private IP ranges. This is probably why changing networks fixes the issue for you.

The simplest fix would be to use Google's public DNS (8.8.8.8 / 8.8.4.4), but you could also follow [these instructions](https://docs.pivotal.io/pcf-dev/work-offline.html) to resolve `*.local.pcfdev.io` domains locally.

**Comment by benwilcock** [comment]
Using _dnsmasq_ has resolved my issue, thank-you!

I think the problem is related to a new dual band wireless router my ISP sent me. It doesn't look like I can change the preferred DNS on the router itself, so going via dnsmasq and adding `*.local.pcfdev.io` to it's config seems to be the only option for me right now. :(
