### ISSUE TITLE
Using tabs in setup output makes it harder to copy and paste

### ISSUE THREAD

**Issue by jchesterpivotal** [vmware-archive/pcfdev#122]
Once we've performed `cf dev start`, we get this shiny output:

```
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
is now running.
To begin using PCF Dev, please run:
        cf login -a https://api.local.pcfdev.io --skip-ssl-validation
```

The `cf login` line is indented using tabs.

iTerm correctly warns us against this, because pasting a tab character into a terminal typically causes autocompletions to fire. When followed by characters from the `cf login...` bit, this leads to confusing-as-hell behaviour.

We suggest replacing the tabs with spaces.

**Comment by mdelillo** [comment]
Thanks @jchesterpivotal, this will be in the next release
