### ISSUE TITLE
PCF Dev build script does not pull submodules

### ISSUE THREAD

**Issue by mattjcurry** [vmware-archive/pcfdev#124]
PCF Dev build script does not clone the cppforlife repositories.  Therefore, when the script is first run, it fails.  The work around for now is to manually set your GOPATH to the pcfdev/bosh directory and do a go get on each package.  (Alternatively you can manually git clone the repos)

`╰─$ ./bin/build -only=virtualbox-iso
- packer_bosh=/Users/Matt/github/pcfdev/output/packer-bosh
  +++ dirname /Users/Matt/github/pcfdev/bin/setup-packer
  ++ cd /Users/Matt/github/pcfdev/bin
  ++ cd ..
  ++ pwd
- bosh_gopath=/Users/Matt/github/pcfdev/bosh
- packer_bosh_gopath=/Users/Matt/github/pcfdev/bosh/src/github.com/cppforlife/packer-bosh/Godeps/_workspace
- GOPATH=/Users/Matt/github/pcfdev/bosh/src/github.com/cppforlife/packer-bosh/Godeps/_workspace:/Users/Matt/github/pcfdev/bosh
- eval 'go build -a -o /Users/Matt/github/pcfdev/output/packer-bosh github.com/cppforlife/packer-bosh/main'
  ++ go build -a -o /Users/Matt/github/pcfdev/output/packer-bosh github.com/cppforlife/packer-bosh/main
  can't load package: package github.com/cppforlife/packer-bosh/main: cannot find package "github.com/cppforlife/packer-bosh/main" in any of:
      /usr/local/Cellar/go/1.7/libexec/src/github.com/cppforlife/packer-bosh/main (from $GOROOT)
      /Users/Matt/github/pcfdev/bosh/src/github.com/cppforlife/packer-bosh/Godeps/_workspace/src/github.com/cppforlife/packer-bosh/main (from $GOPATH)
      /Users/Matt/github/pcfdev/bosh/src/github.com/cppforlife/packer-bosh/main`

**Comment by mdelillo** [comment]
@mattjcurry Those repos are submodules in PCF Dev so you can get them by running `git submodule update --init --recursive` in the pcfdev repo. You can also use `git clone --recursive` when cloning pcfdev to get the submodules automatically.
