### ISSUE TITLE
Build packs

### ISSUE THREAD

**Issue by psadineni** [vmware-archive/pcfdev#133]
When I am pushing an application it will be downloading the build packs and create a droplets and push the droplet and destroy the build packs, I would like to understand from where it is downloading the build packs. If I am correct it should be from Github. Second question is : If I am using an old application which is running on Java 1.4 does it download the build pack which supports JAVA 1.4, or as the support of java 1,4 is no more the build pack will not be available any more? ​

**Comment by sclevine** [comment]
This is a general CF question that you asked on the cf-dev mailing list today. The question can be addressed there.
