### ISSUE TITLE
Getting error when trying to download the java buildpack

### ISSUE THREAD

**Issue by psadineni** [vmware-archive/pcfdev#135]
C:\Users\vaishnavi\java-test-applications-master\java-test-applications-master>cf push testjava -b https://github.com/cloudfoundry/java-buildpack.git -p C:\Users\vaishnavi\java-test-applications-master\java-test-applications-master
Updating app testjava in org development1 / space dev1 as admin...
OK

Uploading testjava...
Uploading app files from: C:\Users\vaishnavi\java-test-applications-master\java-test-applications-master
Uploading 429K, 246 files
Done uploading
OK

Starting app testjava in org development1 / space dev1 as admin...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (172.2K)
Staging...
-----> Java Buildpack Version: 1447aa9 | https://github.com/cloudfoundry/java-buildpack.git#1447aa9
[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: No container can run this application. Please ensure that you’ve pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. >
No container can run this application. Please ensure that you’ve pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation.
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
Error restarting application: BuildpackCompileFailed

TIP: use 'cf logs testjava --recent' for more information

C:\Users\vaishnavi\java-test-applications-master\java-test-applications-master>

Do we need to give any parameter, below are the files

C:\Users\vaishnavi\java-test-applications-master\java-test-applications-master>dir
 Volume in drive C is Windows
 Volume Serial Number is 7480-9566

 Directory of C:\Users\vaishnavi\java-test-applications-master\java-test-applications-master

09/08/2016  07:53 AM    <DIR>          .
09/08/2016  07:53 AM    <DIR>          ..
09/08/2016  10:20 AM                86 .gitignore
09/08/2016  07:53 AM    <DIR>          .gradle
09/08/2016  07:51 AM    <DIR>          .idea
09/08/2016  10:20 AM             1,488 build.gradle
09/08/2016  07:51 AM    <DIR>          ci
09/08/2016  10:20 AM             8,758 CONTRIBUTING.md
09/08/2016  07:51 AM    <DIR>          core
09/08/2016  07:51 AM    <DIR>          dist-zip-application
09/08/2016  07:51 AM    <DIR>          ejb-application
09/08/2016  07:51 AM    <DIR>          gradle
09/08/2016  10:20 AM               188 gradle.properties
09/08/2016  10:20 AM             4,971 gradlew
09/08/2016  10:20 AM             2,314 gradlew.bat
09/08/2016  07:51 AM    <DIR>          groovy-application
09/08/2016  07:51 AM    <DIR>          java-main-application
09/08/2016  10:20 AM            11,358 LICENSE
09/08/2016  10:20 AM                95 NOTICE
09/08/2016  07:51 AM    <DIR>          ratpack-application
09/08/2016  10:20 AM             4,334 README.md
09/08/2016  10:20 AM               991 settings.gradle
09/08/2016  07:51 AM    <DIR>          spring-boot-cli-application
09/08/2016  07:51 AM    <DIR>          spring-boot-cli-jar-application
09/08/2016  07:51 AM    <DIR>          spring-common
09/08/2016  07:51 AM    <DIR>          web-application
09/08/2016  07:51 AM    <DIR>          web-servlet-2-application
              10 File(s)         34,583 bytes
              17 Dir(s)  118,822,883,328 bytes free

C:\Users\vaishnavi\java-test-applications-master\java-test-applications-master>

**Comment by sclevine** [comment]
Hi @psadineni,

Using the Java buildpack, you must specify a `.jar` or `.war` file with the `-p` flag unless you have a `manifest.yml` file.
Docs here: https://docs.cloudfoundry.org/buildpacks/java/

**Comment by psadineni** [comment]
Thank you...I am able to build it and deploy the war
