### ISSUE TITLE
pfc dev behind firewall, cant start.

### ISSUE THREAD

**Issue by Frost208** [vmware-archive/pcfdev#136]
Hello,
i am new to PCF dev and installed it according to the guidance on https://docs.pivotal.io/pcf-dev/install-windows.html. (Win 7)

When i try to start it with
`cf dev start`

i get the following output

> PS H:> cf dev start
> Please retrieve your Pivotal Network API from:
> https://network.pivotal.io/users/dashboard/edit-profile
> 
> API token>
> FAILED
> Error: failed to reach Pivotal Network: Post https://network.pivotal.io/api/v2/p
> roducts/pcfdev/releases/1622/product_files/5496/download: dial tcp 52.73.53.122:
> 443: i/o timeout.

I am using it from a company-internal network behind a firewall. Are there some special settings to do? Maybe a entry in the etc/hosts ?

Hope someone can help me.

**Comment by sclevine** [comment]
Hi @Frost208,

Do you require an HTTP or HTTPS proxy to connect to the internet?
If so, see here: https://docs.pivotal.io/pcf-dev/proxy.html

If all else fails (and assuming you're running PCF Dev 0.19.0), you can manually download the 0.234.0 OVA from the `internal` release on PivNet and run `cf dev import` on it. The downloaded OVA can be deleted after running `cf dev import`. If you do require an HTTP or HTTPS proxy, you will still need to follow the proxy instructions for your VM to have appropriately configured internet connectivity.

**Comment by Frost208** [comment]
Thank you, that worked for me.

**Comment by sclevine** [comment]
Happy to help!
