### ISSUE TITLE
JVM arguments

### ISSUE THREAD

**Issue by psadineni** [vmware-archive/pcfdev#139]
Hello,

I have deployed a sample ear in to my liberty application and have to set additional custom properties in my JVM arguments to make the application work i have set them in the environment variables of CF , but no luck, where do i need to set them  to make my application work

**Comment by sclevine** [comment]
Hi @psadineni,

Depending on the buildpack, you may have to restart or restage your application for environment variables to take effect.

This issue tracker is for issues related to starting and managing a PCF Dev VM, not for general CF questions. I recommend that you ask your question with more details on the cf-dev mailing list, or on the Github issues for the [liberty buildpack](https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack) or [Java buildpack](https://github.com/cloudfoundry/java-buildpack) (whichever you are using).

**Comment by psadineni** [comment]
I have restaged the application after setting the env variables, but application does not work as expected.
which file can I find the details of the env variables set.

I have raised this question in the cf dev mailing list of the files where I can find the env and others but no reply on that , so that I have raised the question in this forum. Please help.
