### ISSUE TITLE
JVM arguments

### ISSUE THREAD

**Issue by psadineni** [vmware-archive/pcfdev#140]
I have restaged the application after setting the env variables, but application does not work as expected.
which file can I find the details of the env variables set.

I have raised this question in the cf dev mailing list of the files where I can find the env and others but no reply on that , so that I have raised the question in this forum. Please help.

**Comment by sclevine** [comment]
What buildpack are you using? As mentioned in #139, you should reach out to the maintainers of that buildpack for help with this issue.

**Comment by psadineni** [comment]
I am using Liberty Build pack.

**Comment by sclevine** [comment]
That buildpack is maintained here: https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack

It's not included with PCF Dev, and we don't have the context here to answer your question, so I'm closing this issue. Maybe [this doc](https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/blob/master/docs/framework-java_opts.md) is useful?
