### ISSUE TITLE
cf dev trust fails (0.20.0)

### ISSUE THREAD

**Issue by rnadler** [vmware-archive/pcfdev#144]
cf dev version: 0.20.0 (CLI: 54fb957, OVA: 0.317.0)
Windows 10 Pro, 64-bit, Version 1607, Build 14393.187

After successful VM start: 

```
> cf dev trust
FAILED
Error: failed to trust VM certificates: exit status 2147942405.
>
```

**Comment by rnadler** [comment]
Yes, my account has Administrator privileges.

**Comment by sclevine** [comment]
I'll file a story to investigate and improve the error message. In the meantime, could you let us know what happens when you run [this line](https://github.com/pivotal-cf/pcfdev-cli/blob/master/cert/concrete_system_store_windows.go#L10) manually using the CA cert that's returned by `cf dev trust -p`?

**Comment by rnadler** [comment]
Running under my user account which is _supposed_ to be an Administrator:

> > certutil -addstore -f ROOT .\dev-trust.cer
> Administrator permissions are needed to use the selected options.  Use an administrator command prompt to complete these
>  tasks.
> ROOT "Trusted Root Certification Authorities"
> Cannot open Cert store.
> CertUtil: -addstore command FAILED: 0x80070005 (WIN32: 5 ERROR_ACCESS_DENIED)
> CertUtil: Access is denied.

Running as Administrator:

> > certutil -addstore -f ROOT .\dev-trust.cer
> ROOT "Trusted Root Certification Authorities"
> Signature matches Public Key
> Certificate "local.pcfdev.io 2016-09-23T10:07:44Z" added to store.
> CertUtil: -addstore command completed successfully.

The only issue with running as Administrator is that 'cf dev' doesn't see the running VM:

> > cf dev trust
> Your VM is currently stopped. Start VM to trust VM certificates.
> > cf dev status
> Stopped

**Comment by sclevine** [comment]
Can you confirm that the VM doesn't look "Stopped" in a non-Administrator terminal? That's very unexpected.

**Comment by rnadler** [comment]
Yes, running as my normal user account:

> > cf dev status
> Running
> CLI Login: cf login -a https://api.local.pcfdev.io --skip-ssl-validation
> Apps Manager URL: https://local.pcfdev.io
> Admin user => Email: admin / Password: admin
> Regular user => Email: user / Password: pass

**Comment by sclevine** [comment]
Interesting. Did your workaround allow you to use the feature for now?
I prioritized a story to make `cf dev trust` attempt to escalate privileges.

**Comment by rnadler** [comment]
Yes. All of the annoying security prompts are now gone!

**Comment by rnadler** [comment]
Confirmed that 0.21.0 resolves this issue:

> > cf dev trust
> (Confirmation pop-up)
> ***Warning: a self-signed certificate for _.local.pcfdev.io has been inserted into your OS certificate store. To remove this certificate, run: cf dev untrust_***

**Comment by sclevine** [comment]
👍
