### ISSUE TITLE
Installing java on application space of CF

### ISSUE THREAD

**Issue by psadineni** [vmware-archive/pcfdev#147]
Hello team,

I have installed an application on my pcf dev using liberty as a profile , now to start my services ( liberty profile) , I need to install java on container of the application, for that it is requesting for the vcap password, can some one suggest how can I do it.

**Comment by sclevine** [comment]
Hi @psadineni,

This is a general CF question, not a question specific to PCF Dev. Java is already installed by the liberty buildpack. This was answered in your duplicate issue in the liberty buildpack issue tracker: https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack/issues/313
