### ISSUE TITLE
Conflicting versions of packer on RHEL

### ISSUE THREAD

**Issue by sleighsoft** [vmware-archive/pcfdev#150]
I am trying to run the build script on RHEL Linux, CentOS 7.
The problem is that if I install `packer` then I have two different applications called `packer`.
See here also: https://www.packer.io/intro/getting-started/setup.html
It would therefore be good if a user can specify the location of `packer` when executin `./bin/build`.
I can make the necessary changes and open up a pull request. I just wanted to know if there is any requirement on the position of that parameter.

**Comment by sclevine** [comment]
Hi @sleighsoft,

I recommend that you install packer into a different directory and run `./bin/build` with that directory at the front of  `$PATH`. Ex.

```
PATH=/usr/local/packer/bin ./bin/build
```

**Comment by sleighsoft** [comment]
That is a good solution. Thanks @sclevine
