### ISSUE TITLE
Building behind corporate firewall

### ISSUE THREAD

**Issue by sleighsoft** [vmware-archive/pcfdev#154]
When building behind a corporate firewall packer will fail to install VirtualBoxGuestAdditions.

apt-get will fail to download dkms and this will result in failure to install VirtualBoxGuestAdditions.

**Comment by aemengo** [comment]
`apt-get` reaches out into the public internet to retrieve the packages necessary for installing VirtualBoxGuestAdditions. You may need to allow access to the pertinent repositories through your corporate firewall for the packer script to continue successfully in that environment. Regardless, this is not an appropriate question for the PCF Dev project.
