### ISSUE TITLE
Error during VM build

### ISSUE THREAD

**Issue by sleighsoft** [vmware-archive/pcfdev#155]
When I build the project during VM setup it tries to install VirtualBoxGuestAdditions with `apt-get install -y dkms` it gets required features. Sadly `dkms` is not available when it runs the install but becomes available after an `apt-get update`.

Any ideas on why this happens?

**Comment by aemengo** [comment]
Are you perhaps using a different iso than the one provided in the  `pcfdev.json`? In any event, we've modified the script to perform an `apt-get update` before installing VirtualBoxGuestAdditions. Many thanks for bringing this to our attention.
