### ISSUE TITLE
Changing the default ova location

### ISSUE THREAD

**Issue by pcmgit007** [vmware-archive/pcfdev#156]
Hi I am trying to change the default downloaded vm location with the below command on Windows 7 and getting this. Is there an other way around?

E:\CFTools\CloudFoundry>cf dev start -o E:/PCFOvanVms
Allocating 4048 MB out of 8096 MB total system memory (4532 MB free).
Importing VM...
FAILED
Error: failed to import VM: malformed tar E:/PCFOvanVms:read E:/PCFOvanVms: The handle is invalid..

**Comment by mdelillo** [comment]
HI @pcmgit007, the `-o` flag should be used when you have already downloaded the OVA to your filesystem. To change the location of the VM, set the `PCFDEV_HOME` environment variable.

**Comment by sclevine** [comment]
Note, the `-o` flag is only intended for use with a custom OVA, generally for development purposes. It disables important system memory checks.

**Comment by pcmgit007** [comment]
Hi @mdelillo ,

Thanks for the answer. It is working now.
We are trying to install the cf on a remote machine which multiple users can access. As per the cf default behavior for each user a separate vm will get imported which eats up the disk space. If we set PCFDEV_HOME as a system level environment variable, will it be used as a common location for all the users?

**Comment by mdelillo** [comment]
@pcmgit007 if multiple users set PCFDEV_HOME to the same value on the same computer, they will be interacting with the same PCF Dev instance. Only one VM will be running, but everyone will be pushing to the same PCF Dev. If you want users to have their own PCF Dev, they must use different values for PCFDEV_HOME.
