### ISSUE TITLE
Permission denied (publickey) after building pcfdev

### ISSUE THREAD

**Issue by sleighsoft** [vmware-archive/pcfdev#157]
PCFDev builds fine and creates an ova file.
When executing `cf dev start -o /home/vms/pcfdev-custom-v1.ova` it boots up the VM but connecting via ssh fails for `cf dev start`.
The VM keeps running.
When I try to manually ssh to the machine it gives me a `publickkey denied` error.

**Comment by mdelillo** [comment]
@sleighsoft We disable SSH password authentication for the VM [here](https://github.com/pivotal-cf/pcfdev/blob/73ee373fa6c040ebb43adb6e380d69e2e79407f4/pcfdev.json#L147). You could remove that line before building or use your own keypair by specifying `ova_public_key` when running the build script (i.e. `bin/build -var="ova_public_key=ssh-rsa ..."`)
