### ISSUE TITLE
pcfdev doesn't seem to work with the dotnet core build pack

### ISSUE THREAD

**Issue by aidiegoml** [vmware-archive/pcfdev#163]
I can't seem to make a dotnet sample app work on pcfdev. Currently running:

PCF Dev version 0.21.0 (CLI: e0fdf71, OVA: 0.337.0)

This command:

```
cf push dotnet-sample -b https://github.com/cloudfoundry-community/dotnet-core-buildpack.git
```

works on run.pivotal.io. I increased app instance memory in pcfdev to match what was running in run.pivotal.io. The following is the error that I get in pcfdev:

```
App instance exited with guid 273abf65-6e8d-41e5-81ce-eab0a1ff0583 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"Copying into the container failed", "crash_count"=>3, "crash_timestamp"=>1477452992991898761, "version"=>"3f6ccae3-f0e9-4c2a-b2f8-ed5c83a2bc70"}
```

Perhaps a quota limit? My total space usage according to the stats is:

```
Uploading dotnet-sample...
Uploading app files from: /Users/johnyi/Sandbox/DotNet/cli-samples/HelloMvc
Uploading 27.1K, 36 files
Done uploading               
OK

Starting app dotnet-sample in org pcfdev-org / space pcfdev-space as admin...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (135.1K)
Staging...
ASP.NET Core buildpack version: 1.0.3
ASP.NET Core buildpack starting compile
```

**Comment by sclevine** [comment]
The .Net Core buildpack requires more disk space than many other buildpacks. The disk usage you show is just the size of the source code, not the size of the staged app with dependencies. Try starting the app with `cf push your-app -k 2G`.

**Comment by aidiegoml** [comment]
Thanks sclevine, that would be the magic touch. Is there an easy way to know how determine the space needed for my apps in the future? or is it a little bit trial and error with -k?

**Comment by sclevine** [comment]
The `cf app you-app` command may be used to examine the disk usage of a running app, but it's not helpful in your case. The .Net Core buildpack is somewhat unusual in its disk space requirements -- I'll make sure that it gets documented.
