### ISSUE TITLE
failing to build local from latest commit

### ISSUE THREAD

**Issue by lwoydziak** [vmware-archive/pcfdev#164]
It appears that commit:
https://github.com/pivotal-cf/pcfdev/commit/df1159d174b4a02ce5442dc938013e99bf6613ae
causes the "apt-get -y --force-yes dist-upgrade" to do something significant.

We are unable to get the full packer build to complete.

Attaching the log, please see the last two lines.
[pcfdev.txt](https://github.com/pivotal-cf/pcfdev/files/554642/pcfdev.txt)

**Comment by julian-hj** [comment]
Weirdly we also get the same errors if we pull [the commit from 10 days ago](https://github.com/pivotal-cf/pcfdev/commit/73ee373fa6c040ebb43adb6e380d69e2e79407f4).  Full logs attached
[pcfdev2.txt](https://github.com/pivotal-cf/pcfdev/files/554691/pcfdev2.txt)

**Comment by sclevine** [comment]
We only guarantee that tagged releases are stable and working. If you would like to build the latest version of PCF Dev, please use [v0.21.0](https://github.com/pivotal-cf/pcfdev/tree/v0.21.0).

That said, I can confirm that our CI built 7282cd7 successfully.

**Comment by mdelillo** [comment]
An updated sudo package is causing this issue, we have an uncommitted fix for it. Should be out later today.

**Comment by julian-hj** [comment]
Thanks! We are trying out your fix now...

**Comment by lwoydziak** [comment]
Working now, thank you!
