### ISSUE TITLE
Issues pushing golang to PCF-dev

### ISSUE THREAD

**Issue by mikemcguire** [vmware-archive/pcfdev#165]
Yesterday my app was pushing fine. When I came back today to push I am having issues where godeps can't find certain dependencies. Im able to godep go install just fine on my local machine, which leads me to believe this is a PCF issue of some type. Not sure if I should be posting this here or on the buildpack repo. Anyway help would be much appreciated...

`go push` output: 

```
Starting app business-service in org pcfdev-org / space pcfdev-space as user...
Downloading dotnet_core_buildpack_beta...
Downloading go_buildpack...
Downloading nodejs_buildpack...
Downloading ruby_buildpack...
Downloading staticfile_buildpack...
Downloaded ruby_buildpack
Downloading python_buildpack...
Downloaded go_buildpack
Downloading php_buildpack...
Downloaded nodejs_buildpack
Downloading binary_buildpack...
Downloaded dotnet_core_buildpack_beta
Downloading java_buildpack...
Downloaded binary_buildpack
Downloaded php_buildpack
Downloaded python_buildpack
Downloaded staticfile_buildpack
Downloaded java_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (9.1K)
Staging...
-------> Buildpack version 1.7.10
file:///tmp/buildpacks/d17226e3d1bc5f728403b1521b69c8ae/dependencies/https___buildpacks.cloudfoundry.org_concourse-binaries_godep_godep-v74-linux-x64.tgz
file:///tmp/buildpacks/d17226e3d1bc5f728403b1521b69c8ae/dependencies/https___buildpacks.cloudfoundry.org_concourse-binaries_glide_glide-v0.11.0-linux-x64.tgz
-----> Checking Godeps/Godeps.json file.
-----> Installing go1.6.3... done
Downloaded [file:///tmp/buildpacks/d17226e3d1bc5f728403b1521b69c8ae/dependencies/https___storage.googleapis.com_golang_go1.6.3.linux-amd64.tar.gz]
 !!    Installing package '.' (default)
-----> Running: godep go install -v -tags cloudfoundry --buildmode=pie .
server/server.go:4:2: cannot find package "gopkg.in/gin-gonic/gin.v1" in any of:
    /tmp/cache/go1.6.3/go/src/gopkg.in/gin-gonic/gin.v1 (from $GOROOT)
    /tmp/app/.heroku/go/src/business-service/Godeps/_workspace/src/gopkg.in/gin-gonic/gin.v1 (from $GOPATH)
    /tmp/app/.heroku/go/src/gopkg.in/gin-gonic/gin.v1
godep: go exit status 1
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container
```

Godeps.json:

```
{
    "ImportPath": "business-service",
    "GoVersion": "go1.6",
    "GodepVersion": "v74",
    "Deps": [
        {
            "ImportPath": "github.com/gin-gonic/gin/binding",
            "Comment": "v1.0-2-g3900df0",
            "Rev": "3900df04d2a88e22beaf6a2970c63648b9e1b0e1"
        },
        {
            "ImportPath": "github.com/gin-gonic/gin/render",
            "Comment": "v1.0-2-g3900df0",
            "Rev": "3900df04d2a88e22beaf6a2970c63648b9e1b0e1"
        },
        {
            "ImportPath": "github.com/golang/protobuf/proto",
            "Rev": "98fa357170587e470c5f27d3c3ea0947b71eb455"
        },
        {
            "ImportPath": "github.com/manucorporat/sse",
            "Rev": "ee05b128a739a0fb76c7ebd3ae4810c1de808d6d"
        },
        {
            "ImportPath": "golang.org/x/net/context",
            "Rev": "65dfc08770ce66f74becfdff5f8ab01caef4e946"
        },
        {
            "ImportPath": "gopkg.in/gin-gonic/gin.v1",
            "Comment": "v1.0",
            "Rev": "2dae550eb5392006a4582ce9c90016a9b5a74e8b"
        },
        {
            "ImportPath": "gopkg.in/go-playground/validator.v8",
            "Comment": "v8.18.1",
            "Rev": "5f57d2222ad794d0dffb07e664ea05e2ee07d60c"
        },
        {
            "ImportPath": "gopkg.in/yaml.v2",
            "Rev": "a5b47d31c556af34a302ce5d659e6fea44d90de0"
        }
    ]
}
```

**Comment by sclevine** [comment]
Can you provide a sample app that fails, and the version of PCF Dev that you're using (`cf dev version`)?

**Comment by mikemcguire** [comment]
@sclevine Thanks for the quick response, I have a test repo setup that I am experiencing this behavior with https://github.com/mikemcguire/go-test
Let me know if I can provide more info.

**Comment by mikemcguire** [comment]
Oh yeah, the dev version Im using: PCF Dev version 0.21.0 (CLI: e0fdf71, OVA: 0.337.0)

**Comment by mikemcguire** [comment]
Didn't think to but am experiencing the same behavior when pushing to run.pivotal.io. Probably better to post this in the buildpack repo?

**Comment by chhhavi** [comment]
@mikemcguire We were able to get your application working on PCF Dev after vendoring your Godeps dependencies into the Godeps _workspace directory - with the application.

We were able to do this with this command: `GOPATH=$(godep path) godep restore`

Attached is the fork of the repository where we made our changes: 

https://github.com/mikemcguire/go-test/compare/master...aemengo:working-on-pcfdev

**Comment by mikemcguire** [comment]
@chhhavi Unfortunately this still doesn't appear to be working for me. I've spent the last few days trying different configurations for my go environment variables to no avail. I felt like this was an issue with how I had my go workspace setup.. But ultimately I only have problems with the godep commands with cloud foundry. I've since restored my environment variables to reflect that is recommended here https://golang.org/doc/code.html

**Comment by mikemcguire** [comment]
I've also tried those differing environment configurations using both the newer vendor expirament & the godeps/_workspaces conventions.

**Comment by aemengo** [comment]
@mikemcguire Unfortunately this question falls outside the realm of a PCF Dev specific issue and this is not the appropriate repository to ask. As you have mentioned before, perhaps the golang cloudfoundry project might serve you better. https://github.com/cloudfoundry/go-buildpack/issues
