### ISSUE TITLE
Stuck on "Starting VM"

### ISSUE THREAD

**Issue by dtpest** [vmware-archive/pcfdev#169]
Hi,

I've trying to run "cf dev start" on different Ubuntu 16 Nodes.
On every Node is Virtualbox 5.0 or greater installed.
Also CF CLI is installed and Internet Connection does work.

But on every Node it stucks on "Starting VM..." without any error.

Best,
Peter

**Comment by aemengo** [comment]
We've generally seen this behavior when running `cf dev start` is run without `VT-x` enabled. Is that perhaps the case here?

**Comment by dtpest** [comment]
Also had this Issue on one Node - but then this message was shown.
But on several other Ubuntu 16 Nodes this is activated and also the message is not getting displayed.

**Comment by dtpest** [comment]
Environment: 
Host: Arch Linux + kvm (qemu)
VM: Ubuntu 16.04.01 server (complete new Installation)

Steps:
Install Virtualbox 5.1 (https://www.virtualbox.org/wiki/Linux_Downloads)
Install CF CLI (https://github.com/pivotal-cf/pcfdev)
Check Internetconnection (ping www.google.com)
Download pfdev (https://github.com/pivotal-cf/pcfdev)
Extract and Execute binary (./pcfdev-vxxxxxx)
Run CF (cf dev start)

----> Output

```
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io
Email> XXXXXX
Password> XXXXXXX
Downloading VM...
Progress: |====================>| 100% 
VM downloaded.
Allocating 4096 MB out of 16049 MB total system memory (15789 MB free).
Importing VM...
Starting VM...
```

**Comment by dtpest** [comment]
cat /proc/cpuinfo| egrep "vmx|svm"
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq **vmx** ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 arat

**Comment by aemengo** [comment]
Could you try 2 things on a node where this is happening to help us debug?
1. Please run `cf dev target` and submit the output
2. Please `VBoxManage startvm pcfdev-v0.337.0 --type headless` and submit the output

**Comment by dtpest** [comment]
---

```
labuser@ls-ub-tf4002cv:/tmp$ ./pcfdev-v0.21.0+PCF1.8.2-linux 
Plugin successfully installed. Current version: 0.21.0. For more info run: cf dev help
labuser@ls-ub-tf4002cv:/tmp$ cf dev start
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email> XXXXXX

Password> XXXXXX
Downloading VM...
Progress: |====================>| 100% 
VM downloaded.
Allocating 4096 MB out of 16049 MB total system memory (15789 MB free).
Importing VM...
Starting VM...
^C
labuser@ls-ub-tf4002cv:/tmp$                                                                                                         
labuser@ls-ub-tf4002cv:/tmp$                                                                                                         
labuser@ls-ub-tf4002cv:/tmp$                                                                                                         
labuser@ls-ub-tf4002cv:/tmp$                                                                                                         
labuser@ls-ub-tf4002cv:/tmp$                                                                                                         
labuser@ls-ub-tf4002cv:/tmp$                                                                                                         
labuser@ls-ub-tf4002cv:/tmp$ cf dev target                                                                                           
FAILED                                                                                                                               
Error: vm in unknown state.                                                                                                          
PCF Dev is in an invalid state. Please run 'cf dev destroy'.                                                                         
labuser@ls-ub-tf4002cv:/tmp$ cf dev destroy                                                                                          
FAILED                                                                                                                               
Error: error destroying PCF Dev VM: failed to destroy all pcfdev vms.                                                                
labuser@ls-ub-tf4002cv:/tmp$ cf dev destroy                                                                                          
FAILED                                                                                                                               
Error: error destroying PCF Dev VM: failed to destroy all pcfdev vms.                                                                
labuser@ls-ub-tf4002cv:/tmp$
```

---

Restarted VM and after that tried again:

```
labuser@ub-gui:~$ cf dev target                                                                                                      
Your VM is currently stopped. Start VM to target PCF Dev. 
```

---

```
labuser@ub-gui:~$ VBoxManage startvm pcfdev-v0.337.0 --type headless
Waiting for VM "pcfdev-v0.337.0" to power on...
```

**Comment by aemengo** [comment]
Could you please run this command and submit the output to show what state the VM is in after starting hangs indefinitely?

```
VBoxManage showvminfo pcfdev-v0.337.0 --machinereadable | grep VMState
```

Are you having trouble starting other VMs on these nodes or is it just PCF Dev? And also please make sure that there is ample disk space (>40 GBs) on the filesystems that PCF Dev is running on.

**Comment by dtpest** [comment]
Problem is the nested virtualization.
On the Host (Arch Linux) it does start.
