### ISSUE TITLE
pcf dev start issue- 

### ISSUE THREAD

**Issue by NaveenRajaMarri** [vmware-archive/pcfdev#172]
I have installed oracle VM virtual box manager in my laptop  and created a VM  with  2gb ram & space25gb
once i have executed the pcf dev start i am getting the below error " could not found VBoxManage Executable" .
If issue is with configuring a virtual vm..pls let me know the steps for configuring/ setting  up  a VM .Does it need an external harddisk/ otherlaptop

 can someone help me here! for installing  configuring a PCF dev

**Comment by sclevine** [comment]
Hi @NaveenRajaMarri,

PCF Dev creates a VM for you when you run `cf dev start` on the host. Please install the cf CLI and PCF Dev plugin on your host machine and run `cf dev start` from there.

Check out our [documentation](https://docs.pivotal.io/pcf-dev/index.html) for more info.

**Comment by NaveenRajaMarri** [comment]
@sclevine thanks for your response.
I have already followed the procedure what u said but the mistake what I did is instead of "cf dev start " I have ran pcf dev start .

Now it was downloading vm ,post execution of cf dev start. What wil be size of that vm ? It was showing the status as 1℅ from long time.

**Comment by sclevine** [comment]
The PCF Dev OVA is slightly under 5 GB.

**Comment by NaveenRajaMarri** [comment]
@sclevine. 

Once vm is downloaded.. it shows as below. .....
```
Allocating 3072 mb out of 2993 mb total system memory<1648 mb free>.
Importing vm
Starting vm
Provisioning vm
Waiting for service to start...
```
After this I have waited for 1hour .. but am not able to see the services as started.. 

Can you guide me here to proceed further ..

**Comment by sclevine** [comment]
> Allocating 3072 mb out of 2993 mb total system memory<1648 mb free>.

As mentioned in the [docs](https://docs.pivotal.io/pcf-dev/index.html), PCF Dev requires at least 3 GB of free system memory to run. We recommend running PCF Dev on a workstation with at least 8 GB of total system memory.

**Comment by NaveenRajaMarri** [comment]
Oh..
After triggering "cf dev start" When the services are waiting to start ..In vm it is asking to login as below..
```
Ubuntu 14.04.5 Lts agent-id-pcfdev-0 tty1
agent-id-pcfdev-0 login :. 
```
What will be the credentials for this and how I can reset the login credentials?

**Comment by aemengo** [comment]
If you would like to gain access to the PCF Dev instance, the recommended way is to run: `cf dev ssh` from your workstation.

**Comment by sclevine** [comment]
@NaveenRajaMarri You should only need to interact with PCF Dev using the `cf` CLI. There is no need to login the VM. You can do so with `cf dev ssh` as @aemengo mentions, but this is only encouraged for debugging purposes.

You won't be able to use PCF Dev with so little system memory. You need at least 3 GB of free RAM for PCF Dev to start successfully.

**Comment by NaveenRajaMarri** [comment]
Yeah got it.  thankyou
