### ISSUE TITLE
Add support for posgres service

### ISSUE THREAD

**Issue by shpandrak** [vmware-archive/pcfdev#173]
It would be great if the services in the marketplace for pcfdev will include postgres. currently there are only mysql,redis and rabbitmq. should be easier to add other existing bosh releases - starting with postgres :)

**Comment by sclevine** [comment]
Hi @shpandrak,

Thanks for the feature request. What postgres service broker would you like to see in PCF Dev? The only service brokers I am aware of are community supported.

**Comment by sclevine** [comment]
Closing due to lack of response and inability to proceed. Feel free to re-open.
