### ISSUE TITLE
pcf ops manager installation on openstack

### ISSUE THREAD

**Issue by NaveenRajaMarri** [vmware-archive/pcfdev#174]
Installation of pcf ops manager can be done on  AWS, openstack, vsphere !! 

1. what are the advantages over other? which should be preferred for which requirement ?
2. Is the configuration required(RAM 50+GB , Memory 100+ GB )  same while installing either on AWS/ openstack/vsphere? or will it be differs to each?

**Comment by aemengo** [comment]
This is not the appropriate Github repository to post this issue. We cater to PCF Dev specific issues. PCF Ops manager documentation can be found here: http://docs.pivotal.io/pivotalcf/1-8/installing/pcf-docs.html

**Comment by sclevine** [comment]
@NaveenRajaMarri If you're a Pivotal customer, don't hesitate to reach out to Pivotal Support for your PCF-related questions.

**Comment by NaveenRajaMarri** [comment]
Sure Thanks
