### ISSUE TITLE
Custom Service support

### ISSUE THREAD

**Issue by nissshh** [vmware-archive/pcfdev#175]
I've gone through many references on web but couldnt find any reference where I can use Service Brokers e.g.  kind of run cf add-service-broker on pcfdev. Is there a support? Anyplans when this would be on . It'd be of great help.

Update : CF version is cf version 6.22.1+6b7af9c-2016-09-24

**Comment by nissshh** [comment]
Please hold on this issue as I am checking the CF CLI I installed on windows.

**Comment by sclevine** [comment]
Hi @nissshh,

In general, all cf CLI functionality that works with a real PCF installation also works with PCF Dev. This means that you can use `cf create-service-broker` with broker apps that you push to PCF Dev, brokers that you're running in other VMs, and brokers that you're running directly on your workstation.

However, PCF Dev doesn't support BOSH, so you won't be able to deploy a BOSH release for a service broker to PCF Dev.

Does this make sense?

**Comment by sclevine** [comment]
Closing due to lack of response.
