### ISSUE TITLE
Local PCF Dev issue

### ISSUE THREAD

**Issue by tchaganti** [vmware-archive/pcfdev#176]
Am very new the PCF.
AM trying to create a gradle project and deploy it on the local pCF.

I have downloaded the orcale virtual machine
Also installed the CLI
PCF in the local..

My pcf dev is running on the virtual box.

Am using the following cf api local.pcfdev.io 
it failing all the time:(

With the below message:
```
FAILED
Error performing request: Get https://local.pcfdev.io/v2/info: dial tcp 192.168.
11.11:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_pr
oxy environment variable is correctly set. Else, check your network connection.
```

I have configured the environment variables
as
```
https_proxy
local.pcfdev.io,api.local.pcfdev.io

no_proxy
local.pcfdev.io,localhost,192.168.11.11, .local.pcfdev.io,api.local.pcfdev.io 
```
added an entry in the etc/host

also added env. variable:
CF_DIAL_TIMEOUT
5

Still no success.
Can anyone please help me on this issue.

Thanks for reading this post

**Comment by aemengo** [comment]
hi @tchaganti. There is no need to add an entry into `etc/host` or configure http proxy environment variables to use PCF Dev locally. `cf api local.pcfdev.io` requires that you hit the api of our PCF Dev instance. In this case it would be **api**.local.pcfdev.io. If you are trying to perform a CF login into your PCF Dev instance, the recommended way is to perform the login command that is shown as part of the provisioning process.

See [here](http://docs.pivotal.io/pcf-dev/usage.html#pcf-dev) for more documentation

**Comment by sclevine** [comment]
Closing due to lack of response. Let us know if you're still experiencing issues and we will re-open.
