### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dprotaso** [vmware-archive/pcfdev#177]
mac3057:~ davep$ cf dev version
PCF Dev version 0.22.0 (CLI: e278885, OVA: 0.389.0)

mac3057:~ davep$ cf dev start

Less than 4096 MB of free memory detected, continue (y/N): > n
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40c3ff9]

goroutine 1 [running]:
panic(0x4440620, 0xc4200140e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/pivotal-cf/pcfdev-cli/vendor/github.com/cloudfoundry/cli/cf/terminal.(*terminalUI).Confirm(0xc4201ad580, 0xc4201ea8c0, 0x3b, 0x1)
	/ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/vendor/github.com/cloudfoundry/cli/cf/terminal/ui.go:150 +0xb9
github.com/pivotal-cf/pcfdev-cli/vm.(*Saved).checkMemory(0xc4200a1f40, 0x41cc4e9, 0xc4201aca40)
	/ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/vm/saved.go:95 +0xee
github.com/pivotal-cf/pcfdev-cli/vm.(*Saved).VerifyStartOpts(0xc4200a1f40, 0xc42009ef80, 0x0, 0x46ebc00)
	/ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/vm/saved.go:38 +0xdd
github.com/pivotal-cf/pcfdev-cli/plugin/cmd.(*StartCmd).Run(0xc42009ef00, 0xc42007c0e0, 0x0)
	/ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/plugin/cmd/start.go:114 +0x2d0
github.com/pivotal-cf/pcfdev-cli/plugin.(*Plugin).Run(0xc4201aca00, 0x46ed340, 0xc4201a1a60, 0xc42007c0e0, 0x2, 0x2)
	/ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/plugin/plugin.go:61 +0x178
github.com/pivotal-cf/pcfdev-cli/vendor/github.com/cloudfoundry/cli/plugin.Start(0x46e5dc0, 0xc4201aca00)
	/ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/vendor/github.com/cloudfoundry/cli/plugin/plugin_shim.go:30 +0x288
main.main()
	/ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/main.go:141 +0xd7d

**Comment by mdelillo** [comment]
Thanks for reporting this @dprotaso. It has been fixed in our latest release (v0.26.0).
