### ISSUE TITLE
"The file already exists under the plugin directory" when installing PCF Dev on Windows

### ISSUE THREAD

**Issue by nathan-alden-sr** [vmware-archive/pcfdev#178]
I am running Windows 7 SP1 x64 in a corporate environment. The `HOMEDRIVE` enviromment variable is set to `H:`. The `HOMEPATH` environment variable is set to `\`. Because of this, I decided to set the `CF_HOME` environment variable.

Here are the steps I followed:
1. Downloaded and installed VirtualBox 5.1.10
2. Downloaded and installed Cloud Foundry CLI 6.22.2
3. Created the new home directory and set the `CF_HOME` environment variable:
    ```
    # Creates a new Cloud Foundry home directory if it doesn't exist
    $CfHome = Join-Path $env:ProgramData CloudFoundry
    if (!(Test-Path $CfHome -PathType Container)) {
        New-Item $CfHome -ItemType Directory > $null
    }

    # Sets machine-level environment variable
    [Environment]::SetEnvironmentVariable("CF_HOME", $CfHome, [EnvironmentVariableTarget]::Machine)
    ```
4. Set the two proxy environment variables:
    ```
    [Environment]::SetEnvironmentVariable("HTTP_PROXY", "http://redacted.com", [EnvironmentVariableTarget]::Machine)
    [Environment]::SetEnvironmentVariable("HTTPS_PROXY", "http://redacted.com", [EnvironmentVariableTarget]::Machine)
    ```
5. Closed all PowerShell windows
6. Downloaded PCF Dev 0.22.0
7. Opened a new PowerShell window as an administrator and executed `pcfdev-v0.22.0+PCF1.8.2-windows.exe`

Here's the output from the PCF Dev installer:
```
Installing plugin pcfdev-v0.22.0+PCF1.8.2-windows.exe...
FAILED
The file pcfdev-v0.22.0+PCF1.8.2-windows.exe already exists under the plugin directory.
```
My `C:\ProgramData\CloudFoundry` directory is empty. I don't know what directory the installer is using because it doesn't say in its output.

Cloud Foundry CLI says I have no plugins installed:
```
Listing Installed Plugins...
OK

Plugin Name   Version   Command Name   Command Help
```

Help!

**Comment by nathan-alden-sr** [comment]
I edited my original post to redact the proxy URLs. Can you folks please make the same change in Pivotal Tracker?

**Comment by sclevine** [comment]
Hi @nathan-alden,

Can you try installing the plugin with:
```
cf install-plugin .\pcfdev-v0.22.0+PCF1.8.2-windows.exe
```
(The Tracker story bot has a character limit, so your proxy URLs were not copied into Tracker.)

**Comment by nathan-alden-sr** [comment]
Unfortunately, that didn't seem to work:
```
C:\Users\Redacted\Downloads>cf install-plugin pcfdev-v0.22.0+PCF1.8.2-windows.exe

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin pcfdev-v0.22.0+PCF1.8.2-windows.exe? (y or n)> y

Installing plugin pcfdev-v0.22.0+PCF1.8.2-windows.exe...
FAILED
The file pcfdev-v0.22.0+PCF1.8.2-windows.exe already exists under the plugin directory.
```

**Comment by sclevine** [comment]
Can you provide the output of `cf plugins`?

**Comment by nathan-alden-sr** [comment]
I did in my OP; it shows no plugins installed. Here it is again:
```
PS C:\> cf plugins
Listing Installed Plugins...
OK

Plugin Name   Version   Command Name   Command Help
PS C:\>
```

**Comment by nathan-alden-sr** [comment]
I think it's possible I had, long ago, installed PCF Dev. Before doing all of this, I had uninstalled all Cloud Foundry installations. Not sure if that matters.

**Comment by sclevine** [comment]
It seems like you have a plugin in `~\.cf\plugins\` that doesn't have an entry in `~\.cf\plugins\config.json`. Can you delete that file, if you can find it?

**Comment by sclevine** [comment]
Also, as a workaround, you could try renaming the plugin (ex. to `pcfdev-v0.22.0+PCF1.8.2-windows-NEW.exe`) before running it.

**Comment by sclevine** [comment]
If neither of those suggestions work, could you try installing any other plugin from https://plugins.cloudfoundry.org/ and see if you get the same error?

**Comment by nathan-alden-sr** [comment]
I found two `.cf` folders. I didn't know they were hidden, though! That's why I thought my `ProgramData` folder was empty:
```
C:\Users\All Users\CloudFoundry\.cf
C:\ProgramData\CloudFoundry\.cf
```
Unfortunately, I didn't find a `plugins` folder in either of those `.cf` folders. Both `config.json`s did not appear to reference the plugin.

**Comment by nathan-alden-sr** [comment]
I figured out what's going on. Apparently, Cloud Foundry is _not_ using my `CF_HOME` environment variable. The _real_ .cf folder is still `H:\.cf`. This may be because I didn't restart my machine after setting the system environment variables. I'll give that a try now.

**Comment by sclevine** [comment]
Did you try renaming the plugin?

Also, can you check if you have the `CF_PLUGIN_HOME` env var set?

**Comment by nathan-alden-sr** [comment]
That was part of the issue. I ended up setting both `CF_HOME` and `CF_PLUGIN_HOME` to `C:\ProgramData\CloudFoundry`. Now `cf` is downloading the plugins to the correct directory structure of `C:\ProgramData\CloudFoundry\.cf\plugins`.

Sorry for the trouble, guys!
