### ISSUE TITLE
pcf dev install failed

### ISSUE THREAD

**Issue by ghost** [vmware-archive/pcfdev#179]
PCF dev install failed with Error: exec: "cmd": executable file not found in %!P(MISSING)ATH%!.(MISSING)

after hitting y for accepting the license agreement im getting Error: exec: "cmd": executable file not found in %!P(MISSING)ATH%!.(MISSING)  please help me what to do to solve the issue

Im using windows 10 OS
i have followed same instructions provided in https://docs.pivotal.io/pcf-dev/install-windows.html#virtualbox

**Comment by sclevine** [comment]
Closing due to lack of response and inability to replicate. Please let us know if you're still experiencing this issue and can provide the requested debugging info.
