### ISSUE TITLE
Cannot connect to MySQL database in PCFDev through a SQL Client (HeidiSQL)

### ISSUE THREAD

**Issue by cshubhra** [vmware-archive/pcfdev#182]
I can connect to this database using JPA - however I do not want hibernate to create my database objects, so I tried to connect using SQL client using the following information extracted from the system provided environment variables

            "hostname": "mysql-broker.local.pcfdev.io",
            "port": 3306,
            "name": "<Name in the env variable>",
            "username": "<username in the env variable>",
            "password": "<password in the env variable>",

However I am getting an access denied error. I need to connect to the mysql instance for creating the db objects in a controlled manner

**Comment by sclevine** [comment]
Hi @cshubhra,

What version of PCF Dev are you using?

**Comment by cshubhra** [comment]
pcfdev-v0.21.0+PCF1.8.2-windows

**Comment by sclevine** [comment]
Can you upgrade to the latest version, or at least to v0.22.0 if you need PCF 1.8.2 components?

**Comment by cshubhra** [comment]
Will it fix? I have not seen a change log which states that this has been fixed

**Comment by sclevine** [comment]
I'm pretty sure I've done this successfully with v0.21.0, but I just tested this with v0.23.0, and I have no issues connecting (using the built-in p-mysql service, bound to an app, with the credentials you mention). I'm connecting from Sequel Pro on my Mac.

**Comment by cshubhra** [comment]
You can close the issue. I believe it may be a problem with the SQL Client. I re-tried with My SQL Workbench, and it worked

**Comment by sclevine** [comment]
Thanks!
