### ISSUE TITLE
PCF Dev not resolving api although running successfully

### ISSUE THREAD

**Issue by mcnichol** [vmware-archive/pcfdev#183]
I feel pretty strongly that I haven't missed anything in the documentation as it is straight forward although I've made mistakes in the past....

I am on a Mac, I installed the plugin, I have Virtualbox > 5 with brew as my package manager.

`$ cf dev start`

Everything runs, PCF Dev banner pops, 57 services running....looks good.

Running:
```
cf login -a https://api.local.pcfdev.io --skip-ssl-validation
```

Gives me:
```
API endpoint: https://api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp: lookup api.local.pcfdev.io: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
```

I run: 
`cf dev status`

It gives me
```
Running
CLI Login: cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass
```

I can't get to the Apps Manager https://local.pcfdev.io either. It feels like I'm doing everything right, the instructions are quite simple, they seem hard to mess up (at this point at least).

**Comment by mcnichol** [comment]
When I worked through using PCF Dev offline setting up my own dns as instructed in the [working offline](http://docs.pivotal.io/pcf-dev/work-offline.html) section of the pivotal docs, everything appears to be working.  

Would I be correct in saying this is the endpoint you have exposed that is not resolving correctly or is there something else going on here?

Second.  For the PCF Dev dash, is the expected behavior to have self-signed certs and having devs manually bring them in to quiet Chrome down?

**Comment by sclevine** [comment]
Do you happen to have custom router firmware (ex. dd-wrt, openwrt, tomato) that is configured to prevent DNS re-bind attacks? That would prevent you from resolving any public DNS records that specify private IP ranges.

To prevent the certificate warnings (and allow you to skip the `--skip-ssl-validation` flag), you can start PCF Dev with `cf dev start -k`. This adds the PCF Dev self-signed cert to the OS certificate store.

**Comment by mcnichol** [comment]
I have dd-wrt.  Didn't think to check that. I will check that and report
back. Likely resolves it, thanks!

I had seen the self-signed cert solution. Wasn't sure if it was final
solution.  Thanks for that.

**Comment by sclevine** [comment]
Closing as this seems to be addressed. Let us know if we should re-open.
