### ISSUE TITLE
Upgrade Option

### ISSUE THREAD

**Issue by mcowger** [vmware-archive/pcfdev#185]
We should have a `cf dev upgrade` option to make it easy to upgrade when a new version of pcfdev is released...

**Comment by sclevine** [comment]
This feature is on the roadmap, but I don't have an estimate for when it will be delivered.

**Comment by sclevine** [comment]
The next release of PCF Dev will use the new [CF Dev](https://github.com/pivotal-cf/cfdev) project (which provides real BOSH and runs on native hypervisors) as its backend. Upgrades will work via BOSH and/or OpsManager.
