### ISSUE TITLE
apps manager default domain

### ISSUE THREAD

**Issue by jbayer** [vmware-archive/pcfdev#186]
apps manager worked like a charm, but i noticed that it resolved to capps-manager.local2.pcfdev.io or console.local2.pcfdev.io rather than apps.local2.pcfdev.io. in PCF, apps mgr now only resolves to apps.SYSTEMDOMAIN by default. is there a reason it's using console rather than apps in PCF Dev?

**Comment by sclevine** [comment]
No reason, seems like we missed that PCF change. This will be fixed in 0.24.0.
Thanks for the report!

**Comment by sclevine** [comment]
@jbayer fixed in 0.24.0 😃
