### ISSUE TITLE
PCF DEV installation failed

### ISSUE THREAD

**Issue by kkkkramu** [vmware-archive/pcfdev#187]
I am trying to  start PCF DEV on my windows 7 mechine. But got failed.  then i tried to connect to PCCF end point but that also giving error. as i am new to this Cloud world unable to solve. please help me.

D:\Ram\PCF>cf dev start

Less than 4069 MB of free memory detected, continue (y/N): ←[36;1m>←[0m y
Using existing image.
Allocating 4069 MB out of 8139 MB total system memory (2777 MB free).
Importing VM...
Starting VM...
←[31;1mFAILED←[0m
Error: failed to start VM: failed to execute 'C:\Program Files\Oracle\VirtualBox
\VBoxManage startvm pcfdev-v0.436.0 --type headless': exit status 1: Waiting for
 VM "pcfdev-v0.436.0" to power on...
VM "pcfdev-v0.436.0" has been successfully started.
.

D:\Ram\PCF>cd .\spring-music-master

D:\Ram\PCF\spring-music-master>cd..

D:\Ram\PCF>cf login -a api.local.pcfdev.io --skip-ssl-validation
API endpoint: api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.
168.11.11:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_pr
oxy environment variable is correctly set. Else, check your network connection.

D:\Ram\PCF>

**Comment by mdelillo** [comment]
Hi @kkkkramu,

It looks like you only had 2777MB of free memory available when you started PCF Dev:
`Allocating 4069 MB out of 8139 MB total system memory (2777 MB free).`

We recommend having [at least 3GB](https://docs.pivotal.io/pcf-dev/index.html#prerequisites) of memory available. Can you try freeing up some memory and then starting PCF Dev again?

**Comment by sclevine** [comment]
PCF Dev requires at least 3GB (ideally 4GB) of system memory to run. See [here](https://docs.pivotal.io/pcf-dev/index.html#prerequisites). The output you provide shows that you don't have enough memory available:
```
Less than 4069 MB of free memory detected, continue (y/N): ←[36;1m>←[0m y
```
Also, we strongly recommend using PowerShell instead of `cmd.exe` for a better experience (without the "`←[36;1m>←[0m`"). See [here](https://docs.pivotal.io/pcf-dev/install-windows.html).

**Comment by sclevine** [comment]
Also, we strongly recommend using PowerShell instead of cmd.exe for a better experience (without the "`←[36;1m>←[0m`"). See [here](https://docs.pivotal.io/pcf-dev/install-windows.html).

**Comment by kkkkramu** [comment]
Hi mdelillo and sclevine

Again got the same issue. this time i took more than 4GB memory, and VM is dowloaded from PCF Dev site. 

Downloading VM...
Progress: |====================>| 100%
VM downloaded.
Allocating 4069 MB out of 8139 MB total system memory (4268 MB free).
Importing VM...
Starting VM...
Error: failed to start VM: failed to execute 'C:\Program Files\Oracle\VirtualBox
\VBoxManage startvm pcfdev-v0.436.0 --type headless': exit status 1: Waiting for
 VM "pcfdev-v0.436.0" to power on...
VBoxManage.exe: error: The virtual machine 'pcfdev-v0.436.0' has terminated unex
pectedly during startup with exit code 1 (0x1).  More details may be available i
n 'C:\Users\RAMMURTHY RAJU\.pcfdev\vms\pcfdev-v0.436.0\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap,
 interface IMachine
.


Here is my few lines of VM log file

1584.1768:   000000013fa88000-000000013fa8cfff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume2\Program Files\Oracle\VirtualBox\VirtualBox.exe
1584.1768:   000000013fa8d000-000000013fa8dfff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume2\Program Files\Oracle\VirtualBox\VirtualBox.exe
1584.1768:   000000013fa8e000-000000013fa8efff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume2\Program Files\Oracle\VirtualBox\VirtualBox.exe
1584.1768:   000000013fa8f000-000000013fa92fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume2\Program Files\Oracle\VirtualBox\VirtualBox.exe
1584.1768:   000000013fa93000-000000013fadafff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume2\Program Files\Oracle\VirtualBox\VirtualBox.exe
1584.1768:   000000013fadb000-fffff8037fc55fff 0x0001/0x0000 0x0000000
1584.1768:  *000007feff960000-000007feff960fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume2\Windows\System32\apisetschema.dll
1584.1768:   000007feff961000-000007fdff311fff 0x0001/0x0000 0x0000000
1584.1768:  *000007fffffb0000-000007fffff8cfff 0x0002/0x0002 0x0040000
1584.1768:   000007fffffd3000-000007fffffcafff 0x0001/0x0000 0x0000000
1584.1768:  *000007fffffdb000-000007fffffd9fff 0x0004/0x0004 0x0020000
1584.1768:   000007fffffdc000-000007fffffd9fff 0x0001/0x0000 0x0000000
1584.1768:  *000007fffffde000-000007fffffdbfff 0x0004/0x0004 0x0020000
1584.1768:  *000007fffffe0000-000007fffffcffff 0x0001/0x0002 0x0020000
1584.1768: apisetschema.dll: timestamp 0x4a5bdeab (rc=VINF_SUCCESS)
1584.1768: VirtualBox.exe: timestamp 0x58594e7b (rc=VINF_SUCCESS)
1584.1768: '\Device\HarddiskVolume2\Program Files\Oracle\VirtualBox\VirtualBox.exe' has no imports
1584.1768: '\Device\HarddiskVolume2\Windows\System32\apisetschema.dll' has no imports
1584.1768: '\Device\HarddiskVolume2\Windows\System32\ntdll.dll' has no imports
1584.1768: supR3HardNtChildPurify: Done after 290 ms and 0 fixes (loop #0).
a20.1abc: Log file opened: 5.1.12r112440 g_hStartupLog=0000000000000004 g_uNtVerCombined=0x611db100
a20.1abc: supR3HardenedVmProcessInit: uNtDllAddr=0000000077640000 g_uNtVerCombined=0x611db100
1584.1768: supR3HardNtEnableThreadCreation:
a20.1abc: ntdll.dll: timestamp 0x4ce7c8f9 (rc=VINF_SUCCESS)
a20.1abc: New simple heap: #1 0000000000260000 LB 0x400000 (for 1740800 allocation)
a20.1abc: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume2\Program Files\Oracle\VirtualBox'
a20.1abc: System32:  \Device\HarddiskVolume2\Windows\System32
a20.1abc: WinSxS:    \Device\HarddiskVolume2\Windows\winsxs
a20.1abc: KnownDllPath: C:\Windows\system32
a20.1abc: supR3HardenedVmProcessInit: Opening vboxdrv stub...
a20.1abc: supR3HardenedVmProcessInit: Restoring LdrInitializeThunk...
a20.1abc: supR3HardenedVmProcessInit: Returning to LdrInitializeThunk...
a20.1abc: Registered Dll notification callback with NTDLL.
a20.1abc: supHardenedWinVerifyImageByHandle: -> 22900 (\Device\HarddiskVolume2\Windows\System32\kernel32.dll)
a20.1abc: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume2\Windows\System32\kernel32.dll
a20.1abc: supR3HardenedMonitor_LdrLoadDll: pName=C:\Windows\system32\kernel32.dll (Input=kernel32.dll, rcNtResolve=0xc0150008) *pfFlags=0xffffffff pwszSearchPath=0000000000000000:<flags> [calling]
a20.1abc: supR3HardenedScreenImage/NtCreateSection: cache hit (Unknown Status 22900 (0x5974)) on \Device\HarddiskVolume2\Windows\System32\kernel32.dll [lacks WinVerifyTrust]
1584.1768: Error (rc=258):
1584.1768: Timed out after 60001 ms waiting for child request #1 (CloseEvents).
1584.1768: Error 258 in supR3HardNtChildWaitFor! (enmWhat=5)
1584.1768: Timed out after 60001 ms waiting for child request #1 (CloseEvents).

**Comment by sclevine** [comment]
Can you run other VMs in Virtualbox? Have you tried re-installing Virtualbox 5.1 and rebooting after?

**Comment by sclevine** [comment]
Closing for now due to inactivity. Let us know if you're still having issues with PCF Dev.

**Comment by mahendraph** [comment]
I am  having simillar issue:

Downloading VM...
Progress: |++++++==============>| 100%
VM downloaded.
Allocating 4096 MB out of 16260 MB total system memory (10601 MB free).
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: failed to execute 'C:\Program Files\Oracle\VirtualBox\VBoxManage startvm pcfdev-v0.547.0 --type headle
ss': exit status 1: Waiting for VM "pcfdev-v0.547.0" to power on...
VM "pcfdev-v0.547.0" has been successfully started.
