### ISSUE TITLE
PCF Dev VM starting failed

### ISSUE THREAD

**Issue by kkkkramu** [vmware-archive/pcfdev#188]
I am starting PCF Dev from below VM.
![image](https://cloud.githubusercontent.com/assets/24977880/21744333/71913b84-d539-11e6-9b60-53008d747933.png)

But getting the below issue

The virtual machine 'pcfdev-v0.436.0' has terminated unexpectedly during startup with exit code 1 (0x1). More details may be available in 'C:\Users\RAMMURTHY RAJU\.pcfdev\vms\pcfdev-v0.436.0\Logs\VBoxHardening.log'.

Result Code: 
E_FAIL (0x80004005)
Component: 
MachineWrap
Interface: 
IMachine {f30138d4-e5ea-4b3a-8858-a059de4c93fd}

**Comment by sclevine** [comment]
Hi @kkkkramu,

Starting the PCF Dev VM manually in Virtualbox is not supported and will not work. That said, you're experiencing the same issue that you reported in #187, so I'm closing this issue for now.

Please ensure that you have enough free memory to run PCF Dev (at least 3GB, and ideally 4GB of free RAM), and re-install Virtualbox 5.1+.  If that doesn't fix your issue, confirm that you can start other VMs in Virtualbox, and follow up with us in #187.
