### ISSUE TITLE
32 bit pcfdev support on windows

### ISSUE THREAD

**Issue by muralaris** [vmware-archive/pcfdev#193]
Hi,
Can we run pcf dev in a 32 bit windows 7 OS.
I am using 32 bit CLI and when i try to install the latest pcfdev-v0.24.0+PCF1.9.0-windows.exe, errors are reported wrt to version of the binary used.(I presume the binary is 64 bit)
Please throw some light on its support for 32 bit windows.
-Murali

**Comment by mdelillo** [comment]
Hi @muralaris,

PCF Dev does not support 32 bit OSs. The binaries are only compiled for 64 bit OSs, and it is unlikely that a 32 bit machine would have enough free memory to run PCF Dev (it requires at least 3GB but 4GB is recommended).

**Comment by sclevine** [comment]
It's not just a memory issue -- attempting to virtualize (really emulate) a 64-bit Ubuntu VM on a 32-bit machine would be very slow (maybe not even possible with Virtualbox).

(If you happen to have 64-bit hardware under your 32-bit OS, it may be possible to get this working, but you would likely run into the memory limitation that Mark brings up.)

**Comment by muralaris** [comment]
Thanks for the clarification.
