### ISSUE TITLE
CF dev Start Failed on Windows 10 Machine.

### ISSUE THREAD

**Issue by abhijitpatil1009** [vmware-archive/pcfdev#200]
Hi Stephen,
I am facing issue-cf dev start Failed, I am installing CFdev on windows10 machine. I have 64 bit machine and I have installed Virtual box 5.1.14 

Downloading VM...
Progress: |====================>| 100%
VM downloaded.
Allocating 3575 MB out of 7150 MB total system memory (3197 MB free).
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: ssh connection timed out: ssh: handshake failed: read tcp 127.0.0.1:60481->127.0.0.1:60422: wsarecv: An existing connection was forcibly closed by the remote host..

If I check in Virtual box in give me error pop up message "VT-x/AMD-vHardware acceleration not available on your machine  "
![image](https://cloud.githubusercontent.com/assets/25744576/23500572/9a1efd6a-ff56-11e6-80b6-2a343dc1d767.png)

Please Help
Thanks a lot !
Abhijit patil.

**Comment by sclevine** [comment]
@abhijitpatil1009 The `VT-x/AMD-v Hardware acceleration not available on your machine` error is likely due to an attempt to run `cf dev start` from within another VM that doesn't support nested virtualization. For example, most cloud VM solutions don't support VT-x.

**Comment by abhijitpatil1009** [comment]
HI Stephen,
 I am trying to install Cf Dev on my local machine, I have 8GB RAM and 500GB HDD
got following error

Error: failed to start VM: ssh connection timed out: ssh: handshake failed: read tcp 127.0.0.1:60481->127.0.0.1:60422: wsarecv: An existing connection was forcibly closed by the remote host..

**Comment by sclevine** [comment]
Hi @abhijitpatil1009,

Can you run `cf dev destroy`, and then provide the full output of running `cf dev start`?

Also, if you're running a restrictive firewall (that prevents applications from binding to localhost), can you see if disabling it allows PCF Dev to start successfully?

**Comment by abhijitpatil1009** [comment]
Thanks Stephen,
I have destroyed existing dev then tried to run cf dev start command it uses existing image and tried to import vm. I have installed mention plug-in of pcf dev v0.24.0+PCF-windows1.9.0. I have pasted detail error below.  Yes , I also think my company firewall may causes some issue,that's why I also tried it on Azure VM as well.
<---Screen log--->
C:\CloudFoundry>cf uninstall-plugin pcfdev
Uninstalling plugin pcfdev...
OK
Plugin pcfdev successfully uninstalled.

C:\CloudFoundry>.\pcfdev-v0.24.0+PCF1.9.0-windows
Plugin successfully installed. Current version: 0.24.0. For more info run: cf dev help

C:\CloudFoundry>cf dev start

Less than 3575 MB of free memory detected, continue (y/N): > Y
Using existing image.
Allocating 3575 MB out of 7150 MB total system memory (1526 MB free).
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: ssh connection timed out: ssh: handshake failed: read tcp 127.0.0.1:59061->127.0.0.1:59002: wsarecv: An existing connection was forcibly closed by the remote host..

C:\CloudFoundry>cf dev destroy
PCF Dev VM has been destroyed.

C:\CloudFoundry>
<----end--->

Please Help in it as well->
After successful deployment PCF dev my main objective is to deployed ASP.NET applications on cloud foundry, please suggest the Right way to do it. 
Please let me know
can I use AWS VM to deploy PCF Dev?
Using PCF dev can I deploy the ASP.Net applications(not .NET Core) i.e ASP.NET 3.5/4.0/MVC on PCFdev environment.

Thanks Again!

**Comment by sclevine** [comment]
> `Less than 3575 MB of free memory detected, continue (y/N): > Y`

You'll need more free memory for PCF Dev to run smoothly, or to push more than a few apps. 

> `Error: failed to start VM: ssh connection timed out: ssh: handshake failed: read tcp 127.0.0.1:59061->127.0.0.1:59002: wsarecv: An existing connection was forcibly closed by the remote host..`

Seems like an issue with your local firewall. Can you disable it or reconfigure it to allow applications to bind to localhost?

> Using PCF dev can I deploy the ASP.Net applications(not .NET Core) i.e ASP.NET 3.5/4.0/MVC on PCFdev environment.

No, PCF Dev does not support Windows stacks at this time.

> can I use AWS VM to deploy PCF Dev?

No, just like Azure, AWS does not support VT-x.

**Comment by abhijitpatil1009** [comment]
Thank you very much for resolving my confusion. I am finding correct way to migrate ASP.NET applications on Cloud foundry. Please help me to find  the right way.
Please guide on following 
1.How I can deploy Asp.net Applications on pivotal cloud foundry?
2.Do Pivotal have any build pack for legacy .net applications(3.5/4.0) or in future we get it?
3.how we can enable windows stack on Pivotal Or we have to deploy pivotal on private environment Or Azure?
4.are there any way in pivotal CF, that helps ?
5.As you said AWS, Azure  does not support VT-x so, can we use normal PCF on them or not? 
6.I have tried to set up BOSH on Azure VM however I was unable to target IP 192.168.50.1, got error"cannot access director-connection refused". 
![image](https://cloud.githubusercontent.com/assets/25744576/23784874/9c421a34-058a-11e7-9b7f-103f91d41c2f.png)

7.for ASP.Net application deployment DIEGO could help,however please let me know,how I can set up DIEGO on VM or AWS VM or any other workstation?

Please suggest details links or blogs which I can refer and find the way to deploy applications on Cloud foundry.

Thanks again!

**Comment by sclevine** [comment]
Hi @abhijitpatil1009,

Are you interested in purchasing PCF? If so, please reach out to sales@pivotal.io for more information on our PCF offerings. They include support for Windows stacks, which can run ASP.NET applications.

VT-x is only required to run PCF Dev, not PCF. A full PCF installation does not require nested virtualization.

If you're attempting to deploy vanilla Cloud Foundry with support for Windows, check out these repositories:
https://github.com/cloudfoundry/diego-windows-release
https://github.com/cloudfoundry/garden-windows

This Github repo is for questions about PCF Dev. See the BOSH documentation for information on deploying BOSH to Azure:
https://bosh.io/docs/init-azure.html

**Comment by abhijitpatil1009** [comment]
Thanks!Yes if it supports ASP.NET application deployments without any hassle. Sure I will connect with support and sales team.
I have check the repositories as well however in that I Found "working CF/Diego deployment with windows stack" required. no steps to deploy windows stack.

Thanks A lot!!

**Comment by santoshgodavarthi** [comment]
Hi,

I have tried all the possible options mentioned in this thread, even though I am struck with the same issue, I have some observations and want to know more about them

1) cf dev start (without any -m option) gives the following error.

Less than 4033 MB of free memory detected, continue (y/N): ←[36;1m>←[0m yes
Using existing image.
Starting VM...
←[31;1mFAILED←[0m
Error: failed to start VM: failed to execute 'VBoxManage.exe startvm pcfdev-v0.5
47.0 --type headless': exit status 1: Waiting for VM "pcfdev-v0.547.0" to power
on...
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_
MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole
.

From the error it is clear that VT-x is not enabled at BIOS level on my machine. HOwever, in the Oracle Vitual Box manager I do see the VM in stopped mode and when I lower the memory requirement to some 3099 MB and do a headless start from the Oracle VM Manager, VM starts. Not sure how to interpret this.

2) cf dev start ( with an -m 3099 option)  gives the following error

C:\Program Files\Oracle\VirtualBox>cf dev start -d local.pcfdev.io -m 3099

Less than 3099 MB of free memory detected, continue (y/N): ←[36;1m>←[0m yes
Using existing image.
Allocating 3099 MB out of 8067 MB total system memory (2337 MB free).
Importing VM...
Starting VM...
←[31;1mFAILED←[0m
Error: failed to start VM: ssh connection timed out: ssh: handshake failed: read
 tcp 127.0.0.1:61867->127.0.0.1:61454: wsarecv: An existing connection was forci
bly closed by the remote host..

This seems to be a firewall issue, but I have disabled all my firewalls. This also appears in the Oracle VM manager and would start right away when I do a headless start from there. 

Can you please help with understanding/resolving the issue.

**Comment by duthng** [comment]
I used the command in power shell as admin

netsh http add iplisten 127.0.0.1

in https://stackoverflow.com/questions/34543443/cant-access-127-0-0-1 

and it worked.
