### ISSUE TITLE
 Error performing request: Get https://api.local.pcfdev.io/v2/info: Service Unavailable

### ISSUE THREAD

**Issue by amitrajbaral** [vmware-archive/pcfdev#201]
API endpoint: https://api.local.pcfdev.io FAILED
 Error performing request: Get https://api.local.pcfdev.io/v2/info: Service Unavailable

I was using Mac and following steps below to setup PCF dev.
https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry-dev/deploy-the-sample-app 

It was working well until i login with api URI. I am using corporate network and used https_proxy and http_proxy as well with no success. One of my colleague was having similar issue  and suggested me to use different domain  api.local3.pcfdev.io but it also did not work and i got same error.

Looking for some suggestions.

**Comment by sclevine** [comment]
Hi @amitrajbaral,

Did you set `NO_PROXY` before attempting to connect with the cf CLI, as mentioned in [the docs](https://docs.pivotal.io/pcf-dev/proxy.html#allow-cf-cli-behind-proxy)?

**Comment by amitrajbaral** [comment]
Yeah, it was missing thank you very much. it worked like charm now.

**Comment by DreamYueYue** [comment]
Hi,@sclevine 
How to set NO_PROXY?And for where ?
