### ISSUE TITLE
PCF Dev login failed on Local Workstation

### ISSUE THREAD

**Issue by vgindin** [vmware-archive/pcfdev#203]
Hi, I've faced with the problem during the "Try PCF on your Local Workstation with PCF Dev" tutorial.
I've installed CLI, PCF Dev and ran it. When I'm trying to login I got the error:

```
[vig:~] $ cf login -a api.local.pcfdev.io --skip-ssl-validation
API endpoint: api.local.pcfdev.io

Email> ****

Password> 
Authenticating...
Credentials were rejected, please try again.

Password> 
```

I'm getting the same error when trying to specify user Email and Password in command line using -u and -p parameters.

I can successfully loging in web page of pivotal network, or I've successfully went through PCF Web Services tutorial using the same credentials. So the credentials are correct.

Environment.
My machine is Lubuntu 16.04 Xenial. 
PCF Dev distrib is pcfdev-v0.24.0+PCF1.9.0-linux.zip

**Comment by sclevine** [comment]
Hi @vgindin,

PCF Dev only requires your PivNet credentials to download and start the VM.
Once the VM is started, you should see a message that looks like this:
```
To begin using PCF Dev, please run:
   cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass
```
The "Admin user" and "Regular user" credentials are the default credentials for PCF Dev.
Alternatively, running:
```
cf dev target
```
will log you into PCF Dev using the cf CLI automatically, without needing to enter credentials.

**Comment by sclevine** [comment]
Closing this for now. Let me know if this didn't address your question.
