### ISSUE TITLE
Spring Boot Actuator Integration is not working

### ISSUE THREAD

**Issue by ynojima** [vmware-archive/pcfdev#205]
Hello,
I deployed an Actuator enabled Spring Boot application on PCFDev v0.24 on windows, but the Apps Manager won't enable Spring Boot integration feature.
I confirmed my Spring Boot application's actuator works fine on PCF Cloud.
Is actuator integration feature is omitted on PCFDev by design?

https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-cloudfoundry.html

**Comment by sclevine** [comment]
I believe the version of Apps Manager shipped with 1.9.0 does not have actuator support. This should be included in the next release of PCF Dev (for PCF 1.10).

**Comment by ynojima** [comment]
Thank you for your response. But the document for PCF v1.9 explains Spring Boot Actuator support. Is it documentation mistake?
https://docs.pivotal.io/pivotalcf/1-9/console/using-actuators.html

**Comment by sclevine** [comment]
No, that documentation is correct. The latest release of PCF Dev is based off of the first release of PCF 1.9, which was PCF 1.9.**0**. I believe that they introduced Actuator support in a later patch release of PCF 1.9.

**Comment by ynojima** [comment]
Thank you for your clarification. I'll wait for the release of PCF Dev based on 1.10.

**Comment by mdelillo** [comment]
Hi @ynojima, the latest release (v0.26.0) has Apps Manager integration for Spring Boot Actuator. Note that if your app uses a self-signed cert, you'll need to visit the app and accept the security warning your browser gives you before the spring integration can work.

**Comment by ynojima** [comment]
Hi, I confirmed Spring Boot integration works on the latest release of PCF Dev. Thanks a lot!

**Comment by dwilliss** [comment]
One thing that I have noticed is that if you add spring boot actuators to an existing program and then repush it, the apps manager will ignore them until you log out and log back in.
