### ISSUE TITLE
Downloading VM failed

### ISSUE THREAD

**Issue by KalyanVudath** [vmware-archive/pcfdev#206]
$cf dev start
Downloading VM...
[31;1mFAILED[0m
Error: Pivotal Network returned: 416 Requested Range Not Satisfiable.

How should i fix this issue.

I am using windows7 64 bit.

**Comment by sclevine** [comment]
Hi @KalyanVudath,

Are you using PCF Dev v0.24.0? I cannot replicate this failure on Windows 7 64-bit using v0.24.0.

Do you require an HTTP proxy to connect to the internet? If so, see here:
https://docs.pivotal.io/pcf-dev/proxy.html

If configuring your proxy settings appropriately does not work, you can find the corresponding OVA version for your plugin using `cf dev version` (ex. OVA v0.447.0 for plugin v0.24.0), download the OVA manually from the **"internal"** release on PivNet, and then run `cf dev import /path/to/ova`.

**Comment by KalyanVudath** [comment]
I am using pcfdev-v0.24.0+PCF1.9.0-windows. Let me know which version should i use and from where should i download the other version.

Sorry i am using windows 10 Home, 64 bit

**Comment by sclevine** [comment]
You are using the correct version. Can you confirm that you don't require a proxy to connect to the internet?

**Comment by KalyanVudath** [comment]
I dont require a proxy to connect to the internet.
I have entered cf dev start in the command prompt, Downloading VM was in progress 100%. It stayed like that for few minutes then i have stopped the command prompt. I tried restarting the command 
cf dev start then i started facing this issue.

**Comment by KalyanVudath** [comment]
Can we manually add the image file to Virtual box. how can we get the image file to add it to virtual box.

**Comment by sclevine** [comment]
As I mentioned, you can:
1. Find the corresponding OVA version for your plugin by running `cf dev version`. In your case, this should be OVA v0.447.0, because you're running plugin v0.24.0.
2. Download the OVA manually from the "internal" release on PivNet here: https://network.pivotal.io/products/pcfdev#/releases/1622
3. Run: `cf dev import /path/to/ova`

**Comment by KalyanVudath** [comment]
OVA version 0.447.0 imported successfully. 

I am able to do the pcf dev start and stop now. Thanks for the help.

**Comment by sclevine** [comment]
Glad that you have it working!
