### ISSUE TITLE
pcfdev-v0.447.0: rror: failed to provision VM: Process exited with: 1. Reason was:  ()

### ISSUE THREAD

**Issue by GiridharJaligama** [vmware-archive/pcfdev#208]
Hi,

While starting pcfdev using cf dev start -s all, throwing below error.
'cf dev start' this commands starts without issues. I want to test spring cloud config services for that I started with cf dev start -s all, its failing. I also tested with cf dev start -s scs, same results (error).

My system details: Windows 10, 16GB RAM

PS C:\> cf dev start -s all
Using existing image.
Allocating 8132 MB out of 16264 MB total system memory (13841 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
8 out of 57 running
8 out of 57 running
8 out of 57 running
35 out of 57 running
57 out of 57 running
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().

-----------------------------------------
PCF Dev: pcfdev-v0.447.0
CF CLI: cf-cli-installer 6.23.1
Virtual box : VirtualBox-5.1.18-114002-Win

Thanks a lot for your help.

Regards,
Giri

**Comment by GiridharJaligama** [comment]
I'm closing this issue, after setting 12GB its working. I think this need to updated some where in docs, min ram need to be set as 12gb otherwise it will not work.

**Comment by sclevine** [comment]
Thanks for the report. Many factors play into whether your system is performant enough to start PCF Dev with SCS successfully. Usually 8GB of RAM is sufficient, but I'll consider having PCF Dev allocate up to 10GB when more than 8GB is available. Apologies for the poor logging when starting the VM fails in this manner.

**Comment by GiridharJaligama** [comment]
Stephen, first I would like to thank you. I saw your suggestions on many issues then I went on checking provision.log, first time I set 8GB it failed in loading 1 buildpack, then I increased to 10GB I saw that buildpack loaded next it failed on 2nd buildpack, increased to 12gb then all buildpacks loaded and issue resolved.

I have one question, for my requirement I dont want all the buildpacks for now. To improve is there a way  I can disable for buildpack while PROVISIONING VM? I know command to delete buildpack, but this is after starting of cf, and its provisioned CF with 12gb.

**Comment by sclevine** [comment]
We don't have support for that functionality, and I wouldn't expect the availability of the buildpacks to make a noticeable difference in performance. Are you able to replicate these failures?

We will definitely review the performance requirements of PCF Dev running SCS before the next release.
