### ISSUE TITLE
PCF Dev remote access 

### ISSUE THREAD

**Issue by cdharma** [vmware-archive/pcfdev#211]
Hi 
I have a PCF Dev instance on my macbook pro which i can log in to successfully and i can log in to this url as well : https://uaa.local.pcfdev.io/login
I want other developers on the same network as i am to be able to do the same i.e. they should also be open this url https://uaa.local.pcfdev.io/login and remotely login into my pcf dev instance from their machines. 

I am not very sure how to achieve this? Is this possible?

Thanks

**Comment by cdharma** [comment]
any idea guys?

**Comment by sclevine** [comment]
PCF Dev does not currently support this workflow. PCF Dev is not a secure distribution of PCF, so we don't encourage you to make access available to multiple tenants.

That said, it may be possible to achieve this by forwarding certain VM ports to the host (80, 443, and 2222), and making the PCF Dev system domain (*.local.pcfdev.io) resolve to the host IP when queried from the other machines on your network. This is not trivial to configure and not secure, so we don't encourage it.

**Comment by sclevine** [comment]
Closing this for now.
