### ISSUE TITLE
PCFDev (pcfdev-v0.447.0) cf login failed

### ISSUE THREAD

**Issue by MikeQin** [vmware-archive/pcfdev#212]
I have installed PCFDev successfully on a company laptop.

**pcfdev-v0.447.0**

I also set environment variables:

> http_proxy=http://mycompany.com:80
> https_proxy=http://mycompany.com:80
> no_proxy=*.local.pcfdev.io,localhost,*.mycompany.com

Here was the info I got below ...
Any help will be greatly appreciated.

```
D:\>cf dev start
Using existing image.
Starting VM...
Provisioning VM...
Waiting for services to start...
9 out of 57 running
9 out of 57 running
9 out of 57 running
40 out of 57 running
57 out of 57 running
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
is now running.
To begin using PCF Dev, please run:
   cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass

D:\>cf login -a https://api.local.pcfdev.io --skip-ssl-validation
API endpoint: https://api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: EOF
```

**Comment by MikeQin** [comment]
I was able to ping ...

`D:\>ping api.local.pcfdev.io`

```
Pinging api.local.pcfdev.io [192.168.11.11] with 32 bytes of data:
Reply from 192.168.11.11: bytes=32 time<1ms TTL=64
Reply from 192.168.11.11: bytes=32 time<1ms TTL=64
Reply from 192.168.11.11: bytes=32 time<1ms TTL=64
Reply from 192.168.11.11: bytes=32 time<1ms TTL=64

Ping statistics for 192.168.11.11:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

**Comment by sclevine** [comment]
It seems likely that the `cf` utility is not picking up your `no_proxy` env var, and attempting to connect to 192.168.11.11:443 via your HTTP proxy. Can you confirm that you have `no_proxy` set in that shell? Can you try in PowerShell, as recommended in the docs?

**Comment by MikeQin** [comment]
sclevine: You're 100% correct, after I set http_proxy= and https_proxy= to "null" before cf login, it worked. It's not picking up "no_proxy" setting at all. I will give it a try in PowerShell tomorrow, and let you know.

Thanks,

Mike

**Comment by sclevine** [comment]
Closing this for now, because it appears to have been addressed by the environment variable changes. Let us know if you're still experiencing this issue.
