### ISSUE TITLE
Issue logging into https://api.local.pcfdev.io with pcf dev 0.26.0 on OS X El Capitan

### ISSUE THREAD

**Issue by pilif74** [vmware-archive/pcfdev#215]
I am using OS X El Capitan version 10.11.6 (15G1217), Oracle VirtualBox Version 5.1.14 r112924 (Qt5.6.2), cf version 6.26.0+9c9a261fd.2017-04-06 and pcf dev 0.26.0.

I have followed https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry-dev to install these. My PCF Dev starts cleanly: 56 out of 56 running and 'is now running'. 

When I issue the command: cf login -a https://api.local.pcfdev.io --skip-ssl-validation
I get: Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp: lookup api.local.pcfdev.io: no such host

dig api.local.pcfdev.io gives me:
; <<>> DiG 9.8.3-P1 <<>> api.local.pcfdev.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29407
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.local.pcfdev.io.		IN	A

;; Query time: 69 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Wed Apr 12 13:00:29 2017
;; MSG SIZE  rcvd: 37

**Comment by pilif74** [comment]
I added the following to /etc/hosts
			192.168.11.11   api.local.pcfdev.io
			192.168.11.11   login.local.pcfdev.io

It solved the issue.

**Comment by sclevine** [comment]
@pilif74 You probably won't be able to resolve app domains with just those changes.

We usually see this in two cases:
1. You don't have internet access.
2. You have custom router firmware (ex. dd-wrt) that prevents "DNS rebind attacks" by preventing domains from resolving to private IP ranges.

If you are affected by (2), you can usually disable this setting in your router configuration. Alternatively, in either case, you can use a local DNS cache like dnsmasq to make `*.local.pcfdev.io` resolve to `192.168.11.11`.
