### ISSUE TITLE
bin/build: line 34: wget: command not found

### ISSUE THREAD

**Issue by herrkulesh** [vmware-archive/pcfdev#218]
When building a PCF Dev Box on OSX bin/build fails with
```
$ bin/build
bin/build: line 34: wget: command not found
```
For maximum compatibility I recommend using **curl** instead of **wget** on OSTYPE==darwin*
Successfully tested locally, happy to provide _enhancement_

**Comment by sclevine** [comment]
Closing this, as the next version of PCF Dev won't use this script.
