### ISSUE TITLE
Error performing request: Get https://api.local.pcfdev.io/v2/info: Service unavailable

### ISSUE THREAD

**Issue by gsainagendraprasad** [vmware-archive/pcfdev#219]
Hi over the weekend my system got restarted and morning when i tried to log in to apps manager it was not up. Then i went to power shell window, did a cf dev destroy and then did cf dev start. After all the 56 services start it asked to login and when i tried : cf login -a https://api.local.pcfdev.io --skip-ssl-validation , it is giving this error:

**Error performing request: Get https://api.local.pcfdev.io/v2/info: Service unavailable**

where as i am able to log in to apps manager through browser. Any reason why it is saying service unavailable ??

**Comment by sclevine** [comment]
Can you provide the full output of `cf dev start`?

**Comment by gsainagendraprasad** [comment]
you mean power shell window screen shot ? if so i am sorry i just closed the window.  Do you want me to try cf login command again ?

**Comment by gsainagendraprasad** [comment]
I opened new power shell window and ran cf login command and i was able to login to https://api.local.npcfdev.io.
