### ISSUE TITLE
Error while deploying dotnet core app using dotnet-core_buildpack in to pcfdev.

### ISSUE THREAD

**Issue by gsainagendraprasad** [vmware-archive/pcfdev#220]
Hi,
I wrote a dotnet core app , its an api. when i try to push this into pcfdev using cf push i am getting this below error: (Error restarting application: InsufficientResources). Can i be able to push dotnet core app in pcfdev ??

Here are the power shell logs:

PS C:\VS2015Samples\SecondCoreApi> cf push
Using manifest file C:\VS2015Samples\SecondCoreApi\manifest.yml

Creating app FirstCoreApp in org pcfdev-org / space Demo as admin...
OK

Creating route firstcoreapp-noncontiguous-aerostat.local.pcfdev.io...
OK

Binding firstcoreapp-noncontiguous-aerostat.local.pcfdev.io to FirstCoreApp...
OK

Uploading FirstCoreApp...
Uploading app files from: C:\VS2015Samples\SecondCoreApi
Uploading 61.8K, 46 files
Done uploading
OK

Starting app FirstCoreApp in org pcfdev-org / space Demo as admin...

FAILED
Error restarting application: InsufficientResources

TIP: use 'cf logs FirstCoreApp --recent' for more information
PS C:\VS2015Samples\SecondCoreApi> cf logs FirstCoreApp --recent
Retrieving logs for app FirstCoreApp in org pcfdev-org / space Demo as admin...

2017-04-19T10:43:11.94-0500 [API/0] OUT Created app with guid 6e0e7929-887c-40be-a3a1-6311dba534ae
2017-04-19T10:43:12.19-0500 [API/0] OUT Updated app with guid 6e0e7929-887c-40be-a3a1-6311dba534ae ({"route"=>"76a2c36b-
2849-4011-853e-f1627370b0d0", :verb=>"add", :relation=>"routes", :related_guid=>"76a2c36b-2849-4011-853e-f1627370b0d0"})

2017-04-19T10:43:17.69-0500 [API/0] OUT Updated app with guid 6e0e7929-887c-40be-a3a1-6311dba534ae ({"state"=>"STARTED"}
)

**Comment by sclevine** [comment]
You can push the app with more memory or disk using the `-m` and `-k` options to `cf push`.
If you're running out of memory on the PCF Dev VM itself, you can destroy your VM and re-create it with more memory using the `-m` flag to `cf dev start`.

**Comment by gsainagendraprasad** [comment]
Thank you Stephen, I deleted all the other apps running on my pcfdev and i just pushed this dotnetcore app alone and it started downloading the dot net core build pack. unfortunately it failed at restoring packages.

2017-04-19T11:02:45.83-0500 [STG/0] OUT        log  : Restoring packages for /tmp/app/src/SecondCoreApi/project.json...
2017-04-19T11:02:47.56-0500 [STG/0] OUT        error: Unable to load the service index for source https://api.nuget.org/
v3/index.json.
2017-04-19T11:02:47.56-0500 [STG/0] OUT        error:   An error occurred while sending the request.
2017-04-19T11:02:47.56-0500 [STG/0] OUT        error:   Failure when receiving data from the peer
2017-04-19T11:02:47.61-0500 [STG/0] OUT        FAILED: command failed, exit status 1
2017-04-19T11:02:47.61-0500 [STG/0] OUT        FAILED: Restoring dependencies with Dotnet CLI failed, command failed, ex
it status 1
2017-04-19T11:02:47.61-0500 [STG/0] ERR Failed to compile droplet
2017-04-19T11:02:47.61-0500 [STG/0] OUT Exit status 223
2017-04-19T11:02:47.62-0500 [STG/0] ERR Staging failed: Exited with status 223
2017-04-19T11:02:47.63-0500 [STG/0] OUT Destroying container
2017-04-19T11:02:48.07-0500 [STG/0] OUT Successfully destroyed container

**Comment by sclevine** [comment]
Are your apps able to reach out to the internet? If you're behind a corporate proxy, have you followed [these instructions](https://docs.pivotal.io/pcf-dev/proxy.html), and confirmed that your apps have outbound HTTP connectivity?

**Comment by gsainagendraprasad** [comment]
Yes i did, I was able to deploy java applications before and they were working fine. those applications were able to talk to mavencentral to pull its dependencies.

**Comment by gsainagendraprasad** [comment]
May be this is useful information, when i got to apps manager and click on application EnvVariables i can see this : {
  "staging_env_json": {
    "HTTP_PROXY": "172.22.1.23:8080",
    "HTTPS_PROXY": "172.22.1.23:8080",
    "NO_PROXY": "localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,.local.pcfdev.io",
    "http_proxy": "172.22.1.23:8080",
    "https_proxy": "172.22.1.23:8080",
    "no_proxy": "localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,.local.pcfdev.io"
  },
  "running_env_json": {
    "HTTP_PROXY": "172.22.1.23:8080",
    "HTTPS_PROXY": "172.22.1.23:8080",
    "NO_PROXY": "localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,.local.pcfdev.io",
    "http_proxy": "172.22.1.23:8080",
    "https_proxy": "172.22.1.23:8080",
    "no_proxy": "localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,.local.pcfdev.io"
  },
  "environment_json": "invalid_key",
  "system_env_json": {
    "VCAP_SERVICES": {}
  },
  "application_env_json": {
    "VCAP_APPLICATION": {
      "cf_api": "http://api.local.pcfdev.io",
      "limits": {
        "fds": 16384,
        "mem": 2048,
        "disk": 512
      },
      "application_name": "FirstCoreApp",
      "application_uris": [
        "firstcoreapp-ampherotokous-heritability.local.pcfdev.io"
      ],
      "name": "FirstCoreApp",
      "space_name": "pcfdev-space",
      "space_id": "4a7196f5-9e87-4f87-a875-41e7f8a2e166",
      "uris": [
        "firstcoreapp-ampherotokous-heritability.local.pcfdev.io"
      ],
      "users": null,
      "application_id": "49add544-6ef4-4550-9c5b-7ea316afa091",
      "version": "fc2a0090-fa2f-4161-8b45-2652c8e0e239",
      "application_version": "fc2a0090-fa2f-4161-8b45-2652c8e0e239"
    }
  }
}

**Comment by gsainagendraprasad** [comment]
Hi Stephen, I added a NuGet config file with proxy settings in it , even then i am facing the same issue  :(.
here is my NuGet config file: 

<configuration>
<config>
        <add key="http_proxy" value="http://172.22.1.23:8080" />
        <add key="http_proxy.user" value="Deerfield/sgunturu" />
        <add key="http_proxy.password" value="Mysixthmonth$16" />
</config>
  <packageSources>
    <add key="nuget.org" value="http://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>

**Comment by gsainagendraprasad** [comment]
Hi Stephen, I destroyed and started again using cf dev destroy and cf dev start along with http_proxy settings. After  that I tried to push the app using dotnet-core_buildpack , still it is failing at staging with this below error :(

2017-04-19T15:31:01.399-05:00 [STG/0] [OUT] log : Restoring packages for /tmp/app/src/SecondCoreApi/project.json...
2017-04-19T15:31:03.108-05:00 [STG/0] [OUT] error: Failure when receiving data from the peer
2017-04-19T15:31:03.108-05:00 [STG/0] [OUT] error: An error occurred while sending the request.
2017-04-19T15:31:03.108-05:00 [STG/0] [OUT] error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
2017-04-19T15:31:03.134-05:00 [STG/0] [OUT] FAILED: command failed, exit status 1
2017-04-19T15:31:03.134-05:00 [STG/0] [OUT] FAILED: Restoring dependencies with Dotnet CLI failed, command failed, exit status 1
2017-04-19T15:31:03.141-05:00 [STG/0] [OUT] Exit status 223
2017-04-19T15:31:03.141-05:00 [STG/0] [ERR] Failed to compile droplet
2017-04-19T15:31:03.147-05:00 [STG/0] [ERR] Staging failed: Exited with status 223

**Comment by gsainagendraprasad** [comment]
Hi Stephen, How do i make sure my VM is configured appropriately for  internet connectivity ??

**Comment by sclevine** [comment]
Your proxy settings look okay. Can you `cf ssh` into the app and `curl https://api.nuget.org/v3/index.json` successfully? Can you confirm that the app works on PWS or any other CF deployment?

**Comment by gsainagendraprasad** [comment]
When i tried cf ssh FirstCoreApp, it says Error opening SSH connection: Application "FirstCoreApp" is not in the STARTED state.

App works fine in  local IIS and also works well using dontnet Run command. I haven't tried with any other cf deployments.

**Comment by sclevine** [comment]
Sorry, I meant, can you `cf ssh` into any other running app in PCF Dev and run `curl https://api.nuget.org/v3/index.json`?

**Comment by gsainagendraprasad** [comment]
It says Received HTTP code 407 from proxy after CONNECT

PS C:\JavaSamples\HelloRest> cf ssh hellorest
vcap@7566dac2-4d03-47bf-5855-a8c00660ba7d:~$ curl https://api.nuget.org/v3/index.json
curl: (56) Received HTTP code 407 from proxy after CONNECT
vcap@7566dac2-4d03-47bf-5855-a8c00660ba7d:~$

**Comment by sclevine** [comment]
Can you confirm that the correct proxy settings are present in that ssh shell with the `env` command?

It seems like `172.22.1.23:8080` is not a functional HTTPS proxy and that you can't establish an HTTPS connection from the app container.

**Comment by gsainagendraprasad** [comment]
My network guys said 172.22.1.23:8080 and 172.22.1.22:8080 are our proxies, so i destroyed cf and started with proxy settings to 172.22.1.22:8080. I deployed a java application and did ssh , curl https://api.nuget.org/v3/index.json. It is still give me 407 http code.  Issue still exist :(

then I also did ssh env , here is the out put:

PS C:\JavaSamples\HelloRest> cf ssh hellorest
vcap@07bac01f-4042-41af-75e4-9005da56e19d:~$ curl https://api.nuget.org/v3/index.json
curl: (56) Received HTTP code 407 from proxy after CONNECT
vcap@07bac01f-4042-41af-75e4-9005da56e19d:~$ env
CF_INSTANCE_ADDR=10.0.2.15:60004
TERM=xterm
VCAP_APP_PORT=8080
NO_PROXY=localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,.local.pcfdev.io,.local.pcfdev.io,local.pcfdev.i
o,OTHER-DOMAINS
USER=vcap
http_proxy=http://172.22.1.22:8080
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:
ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.
tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31
:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31
:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35
:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;
35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=0
1;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=0
1;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;
35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00
;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
CF_INSTANCE_INTERNAL_IP=10.254.0.6
VCAP_APPLICATION={"cf_api":"http://api.local.pcfdev.io","limits":{"fds":16384,"mem":1024,"disk":512},"application_name":
"HelloRest","application_uris":["hellorest.local.pcfdev.io"],"name":"HelloRest","space_name":"pcfdev-space","space_id":"
ab068872-1704-44c0-aabd-5229e0096e8c","uris":["hellorest.local.pcfdev.io"],"application_id":"d30e514e-59c8-4a30-857a-aee
99da85fcf","version":"a3ac8bbc-777b-49c2-a124-d1e407296d89","application_version":"a3ac8bbc-777b-49c2-a124-d1e407296d89"
}
CF_INSTANCE_GUID=07bac01f-4042-41af-75e4-9005da56e19d
PATH=/bin:/usr/bin
PWD=/home/vcap
LANG=en_US.UTF-8
CF_INSTANCE_PORT=60004
CF_INSTANCE_IP=10.0.2.15
VCAP_SERVICES={}
HTTPS_PROXY=http://172.22.1.22:8080
CF_INSTANCE_INDEX=0
https_proxy=http://172.22.1.22:8080
SHLVL=1
HOME=/home/vcap
no_proxy=localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,.local.pcfdev.io,.local.pcfdev.io,local.pcfdev.i
o,OTHER-DOMAINS
HTTP_PROXY=http://172.22.1.22:8080
CF_INSTANCE_PORTS=[{"external":60004,"internal":8080},{"external":60005,"internal":2222}]
LESSOPEN=| /bin/lesspipe %s
INSTANCE_INDEX=0
PORT=8080
INSTANCE_GUID=07bac01f-4042-41af-75e4-9005da56e19d
LESSCLOSE=/bin/lesspipe %s %s
MEMORY_LIMIT=1024m
_=/usr/bin/env
vcap@07bac01f-4042-41af-75e4-9005da56e19d:~$

**Comment by gsainagendraprasad** [comment]
I specified the credentials in power shell using this : 
$webclient=New-Object System.Net.WebClient
$creds=Get-Credential
$webclient.Proxy.Credentials=$creds

after this it was able to restore the NuGet packages. Thank you.

Then I got this next error in staging : ERR Failed to compress build artifacts: signal : broken pipe

**Comment by gsainagendraprasad** [comment]
Hi Stephen,
Inspite of my VM having 10GB , I am getting this error : ERR Failed to compress build artifacts: signal : broken pipe. Do you have any idea why this is happening ?

**Comment by sclevine** [comment]
You may be running out of disk space in the staging container.
The easiest thing to do would be to `dotnet publish` your app locally first, and push that.

**Comment by gsainagendraprasad** [comment]
I did "dotnet publish" and it published my app and its dependencies in to a folder (src\SecondCoreApi\bin\Debug\netcoreapp1.0\publish) . Now do you want me to add a manifest.yml file inside this publish folder and do a cf push command from this folder ??

**Comment by sclevine** [comment]
See: http://docs.cloudfoundry.org/buildpacks/dotnet-core/index.html#disconnected-environments

**Comment by gsainagendraprasad** [comment]
Cool Stephen, Finally i am able to deploy my first Dotnet Core REST API in to PCFDev. Thanks a lot for your support. This is just a beginning for me, now i have to start writing complex REST services which contains database operations and also talking to external api's. Not sure how many more issue i will encounter while doing it. But for now Thank you very much for all your support.
