### ISSUE TITLE
Error accessing PCF Dev after switching network

### ISSUE THREAD

**Issue by nigelcharman** [vmware-archive/pcfdev#221]
After switching wireless network, I am seeing the error:

```
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.168.11.11:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
```

This is sometimes resolved by performing a `cf dev stop` and `cf dev start`, but sometimes requires a `cf dev destroy`, `rm ~/.pcfdev ~/.cf` and `cf dev start`. 

I have installed and configured dnsmasq according to the instructions at https://docs.pivotal.io/pcf-dev/work-offline.html, but am still getting this issue.

My machine is running MacOS 10.12.4, VirtualBox 5.1.19, cf 6.25.0+787326d95.2017-02-28.

VBox.log ends with 

```
00:00:32.896835 Display::handleDisplayResize: uScreenId=0 pvVRAM=000000010d18f000 w=640 h=480 bpp=32 cbLine=0xA00 flags=0x1
00:00:33.177062 Display::handleDisplayResize: uScreenId=0 pvVRAM=0000000000000000 w=720 h=400 bpp=0 cbLine=0x0 flags=0x1
00:00:33.412870 PIT: mode=2 count=0x12a5 (4773) - 249.98 Hz (ch=0)
00:00:33.633200 PIT: mode=0 count=0x10000 (65536) - 18.20 Hz (ch=0)
00:00:33.635527 CPUM: VCPU  1: Cached APIC base MSR = 0xfee00800
00:00:33.640074 CPUM: VCPU  2: Cached APIC base MSR = 0xfee00800
00:00:33.644445 CPUM: VCPU  3: Cached APIC base MSR = 0xfee00800
00:00:34.089003 AHCI#0: Reset the HBA
00:00:34.104883 AHCI#0: Port 0 reset
00:00:45.583543 AC97: Reset
00:00:45.585446 AC97: Reset
00:00:45.598094 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.598220 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.598848 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.598912 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.601601 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.607438 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.607567 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.607668 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.607799 Audio: Skipping to create input stream "[LUN#0] ac97.mc", as the host audio backend reached its maximum of concurrent audio input streams
00:00:45.643031 NAT: IPv6 not supported
00:00:45.880086 NAT: DHCP offered IP address 10.0.2.15
00:00:45.881225 NAT: DHCP offered IP address 10.0.2.15
```

Any advice on what to look at next?

**Comment by sclevine** [comment]
Hi @nigelcharman,

This is an issue with Virtualbox host-only networking, where the VM IP (192.168.11.11) becomes inaccessible to the host. This happens because your operating system modifies the routing tables when you switch networks, and it can't be solved with DNS.

We could investigate adding a `cf dev fix-networking` command in a future release, but there isn't much we can do aside from that.

**Comment by nigelcharman** [comment]
Thanks @sclevine, a `cf dev fix-networking` command would be useful since it would save 10-20 minutes of rebuilding PCF Dev each time this happens.

**Comment by chris-pollard-assurity** [comment]
The same problem has been seen running boot2docker on VirtualBox. Here is a fix using the `VBoxManage` commands from [@berngp](https://github.com/berngp)

[boot2docker issue 945 comment 130113866](https://github.com/boot2docker/boot2docker/issues/945#issuecomment-130113866)

The short version is
a) find name of running vm: `VBoxManage list runningvms`
b) look up vbox network name in use by the vm: `VBoxManage showvminfo <name-of-vm> | grep "Host-only Interface"`
c) stop then start the network: `sudo ifconfig <vboxnetX> down && sudo ifconfig <vboxnetX> up`

I can confirm this works for me.
