### ISSUE TITLE
pcf dev startup times far too slow

### ISSUE THREAD

**Issue by uromahn** [vmware-archive/pcfdev#222]
I am using pcf dev on my Mac Book Pro which is considered among the more powerful laptops.
Starting a new PCF DEV Vm takes 12 minutes without downloading the OVA image! Once the image has been created and stopped, re-starting it with "cf dev start" takes 9-10 minutes!
I understand that there is a lot going on "under the covers" but this should be much faster.

The only way to make working with PCF DEV acceptable is when I suspend/resume the VM whenever it is necessary. Resuming a suspended VM takes about 30 seconds on my machine.

**Comment by sclevine** [comment]
Booting PCF Dev does indeed take 10-12 minutes on a reasonably provisioned workstation. Remember that PCF components are designed to start in a long-running, highly available cluster of VMs, so their initialization is not optimized for starting quickly on a single VM.

The current 10-12 minute boot is actually an improvement on previous 20+ minute boot times in early versions. We plan to continue to optimize this, but we're also happy to accept a PR that improves it.

**Comment by jkhchan307** [comment]
Mine is a MacBook Pro Late 2016 and running PCF Dev actually slows it down to a halt. I had to hot boot my machine to regain control.
