### ISSUE TITLE
Pcfdev deployed rest service returns null.

### ISSUE THREAD

**Issue by gsainagendraprasad** [vmware-archive/pcfdev#225]
Hi I wrote a Dotnet core REST service which has a controller, this controller is consuming a WCF service to get its data, When i deploy this to PCF dev using dotnetcore build pack, i am getting null when i call this controller. But this worked well in localhost.

Is there any documentation that i can go through and understand how can i achieve this service to service interaction in cloud foundry.

**Comment by sclevine** [comment]
Apologies for overlooking this issue.

If you're still experiencing this behavior, please reach out via the .NET Core buildpack repo: https://github.com/cloudfoundry/dotnet-core-buildpack
