### ISSUE TITLE
'cf dev start' fails after waiting 3600 seconds for services to become active

### ISSUE THREAD

**Issue by ivandavidov** [vmware-archive/pcfdev#228]
Hello,

I've been trying to setup ``PCF Dev`` on my local Windows 10 machine. This is the whole output from my attempt:

```
C:\Users\Ivan>cf dev start -s none
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email<***>

Password<***>
Downloading VM...
Progress: |====================>| 100% (this took 55 minutes)
VM downloaded.
Allocating 4054 MB out of 8109 MB total system memory (6080 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 48 running
7 out of 48 running
9 out of 48 running
29 out of 48 running
36 out of 48 running
37 out of 48 running
39 out of 48 running
40 out of 48 running
39 out of 48 running
39 out of 48 running
40 out of 48 running
40 out of 48 running
39 out of 48 running
39 out of 48 running
40 out of 48 running
40 out of 48 running
40 out of 48 running
40 out of 48 running
Timed out after 3600 seconds.
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().

C:\Users\Ivan>
```

The whole process took ~3 hours, including the initial VM download of ~1 hour. The ``Waiting for services to start...`` part failed after one hour. I understand that my hardware is not well suited for PCF Dev (Pentium N3700, 8GB RAM) but still I'd like to try it, if that's possible.

I have few questions:

- Is it normal for the active services to go back and forth between 39 and 40?
- If this behavior with the services is normal and assuming that the problem is in my weak hardware, is there a way to increase the default timeout of 3600 seconds?
- Is there a way to configure the VM in a way to remove/disable some of the services in order to reduce them from 48 to lower number?

Thank you!

**Comment by ivandavidov** [comment]
I tried exactly the same but this time on Ubuntu OS on the same machine. Everything worked OK and it was considerably faster this time. In the end I was able to perform ``cf push`` and observe the result in the PCF web app manager (or whatever it is called, I'm still learning the terminology) so I am willing to accept that there is a workaround for my issue - use Linux instead of Windows.

Nevertheless, the issue is still there and I am still not able to use PCF Dev on my Windows 10 OS which is on the same machine as my primary OS. Any feedback and/or suggestion on this matter is highly appreciated.

Thank you!

**Comment by sclevine** [comment]
Hi @ivandavidov,

We made some I/O optimizations in PCF Dev 0.26.0 that could have affected performance on various OSs. Could you try 0.25.0 on Windows 10, and see if you have the same experience?

**Comment by ivandavidov** [comment]
Unfortunately I got very similar results with version 0.25.0.

```
C:\Users\Ivan>cf dev version
PCF Dev version 0.25.0 (CLI: 47bebde, OVA: 0.459.0)

C:\Users\Ivan>cf dev start -s none
Downloading VM...
Progress: |====================>| 100%
VM downloaded.
Allocating 4054 MB out of 8109 MB total system memory (5738 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 48 running
7 out of 48 running
9 out of 48 running
26 out of 48 running
30 out of 48 running
36 out of 48 running
39 out of 48 running
40 out of 48 running
40 out of 48 running
40 out of 48 running
40 out of 48 running
39 out of 48 running
39 out of 48 running
40 out of 48 running
40 out of 48 running
40 out of 48 running
Timed out after 3600 seconds.
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().
C:\Users\Ivan>
```

Maybe I should switch to Linux as my primary OS since I had no issues with the plugin there. :)

**Comment by sachinsharma** [comment]
I faced exactly same issue on my Windows 7 8GBRAM Machine.
Any hopes for the lesser mortals working on Windows desktops?
Is there a way / commandline switch to increase the timeout from 3600 seconds

D:\Users\sasharma                                                        
λ cf dev start                                                           
Using existing image.                                                    
Allocating 4063 MB out of 8126 MB total system memory (4091 MB free).    
Importing VM...                                                          
Starting VM...                                                           
Provisioning VM...                                                       
Waiting for services to start...                                         
7 out of 58 running                                                      
7 out of 58 running                                                      
7 out of 58 running                                                      
7 out of 58 running                                                      
7 out of 58 running                                                      
7 out of 58 running                                                      
9 out of 58 running                                                      
9 out of 58 running                                                      
19 out of 58 running                                                     
29 out of 58 running                                                     
36 out of 58 running                                                     
42 out of 58 running                                                     
Timed out after 3600 seconds.                                            
FAILED                                                                   
Error: failed to provision VM: Process exited with: 1. Reason was:  ().

**Comment by ivandavidov** [comment]
@sachinsharma - the only workaround I have found for now is to use native Linux OS and try ``pcfdev`` there.

**Comment by sclevine** [comment]
The next version of PCF Dev will re-implement much of this logic using BOSH. I'm closing this issue for now, but feel free to open new issues if you run into similar issues in subsequent versions of PCF Dev.
