### ISSUE TITLE
"cf dev start" prompt for username and password then timesout on login 

### ISSUE THREAD

**Issue by nickzeus** [vmware-archive/pcfdev#230]
I am trying to learn how to use pcf through the tutorial and before I can it won't allow me to login using the command prompt when I run the command cf dev start.  
![pivotalerror](https://cloud.githubusercontent.com/assets/12501175/25869361/436db726-34bd-11e7-929d-a0e86a862fa4.PNG)

I have downloaded all of the proper tools to use pcf dev based on the installation process located here: https://docs.pivotal.io/pcf-dev/install-windows.html

I am able to login to my PCF account using the web application and have even tried updating my information, and it still does not work.

Does anyone have any Ideas on what could be going wrong here?

**Comment by ivandavidov** [comment]
You may need to [change the command prompt encoding](http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500) before you execute the ``cf dev start`` command.

```
C:\>chcp 65001
Active code page: 65001

C:\>cf dev start
```

**UPDATE:** This may not solve the issue but it will ensure that your local console handles Unicode characters (almost) correctly.

**Comment by nickzeus** [comment]
I think it is because I am behind a proxy but I cant seem to get it to work even after setting the environment variables to be the schwab proxy and the port to 8080

It still throws the same error after running the chcp command

**Comment by sclevine** [comment]
Hey @nickzeus,

Can you try it in PowerShell? Before you run `cf dev start` in PowerShell, make sure you've followed the instructions here: https://docs.pivotal.io/pcf-dev/proxy.html

**Comment by sclevine** [comment]
Also, as a workaround, you can download the corresponding OVA version (found with `cf dev version`) directly from the "internal" release on PivNet. The run `cf dev import` on the OVA.

**Comment by nickzeus** [comment]
Using PowerShell the Error Comes out to "proxy authentication required" 
I changed the env variables as shown in the code below.
![pivotalerror](https://cloud.githubusercontent.com/assets/12501175/25908496/939bd71e-3567-11e7-8975-2b55cc487a06.PNG)

How do I fix this Proxy issue?

**Comment by sclevine** [comment]
Seems like your HTTP proxy requires authentication. You should be able to pass proxy credentials in those environment variables in the format:
```
$env:HTTPS_PROXY = "http://username:password@example.com:8080"
```
Alternatively, if you don't need a working internet connection in the VM, you could follow the workaround instructions.

**Comment by nickzeus** [comment]
I'm so close!!! Command still throws an error when I try to run cf dev start, but this time it is saying:
![pivotalerror](https://cloud.githubusercontent.com/assets/12501175/25919300/925e45ac-358b-11e7-8bad-2b06859b3f02.PNG)

Why would my virtual machine be refusing the connection?

**Comment by sclevine** [comment]
Closing in favor of #231.
