### ISSUE TITLE
"cf dev start" no connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by nickzeus** [vmware-archive/pcfdev#231]

**Comment by sclevine** [comment]
To confirm, your proxy server takes the basic auth credentials that you're providing over plain HTTP, and this works in other applications? It looks like your proxy server is refusing the connection.

As a workaround, you can find the OVA version that corresponds to your PCF Dev version (by running `cf dev version`) and download that OVA version from the `internal` release on PivNet. Then you can run `cf dev import /path/to/file.ova` to import it.

Worth noting though, if applications can't use those proxy settings to access the internet, the VM will likely not have internet access.

**Comment by nickzeus** [comment]
So I finally got the proxy to accept the login it seems.... I changed the proxy environment variables to be https//:proxy.schwab.com:8080

Not it shows the user license agreement and when I try to accept it I get:
Pivotal Network returned: 451 Unavailable for Legal Reasons 

What is happening now?

**Comment by sclevine** [comment]
Glad that the proxy connection is working!

Can you attempt to download the OVA from the "internal" release on the PCF Dev product page on PivNet in a web browser? That `451` error may indicate that your PivNet account was automatically flagged (usually for export control reasons), and downloading the OVA directly will give you more information about why. Sorry for the trouble!

**Comment by nickzeus** [comment]
I ran cf version and it says OVA version 0.461.0 then I went to the PCF Dev downloads site and changes it to internal and clicked on the corresponding OVA. a new tab pops open and looks like it wants to start a download but never does... the new tab that opens shows this below:

![pivotalerror](https://cloud.githubusercontent.com/assets/12501175/26125841/a687eb64-3a40-11e7-8be0-8fbe62f69c42.PNG)

**Comment by sclevine** [comment]
Interesting. It looks like your browser is displaying the initial contents of the OVA. (An OVA is really just a tar archive.)

Can you try `cf dev start` again with the same account that you used in the browser? Alternatively, can you try to download the OVA in a different browser?

**Comment by nickzeus** [comment]
Its finally working!!!! the Virtual Machine is starting to download! Thank you @sclevine
