### ISSUE TITLE
Moving image in VirtualBox UI changes path in ~/.pcfdev/vms, causing cf dev start failure

### ISSUE THREAD

**Issue by awmartin** [vmware-archive/pcfdev#232]
The VirtualBox UI gives the user the ability to organize disk images into "Groups," which one can create by navigating to Machine > Group in the main menu. Once moving the PCF Dev image into the group, it changes the path to the VM inside `~/.pcfdev/vms`, meaning PCF Dev cannot find the VM to start, so `cf dev start` fails.

For example, when I created a "Pivotal" group and moved the PCF Dev image into that group, the folders inside `~/.pcfdev/vms` changed from `~/.pcfdev/vms/pcfdev-v0.461.0` to `~/.pcfdev/vms/Pivotal`.

`cf dev start` then failed with the following message:

```
Downloading VM...
Progress: |====================>| 100%
VM downloaded.
Allocating 4096 MB out of 16384 MB total system memory (5003 MB free).
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: failed to execute 'VBoxManage startvm pcfdev-v0.461.0 --type headless': exit status 1: VBoxManage: error: Could not open the medium '/Users/awmartin/.pcfdev/vms/pcfdev-v0.461.0/pcfdev-v0.461.0-disk1.vmdk'.
VBoxManage: error: VD: error VERR_FILE_NOT_FOUND opening image file '/Users/awmartin/.pcfdev/vms/pcfdev-v0.461.0/pcfdev-v0.461.0-disk1.vmdk' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium
Waiting for VM "pcfdev-v0.461.0" to power on...
```

Granted, I did move the image during the deployment.

After moving the image out of the Group in the VirtualBox UI, the `cf dev start` command succeeded.

**Comment by sclevine** [comment]
Thanks for the report. We don't support externally modifying the VM that gets created by the plugin. Instead, the plugin has commands that you can use to manage the VM. See: `cf help dev`

We will eventually switch to libmachine for VM management, and that may have more robust support for external VM changes. We'll revisit this issue after we make that migration.
