### ISSUE TITLE
Upgrading PCF Dev results in "PCF Dev already running" warning, even though it's not running

### ISSUE THREAD

**Issue by awmartin** [vmware-archive/pcfdev#233]
I updated the PCF Dev CLI plugin to v0.26, but when I ran `cf dev start`, it resulted in a warning:
```
FAILED
Error: old version of PCF Dev already running, please run `cf dev destroy` to continue.
```

However, the PCF Dev VM was not running; I hadn't run PCF Dev in weeks. `cf dev destroy` did resolve the issue, and I was able to `cf dev start` to download the new image... Well, after dealing with another bug.

**Comment by sclevine** [comment]
"Running" really means "created" in this context. We don't want to destroy your data, so we make you run `cf dev destroy` before we boot the new version.

**Comment by sclevine** [comment]
Prioritized a text change, see the story for details.

**Comment by sclevine** [comment]
Closing this as we've opted to re-write the plugin once we move to real BOSH + native hypervisors.
