### ISSUE TITLE
pcfdev build issue with gradle

### ISSUE THREAD

**Issue by Stakman** [vmware-archive/pcfdev#237]
Following the tutorial, I am trying to build spring-music but keep erroring out:

PS C:\windows\system32\spring-music> .\gradlew.bat assemble
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

PS C:\windows\system32\spring-music> ./gradlew assemble
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

PS C:\windows\system32\spring-music> ./gradlew clean assemble
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by sclevine** [comment]
Hi @Stakman,

Sorry for the delay. I am not able to replicate those errors. I suggest reaching out to the maintainers of that Spring app for assistance.

**Comment by ivandavidov** [comment]
Hi @Stakman,

Are you able to run anything with Gradle from the same directory, e.g. ``gradlew help`` or ``gradlew tasks``?
