### ISSUE TITLE
Need to start cfdev instance in bridged mode

### ISSUE THREAD

**Issue by jlangowski** [vmware-archive/pcfdev#239]
1. why cant i start cf dev in bridged mode and use my local dns? 
2. why cant i login to cf dev vm?

**Comment by sclevine** [comment]
1. PCF Dev is not a secure distribution of PCF. Making the VM only accessible via a consistently addressed, host-only network is more secure and requires less configuration.
2. You can: `cf dev ssh`

**Comment by jlangowski** [comment]
Ok. I have a local network with a local dns. I wanted to route traffic and cnames from there.... 
bummer maybe i can port forward in virtualbox. ill try that.
Too bad it can't be open to change the configuration a little bit it would be kind of fun to play around with it.
anyways thanks.

**Comment by jlangowski** [comment]
port forwarding is not working...

**Comment by sclevine** [comment]
To clarify, nothing prevents you from changing the networking settings in Virtualbox manually. Switching to bridged networking will likely break functionality, but I have heard that port forwarding (ports 80, 443, and 2222) to the host works. You'll need to:

1. Make sure that only trusted machines have access to those forwarded host ports.
2. Start PCF Dev with `-d` followed by a wildcard domain that clients can use to reference the host machine. Alternatively, you can make `*.local.pcfdev.io` resolve to the host machine on each client machine using dnsmasq or similar.
3. Use Virtualbox port forwarding, iptables, or some other method to forward ports 80, 443, and 2222 from the host machine to the VM.
