### ISSUE TITLE
Cannot ping api.local.pcfdev.io

### ISSUE THREAD

**Issue by jonbuck16** [vmware-archive/pcfdev#241]
I am on a laptop with a direct connection to the internet and I cannot ping 'api.local.pcfdev.io', do you know if there is an issue with this DNS entry or why I might not be able to ping that address..   It is preventing me from logging into pcfdev..

**Comment by jonbuck16** [comment]
Apologies I should have said that it doesn't even resolve.. returns no such host..  it's not like it returns the 192.168.1.11 address or whatever and can't connect to it..

**Comment by sclevine** [comment]
Do you have a router with custom firmware (like dd-wrt) that prevents DNS rebind attacks? Some routers will prevent public DNS records from resolving to private IP ranges.

If so, you can work around this without changing your router settings by following these instructions:
https://docs.pivotal.io/pcf-dev/work-offline.html

**Comment by jonbuck16** [comment]
Hi @sclevine , many thanks for this, you were right in that for some reason the router or the DNS servers the router is hard coded to use was preventing the address from being resolved, I have changed my machine to use Google's DNS servers and it is now resolving correctly however I may just configure dnsmasq as suggested.

**Comment by kingdonb** [comment]
I have seen this happen before with my own DNS records, on other platforms that want to set up a local star record, and spent hours racking my brain!  Thank you for finding the answer and having the solution in what basically amounts to a KB article that I can share with my co-workers 👍
