### ISSUE TITLE
pcf dev start issue

### ISSUE THREAD

**Issue by dsubudhi26** [vmware-archive/pcfdev#243]
When I was trying to create a VM for pcf dev , I got the following error message:
Downloading VM...
Progress: |====================>| 100%
VM downloaded.
Allocating 4044 MB out of 8089 MB total system memory (2586 MB free).
Importing VM...
FAILED
Error: failed to import VM: failed to execute 'C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create': exit status 1: 0%!.(MISSING).
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Operation canceled by the user
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component VirtualBoxWrap, interface IVirtualBox
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
.
Please let me know if I am doing anything wrong here

**Comment by sclevine** [comment]
Hi @dsubudhi26,

It seems like Virtualbox is unable to create a network adapter for PCF Dev.

Do you get this error if you destroy the VM with `cf dev destroy` and start it again with `cf dev start`?

Have you tried rebooting the host machine?

**Comment by dsubudhi26** [comment]
Hi Stephen,

Thanks for the help. I have resolved the issue by changing the IP of host
network adapter

**Comment by anand4252** [comment]
I had a similar issue. I was able to resolve it by restarting my host machine. Thanks for the help.
