### ISSUE TITLE
Error in cf dev start

### ISSUE THREAD

**Issue by dsubudhi26** [vmware-archive/pcfdev#244]
Hi,

I am getting the following error when I gave the "cf dev start" command on linux machine
[root@localhost deb]# cf dev start
Using existing image.
Allocating 4096 MB out of 15951 MB total system memory (7662 MB free).
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: failed to execute 'VBoxManage startvm pcfdev-v0.461.0 --type headless': exit status 1: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
Waiting for VM "pcfdev-v0.461.0" to power on...
.

**Comment by sclevine** [comment]
Hi @dsubudhi26,

You are attempting to start PCF Dev inside of a VM, or on a machine that does not support the VT-x processor extension. The VT-x processor extension is required to run 64-bit VMs in Virtualbox (such as the PCF Dev VM).

**Comment by dsubudhi26** [comment]
Hi Stephen,

Thanks for the info .Can PCF Dev run inside a VM, which has VT-x processor
extension or it needs a physical machine ?

Regards,
Debabrata

**Comment by sclevine** [comment]
PCF Dev can technically run in a VM that exposes the VT-x processor extension, but it may not be very performant depending on the resources available to the outer VM. I would encourage you to run PCF Dev on a physical machine if possible.

(We test PCF Dev nested in vSphere VMs with VT-x that have 8-16 Xeon CPUs and 64 GB of RAM available.)
