### ISSUE TITLE
Accessing pcfdev dev running on Debian from a Windows pc on the same network

### ISSUE THREAD

**Issue by Andrei0105** [vmware-archive/pcfdev#245]
I have a pcfdev running on a Debian machine on the same network as my laptop with Windows from which I would like to work and be able to connect to pcfdev.
The Debian machine has the address 192.168.100.6.
From what I understand, I must route traffic for 192.168.22.11 (local2.pcfdev.io) to 192.168.100.6. Can I use netsh to do this? I don't know how I should configure the host machine to respond.

Thank you

**Comment by sclevine** [comment]
Duplicate of #239. This workflow is unsupported, but see that issue for a possible solution.
