### ISSUE TITLE
After restarting the pcfdev, Unable to start an Application that was bind to local-volume service

### ISSUE THREAD

**Issue by mahesh1247** [vmware-archive/pcfdev#246]
I have an application that uses physical file system. so i have created local-volume service and bind to my application. It was working fine. And when i restart my pcfDev the application is crashing with an  error message "exit_description"=>"failed to mount volume". But when i create a new volume service and bind to an application it is working fine, till pcf dev restart. once i restart the pcfdev the application is crashing with new service.

**Comment by sclevine** [comment]
Thanks for the report. You may be able to work around this behavior by suspending PCF Dev instead of stopping it. Use: `cf dev suspend`
