### ISSUE TITLE
Not a valid cf CLI plugin on Windows 7

### ISSUE THREAD

**Issue by sorvis** [vmware-archive/pcfdev#248]
Looking through the issues it seems like there have been several very similar issues to mine, but all those issues seem to be closed. I'm running Windows 7 and trying to install pcfdev through an Administrator powershell window. Its complaining that "File is not a valid cf CLI plugin binary" is there another fix I'm missing?

```
PS C:\Users\sorvis\Downloads\pcfdev-v0.26.0+PCF1.10.0-windows> .\pcfdev-v0.26.0+PCF1.10.0-windows.exe
←[1mAttention: Plugins are binaries written by potentially untrusted authors.←[0m
←[1mInstall and use plugins at your own risk.←[0m
dial tcp 127.0.0.1:38685: socket: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
←[31;1mFAILED←[0m
PS C:\Users\sorvis\Downloads\pcfdev-v0.26.0+PCF1.10.0-windows> cf --version
cf.exe version 6.28.0+9e024bd.2017-06-27
```

**Comment by sclevine** [comment]
Are you running the latest version of the cf CLI?
Can you install it using:
```
cf install-plugin .\pcfdev-v0.26.0+PCF1.10.0-windows.exe
```

**Comment by sorvis** [comment]
I'm running version 6.28.0+9e024bd.2017-06-27 of cf

Below is the output by running cf install-plugin directly:

```
PS C:\Users\sorvis\Downloads\pcfdev-v0.26.0+PCF1.10.0-windows> cf install-plugin .\pcfdev-v0.26.0+PCF1.10.0-windows.exe
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin .\pcfdev-v0.26.0+PCF1.10.0-windows.exe? [yN]: y
y
dial tcp 127.0.0.1:43004: socket: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED
PS C:\Users\sorvis\Downloads\pcfdev-v0.26.0+PCF1.10.0-windows>
```

**Comment by sclevine** [comment]
Can you install any other cf CLI plugins?

**Comment by sorvis** [comment]
Good thought it does seem to fail for others:

```
PS C:\Users\sorvis\Downloads\pcfdev-v0.26.0+PCF1.10.0-windows> cf install-plugin -r CF-Community "Live Stats"
Searching CF-Community for plugin Live Stats...
Plugin Live Stats 1.0.0 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin Live Stats? [yN]: y
y
Starting download of plugin binary from repository CF-Community...
 7.64 MiB / 7.64 MiB [=====================================================================================] 100.00% 0s
dial tcp 127.0.0.1:44194: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED
```

Where is the right place to go to for help for figuring out whats up with the cf tool itself?

**Comment by sclevine** [comment]
The cf CLI is maintained here: https://github.com/cloudfoundry/cli

However, I would be willing to bet that you have an ultra-restrictive local firewall that prevents connections on localhost (in this case, RPC between the plugin and CLI).

**Comment by sorvis** [comment]
Hmm, I tried disabling the firewall, but it still seemed to not work. I'll look around some more now that we know the issue is not with PCFDEV that should help. Thank you very much for your help.

**Comment by opensource-dev** [comment]
I still see this issue

**Comment by opensource-dev** [comment]
I still see the issue with both 0.28 and 0.29 windows versions

 cf install-plugin pcfdev-v0.28.0+PCF1.11.0-windows.exe
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin pcfdev-v0.28.0+PCF1.11.0-windows.exe? [yN]: y
dial tcp 127.0.0.1:52059: socket: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED
