### ISSUE TITLE
Load balancing in runtime

### ISSUE THREAD

**Issue by dsubudhi26** [vmware-archive/pcfdev#249]
Hi,

I have planning to run 3 different servers having the same functionality in a docker container on PCF . How will the loadbalancing happen ? Do I need to purchase a load balancer separately or PCF will do it automatically ?

**Comment by sclevine** [comment]
PCF handles load balancing in the platform by creating multiple application instances that are distributed between separate cell VMs automatically. You can scale the number of instances manually with `cf scale`, or use an autoscaling service to scale in response to load.

This question is about PCF, not PCF Dev. Please reach out to support@pivotal.io if you are PCF customer.
