### ISSUE TITLE
Difference between pcfdev and pcf enterprise edition?

### ISSUE THREAD

**Issue by sunilvalmiki** [vmware-archive/pcfdev#251]
What is the difference between the PCF dev and the enterprise PCF?
What type of features divides PCF dev from Enterprise PCF?

**Comment by sclevine** [comment]
Sorry for the delay @sunilvalmiki.

PCF Dev is a freely-available, single VM deployment of PCF that is suitable for local development purposes.

A comparison to PCF is available here: https://docs.pivotal.io/pcf-dev/#comparison-to-pcf
