### ISSUE TITLE
cf dev start is failing while importing vm

### ISSUE THREAD

**Issue by KrishnanandNaik** [vmware-archive/pcfdev#254]
hi, please help me to resolve this issue.

C:\Users\lenovo>cf dev start
Using existing image.
Allocating 4096 MB out of 15960 MB total system memory (12172 MB free).
Importing VM...
←[31;1mFAILED←[0m
Error: failed to import VM: failed to execute 'C:\Program Files\Oracle\VirtualBo
x\VBoxManage clonemedium disk C:\Users\lenovo\.pcfdev\vms\pcfdev-v0.529.0-disk1.
vmdk.compressed C:\Users\lenovo\.pcfdev\vms\pcfdev-v0.529.0\pcfdev-v0.529.0-disk
1.vmdk': exit status 1: 0%!.(MISSING).10%!.(MISSING).20%!.(MISSING).30%!.(MISSIN
G).40%!.(MISSING).50%!.(MISSING).60%!.(MISSING).70%!.(MISSING).80%!.(MISSING).
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Failed to clone medium
VBoxManage.exe: error: Could not create the clone medium 'C:\Users\lenovo\.pcfde
v\vms\pcfdev-v0.529.0\pcfdev-v0.529.0-disk1.vmdk'.
VBoxManage.exe: error: VMDK: cannot write allocated data block in 'C:\Users\leno
vo\.pcfdev\vms\pcfdev-v0.529.0\pcfdev-v0.529.0-disk1.vmdk' (VERR_DISK_FULL)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component M
ediumWrap, interface IMedium
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCloneMedium(struc
t HandlerArg *)" at line 954 of file VBoxManageDisk.cpp

**Comment by sclevine** [comment]
Hi @KrishnanandNaik,

You're out of disk space:
```
VBoxManage.exe: error: VMDK: cannot write allocated data block in 'C:\Users\leno
vo.pcfdev\vms\pcfdev-v0.529.0\pcfdev-v0.529.0-disk1.vmdk' (VERR_DISK_FULL)
```

**Comment by KrishnanandNaik** [comment]
thanks sclevine ! that issue is solved but now i am getting error "Error restarting application: StagingError"
while pushing app to pcf dev.

**Comment by KrishnanandNaik** [comment]
thanks sclevine for your reply ! but i have resolved this issue by enabling the virtualization settings in the BIOS Setup.

**Comment by sclevine** [comment]
Awesome, the VT-x processor extension is definitely also a requirement.
