### ISSUE TITLE
cf dev start fails on windows 10 pro 64 bits: Error: failed to provision VM: Process exited with: 127. Reason was: ()

### ISSUE THREAD

**Issue by javafreek** [vmware-archive/pcfdev#256]
I'm trying to get CF-DEV to run on my local machine but it fails on the same spot:
![image](https://user-images.githubusercontent.com/1488911/29872789-51096dee-8d91-11e7-8fef-d3237499a9b4.png)

I run MS Windows 10 Pro, 64 bits edition with an Intel Core i7-4720HQ and 16GB (DDR3) memory. Image files are stored on a RAID 0 drive (using 2 SSD drives). I'm connected to the internet without using a proxy on a wired connection (to prevent time-outs or slow connections)

What I've tried so far?
* I've switched (removed) off: Hyper-V. (it was conflicting)
* Removed native Docker support. 
* Ubuntu is still part of the install but I doubt it is causing the issue.
* removed virtualBox and installed latest version. (to be sure)
* downloaded CF tool and CF-dev again.
* tried CMD and powershell
* ran cf dev start with 8192MB memory (instead of 4GB it assigned itself)
* tried running with no services: cf dev start -s none
* Modified the vm NAT (shouldn't be a solution): VBoxManage modifyvm "pcfdev-v0.529.0" --natdnshostresolver1 on
* removed all old VM, OVAs and retried the install from scratch again

and all resulted in the same error: Error: failed to provision VM: Process exited with: 127. Reason was: ()

What does work: I can start the image from virtualBox manager (GUI) but can't login on the console: 
![image](https://user-images.githubusercontent.com/1488911/29873597-1be45f7c-8d94-11e7-929c-80b5f0fedaf8.png)
(admin/admin tried as I found in a different issue as a way to login?)
When dev is started in virtualBox Manager and stopped through the console (cf dev stop) It works as expected. If I try (and fail) to start the dev env from the console (cf dev start) and then try to stop it, I get a new error from VirtualBox:
![image](https://user-images.githubusercontent.com/1488911/29873720-97c5a902-8d94-11e7-868f-9f5441999661.png)
and:
![image](https://user-images.githubusercontent.com/1488911/29873745-adc7bc9a-8d94-11e7-8e17-eaba4c18960c.png)
(instruction xxxxx is always pointing to memory on 0xFFFFFFFFFFFFFFFFFFFFFFFFFF.)

**Comment by sclevine** [comment]
Can you provide the full output of `cf dev destroy` followed by `cf dev start`?

Then run `cf dev debug`, make sure the resulting archive doesn't have an sensitive data in it, and send it to me at slevine@pivotal.io.

**Comment by nathan-alden-inl** [comment]
@javafreek, I think this is the same issue that I reported a few days ago. #255

**Comment by sclevine** [comment]
I can confirm that this is the same issue. Even though you mention having a stable internet connect, the VM fails to resolve a Github domain during the provisioning stage:
```
curl: (6) Could not resolve host: raw.githubusercontent.com
```
This request shouldn't happen. We're going to cut a new release (0.28.0) that removes it.

Closing in favor of #255.
