### ISSUE TITLE
Wrong field types for space `user_roles` api

### ISSUE THREAD

**Issue by jcscottiii** [vmware-archive/pcfdev#257]
i'm using the latest PCFDev and i'm seeing a discrepancy between the API docs and the API responses from PCFDev. if i do `/v2/spaces/guid/user_roles` the `admin` and `active` fields are in number format instead of boolean.

```
...
         "entity": {
            "admin": 0,
            "active": 1,
            "default_space_guid": null,
            "username": "admin",
            "space_roles": [
               "space_developer",
               "space_manager"
            ],
...
```

way to reproduce:
```
cf create-org test-org
cf create-space test-org test-space
cf create-space test-space -o test-org
cf t -o test-org -s test-space
cf curl /v2/spaces/$(cf space test-space --guid)/user_roles
```

Here's part of my `/v2/info`

```
cf curl /v2/info
{
   "name": "pcfdev",
   "build": "b8e2fd099b54b0e464a3644c9650a51b409c73b2",
   "support": "pcfdev@pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.local.pcfdev.io",
   "token_endpoint": "https://uaa.local.pcfdev.io",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.82.0",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.local.pcfdev.io/routing",
   "doppler_logging_endpoint": "wss://doppler.local.pcfdev.io:443",
   "user": "f50bd9f5-f973-4f80-ac52-724f8af900c0"
}

```

(BTW: The fields are booleans on our production CF, which is correct)

**Comment by Gerg** [comment]
Hey @jcscottiii. It appears that this is an inconsistency between Postgres and MySQL. Cloud Foundries with a Postgres database will return true/false whereas CFs with a MySQL database will return 1/0.

Ideally, we should hide these implementation details from the API. We will add a story to make it behave the same way across both databases. Thank you for raising this issue!

@gerg && @ljfranklin

**Comment by sclevine** [comment]
Closing as this will be addressed upstream.
