### ISSUE TITLE
CF dev failing to start on Windows

### ISSUE THREAD

**Issue by eddie71** [vmware-archive/pcfdev#258]
i am having a problem where i had a working machine and i dropped the vm so i could add spring cloud services. 

cf dev start
Using existing image.
←[31;1mFAILED←[0m
Error: exit status 2147746065.

cf dev start -s all
Using existing image.
←[31;1mFAILED←[0m
Error: exit status 2147746065.

keep getting an exit status of 2147746065 (80040111 hex) 

i removed pf dev, virtual box, the cli etc and reinstalled. same result. 

i removed all the folders in my profile and tried. same result. 

any clue to what this error code could be?

**Comment by sclevine** [comment]
Sorry for the delay. Have you tried running `cf dev destroy`, and then rebooting?

**Comment by eddie71** [comment]
tried that and it didn't make a difference

**Comment by eddie71** [comment]
I did two further things and that seemed to cure it
i started virtual box

and i set 4 cores 

cf dev start -s all -c 4

not sure which one fixed it

**Comment by sclevine** [comment]
Glad you got it working!
