### ISSUE TITLE
PCF Dev Fails to Provision

### ISSUE THREAD

**Issue by echurchm** [vmware-archive/pcfdev#259]
Machine Info:

- MacOS Sierra
- cf version 6.28.0+9e024bdbd.2017-06-27
- PCF Dev version 0.27.0 (CLI: 01c0c2b, OVA: 0.529.0)
- Running behind Corporate Proxy servers
Here are the proxy variables I have set:
declare -x http_proxy="http://<masked out>"
declare -x https_proxy="http://<masked out>"
declare -x no_proxy="localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,.local.pcfdev.io"

I get the following error when I run: cf dev start
       Error: failed to provision VM: Process exited with: 127. Reason was:  ().

When I tail the provision.log file, I see:

Setting quota apps-manager-quota to org system as admin...
OK
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com
/var/pcfdev/deploy-apps-manager.sh: line 84: nvm: command not found

It looks like curl is not honoring the proxy variables.

**Comment by sclevine** [comment]
Duplicate of #255, about to cut a new release that fixes this.

**Comment by cassidd** [comment]
Can someone please tell me why I'm timing out here.  I've tried 0.24.0, 0.29.0, and tried setting http_proxyies as shown (after if failed with 0.29.0) - still no luck:
declare -x http_proxy="http://"
declare -x https_proxy="http://"
declare -x no_proxy="localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,.local.pcfdev.io"

My system details:
macOS Sierra. Version 10.12.6
VirtualBox 5.1.30 r118389 (Qt5.6.3)
PCF Dev version 0.29.0 (CLI: 49405ec, OVA: 0.548.0)

[pcfdev-debug.tgz.zip](https://github.com/pivotal-cf/pcfdev/files/1940163/pcfdev-debug.tgz.zip)

cf dev destroy
PCF Dev VM has been destroyed.

cf dev start -s all
Using existing image.
Allocating 8192 MB out of 16384 MB total system memory (8954 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
Timed out after 3600 seconds.
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().

**Comment by sclevine** [comment]
Follow #324

**Comment by cassidd** [comment]
Thanks!
