### ISSUE TITLE
Accessing PCF Dev from remote machine

### ISSUE THREAD

**Issue by jeemis23** [vmware-archive/pcfdev#260]
****

**Comment by jeemis23** [comment]
I have installed PCF DEV locally in my centos machine, locally i am able to deploy any project and will get specified URL also  and if i want to verify i do #curl sample..local.pcfdev.io. But what if i want to access from another machine, i.e online from remote machine. Is there any option/way to do that ? Can anybody help with this

**Comment by sclevine** [comment]
See: #239
