### ISSUE TITLE
cf dev start not starting the instance

### ISSUE THREAD

**Issue by svrbedu** [vmware-archive/pcfdev#262]
When I am trying to run PCF Dev Instnace using cf dev start getting following error
'dev' is not a registered command. See 'cf help -a'
I am wondering, what could be the reason for this error?

**Comment by sclevine** [comment]
Hi @svrbedu,

This error indicates that you have not installed PCF Dev. Please see here: https://docs.pivotal.io/pcf-dev/#installing
