### ISSUE TITLE
Domain is hardcoded inside deploy-apps-manager.sh

### ISSUE THREAD

**Issue by juzsal** [vmware-archive/pcfdev#263]
Hi,

I'm starting pcfdev with `-d gb.pcfdev.io -i 192.168.11.100`, and provisioning is failing inside `deploy-apps-manager.sh` because `domain` is hardcoded to `local.pcfdev.io`. Manually editing and rerunning works.

Happy to make a PR to fix if this is a valid issue?

P.S. Thanks for pcfdev, it's awesome, and hopefully the gateway to getting my management to adopt PCF proper!

Cheers,
Justin

**Comment by sclevine** [comment]
Hi @jlsalmon,

Definitely seems like a bug. The next release of PCF Dev will containerize the internal components and use real BOSH. That should address this issue.

Unfortunately, we don't plan to cut any additional releases that use the current single-OVA model.

**Comment by juzsal** [comment]
@sclevine that sounds awesome, does that mean PCF Dev users will have access to things like Ops Manager? Will we be able to deploy additional BOSH releases to the PCF Dev environment?

Do you have a timeline/roadmap for the next release?

**Comment by sclevine** [comment]
The minimum viable feature set for the next release is not locked in yet. We do expect to be able to deploy additional BOSH releases to it.

I plan to make an announcement that includes more details about these changes (along with other exciting changes) soon.

**Comment by lojones** [comment]
@jlsalmon  - Is the deploy-apps-manager.sh file inside the PCF Dev ova?

**Comment by sclevine** [comment]
@lojones Yes

**Comment by ssisil** [comment]
Fixed in [v0.29](https://github.com/pivotal-cf/pcfdev/releases/tag/v0.29.0)
