### ISSUE TITLE
pcfdev all services start fails

### ISSUE THREAD

**Issue by KrishnaT08** [vmware-archive/pcfdev#265]
Hi ,

I am trying to run  pcfdev (pcfdev-v0.547.0) in my local machine(windows 10, 32GM RAM, virtual box 5.2.0) with all services. It fails to start even with memory of 14000 mb allocated. Below error messages from start command and provision log. I tried cf destroy/stop and cf start multiple times but it always fails when i try with all services or scs. It works with default services.   

Please advise on how to resolve this.

cf dev start -s all -m 14000:

Using existing image.
Starting VM...
Provisioning VM...
Waiting for services to start...
8 out of 58 running
8 out of 58 running
8 out of 58 running
8 out of 58 running
8 out of 58 running
8 out of 58 running
41 out of 58 running
58 out of 58 running
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().
----------
**provision log:**

TIP: Use 'cf restage spring-cloud-broker' to ensure your env variable changes take effect
cf bind-service spring-cloud-broker-worker spring-cloud-broker-rmq
Binding service spring-cloud-broker-rmq to app spring-cloud-broker-worker in org system / space p-spring-cloud-services as admin...
OK
TIP: Use 'cf restage spring-cloud-broker-worker' to ensure your env variable changes take effect
cf start spring-cloud-broker
Starting app spring-cloud-broker in org system / space p-spring-cloud-services as admin...
Downloading dotnet-core_buildpack...
Downloading java_buildpack...
Downloading ruby_buildpack...
Downloading nodejs_buildpack...
Downloading go_buildpack...
Downloading nodejs_buildpack failed
Downloading python_buildpack...
Destroying container
Downloading ruby_buildpack failed
Downloading php_buildpack...
Downloading java_buildpack failed
Downloading staticfile_buildpack...
Successfully destroyed container

FAILED
StagingError

TIP: use 'cf logs spring-cloud-broker --recent' for more information
deploy-service-broker failed: exit status 1

**Comment by KrishnaT08** [comment]
Below is additional info from cf logs:

vcap@agent-id-pcfdev-0:/var/pcfdev$ cf logs spring-cloud-broker
FAILED
No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.

**Comment by sclevine** [comment]
Hi @KrishnaT08,

Are you running Windows 10 inside of another VM?

Do you require an HTTP proxy to make HTTP requests?

Can you target the org/space that the spring-cloud-broker is running in before running `cf logs spring-cloud-broker --recent`?

**Comment by KrishnaT08** [comment]
Hi @sclevine,

Thanks for the response.  My machine is having windows 10 pro. I am running PCF dev on VirtualBox as recommended in [pcfdev windows installation](https://docs.pivotal.io/pcf-dev/install-windows.html). Also, i am trying this in my home network, so it doesn't need any proxies.

Below is the log requested. I am new to pcf. i hope these are the right commands to give you requested info.

vcap@agent-id-pcfdev-0:/var/pcfdev$ cf login -a api.local.pcfdev.io --skip-ssl-validation
API endpoint: api.local.pcfdev.io
Email> admin
Password>
Authenticating...
OK

Select an org (or press enter to skip):
1. p-spring-cloud-services
2. pcfdev-org
3. system

Org> 3
Targeted org system
Targeted space p-spring-cloud-services

API endpoint:   https://api.local.pcfdev.io (API version: 2.82.0)
User:           admin
Org:            system
Space:          p-spring-cloud-services

vcap@agent-id-pcfdev-0:/var/pcfdev$ cf logs spring-cloud-broker --recent
Connected, dumping recent logs for app spring-cloud-broker in org system / space p-spring-cloud-services as admin...

2017-10-24T01:01:13.96+0000 [API/0]      OUT Created app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264
2017-10-24T01:01:14.04+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"route"=>"0b5d3dce-23b4-4d97-a520-7d98fac2d1d5", :verb=>"add", :relation=>"routes", :related_guid=>"0b5d3dce-23b4-4d97-a520-7d98fac2d1d5"})
2017-10-24T01:02:39.10+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:39.27+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:43.36+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:43.58+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:43.75+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:43.96+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:44.11+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:44.28+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:44.49+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:44.69+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:44.89+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:02:45.13+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:03:34.33+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2017-10-24T01:03:42.28+0000 [API/0]      OUT Updated app with guid 3c7ffd57-e5fe-4681-ae1f-642f5d55c264 ({"state"=>"STARTED"})
2017-10-24T01:03:42.44+0000 [STG/0]      OUT Downloading dotnet-core_buildpack...
2017-10-24T01:03:42.44+0000 [STG/0]      OUT Downloading java_buildpack...
2017-10-24T01:03:42.45+0000 [STG/0]      OUT Downloading ruby_buildpack...
2017-10-24T01:03:42.45+0000 [STG/0]      OUT Downloading nodejs_buildpack...
2017-10-24T01:04:00.39+0000 [STG/0]      OUT Downloading go_buildpack...
2017-10-24T01:04:12.50+0000 [STG/0]      OUT Downloading ruby_buildpack failed
2017-10-24T01:04:12.50+0000 [STG/0]      OUT Downloading python_buildpack...
2017-10-24T01:04:12.51+0000 [STG/0]      OUT Downloading dotnet-core_buildpack failed
2017-10-24T01:04:12.51+0000 [STG/0]      OUT Downloading php_buildpack...
2017-10-24T01:04:12.73+0000 [STG/0]      OUT Destroying container
2017-10-24T01:04:12.74+0000 [STG/0]      OUT Successfully destroyed container
2017-10-24T01:04:17.13+0000 [STG/0]      OUT Downloaded nodejs_buildpack (78.6M)
2017-10-24T01:04:17.13+0000 [STG/0]      OUT Downloading staticfile_buildpack...
2017-10-24T01:04:26.44+0000 [STG/0]      OUT Downloading java_buildpack failed
2017-10-24T01:04:26.44+0000 [STG/0]      OUT Downloading binary_buildpack...
2017-10-24T01:04:47.07+0000 [STG/0]      OUT Downloading python_buildpack failed
2017-10-24T01:04:47.13+0000 [STG/0]      OUT Downloading staticfile_buildpack failed
2017-10-24T01:04:57.06+0000 [STG/0]      OUT Downloading binary_buildpack failed
2017-10-24T01:05:22.28+0000 [STG/0]      OUT Downloaded go_buildpack (412.8M)
2017-10-24T01:05:23.78+0000 [STG/0]      OUT Downloaded php_buildpack (335.9M)
vcap@agent-id-pcfdev-0:/var/pcfdev$

**Comment by KrishnaT08** [comment]
Hi,

Please help on this issue.

**Comment by sclevine** [comment]
Can you provide the full output of `cf dev start -s scs`?

**Comment by KrishnaT08** [comment]
Hi @sclevine ,

Please find below.

C:\Users\KrishnaPC>cf dev start -s scs -m 12000
Using existing image.
Allocating 12000 MB out of 32590 MB total system memory (28595 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 54 running
7 out of 54 running
7 out of 54 running
7 out of 54 running
7 out of 54 running
9 out of 54 running
28 out of 54 running
32 out of 54 running
45 out of 54 running
54 out of 54 running
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().

**Comment by sclevine** [comment]
Can you run `cf dev debug`, confirm that the generated archive doesn't contain anything sensitive, and send it to me at slevine@pivotal.io?

**Comment by KrishnaT08** [comment]
Hi @sclevine,

I have shared the logs. Please check email.

**Comment by sclevine** [comment]
The spring cloud service broker is failing to start with no additional details or logs.

What does your host CPU look like? How heavily is it utilized when you run the VM? Can you reproduce the failure on another machine in your network?

Can you try downgrading to Virtualbox 5.1?

**Comment by KrishnaT08** [comment]
Hi @sclevine ,

Thank you. It worked with Virtualbox 5.1. Below is the log.

C:\Users\KrishnaPC>cf dev start -s scs
Using existing image.
Allocating 8192 MB out of 32590 MB total system memory (28871 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 54 running
7 out of 54 running
7 out of 54 running
7 out of 54 running
37 out of 54 running
54 out of 54 running
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
is now running.
To begin using PCF Dev, please run:
   cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://apps.local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass

C:\Users\KrishnaPC> cf login -a https://api.local.pcfdev.io --skip-ssl-validation
API endpoint: https://api.local.pcfdev.io

Email> user

Password>
Authenticating...
OK

Targeted org pcfdev-org

Targeted space pcfdev-space



API endpoint:   https://api.local.pcfdev.io (API version: 2.82.0)
User:           user
Org:            pcfdev-org
Space:          pcfdev-space

C:\Users\KrishnaPC>cf services
Getting services in org pcfdev-org / space pcfdev-space as user...
OK

No services found

C:\Users\KrishnaPC>cf marketplace
Getting services from marketplace in org pcfdev-org / space pcfdev-space as user...
OK

service                       plans             description
local-volume                  free-local-disk   Local service docs: https://github.com/cloudfoundry-incubator/local-volume-release/
p-circuit-breaker-dashboard   standard          Circuit Breaker Dashboard for Spring Cloud Applications
p-config-server               standard          Config Server for Spring Cloud Applications
p-mysql                       512mb, 1gb        MySQL databases on demand
p-rabbitmq                    standard          RabbitMQ is a robust and scalable high-performance multi-protocol messaging broker.
p-service-registry            standard          Service Registry for Spring Cloud Applications

TIP:  Use 'cf marketplace -s SERVICE' to view descriptions of individual plans of a given service

**Comment by dashaun** [comment]
I'm running CentOS 7, in a VMWare VM with 28 CPU and 52GB RAM and 256GB disk.

I install cf-cli from the yum repository

I'm using pcfdev 0.28

I've tried every permutation of:
VirtualBox 5.2 / VirtualBox 5.1
Kernel 3.10 / Kernel 4.13
Thin provisioned disk / Thick provisioned disk

I'm using
cf dev start -m 49152 -s all

I get to:
56 out of 58 running

Then I get:
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was: ().

I then use:
cf dev debug

Expand the debug file and looking at provision.log, it looks like the cf-mysql-broker is failing to start.

If I remove destroy that vm and start up normally, allocating 4gb ram, it starts properly:
cf dev start

If I startup with scs, allocating 8gb ram, it fails the same was as -s all
cf dev start -s scs 

I'm stuck.

**Comment by dashaun** [comment]
grep "fail" provision.log

I get a bunch of this:

Process 'cf-mysql-broker'           Execution failed
Process '\''silk-daemon'\''               Execution failed
Process '\''cloud_controller_ng'\''       Execution failed
Process '\''cf-mysql-broker'\''           Execution failed
Process '\''silk-daemon'\''               Execution failed
Process '\''cloud_controller_ng'\''       Execution failed
Process '\''cf-mysql-broker'\''           Execution failed
Process 'silk-daemon'               Execution failed
Process 'cloud_controller_ng'       Execution failed
Process 'cf-mysql-broker'           Execution failed
Process '\''silk-daemon'\''               Execution failed
Process '\''cloud_controller_ng'\''       Execution failed
Process '\''cf-mysql-broker'\''           Execution failed

After the failure, the image is always in a bad state:

cf dev start
FAILED
Error: PCF Dev is in an invalid state. Please run 'cf dev destroy' or 'cf dev stop'.

**Comment by dashaun** [comment]
The tail of my provision.log looks like this:

Wed Nov  1 15:12:18 UTC 2017: Pinging rep...
Wed Nov  1 15:12:18 UTC 2017: Attempt 1 failed. Trying again...
...
Wed Nov  1 15:22:16 UTC 2017: Attempt 341 failed. Trying again...
Wed Nov  1 15:22:18 UTC 2017: Attempt 342 failed. Trying again...
Wed Nov  1 15:22:20 UTC 2017: Timed out pinging rep. Failing post-start.

**Comment by sclevine** [comment]
@dashaun We don't support starting the PCF Dev Virtualbox VM nested inside of another VM. We've only seen this configuration succeed when the outer VM is able to provide the inner VM with a disk with very high I/O throughput. Can you use the plugin to start a Virtualbox VM directly on the host?

**Comment by dashaun** [comment]
@sclevine I bet I could do that if you could point me somewhere with an example.

**Comment by sclevine** [comment]
Instructions for installing PCF Dev on your host machine are here: https://docs.pivotal.io/pcf-dev/#installing

**Comment by dashaun** [comment]
Ahh, I only have ESXI hosts available.

So I can't use PCFDev on my VMWare/ESXI hosts at all?

**Comment by sclevine** [comment]
We are actually able to do this on vSphere for CI, but needed to allocate a very fast SAN disk for the VM to start successfully.

If you do get this working, keep in mind that PCF Dev is not a secure distribution of PCF and should not be exposed to untrusted machines on a network.

**Comment by virsingh19** [comment]
I have Windows 10 Home with 8GB RAM, and "cf dev start" was failing to start my 58th service. By default, it starts with 4GB VM, somewhere i read that you should have 16GB RAM, and allot 8GB to the VM. So two things i did 1) increased my RAM to 16GB, and started with "cf dev start -m 8192", also upgraded PCF CLI to pcfdev-v0.29.0+PCF1.11.0-windows.zip. Then i was able to start it successfully, it takes some time to start it though. This is what i see, sweet:

Allocating 8192 MB out of 16292 MB total system memory (12920 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
16 out of 58 running
41 out of 58 running
58 out of 58 running
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
is now running.
To begin using PCF Dev, please run:
   cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://apps.local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass

**Comment by virsingh19** [comment]
My desktop configuration:
Windows 10 Home
Processor: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Installed Memory (RAM): 16.0 GB
