### ISSUE TITLE
Cannot start with cf dev start

### ISSUE THREAD

**Issue by kwangnam** [vmware-archive/pcfdev#266]
I am trying to run sample codes against VM for local execution from the corporate network and get prompted to enter my account info. When I enter my personal account info, I get bad request error. Same when I try it against pivotal server. Any suggestion would be appreciated.

C:\pcf-dev\bosh-lite-master>cf dev start
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email←[36;1m>←[0m

Error: Get https://network.pivotal.io/api/v2/api_token?password ... : Bad Request.

**Comment by sclevine** [comment]
Hi @kwangnam,

It seems like your shell is not reading your login information correctly:
```
Email←[36;1m>←[0m
```
If you're using cmd.exe on Windows, can you try switching to Powershell?

**Comment by kwangnam** [comment]
Thank you for quick response. I still get these garbages on PS. Any suggestion will be helpful. Thank you.

PS C:\pcf-dev\spring-music-master> cf dev start
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email←[36;1m>←[0m admin

Password←[36;1m>←[0m
←[31;1mFAILED←[0m
Error: Get https://network.pivotal.io/api/v2/api_token?password=admin&username=admin: Bad Request.
PS C:\pcf-dev\spring-music-master>

**Comment by sclevine** [comment]
The credentials actually seemed to go through that time. Do you need to use an HTTP proxy to connect the internet?

**Comment by kwangnam** [comment]
Super fast response.... I have added user env variable for https_proxy. What shall I check now? Thank you

**Comment by sclevine** [comment]
Does your proxy require authentication? How have you setup `https_proxy`?

Also, I assume you're using a real PivNet account to login, not just `admin` / `admin`?

**Comment by kwangnam** [comment]
http://*.*.com:80  Do I need to add my account info here? Yes, the same for admin and my personal account at pivotal. Thank you

**Comment by sclevine** [comment]
To confirm, you have `https_proxy` exported and set to something like:
```
http://proxy-user:proxy-pass@example.com:8080
```
You have an account at network.pivotal.io, and you are able to login. You are providing those same credentials as a username and password to `cf dev start`. And you are using the latest version of PCF Dev?

**Comment by kwangnam** [comment]
Thank you for your help. That worked but got another issue about VirtualBox. 

Error: exec: "wmic": executable file not found in %!P(MISSING)ATH%!.(MISSING)

**Comment by sclevine** [comment]
Are you able to start other VMs in Virtualbox?

**Comment by kwangnam** [comment]
Issue Fixed. Thank you for the help
