### ISSUE TITLE
Help needed - Error creating service registry

### ISSUE THREAD

**Issue by KrishnaT08** [vmware-archive/pcfdev#267]
Hi,

I am unable to create new p-service-registry instance.  Below is the log. "Error getting application archive from resource classpath:/apps/spring-cloud-eureka-server.jar" is shown as reason for failure. Please help.

pcfdev version: pcfdev-v0.547.0
Host OS: Windows 10 pro
PCF dev run through Virtualbox 5.1
RAM: 32GB
Pcfdev started with 8 gb.
Reference: [PCF spring cloud services](http://docs.pivotal.io/spring-cloud-services/1-4/common/service-registry/creating-an-instance.html)

**Below is the detailed log**:

C:\Users\KrishnaPC>cf login
API endpoint: https://api.local.pcfdev.io
Email> user
Password>
Authenticating...
OK

Targeted org pcfdev-org
Targeted space pcfdev-space

API endpoint:   https://api.local.pcfdev.io (API version: 2.82.0)
User:           user
Org:            pcfdev-org
Space:          pcfdev-space

C:\Users\KrishnaPC>**cf marketplace -s p-service-registry**
Getting service plan information for service p-service-registry as user...
OK
service plan   description     free or paid
standard       Standard Plan   free

C:\Users\KrishnaPC>**cf create-service p-service-registry standard service-registry**
Creating service instance service-registry in org pcfdev-org / space pcfdev-space as user...
OK
Create in progress. Use 'cf services' or 'cf service service-registry' to check operation status.

C:\Users\KrishnaPC>cf service service-registry
Service instance: service-registry
Service: p-service-registry
Bound apps:
Tags:
Plan: standard
Description: Service Registry for Spring Cloud Applications
Documentation url: http://docs.pivotal.io/spring-cloud-services/
Dashboard: https://spring-cloud-broker.local.pcfdev.io/dashboard/p-service-registry/74dca749-7a39-4a72-8e68-8f3c082aae62
Last Operation
**Status: create failed
Message: Error creating service instance: java.lang.IllegalStateException: Error getting application archive from resource classpath:/apps/spring-cloud-eureka-server.jar**
Started: 2017-10-25T23:42:54Z
Updated: 2017-10-25T23:42:57Z

C:\Users\KrishnaPC>

**Comment by sclevine** [comment]
Hi @KrishnaT08,

Can you try starting PCF Dev with more memory like this:
```
cf dev start -s scs -m 10000
```

**Comment by KrishnaT08** [comment]
Thank you @sclevine 

It works.
