### ISSUE TITLE
"cf dev start" doesn't start the VM

### ISSUE THREAD

**Issue by santoshgodavarthi** [vmware-archive/pcfdev#269]
Hi,

I have tried all the possible options mentioned in this thread, even though I am struck with the same issue, I have some observations and want to know more about them

1) cf dev start (without any -m option) gives the following error.
Less than 4033 MB of free memory detected, continue (y/N): ←[36;1m>←[0m yes
Using existing image.
Starting VM...
←[31;1mFAILED←[0m
Error: failed to start VM: failed to execute 'VBoxManage.exe startvm pcfdev-v0.5
47.0 --type headless': exit status 1: Waiting for VM "pcfdev-v0.547.0" to power
on...
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_
MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
interface IConsole
.

From the error it is clear that VT-x is not enabled at BIOS level on my machine. HOwever, in the Oracle Vitual Box manager I do see the VM in stopped mode and when I lower the memory requirement to some 3099 MB and do a headless start from the Oracle VM Manager, VM starts. Not sure how to interpret this.

2) cf dev start ( with an -m 3099 option) gives the following error
C:\Program Files\Oracle\VirtualBox>cf dev start -d local.pcfdev.io -m 3099

Less than 3099 MB of free memory detected, continue (y/N): ←[36;1m>←[0m yes
Using existing image.
Allocating 3099 MB out of 8067 MB total system memory (2337 MB free).
Importing VM...
Starting VM...
←[31;1mFAILED←[0m
Error: failed to start VM: ssh connection timed out: ssh: handshake failed: read
tcp 127.0.0.1:61867->127.0.0.1:61454: wsarecv: An existing connection was forci
bly closed by the remote host..

This seems to be a firewall issue, but I have disabled all my firewalls. This also appears in the Oracle VM manager and would start right away when I do a headless start from there.

Can you please help with understanding/resolving the issue.

**Comment by sclevine** [comment]
PCF Dev requires VT-x to run. In most cases, VT-x is disabled when running the PCF Dev VM inside of another nested VM, which is not a supported configuration (even with VT-x passthrough, due to I/O constraints).

Also worth noting, PCF Dev requires at least 4GB of free memory to run.
