### ISSUE TITLE
When I try to deploy app , it is showing 404 not found. 

### ISSUE THREAD

**Issue by Aamir-Meman** [vmware-archive/pcfdev#271]
I tried to deploy an app using cf push command , I uninstalled pcf dev and then again I installed PCF dev but same error 
<img width="1407" alt="screen shot 2017-11-08 at 6 38 57 pm" src="https://user-images.githubusercontent.com/22850300/32585944-cce4f91a-c4b4-11e7-9a35-91ab8805b71e.png">

**Comment by sclevine** [comment]
This error appears to be coming from your app, not from PCF Dev. Can you try this with a different app and see if it works?

**Comment by Aamir-Meman** [comment]
I tried with the different app too , I tried with node.  It started again the 404 not found error it is throwing. Same error as above.

**Comment by sclevine** [comment]
Do you use an HTTP proxy to connect to the internet? If so, have you set `no_proxy` for connections to the VM?

That 404 error is not coming from PCF Dev. It's either coming from the app you're pushing, or `curl` is connecting somewhere else.

**Comment by Aamir-Meman** [comment]
I am closing these because it was my fault , you should be in the same directory of your app and then push the application into the cloud foundary.
