### ISSUE TITLE
Not able to start PCF Dev

### ISSUE THREAD

**Issue by lokeshnambiar** [vmware-archive/pcfdev#272]
Hi,
I installed Oracle VirtualBox 5.2.0 in Windows 10 OS.
I installed PCF dev plugin pcfdev-v0.28.0+PCF1.11.0-windows.
When I start PCF Dev using command cf dev start, I get following error
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: failed to execute 'C:\Program Files\Oracle\VirtualBox\VBoxManage startvm pcfdev-v0.547.0 --ty
pe headless': exit status 1: Waiting for VM "pcfdev-v0.547.0" to power on...
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Kindly suggest how to proceed.

**Comment by lokesh-nambiar** [comment]
This issue is resolved if I reduce the size of Motherboard base memory from VirtualBox(Setting->System->MotherBoard) to 512 MB.
From VirtualBox I am able to start the VM

**Comment by sclevine** [comment]
```
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes 
```

We don't support nesting PCF Dev inside another VM, or running PCF Dev on hardware CPUs without the VT-x extension.
