### ISSUE TITLE
https://login.local.pcfdev.io/login [where to?][console n.a.]

### ISSUE THREAD

**Issue by vlaskovic** [vmware-archive/pcfdev#274]
Hi team,

I have a pcf dev local environment set-up for the purposes LFS232 training.
After a PCF DEV login: https://login.local.pcfdev.io/login [admin/admin], I am being redirected, instead of Console (https://console.local.pcfdev.io), to a blank page 'Where to?'. Only logout and account settings are available.

I've played around in the past, with previous versions of Pivotal's CF Development environment, thus I'm certain that console was available for me.

Is there still a way to use Console along pcfdev-v0.28.0+PCF1.11.0-windows and if not, may we please know the reason?

Thank you.
Slobodanka

**Comment by sclevine** [comment]
Hi @vlaskovik,

Sorry for the delay. You can access apps manager (formerly "console") by navigating to https://apps.local.pcfdev.io.
