### ISSUE TITLE
pcf-dev VM appears to set up and provisioned, 58 services are running, but I have an error on every login attempt.

### ISSUE THREAD

**Issue by majordamo** [vmware-archive/pcfdev#275]
**Environment:** Fresh 60GB install of Ubuntu 16.04 LTS on a Thinkpad X250 with 8GB RAM.

**Login in with:** " cf login -a https://api.local.pcfdev.io --skip-ssl-validation  "

**Full error, message:** 

**firstpcf@PCF-on-X250:~$**    cf login -a https://api.local.pcfdev.io --skip-ssl-validation
 cf login -a https://api.local.pcfdev.io --skip-ssl-validation
API endpoint: https://api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp: lookup api.local.pcfdev.io on [::1]:53: read udp [::1]:54457->[::1]:53: read: connection refused
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

**Comment by majordamo** [comment]
I should add, I am not using any sort of proxy service, and am directly connecting with a typical domestic broadband service. I did a lot of fiddling ( under an old installation) before wiping the partition, reinstalling ubuntu and starting again. 

I've not been able to do anything with PCF, even though I can ssh into the instance.

What in the living hell am I doing wrong. 

Disclaimer,I'm a sales pro, and though I have 20 years of Linux usage ( long story ), am very likely to be doing something stupid. Please don't sugar-coat it.

**Comment by majordamo** [comment]
I have a Pivotal Tracker account, but the 'story' appears not to exist.

I am confused because this issue is so early in the setup that I can't fathom how I could be the only one. I can't find anything to help anywhere, though.

**Comment by majordamo** [comment]
I've tried these suggestions on other threads:

a) My home wifi router ( BT HomeHub 4 ) might be the problem. I've connected using a wifi hotspot on my phone instead which *seems* to solve the DNS resolution issue. Still no login though: I now get a similar error message, but showing that PCFDev is timing out.

"https://api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.168.11.11:443: i/o timeout"

192.168.11.11 doesn't respond to ping, but when I ping api.local.pcfdev.io it seems to know to resolve to 192.168.11.11:

"
ping api.local.pcfdev.io
PING api.local.pcfdev.io (192.168.11.11) 56(84) bytes of data.
"

b) I have since done cf dev ssh and attempted to change the timeout duration on the VM to 30 seconds. No change.

c) I have also tried to make my PCFDev available offline by : 

"sudo echo "address=/.local.pcfdev.io/192.168.11.11" >> /etc/dnsmasq.conf"

which returns 

"bash: /etc/dnsmasq.conf: Permission denied"

**Comment by sclevine** [comment]
Sorry for the delay! I'm on vacation until next week, but hopefully I can guide you in the right direction.

This seems like an issue with Virtualbox's network drivers. Can you completely uninstall Virtualbox and PCF Dev, reboot the laptop, install Virtualbox **5.1.30**, reinstall PCF Dev, and try `cf dev start` again?

We plan to support native hypervisors (potentially even VM-less installation on Linux) in the near future.

**Comment by majordamo** [comment]
This is strange,I thought i asked for this to be closed a day or two ago. I think I had three separate problems, hence the slightly different error message ( connection refused / no such host / login timeout). One, some or all may have contributed to my bow-running PCF Dev instance.

1. I stopped using my home router, which appears to have some kind of proxy installed on it's embedded Linux platform. I reinstalled Ubuntu to get rid of the various attempts I had attempted ( dnsmasq, redirect to Google DNS servers a 8.8.8.8; 8.8.4.4 )

2. Created a WiFi Hotspot from my phone and used that instead of my home broadband.

3. I made sure dnsmasq was installed before doing anything else.

Looking forward to a Linux Native version for Ubuntu 16.04 ( I did wonder why PCF Dev was *required* to run in a VM, but  I suppose that's what cloud-native means).

**Comment by majordamo** [comment]
I'd recommend that some better tests were run on different popular versions of Linux. One of the other things I did was to run 16.04 LTS instead of the 17.04 I'd been using before. not sure if this could have made a difference but knowing how distros can differ in where they keep their resolv.conf, dnsmasq.conf and other key files.

Also the graphical methods for changing proxy and DNS settings can differ quite a bit.

Happy to do some testing if it helps, as I now have 17.10 ( Latest ), 19.04 and  16.04.3 LTS installed and can easily run the same test on any other distro.

**Comment by majordamo** [comment]
In case you have access, sclevine, I filed and closed the ticket here. https://support.pivotal.io/tickets/73242
