### ISSUE TITLE
Starting PCF Dev crashes macOS Sierra

### ISSUE THREAD

**Issue by koundinyabs** [vmware-archive/pcfdev#276]
Starting PCF Dev crashes my Mac running Sierra version 10.12.6 (16G1036). 

I am running the latest version of PCF Dev:

```
$ cf dev version
PCF Dev version 0.28.0 (CLI: 5cda315, OVA: 0.547.0)
```
I am running VirtualBox Version 5.2.4 r119785 (Qt5.6.3).

When I try to start PCF dev as follows:

```
$ cf dev start
Using existing image.
Allocating 4096 MB out of 16384 MB total system memory (6953 MB free).
Importing VM...
Starting VM...
```

My Mac just crashes and restarts. This is consistently reproducible. I have not seen any other such issues reported so I am out of ideas on possible workarounds to try. I have tried deleting the PCF Dev VM and .vmdk files and restarting PCF Dev. 

Any ideas on how I can get this to work?

**Comment by sclevine** [comment]
Can you completely uninstall Virtualbox, install the latest **5.1.x** version of Virtualbox, and try again?

**Comment by svrc** [comment]
FWIW, I'm running High Sierra 10.13.2, VirtualBox Version 5.2.4 r119785 (Qt5.6.3), and PCF Dev 0.28 and it's working here.

**Comment by koundinyabs** [comment]
Reinstalling VirtualBox 5.1.x did not help. I needed to replace my Mac. I have not been able to reproduce the problem with my new Mac. I am not sure there is much that can be done here since the problem is now no longer reproducible. Thanks for the suggestions. I will go ahead close this issue.
