### ISSUE TITLE
cf dev plugin logs pivnet username and password when it can't connect to pivnet

### ISSUE THREAD

**Issue by trayo** [vmware-archive/pcfdev#278]
Just encountered this problem with the cf dev plugin when trying to download pcfdev. 

```bash
$ cf dev start
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email> tyodf@allstate.com

Password>
```

If you turn off your connection to the internet you will encounter this error:

```bash
FAILED
Error: Get https://network.pivotal.io/api/v2/api_token?password=thisIsMyPassword&username=someUsername: read tcp 10.152.32.94:52334->52.1.11.18:443: read: connection reset by peer
```

This error will log your username and password to pivnet because the credentials are being passed as a query on the request. This can cause a problem for us because we pair program and it can expose our password to our pair and log our password to our bash history.

When `resp, err := http.DefaultClient.Do(req)` fails, will log an error that contains the url you're trying to connect to as well as the path and any queries attached to that url.

Here is my plugin version:
```bash
$ cf dev version
PCF Dev version 0.28.0 (CLI: 5cda315, OVA: 0.547.0)
```

Here is some code to reproduce it without the plugin:

```go
package main

import "net/http"

func main() {
	req, err := http.NewRequest(
		"GET",
		"https://network.pivotal.io"+"/api/v2/api_token",
		nil,
	)
	if err != nil {
		panic(err)
	}

	req.Header.Set("User-Agent", "PCF-Dev-client")

	username := "someUsername"
	password := "thisIsMyPassword"

	query := req.URL.Query()
	query.Add("username", username)
	query.Add("password", password)
	req.URL.RawQuery = query.Encode()

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		println("##################################")
		panic(err)
	}
	defer resp.Body.Close()

	println("finished with no errors")
}
```

and the result:

```bash
go run main.go
##################################
panic: Get https://network.pivotal.io/api/v2/api_token?password=thisIsMyPassword&username=someUsername: read tcp 10.152.32.94:52334->52.1.11.18:443: read: connection reset by peer
```

**Comment by sclevine** [comment]
Hi @trayo,

Thank you for reporting this! This is definitely not intentional. I strongly suspect that we shouldn't be sending the credentials in the URL in the first place.

We're currently working on a re-write of PCF Dev that will use a more robust oauth2-based authentication mechanism to talk to PivNet. I'll update this issue soon once we determine the best path forward to fixing this.

**Comment by aemengo** [comment]
This issue is no longer applicable to the latest iteration of [CF Dev](https://github.com/cloudfoundry-incubator/cfdev).
