### ISSUE TITLE
Can't start two PCFDEV environments concurrently

### ISSUE THREAD

**Issue by neilstevenson** [vmware-archive/pcfdev#280]
This doesn't work

```
$ cf dev start -c 2 -m 3072 -d local2.pcfdev.io
```

and

```
$ cf dev start -d local3.pcfdev.io
```
gives
```
Error: the -d flag cannot be used if the VM has already been created.
```

So _local3_ clashes with _local2_.

If two environments can be running concurrently, you can test blue/green deployment.

**Comment by sclevine** [comment]
We don't support running multiple instance of PCF Dev on the same workstation. It is usually possible to do this by setting `PCFDEV_HOME` to a different location for the second invocation of `cf dev start`, but unfortunately a bug in the latest version of PCF Dev prevents apps manager from starting successfully on domains other than `local.pcfdev.io`.

That said, don't need two instances of PCF Dev to test blue-green app deployment. Can you provide more details about your use case?

**Comment by neilstevenson** [comment]
The blue-green option was just an example. What I was trying to do was run two PCF Devs on the one workstation. This would allow me to test failover of an external app from on PCF to another.

If you can't do this, there doesn't seem to be much point in being able specify the domain prefix.

**Comment by sclevine** [comment]
The domain prefix specification with `-d` exists for two reasons:
1. The `local[X].pcfdev.io` DNS records are public records that correspond to particular private IPs. Those IPs may already be in use locally. The CLI plugin will try to detect this scenario and correct for it (by picking `local2.pcfdev.io` if the IP for `local.pcfdev.io` is already in use, for example), but it's useful to be able to control this manually.
2. Sometimes it's useful to bind the PCF Dev VM to the host, which requires setting the CF system domain to a DNS record that resolves to the host IP. (We don't encourage this unless all hosts on the host's network are completely trusted.)

That said, in all versions except for the latest, you should be able to run multiple instances by changing the value of the `PCFDEV_HOME` env var.

**Comment by neilstevenson** [comment]
Perhaps the question is, should this be supported ?

It did work, now it doesn't. 

It would be useful to make it work again, but if that's not the intention this issue is not relevant and can be closed.

**Comment by sclevine** [comment]
Changing the domain should be supported, and changing the storage directory for the VM should be supported. Running multiple instances of PCF Dev happened to work with these two options together, but is not intentionally supported.

The next version of PCF Dev will be a complete re-write, using real BOSH and native hypervisors. It will not be affected by the bug in 0.28.0 that prevents changing the domain. We will likely support changing the domain and storage directory in the next version, but I don't expect that we will explicitly support running multiple instances.
