### ISSUE TITLE
pcfdev on amazon/linux ec2 instance

### ISSUE THREAD

**Issue by TCSCMAPIVOTAL** [vmware-archive/pcfdev#281]
I am using - 
Vagrant.configure("2") do |config|
  config.vm.box = "pcfdev/pcfdev"
end
ver: v0.88.0

Though Vagrant file mentions the aws.ami (the ami_id of my ec2 instance), vagrant up is picking the default ami which is not available in us-west-2.

All other properties are getting picked correctly from Vagrantfile but not the ami. 
Is there any solution?

**Comment by TCSCMAPIVOTAL** [comment]
Adding snippets to the issue:

Vagrantfile

   aws.ami = "ami-bf4193c7"
   aws.region = "us-west-2"
   aws.availability_zone = "us-west-2a"
   aws.instance_type = "t2.large"
   aws.security_groups = ["sg-0d46d071"]
   aws.subnet_id = "subnet-c52ca28d"
   aws.tags = {'Name' => "pcfdev"}
   override.ssh.username = "root"



other properties are also mentioned but not displayed here

]# VAGRANT_LOG=debug vagrant up --provider aws


==> default: Launching an instance with the following settings...
 INFO interface: info:  -- Type: t2.large
 INFO interface: info: ==> default:  -- Type: t2.large
==> default:  -- Type: t2.large
 INFO interface: info:  -- AMI: ami-6e17ef0e
 INFO interface: info: ==> default:  -- AMI: ami-6e17ef0e
==> default:  -- AMI: ami-6e17ef0e
 INFO interface: info:  -- Region: us-west-2
 INFO interface: info: ==> default:  -- Region: us-west-2
==> default:  -- Region: us-west-2
 INFO interface: info:  -- Availability Zone: us-west-2a
 INFO interface: info: ==> default:  -- Availability Zone: us-west-2a
==> default:  -- Availability Zone: us-west-2a


This is not the AMI that is mentioned on Vagrantfile. Where from it's getting picked ?

**Comment by sclevine** [comment]
We no longer publicly offer PCF Dev for AWS. If you are a Pivotal employee, please reach out to me on Slack (slevine).
