### ISSUE TITLE
PCF Config server unable to checkout from Git Repository via SSH

### ISSUE THREAD

**Issue by sunny-xgcp** [vmware-archive/pcfdev#283]
I installed a PCF dev(v0.28.0) instance on one of my machines. I installed a config server instance from the market place on that machine. The configuration which I provided to it was this: 
{ 
 "git": { 
 "uri": "git@gitlab.****.****.com:****/config-server-property-files.git", 
	"hostKey": "AAAA*****************************************fQHgM=", 
	"hostKeyAlgorithm": "ecdsa-sha2-nistp256", 
	"privateKey": "-----BEGIN RSA PRIVATE KEY-----\nMIIPEJrr *******///wIAOZw5P5\n-----END RSA PRIVATE KEY-----", 
	"cloneOnStart": "true" 
	} 
}

But the service fails to start and below error is shown in logs:

Invocation of init method failed; nested exception is org.eclipse.jgit.api.errors.TransportException: ssh://git@gitlab.****.****.com/configuration.git: reject HostKey: gitlab.****.****.com

I double checked the host key and it is correct. I even tried it by removing "hostKey" and "hostKeyAlgorithm" but still no luck, still the same error is shown in logs.

PS: If I provide it http configuration of Git instead of SSH then it works perfectly fine.

**Comment by sclevine** [comment]
Seems like an issue with Spring Config Server. Have you reached out to the developers of that project about this error?

**Comment by sunny-xgcp** [comment]
I've just posted an issue on config server git repo. Closing the issue here.
https://github.com/pcf-guides/gs-configuration-server/issues/3
