### ISSUE TITLE
pcf dev deployment fails on MacOS with -i and -d flags

### ISSUE THREAD

**Issue by crissonpl** [vmware-archive/pcfdev#287]
hi,

I'm trying to deploy pcf dev with the following flags:

cf dev start -i 192.168.56.7 -d chris.io

it fails with the following error:
Warning: the chosen PCF Dev VM IP address may be in use by another VM or device.
Using existing image.
Allocating 4096 MB out of 16384 MB total system memory (7364 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
40 out of 58 running
56 out of 58 running
58 out of 58 running
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().

when I access the provision log I can see that it tries to use the default IP instead of the one I've specified.

Setting api endpoint to http://api.local.pcfdev.io...
Request error: Get http://api.local.pcfdev.io/v2/info: dial tcp 192.168.11.11:80: getsockopt: connection timed out
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED

any hints? the plain cf dev start works fine. macOS HighSierra 10.13.2 (17C205)

**Comment by sclevine** [comment]
Known issue: #263 
Apologies for the delay in fixing this -- the next release is a complete re-write with full BOSH and native hypervisors (no Virtualbox).
