### ISSUE TITLE
pcf dev start issues on windows

### ISSUE THREAD

**Issue by codefordream2014** [vmware-archive/pcfdev#289]
The following errors display when I run pcf dev start .

Error: failed to start VM: ssh connection timed out: ssh: handshake failed: ssh:
 unable to authenticate, attempted methods [none publickey], no supported method
s remain.

PCF DEV Version:
PCF Dev version 0.28.0 (CLI: 5cda315, OVA: 0.547.0)

**Comment by sclevine** [comment]
Hi @codefordream2014, sorry for the extended delay.

Did you get this working? If not, what OS are you running? Can you provide the full output of `cf dev start`?

**Comment by codefordream2014** [comment]
Thanks. This issue was resolved. It was because the network issue I guess.
