### ISSUE TITLE
cf login -a https://api.local.pcfdev.io issue 

### ISSUE THREAD

**Issue by ghost** [vmware-archive/pcfdev#290]
We are facing issue in accessing https://api.local.pcfdev.io --skip-ssl-validation with error message

ubuntu@ubuntu:~$ cf login -a https://api.local.pcfdev.io --skip-ssl-validation
API endpoint: https://api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.168.11.1:443: getsockopt: connection refused
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

Here is my environment 
Ubuntu 14.04, Virtualbox 5.2 , pcfdev-v0.28.0+PCF1.11.0-linux , pcfdev-v0.547.0.ova, cf version 6.34.1+bbdf81482.2018-01-17 

Environment is inside corporate proxy and proxy is set as below  
export HTTP_PROXY=http://x.x.x.x:8080
export HTTPS_PROXY=http://x.x.x.x:8080
export NO_PROXY=localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,localhost,local.pcfdev.io
export http_proxy=http://x.x.x.x:8080
export https_proxy=http://x.x.x.x.10:8080
export no_proxy=localhost,127.0.0.1,192.168.11.1,192.168.11.11,local.pcfdev.io,localhost,local.pcfdev.io

I am able to ping/ssh  Virtualbox IP 

ubuntu@ubuntu:~/.pcfdev/ova$ ping 192.168.11.1
PING 192.168.11.1 (192.168.11.1) 56(84) bytes of data.
64 bytes from 192.168.11.1: icmp_seq=1 ttl=64 time=0.049 ms
64 bytes from 192.168.11.1: icmp_seq=2 ttl=64 time=0.034 ms
^C
--- 192.168.11.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.034/0.041/0.049/0.009 ms

ubuntu@ubuntu:~/.pcfdev/ova$ ping api.local.pcfdev.io
PING api.local.pcfdev.io (192.168.11.1) 56(84) bytes of data.
64 bytes from api.local.pcfdev.io (192.168.11.1): icmp_seq=1 ttl=64 time=0.044 ms
64 bytes from api.local.pcfdev.io (192.168.11.1): icmp_seq=2 ttl=64 time=0.050 ms
64 bytes from api.local.pcfdev.io (192.168.11.1): icmp_seq=3 ttl=64 time=0.047 ms

ubuntu@ubuntu:~/.pcfdev/ova$ ssh admin@api.local.pcfdev.io
The authenticity of host 'api.local.pcfdev.io (192.168.11.1)' can't be established.
ECDSA key fingerprint is 57:6c:4b:a0:01:0f:b3:f3:62:bb:f8:f7:c5:92:2e:58.
Are you sure you want to continue connecting (yes/no)?

could anyone suggest any possible solutions?

**Comment by SnehaKumari22** [comment]
@mymobileapplication  Can you try logging in after unsetting all the proxies.

**Comment by ghost** [comment]
@SnehaKumari22  there was some port issue .. now it work fine .. 
@SnehaKumari22  have you deployed Spring Cloud Services(SCS) in PCF Dev?

**Comment by SnehaKumari22** [comment]
@mymobileapplication  Yes, I have.  You can follow [usage-scs](https://docs.pivotal.io/pcf-dev/usage-scs.html) .

**Comment by sclevine** [comment]
Glad to hear this is working now!
