### ISSUE TITLE
Error: exec: "wmic": executable file not found in %!P(MISSING)ATH%!.(MISSING)

### ISSUE THREAD

**Issue by aalapargekar** [vmware-archive/pcfdev#291]
I amusing windows 10.

These are the steps I followed:
1.	downloaded virtual box from https://www.virtualbox.org/ and installed it
2.	downloaded pcf dev from https://network.pivotal.io/products/pcfdev 
3.	opened cmd, went to location of download and executed .\pcfdev-v0.28.0+PCF1.11.0-windows.exe
4.	started pcf dev with this command
cf dev start
5.	entered my pivotal network user and password
6.	vm download started
after about 15-20 minutes got this error
FAILED
Error: exec: "wmic": executable file not found in %!P(MISSING)ATH%!.(MISSING)

**Comment by sclevine** [comment]
Sorry for the delay. Can you uninstall Virtualbox, reboot, install Virtualbox 5.1, reboot again, and then run `cf dev start`?

**Comment by kfishman** [comment]
I am having the same issue. Also on Windows 10. Followed the instructions to uninstall Virtualbox 5.1, reboot, install Virtual 5.1, reboot, and then I performed the actions in the screenshot provided which closely resembles the steps from the original poster. I am still receiving the same issue.
![image](https://user-images.githubusercontent.com/12885537/37364554-dcc6daee-26c8-11e8-84ba-d25eda95276b.png)

**Comment by sclevine** [comment]
It seems like this happens when you override your `PATH` env var. Have either of you done that?

**Comment by rohitedu08** [comment]
I am also facing the same issue. It happens after the download of VM is finished. I am using powers shell to install it. 

Less than 3943 MB of free memory detected, continue (y/N): ←[36;1m>←[0m y
Downloading VM...
Progress: |====================>| 100%
VM downloaded.
←[31;1mFAILED←[0m
Error: exec: "wmic": executable file not found in %!P(MISSING)ATH%!.(MISSING)

**Comment by aemengo** [comment]
This issue is no longer applicable to the current iteration of [CF Dev](https://github.com/cloudfoundry-incubator/cfdev). Please consider upgrading.
