### ISSUE TITLE
Can't download greenplum 5.3 from Pivotal Network #64

### ISSUE THREAD

**Issue by diaowenyang** [vmware-archive/pcfdev#292]
I get unable to download "Unfortunately, we are unable to provide you with access to download software at this time. Please contact export@pivotal.io for assistance." When trying to download Greenplum Database 5.3.0 Binary Installer for RHEL 7 from the pivotal network.

And I send email to export@pivotal.io but get no reply.
My accounts is : tinyyang@hotmail.com

**Comment by sclevine** [comment]
Hi @diaowenyang,

Please reach out to [Pivotal Support](https://support.pivotal.io/) for questions that are not related to PCF Dev.
