### ISSUE TITLE
How to install pcf-dev on external hard drive not on defaul like C: on Windows 10?

### ISSUE THREAD

**Issue by mikulass** [vmware-archive/pcfdev#295]
Hello, sorry for this strange question... I can't find in the documentation some guidelines how can I force to install pcf-dev on my local Win 10  to the external drive, in my case E. Default installation is using system drive C: by default. My Virtual box has set properties for default VMs folder for the external E: drive, but somehow this property is not used...Any idea is highly appreciated. Thanks in advance. Best regards.

**Comment by cicnavi** [comment]
Hi @mikulass, I was having the same question, so I think I can help you out. You can do this by setting the Windows environment variable with the name of PCFDEV_HOME. For example, I've put my to the "E:\pcfdev". 
![image](https://user-images.githubusercontent.com/3176844/36410349-e5657778-1610-11e8-9688-8fe7d08b10c6.png)

**Comment by mikulass** [comment]
Hi, it works ! Thanks.
