### ISSUE TITLE
Missing marketplace - pcfdev 0.29

### ISSUE THREAD

**Issue by akoranne** [vmware-archive/pcfdev#298]
In 0.29 ver, I don't see the marketplace in the AppsMgr. 
Is that a bug or as expected? 

Attached are the screenshots.
![pcfdev-appsmgr-snap](https://user-images.githubusercontent.com/9610655/36570738-19f09f10-17f9-11e8-99e1-399c3ccdbfb1.jpeg)
![pcfdev-appsmgr-user-snap](https://user-images.githubusercontent.com/9610655/36570739-1a015620-17f9-11e8-967d-d5d6cd0331dc.jpeg)

**Comment by sclevine** [comment]
I don't believe this behavior changed from any previous version of PCF Dev. Marketplace services are accessible via each app page in the interface.

**Comment by akoranne** [comment]
Thanks @sclevine
