### ISSUE TITLE
Issues routing from PCF Dev to local machine since 0.29.0 release

### ISSUE THREAD

**Issue by izgeri** [vmware-archive/pcfdev#299]
I was using `https://host.pcfdev.io:8443/api` in an app (App 1) deployed to PCF Dev to refer to a service (App 2) I am running in a Docker container on my machine (ie not deployed to PCF Dev) that is accessible at `https://localhost:8443/api`. This configuration was working perfectly fine in v0.28.0 (well, until the cert issue prevented PCF Dev from starting).

Since the update to v0.29.0, App 1 is having certificate issues in connecting to App 2. The cert is configured in the env of App 1, and if I copy the env of App 1 to my local env and run the app locally on my machine (ie not in PCF Dev), it is able to connect to App 2 successfully. It seems like the URL `https://host.pcfdev.io:8443/api` within PCF Dev is not successfully routing to `https://localhost:8443/api` as it was before this release.

I am trying to look at your release notes to find more info about the specific changes made for this release, especially those that relate to #263 (since it looks like it could be relevant), but I can't find them (this repo only has README changes; all other referenced services are noted as "maintained" at their current release in the v0.29.0 release notes).

If I want to reference something running at `https://localhost:8443/api` from an app running in PCF Dev, what URL should I be using now?

FWIW, I am able to route http://host.pcfdev.io to http://localhost successfully.

**Comment by izgeri** [comment]
FWIW I was adding `host.pcfdev.io` as an altname on my cert - I'm not sure if I need to change the URL that my internal-to-PCF-Dev app uses or if I need to modify the altname.

The specific error I am seeing on trying to connect is
```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

**Comment by sclevine** [comment]
Hi @izgeri,

We deprecated the current implementation of PCF Dev for [CF Dev](https://github.com/pivotal-cf/cfdev), which runs on native hypervisors and provides a functional BOSH director. We will have a release of PCF Dev that is based on CF Dev soon.

PCF Dev v0.29.0 was created by manually patching the v0.28.0 OVA with two small changes:
1. An internal certificate that expired was replaced with a new certificate.
2. A hard-coded reference to `local.pcfdev.io` in a bash script was replaced with a variable.

Neither of these changes should change the behavior `host.pcfdev.io`.

`host.pcfdev.io` does not actually resolve to the local loopback interface on the host (`localhost`). It resolves to an interface on the host that Virtualbox configures (usually `192.168.11.1`). The host's `localhost` is actually impossible to route from inside of a VM running on the host. Is it possible that your Docker service was listening on `0.0.0.0:8443` (all interfaces), but you changed it to `localhost:8443`?

If not, are you able to login to the PCF Dev VM with `cf dev ssh` and access `host.pcfdev.io:8443` from there?

Also, can you provide the full boot output from `cf dev start`? If PCF Dev started with a different domain (ex. `local2.pcfdev.io`) you may need to use `host2.pcfdev.io` in some cases (although `host.pcfdev.io` should always alias to the correct host interface when inside the VM).

**Comment by sclevine** [comment]
Also, if you have Docker installed and don't use the services included with PCF Dev, you may want to try out [CF Local](https://github.com/cloudfoundry-incubator/cflocal).

**Comment by izgeri** [comment]
Thanks for providing more details. Mysteriously, without changing anything except running `cf dev destroy` and `cf dev start`, it worked today.

I'm looking forward to checking out CF Dev. Thanks!
