### ISSUE TITLE
[Proxy] Unable to start PCF-Dev environment: Timed out after 3600 seconds.

### ISSUE THREAD

**Issue by aibondarenko** [vmware-archive/pcfdev#300]
I have host machine, configured with cntlm proxy.
Cntlm listens on 127.0.0.1:3128 by default, i.e.
$ echo $https_proxy, $https_proxy 
`http://127.0.0.1:3128, http://127.0.0.1:3128`

Then i tried to run `cf dev start` and here is what i get:

$ cat /var/vcap/sys/log/galera-healthcheck/galera-healthcheck.stdout.log

`{"timestamp":"1519629333.416443825","source":"Galera Healthcheck","message":"Galera Healthcheck.Opened DB connection","log_level":1,"data":{"dbHost":"0.0.0.0","dbPort":3306,"dbUser":"galera-healthcheck"}} {"timestamp":"1519629333.416599989","source":"Galera Healthcheck","message":"Galera Healthcheck.Serving healthcheck endpoint","log_level":1,"data":{"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629333.416669369","source":"Galera Healthcheck","message":"Galera Healthcheck.Attempting to GET endpoint...","log_level":1,"data":{"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629333.420529366","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629343.422592878","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629353.495323420","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629363.500431061","source":"Galera Healthcheck","message":"Galera Healthcheck.Initialization failed: Coudn't GET endpoint","log_level":3,"data":{"error":"Get http://0.0.0.0:9200/: http: error connecting to proxy http://192.168.11.1:3128: dial tcp 192.168.11.1:3128: getsockopt: connection refused","retries":0,"trace":"goroutine 6 [running]:\ngithub.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc420016300, 0x78d407, 0x2b, 0x9038e0, 0xc42017a300, 0xc4201ca018, 0x1, 0x1)\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager/logger.go:131 +0xc7\nmain.main.func1(0x909c20, 0xc420016300, 0xc4200cdc40, 0x14, 0xc420011720, 0xc420094f00)\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:112 +0x100e\ncreated by main.main\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:141 +0xe20\n","url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629403.844105959","source":"Galera Healthcheck","message":"Galera Healthcheck.Opened DB connection","log_level":1,"data":{"dbHost":"0.0.0.0","dbPort":3306,"dbUser":"galera-healthcheck"}} {"timestamp":"1519629403.844160795","source":"Galera Healthcheck","message":"Galera Healthcheck.Serving healthcheck endpoint","log_level":1,"data":{"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629403.844226837","source":"Galera Healthcheck","message":"Galera Healthcheck.Attempting to GET endpoint...","log_level":1,"data":{"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629403.844918966","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629413.851252794","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629423.861242056","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629433.861534357","source":"Galera Healthcheck","message":"Galera Healthcheck.Initialization failed: Coudn't GET endpoint","log_level":3,"data":{"error":"Get http://0.0.0.0:9200/: http: error connecting to proxy http://192.168.11.1:3128: dial tcp 192.168.11.1:3128: getsockopt: connection refused","retries":0,"trace":"goroutine 6 [running]:\ngithub.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc420016300, 0x78d407, 0x2b, 0x9038e0, 0xc420164d20, 0xc4201a8000, 0x1, 0x1)\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager/logger.go:131 +0xc7\nmain.main.func1(0x909c20, 0xc420016300, 0xc4200cdc20, 0x14, 0xc4200116f0, 0xc420094f00)\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:112 +0x100e\ncreated by main.main\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:141 +0xe20\n","url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629473.284442663","source":"Galera Healthcheck","message":"Galera Healthcheck.Opened DB connection","log_level":1,"data":{"dbHost":"0.0.0.0","dbPort":3306,"dbUser":"galera-healthcheck"}} {"timestamp":"1519629473.284554958","source":"Galera Healthcheck","message":"Galera Healthcheck.Serving healthcheck endpoint","log_level":1,"data":{"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629473.284676313","source":"Galera Healthcheck","message":"Galera Healthcheck.Attempting to GET endpoint...","log_level":1,"data":{"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629473.288128853","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629483.290256739","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629493.292359591","source":"Galera Healthcheck","message":"Galera Healthcheck.GET endpoint failed, retrying...","log_level":1,"data":{"err":{"Op":"Get","URL":"http://0.0.0.0:9200/","Err":{}},"url":"http://0.0.0.0:9200/"}} {"timestamp":"1519629503.292645454","source":"Galera Healthcheck","message":"Galera Healthcheck.Initialization failed: Coudn't GET endpoint","log_level":3,"data":{"error":"Get http://0.0.0.0:9200/: http: error connecting to proxy http://192.168.11.1:3128: dial tcp 192.168.11.1:3128: getsockopt: connection refused","retries":0,"trace":"goroutine 6 [running]:\ngithub.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc420016300, 0x78d407, 0x2b, 0x9038e0, 0xc420186300, 0xc42002a180, 0x1, 0x1)\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager/logger.go:131 +0xc7\nmain.main.func1(0x909c20, 0xc420016300, 0xc4200cdc60, 0x14, 0xc420011720, 0xc420094f00)\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:112 +0x100e\ncreated by main.main\n\t/var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:141 +0xe20\n","url":"http://0.0.0.0:9200/"}}`

$ cat /var/vcap/sys/log/galera-healthcheck/galera-healthcheck.stderr.log

`panic: Get http://0.0.0.0:9200/: http: error connecting to proxy http://192.168.11.1:3128: dial tcp 192.168.11.1:3128: getsockopt: connection refused
goroutine 6 [running]: panic(0x726660, 0xc42017a300) /var/vcap/data/packages/golang/c9a99ecdee290e15198713da72db3d5d78743f96/src/runtime/panic.go:500 +0x1a1 github.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc420016300, 0x78d407, 0x2b, 0x9038e0, 0xc42017a300, 0xc4201ca018, 0x1, 0x1) /var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager/logger.go:152 +0x41c main.main.func1(0x909c20, 0xc420016300, 0xc4200cdc40, 0x14, 0xc420011720, 0xc420094f00) /var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:112 +0x100e created by main.main /var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:141 +0xe20 panic: Get http://0.0.0.0:9200/: http: error connecting to proxy http://192.168.11.1:3128: dial tcp 192.168.11.1:3128: getsockopt: connection refused
goroutine 6 [running]: panic(0x726660, 0xc420164d20) /var/vcap/data/packages/golang/c9a99ecdee290e15198713da72db3d5d78743f96/src/runtime/panic.go:500 +0x1a1 github.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc420016300, 0x78d407, 0x2b, 0x9038e0, 0xc420164d20, 0xc4201a8000, 0x1, 0x1) /var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/vendor/code.cloudfoundry.org/lager/logger.go:152 +0x41c main.main.func1(0x909c20, 0xc420016300, 0xc4200cdc20, 0x14, 0xc4200116f0, 0xc420094f00) /var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:112 +0x100e created by main.main /var/vcap/packages/galera-healthcheck/src/github.com/cloudfoundry-incubator/galera-healthcheck/main.go:141 +0xe20`

192.168.11.1 is the address of `vboxnet0` network, created by `cf dev start` i guess.
here is the env from `cf dev ssh`:
$ echo $http_proxy, $https_proxy 
`http://192.168.11.1:3128, http://192.168.11.1:3128`
How should i configure it to work behind proxy?

**Comment by aibondarenko** [comment]
I've tried to change cntlm default listen settings (in order to manually force connection),
so i edit /etc/cntlm.conf on host to:
`Listen 192.168.11.1:3128 ` 
and run
`cf dev destroy; cf dev start`

now i get the following:
$ time cf dev start -m 8096 -s none
`Using existing image.
Allocating 8096 MB out of 15924 MB total system memory (14301 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 52 running
...
52 out of 52 running
...
is now running.`

ok, it works with some tricks like
$ http_proxy="" https_proxy="" cf login -a https://api.local.pcfdev.io --skip-ssl-validation
`API endpoint: https://api.local.pcfdev.io`

but, nevertheless, out-of-the-box proxy support is still questionable..

**Comment by sclevine** [comment]
Hi @aibondarenko,

Sorry for the delay. It is not possible for VMs to route the local loopback (`127.0.0.1`). This is not just a limitation of PCF Dev. All local proxies must run on all interfaces, or on the IP that `host.pcfdev.io` resolves to. This is documented here: https://docs.pivotal.io/pcf-dev/proxy.html
