### ISSUE TITLE
pull docker image from remote repository and run on PCF DEV

### ISSUE THREAD

**Issue by ashearer23** [vmware-archive/pcfdev#301]
I have a Docker image hosted on a remote Nexus repository that I want to run on a local PCF DEV Virtual Machine (running version 1.11). 
My manifest.yml file looks like this:

--- 
applications:

- name: image-name 
instances: 1 
random-route: true 
docker: 
image: url-to-repo/image-name

But i get a "Failed getting docker image by tag: Received unexpected HTTP status: 504 Unknown Host Going to retry attempt: 1" message. How do I go about running a docker image on my local Windows PCF DEV VM?

**Comment by sclevine** [comment]
See: https://docs.pivotal.io/pcf-dev/configuring.html#insecure-docker-registries
