### ISSUE TITLE
Unable to push Docker image from local registry

### ISSUE THREAD

**Issue by ashearer23** [vmware-archive/pcfdev#302]
I am running Docker and PCFDEV VM on Windows 7. I built a local registry using the instructions listed here: https://docs.docker.com/registry/deploying/#storage-customization 

I was able to successfully push the Docker image out to the local registry, but when i try to do a cf push of the image to my PCFDEV machine, I get the following:

C:\sandboxes\Pivotal-Cloud-Foundry>cf push image --docker-image localhost:5000/image:latest
REQUEST: [2018-03-02T13:27:51-06:00]
GET /v2/info HTTP/1.1
Host: api.local.pcfdev.io
Accept: application/json
User-Agent: cf/6.34.0+f53d03a5e.2018-01-09 (go1.9.2; amd64 windows)

REQUEST: [2018-03-02T13:27:56-06:00]
GET /v2/info HTTP/1.1
Host: api.local.pcfdev.io
Accept: application/json
User-Agent: cf/6.34.0+f53d03a5e.2018-01-09 (go1.9.2; amd64 windows)

REQUEST: [2018-03-02T13:28:01-06:00]
GET /v2/info HTTP/1.1
Host: api.local.pcfdev.io
Accept: application/json
User-Agent: cf/6.34.0+f53d03a5e.2018-01-09 (go1.9.2; amd64 windows)

Request error: Get https://api.local.pcfdev.io/v2/info: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network co
nnection.
FAILED

I do have the http_proxy & https_proxy set, but I still get this problem. Any ideas?

**Comment by sclevine** [comment]
See: https://docs.pivotal.io/pcf-dev/configuring.html#insecure-docker-registries
