### ISSUE TITLE
Connecting to apps/HTTP over LAN

### ISSUE THREAD

**Issue by pbaletkeman** [vmware-archive/pcfdev#303]
I cannot seem to connect using HTTP/HTTPS to the Ubuntu Server which is running PCFDEV from my Windows 10 Pro system. I can SSH into the PCFDEV system no problem and from there I can access all the commands that you would expect. However now I'm getting to the point where I'd like to connect to the system using a web browser (Chrome) and sites like https://apps.local.pcfdev.io but when I try I'm told that the sites cannot be found/loaded.

I do have Acrylic working as mentioned here https://docs.pivotal.io/pcf-dev/work-offline.html#windows.

I do not have any proxy setup anywhere and there are only three systems on this home LAN.

From the Windows system I can ping 192.168.11.1 and get a response valid reply. 

When I try pinging 192.168.11.11, I get "Request timed out." when tried from both within Windows the my Wifi Router/Access Point.

Nslookup resolves apps.local.pcfdev.io to 192.168.11.11.

- PCFDEV Host System: Ubuntu 17.10 Server
- VirtualBox version:  5.2_5.2.6-120293
- System making HTTP request: Windows 10 Pro

Can you please tell me what I'm missing or how to fix this?

**Comment by sclevine** [comment]
PCF Dev is not a secure distribution of PCF and does not support remote access. You can install Virtualbox and run `cf dev start` directly on your Windows 10 Pro workstation.

**Comment by pbaletkeman** [comment]
Thank you, yes I have started to use PCF Dev on my Windows 10 Pro workstation. However my Windows system is not as strong as my other (Ubuntu) system. Thank you for letting me know of this limitation as I had suspected that my system networking was not setup correctly.
