### ISSUE TITLE
Can you ping/nlsookup/curl an outside domain?

### ISSUE THREAD

**Issue by pbaletkeman** [vmware-archive/pcfdev#304]
From within an org using **cf** can you curl/ping/nslookup an outside domain e.g. google.com ?
For example:
 `cf myOrg curl https://www.google.com`
 `cf myOrg ping www.google.com`
 `cf myOrg nslookup www.google.com`
Something like this would help troubleshoot DNS issues with either the PCFDEV virtual image and/or the system hosting the PCFDEV image. 
If the PCFDEV image cannot get out to an outside site then you would know where to start looking for the cause of the problem.
**cf** does include a variant of curl however it has been very seriously limited with the functionality that it can preform regarding domains outside of the current system/space/org.

**Comment by sclevine** [comment]
PCF Dev is a cf CLI plugin that adds a `cf dev` command to the cf CLI. It does not affect any other behavior of the cf CLI.

The `cf curl` command is intended to automatically authenticate you with the credentials necessary to curl the targetted Cloud Controller API. It isn't intended as a general-purpose version of curl, and it doesn't run the resulting `curl` command from within the VM.

The commands you are looking for are `cf dev ssh`, which gives you shell access to the PCF Dev VM, and `cf ssh`, which gives you shell access to a single application container.

**Comment by pbaletkeman** [comment]
Yes, you are correct and thanks for your insight in this matter.
