### ISSUE TITLE
Dotnet Core Local Debugging in PCF Dev (Question)

### ISSUE THREAD

**Issue by ssuluh** [vmware-archive/pcfdev#305]
Thoughts? Possible or not possible ?
I have tried to google around for guidance but so far I haven't seen any.

**Comment by sclevine** [comment]
Can you provide more detail about what you're trying to accomplish?

**Comment by ssuluh** [comment]
I'm trying to debug an instance of .net core app that is pushed to pcf dev env. I'm still fuzzy on how pcf dev container works, but assuming the right symbols are also pushed along with the package I'm thinking there's a way to enable the remote debugging capability over ssh (https://blogs.msdn.microsoft.com/devops/2017/01/26/debugging-net-core-on-unix-over-ssh/). I'm thinking the flow should be close to JDWP in Java (https://discuss.pivotal.io/hc/en-us/articles/221317307-How-to-Remotely-Debug-Java-Applications-on-Cloud-Foundry)

**Comment by sclevine** [comment]
This seems like a general question about Cloud Foundry, and not about PCF Dev in particular. [See here](https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html) for information about accessing apps over SSH.

**Comment by ssuluh** [comment]
Thanks @sclevine. I'll check it out.
