### ISSUE TITLE
Push docker image produces docker Client.Timeout exceeded error

### ISSUE THREAD

**Issue by pbaletkeman** [vmware-archive/pcfdev#306]
When I try push a docker image using `cf push hello-Docker -o tutum/hello-world` I get the following error message:
> Failed to talk to docker registry: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
>    Failed to talk to docker registry: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
>    Staging process failed: Exit trace for group:
>    builder exited with error: failed to fetch metadata from [tutum/hello-world] with tag [latest] and insecure registries [] due to Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
>    Exit status 2
>    Staging Failed: Exited with status 2

This is a really basic docker image which you can read about here https://hub.docker.com/r/tutum/hello-world/. I does not seem to matter which docker image I try as they all produce the same results.

Setup Check List:
- Use Google's DNS servers
- Windows 10 Pro (with all of the updates)
- Windows Firewall disabled and no other firewall installed
- Small home, LAN setup (using cable Internet) with only three systems in total
- No proxy

I tried stopping and starting PCF Dev a number of times and when that did not change anything I've restarted my computer a number of times.

**Comment by sclevine** [comment]
Can you confirm that your VM has internet access? If you run `cf dev ssh` and then `ping 8.8.8.8`, what output do you get?

**Comment by pbaletkeman** [comment]
Here are the results:

C:\Users\pete>cf dev ssh
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.2.0-42-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '16.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed Feb 21 13:32:05 2018 from 10.0.2.2
vcap@agent-id-pcfdev-0:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=56 time=17.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=56 time=17.3 ms
^C

vcap@agent-id-pcfdev-0:~$ ping 8.8.4.4
PING 8.8.4.4 (8.8.4.4) 56(84) bytes of data.
64 bytes from 8.8.4.4: icmp_seq=1 ttl=56 time=17.3 ms
64 bytes from 8.8.4.4: icmp_seq=2 ttl=56 time=15.8 ms
^C

**Comment by pbaletkeman** [comment]
If it helps at all, I get the previously stated error message in about two to  three seconds after executing the cf push command.

**Comment by pbaletkeman** [comment]
I think that I've narrowed it down to my Windows 10 Pro system, by using a trying the same push command on a Ubuntu 17.10 server system. When I run the same command on the Ubuntu system everything works as expected. I'll see what I can do to solve this and post back when/if I am able to.

**Comment by pbaletkeman** [comment]
Solved, here are the steps that I preformed:

1. Rebuild TCP/IP stack, only need one or two commands which you should be able to find easily enough.
2. Removed **all** network devices using the Windows Device Manager.
3. Rebooted
4. Reinstalled Virtual Box
5. Destroyed the cf dev image

I'm not too sure if you need to do all of those steps or what the exact order should be for some of them. However it's working for me and I'm happy about that.
