### ISSUE TITLE
Helpful troubleshooting note

### ISSUE THREAD

**Issue by pbaletkeman** [vmware-archive/pcfdev#308]
Just a quick note, which you may want to add to your documentation.
On Windows 10 systems if you have any third party VPN software installed on your system you may run into issues even if that VPN software is not being used at the moment.  

Of note, third party OpenVPN software interferes with contacting the public Docker registry hub.docker.com.

Current solution is to uninstall the third part VPN software and reboot your Windows 10 system.

**Comment by sclevine** [comment]
Thanks for the tip! We will test compatibility with OpenVPN on Windows 10 when we have an opportunity.
