### ISSUE TITLE
C2C networking in pcfdev

### ISSUE THREAD

**Issue by sschulze** [vmware-archive/pcfdev#309]
Hi,
I try to use container-to-container networking in pcfdev. According to #240 this is supported.
If I try to execute ``cf add-network-policy ...`` I get this error:
> This command required Network Policy API V1. Your targeted endpoint does not expose it.

The output of ``cf target`` is:
> api endpoint:    https://api.local.pcfdev.io
> api version:       2.82.0
> user:                 admin
> org:                  my-org
> space:               test

The output of ``curl -k https://api.local.pcfdev.io/networking`` is:
> Network policy server, up for 36m30.6824s

``curl -k https://api.local.pcfdev.io/networking/v1`` returns:
> 404 page not found
(not sure if the URL should be valid...)

I already ensured to use cf-cli v6.34.1, pcfdev v0.29.0 and destroyed and recreated my VM.

**Comment by aemengo** [comment]
This issue should be resolved with the latest version of [CF Dev](https://github.com/cloudfoundry-incubator/cfdev).
