### ISSUE TITLE
is PCF Metrics included with PCFDEV?

### ISSUE THREAD

**Issue by antonioaguilar** [vmware-archive/pcfdev#311]
Just wondering if [PCF Metrics](https://docs.pivotal.io/pcf-metrics/1-2/using.html) it's included in PCFDEV or do we have to install it? If we have to install it - does PCFDEV support it?

**Comment by sclevine** [comment]
PCF Metrics is a separate tile that is not included in PAS by default. It is not included in current versions of PCF Dev.

We may choose to include PCF Metrics after we finish re-implementing PCF Dev as an extension on top of [CF Dev](https://github.com/pivotal-cf/cfdev) with support for BOSH and native hypervisors.
