### ISSUE TITLE
[pcf dev] Error: failed to open file: open C:\Users\xxx\.pcfdev\token: Access is denied.. URGENT

### ISSUE THREAD

**Issue by vlaskovic** [vmware-archive/pcfdev#312]
Team,

I have installed brand new cf version 6.35.0+5c7de3e32.2018-03-08 (over an uninstalled previous version) of PCF DEV.
On cf dev start i am getting the attached cf dev start.jpg and in subject.

May you please assist?
It is urgent for me as I need the environment for the preparation of LFS232 exam.
![pcf dev start](https://user-images.githubusercontent.com/12842859/37255908-9b39c058-2553-11e8-9d2f-832ebfdb9fc6.JPG)

ps i am executing as an administrator on windows 10.

Thank you.
Slobodanka

**Comment by vlaskovic** [comment]
Additionally, if a change the location of the cf cli installation ex: C:/Cloud Foundry, the same error now occurs on pcf dev start - access denied as the location under Program Files does not exist any more and the .exe would not look or ask for another location nevertheless the cli install gives you an option to modify the default installation folder?

Installation version(s):
cf-cli-installer_6.35.0_winx64
pcfdev-v0.29.0_PCF1.11.0-windows


Thank you,
Slobodanka

**Comment by sclevine** [comment]
#313 indicates that you figured this out. Is that the case?

**Comment by vlaskovic** [comment]
Yes, true.

It was rather OS problem after an update - I will close the issue.


Thanks,
Slobodanka
