### ISSUE TITLE
[pcf dev][blocked state][57 of 58] running services 

### ISSUE THREAD

**Issue by vlaskovic** [vmware-archive/pcfdev#313]
![stuck](https://user-images.githubusercontent.com/12842859/37282516-faf90516-25f4-11e8-8e1f-6d9991432220.PNG)
Team,

cf dev start is blocked at the 57th service of total 58.
I am attaching the vm logs files.

[VBoxHardening.log](https://github.com/pivotal-cf/pcfdev/files/1802601/VBoxHardening.log)
[VBox.log](https://github.com/pivotal-cf/pcfdev/files/1802602/VBox.log)

May you please help?

I have had the environment up and running normally previously and now I can't have it again not even after brand new install using the latest cf cli and pcf dev release.

Thank you,
Slobodanka

**Comment by vlaskovic** [comment]
I can see anything relevant in the logs.

Pls note that this is urgent for me since I have the LFS232 exam to take and I don't have an enviroment to practice.


If I try and login in parallel, this is the error that I get:
![login](https://user-images.githubusercontent.com/12842859/37283128-29605970-25f7-11e8-8579-b5bcdfd3f87d.PNG)


Thank you,
Slobodanka

**Comment by sclevine** [comment]
What version of PCF Dev do you have installed?
Can you provide the entire output of `cf dev start`?

The errors you're encountering tend to appear on under-provisioned workstations. Can you use PWS to practice for your exam?

**Comment by vlaskovic** [comment]
I have currently pcfdev-v0.28.0+PCF1.11.0-windows and tried with the latest: pcfdev-v0.29.0+PCF1.11.0-windows, as well some previous - 24 I believe.

My trial for PWS expired thus I have decided to go with pcf dev instead as I have had used the environment before (using TIBCO build-pack) and all went fine..


Practically, the output is what is represented in the screen-shot - it just stops at 57 of 58 services running and nothing will ever happen.

I believe that timeout will happen at some point of time - for a full copy pls let me try to reproduce and I will get back to you.
Thanks,
Slobodanka

**Comment by sclevine** [comment]
A certificate expired that prevents all versions before v0.29.0 from starting. Please install v0.29.0 and Virtualbox 5.1.x and provide the full output from `cf dev start`.

**Comment by vlaskovic** [comment]
Thank you, worked for me.

Pls note down this as may other users experience the same troubles as I did.


Thank you,
Slobodanka
