### ISSUE TITLE
https://apps.local.pcfdev.io [invalid certificate] [https]

### ISSUE THREAD

**Issue by vlaskovic** [vmware-archive/pcfdev#314]
Team,

I would like to thank you for your support until now.
I have another problem - stopping me from using 'curl' for CF, more precisely pcf dev locally.
URL in subject is not valid thus **curl** of the same results with the following error:

C:\WINDOWS\system32>curl **https://api.local.pcfdev.io**
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

I see in my browser the state yet I am not able to verify the certificate in order to overcome the issue.
May you pls help?
![local pcfdev io - invalid cert](https://user-images.githubusercontent.com/12842859/37333125-cf6e3042-26a8-11e8-9ded-4088a0cc6690.JPG)

This blocks any httpS action, for instance Logs button START pop-up couldn't be enabled. 
Thank you,
Slobodanka

**Comment by sclevine** [comment]
Running `cf dev trust` will install the PCF Dev CA certificate on your machine. This will make those errors go away. Alternatively, you can use curl with `curl -k`.
