### ISSUE TITLE
PCF DEV [pcfdev-v0.29.0_PCF1.11.0-windows][docker][error]

### ISSUE THREAD

**Issue by vlaskovic** [vmware-archive/pcfdev#316]
Team,

I am unable to push https://hub.docker.com/r/engineerbetter/worker-image/ in pcf dev environment locally.
Pls find attached application logs extracted from console.
[worker-app-logs.txt](https://github.com/pivotal-cf/pcfdev/files/1819463/worker-app-logs.txt)

C:\Users\Slobodanka\Documents\tmns\training\LinuxFoundation\CloudFoundry\LFS232\class-artifacts>cf enable-feature-flag diego_docker
Setting status of diego_docker as admin...

OK

Feature diego_docker Enabled.

C:\Users\Slobodanka\Documents\tmns\training\LinuxFoundation\CloudFoundry\LFS232\class-artifacts>cf push worker-image --docker-image engineerbetter/worker-image:latest -i 1 -m 512M --no-manifest
Pushing app worker-image to org pcfdev-org / space pcfdev-space as admin...
Getting app info...
Creating app with these attributes...
+ name:           worker-image
+ docker image:   engineerbetter/worker-image:latest
+ instances:      1
+ memory:         512M
  routes:
+   worker-image.local.pcfdev.io

Creating app worker-image...
Mapping routes...

Staging app and tracing logs...
   Successfully created container
   Staging...
   Staging process started ...
   Staging process finished
   Exit status 0
   Staging Complete
   Destroying container
   Successfully destroyed container

Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs worker-image --recent' for more information
FAILED

May you pleae have a look? Is docker working for PCF DEV at all?

Thank you.
Slobodanka

**Comment by pbaletkeman** [comment]
@vlaskovic if you are using Windows then do you have any VPN or other networking software installed on your system? I was experiencing a problem and pushing a Docker image and the only solution I found was uninstalling the OpenVPN software, even though the I was not using the VPN software when I was trying to push the Docker image. VPN can interfere with or alter the TCP/IP stack on Windows 10 systems.

**Comment by vlaskovic** [comment]
@letkemanpete78 thank you for your help.
I have had OpenVPN installed previously, strange though since I have removed this program sometime ago.
Maybe the system is not cleaned during uninstallation.

I have VPN Access Manager additionally and is app that I can't remove.

Do we believe that it is rather Docker related? 

I haven't pushing an app directly on docker rather to my pcf dev env:
from the logs: cf enable-feature-flag diego_docker


Thank you,
Slobodanka

**Comment by sclevine** [comment]
This looks like you're trying to push a "worker" image with no listening port, and it fails because CF has an HTTP port based healthcheck by default (although I'm not totally sure if that's true for Docker).

What does `cf logs` say?

**Comment by vlaskovic** [comment]
logs from above:
C:\Users\Slobodanka\Documents\tmns\training\LinuxFoundation\CloudFoundry\LFS232\class-artifacts>cf push worker-image --docker-image engineerbetter/worker-image:latest -i 1 -m 512M --no-manifest
Pushing app worker-image to org pcfdev-org / space pcfdev-space as admin...
Getting app info...
Creating app with these attributes...

name: worker-image
docker image: engineerbetter/worker-image:latest
instances: 1
memory: 512M
routes:
worker-image.local.pcfdev.io
Creating app worker-image...
Mapping routes...

Staging app and tracing logs...
Successfully created container
Staging...
Staging process started ...
Staging process finished
Exit status 0
Staging Complete
Destroying container
Successfully destroyed container

Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs worker-image --recent' for more information
FAILED

now, if i try again i am getting another (timeout) error during staging phase:
C:\WINDOWS\system32>cf push worker-image --docker-image engineerbetter/worker-image
Pushing app worker-image to org pcfdev-org / space pcfdev-space as admin...
Getting app info...
Updating app with these attributes...
  name:                worker-image
  docker image:        engineerbetter/worker-image
  disk quota:          512M
  health check type:   port
  instances:           1
  memory:              512M
  stack:               cflinuxfs2
  routes:
    worker-image.local.pcfdev.io

Updating app worker-image...
Mapping routes...

Staging app and tracing logs...
   Creating container
   Successfully created container
   Staging...
   Staging process started ...
   Failed to talk to docker registry: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
   Failed to talk to docker registry: Get http://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
   Staging process failed: Exit trace for group:
   builder exited with error: failed to fetch metadata from [engineerbetter/worker-image] with tag [latest] and insecure registries [] due to Get http://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
   Exit status 2
   Staging Failed: Exited with status 2
   Destroying container
   Successfully destroyed container
Error staging application: Staging error: staging failed
FAILED

Thank you.

**Comment by pbaletkeman** [comment]
This is rather drastic, but initially when I had issue pushing with an OpenVPN client installed (not knowing that is was the issue) I removed all network interfaces using the Windows device manager.
This stops the OpenVPN software, netowrk connections and other VPN software. Afterwards I did a "scan for change in the devcie manager" and added in my real network cards. Then I was able to push the Docker image. I think I rebooted once or twice as well.
It was only later that I learned the VPN software can cause problems and all that I needed to remove was the VPN software.
Be sure to know all of the correct network settings before you remove the cards so that you can apply them once more when you need to.

**Comment by vlaskovic** [comment]
@letkemanpete78 
Thank you for sharing your experience unfortunately is enormous effort to be applied and then withdrawn to a working personal machine.
What I would like to understand is, to whom we've transcribed the issue: docker, windows, pcf dev?
(Open) VPN is causing the problems for which pillar of the PUSH process?


Thank you.

**Comment by pbaletkeman** [comment]
I do not know who you should direct this concern to, I suspect that the maintainers of anyone of people you mentioned could be at fault. However, I also suspect that Microsoft is not going to change anything as such the other three parties would have to work together and I'm not too sure who is going to be the most accommodating.
For the moment there is a work around, which may not be the best but it's a place to start.

**Comment by sclevine** [comment]
I still suspect that when you don't encounter the network flakiness and the image fails to launch, it's failing because the app is not configured with the correct healthcheck options. You didn't provide the output of `cf logs` for that run.

The network flakiness is beyond our control in this version of PCF Dev, as we use networks that are provided by Virtualbox and work in many different environments, including environments with OpenVPN.

It's worth mentioning that the next release of PCF Dev will be as an extension on top of [CF Dev](https://github.com/pivotal-cf/cfdev), which uses native hypervisors and provides a working BOSH director. We have no plans to release future versions of this Virtualbox-based implementation. (Although we may release an OVA version of CF Dev with no management plugin.)

**Comment by vlaskovic** [comment]
Thank you @sclevine 
Logs are attached: 
[logs_worker-docker.txt](https://github.com/pivotal-cf/pcfdev/files/1832405/logs_worker-docker.txt)

I understand your point and will try and switch to cf dev instead, as suggested. 


Thank you,
Slobodanka
