### ISSUE TITLE
Error: failed to provision VM: Process exited with: 1. Reason was:  ().

### ISSUE THREAD

**Issue by godfreym1978** [vmware-archive/pcfdev#317]
Using Ubuntu 16.04, Oracle Virtual box 5.2 pcfdev ova 548.

I just can't get this thing to start at all!!!

`
godfrey@ideapad:~$ cf dev start
Using existing image.
Allocating 3925 MB out of 7850 MB total system memory (6429 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
9 out of 58 running
15 out of 58 running
28 out of 58 running
31 out of 58 running
35 out of 58 running
41 out of 58 running
41 out of 58 running
41 out of 58 running
42 out of 58 running
43 out of 58 running
48 out of 58 running
48 out of 58 running
48 out of 58 running
49 out of 58 running
Timed out after 3600 seconds.
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().
`

**Comment by sclevine** [comment]
Can you describe the hardware that you're attempting to run PCF Dev on?
Are you attempting to start PCF Dev from inside of another VM?

**Comment by godfreym1978** [comment]
Downgraded Oracle VirtualBox from 5.2 to 5.1 and it started! Seems like VBox 5.2, pcf 0.29 and ova 548 don't work together on my Ubuntu 16.04, 8GM RAM, i5 core on Ideapad u510. I'm not running it from a VM.

Having said that, there is still one problem, can't connect to https://api.local.pcfdev.io, it gives me connection refused -

`godfrey@ideapad:~/Downloads$ cf dev start 
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email> ********@gmail.com

Password> 
Downloading VM...
Progress: |====================>| 100% 
VM downloaded.
Allocating 3925 MB out of 7850 MB total system memory (6254 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
37 out of 58 running
58 out of 58 running
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
is now running.
To begin using PCF Dev, please run:
   cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://apps.local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass
godfrey@ideapad:~/Downloads$ cf login -a https://api.local.pcfdev.io --skip-ssl-validation
API endpoint: https://api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.168.11.1:443: connect: connection refused
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
godfrey@ideapad:~/Downloads$ ping 192.168.11.1
PING 192.168.11.1 (192.168.11.1) 56(84) bytes of data.
64 bytes from 192.168.11.1: icmp_seq=1 ttl=64 time=0.150 ms
64 bytes from 192.168.11.1: icmp_seq=2 ttl=64 time=0.057 ms
64 bytes from 192.168.11.1: icmp_seq=3 ttl=64 time=0.081 ms
64 bytes from 192.168.11.1: icmp_seq=4 ttl=64 time=0.214 ms
`

**Comment by godfreym1978** [comment]
Now I get another error in here - 
`Using existing image.
Allocating 3925 MB out of 7850 MB total system memory (5909 MB free).
Importing VM...


Starting VM...
FAILED
Error: failed to start VM: ssh connection timed out: dial tcp 192.168.11.11:22: getsockopt: no route to host.
`

**Comment by godfreym1978** [comment]
After I downgraded to the Oracle VirtualBox 5.1 I'm able to connect and access. You may close this issue but may want to check why it did not work with VirtualBox 5.2.8.

**Comment by sclevine** [comment]
Sorry for the delayed reply. We are aware of the issues with Virtualbox 5.2.x.

The next version of PCF Dev will not require Virtualbox. An alpha release (without the PCF-specific components) is available here: https://github.com/pivotal-cf/cfdev
