### ISSUE TITLE
cf dev start failing with error 2147749902

### ISSUE THREAD

**Issue by carljonescf** [vmware-archive/pcfdev#320]
I'm working through tutorial at https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry-dev/deploy-the-sample-app.

> cf dev start 

is reporting

> Using existing image.

> [31;1mFAILED[0m

> Error: exit status 2147749902.

I'm running on Windows 10.

Virtual Box version 5.2.8.

The number seems to suggest a WMI, but the WMI repository is verified and reporting no issues.

**Comment by sclevine** [comment]
Hi @carljonescf,

Can you try uninstalling Virtualbox 5.2.8 and installing the latest version of Virtualbox 5.1.x?

**Comment by carljonescf** [comment]
Hi

Thanks for the quick response.

Installed 5.1.34 and still getting the same issue.

Thanks
Carl

**Comment by sclevine** [comment]
Can you provide all of the output from `cf dev start`?
Are you able to start other VMs in Virtualbox?
Do you use an HTTP proxy to connect to the internet?

**Comment by carljonescf** [comment]
Hi

Full output is

C:\Users\Carl>cf dev start
Using existing image.
[31;1mFAILED[0m
Error: exit status 2147749902.

Yes – I can start an Ubuntu VM in VirtualBox.

No proxy.

Thanks
Carl
