### ISSUE TITLE
Cf dev status command throws error

### ISSUE THREAD

**Issue by saranya2293** [vmware-archive/pcfdev#322]
I installed PCF Dev in Ubuntu 16.04. when i enter the command **cf dev help**, it works fine.
But, when i give **cf dev status**, it shows following error
FAILED
Error: failed to execute 'VBoxManage list vms': exec: "VBoxManage": executable file not found in $PATH: .

**Comment by sclevine** [comment]
You need Virtualbox installed to use PCF Dev.
