### ISSUE TITLE
Failed to deploy pcfdev and existing pcfdev failed to start

### ISSUE THREAD

**Issue by patrickdung** [vmware-archive/pcfdev#323]
I had installed pcfdev about one week ago, it was working fine.
Suddenly 'cf dev start' failed to work for existing pcfdev and new installation.

Findings:
/var/vcap/data/sys/log/consul_agent/consul_agent.stdout.log
    2018/04/23 10:50:09 [ERR] http: Request GET /v1/operator/keyring, error: rpc error: failed to get conn: x509: certificate has expired or is not yet valid from=127.0.0.1:37097

root@agent-id-pcfdev-0:/var/vcap# openssl x509 -in ./data/jobs/consul_agent/fake-job-template-version-12db66540e952ad87de9bc62508a042c1765deba/config/certs/server.crt -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            16:13:c9:22:9e:22:08:9e:87:ad:1b:bd:f9:52:8e:24
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=consulCA
        Validity
            Not Before: Apr 22 16:38:32 2016 GMT
            Not After : Apr 22 16:38:32 2018 GMT

Looks like related to cert expiry issue.

**Comment by ssisil** [comment]
Closing this out and consolidating to this thread - https://github.com/pivotal-cf/pcfdev/issues/324
