### ISSUE TITLE
cf dev start fails with no apparent reason

### ISSUE THREAD

**Issue by retgits** [vmware-archive/pcfdev#324]
After downloading and installing the latest versions of `cf` and `pcfdev`, running the command `cf dev start` fails for no apparent reason. It looks similar to the other issues mentioned, but in this case it simply doesn't do anything.

```
cf dev start
Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email> xxx

Password>
Downloading VM...
Progress: |====================>| 100%
VM downloaded.
Allocating 4096 MB out of 16384 MB total system memory (7168 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
Timed out after 3600 seconds.
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().
```

cf version
```
cf version 6.36.1+e3799ad7e.2018-04-04
```

pcf dev version
```
PCF Dev version 0.29.0 (CLI: 49405ec, OVA: 0.548.0)
```

VirtualBox version
```
5.1.36r122089
```

**Comment by ssisil** [comment]
hi @retgits - we are aware of the issue are are actively working on resolving it. I will update this thread when I have more details.

**Comment by ssisil** [comment]
This has been resolved in [Release v0.30.0](https://github.com/pivotal-cf/pcfdev/releases/tag/v0.30.0)

**Comment by cassidd** [comment]
Can I get the PCF1.11.0-osx executable or do I have to build it myself?

**Comment by cassidd** [comment]
Forget that - I see it.  Thanks.

**Comment by masalinas** [comment]
pcfdev continue stuck on 'waiting for services to start' executing `cf dev start `for that infraestructure:

- Ubuntu 16.04 64 bits (8Gb), sufficient hard disk.
- Virtual Box 5.2.2
- pcfdev 0.30.0 + PCF1.11.0-linux from pcfdev-v0.549 ova file

What is the pcfdev without error??

**Comment by sclevine** [comment]
1. Make sure you aren't running in another nested VM
2. Use the latest Virtualbox 5.1.x release, instead of 5.2.2

**Comment by masalinas** [comment]
1. I'm running under native Linux Ubuntu 16.04 version 64Bits with 8GB of RAM
2. Is impossible for me, downgrade to Virtualbox 5.1.X I have many VMs and I don't want to cry if finally these VMs not start after downgrade. So:
1) Exist a bug of the 0.30 PCF Dev with this VirtualBox version?.
2) Exist other solution and use the VirtualBox 5.2.x?.
3) Where are the logs created from cf to watch the problem?

Regards

**Comment by sclevine** [comment]
We have no plans to support Virtualbox 5.2.x. This version of PCF Dev will soon be deprecated in favor of a PAS extension that will use CF Dev: https://github.com/cloudfoundry-incubator/cfdev

You can access the VM with `cf dev ssh`, and look at logs in `/var/vcap/logs` and /var/pcfdev`.

**Comment by masalinas** [comment]
Ok Bad notice for me and my Linux. The problem is that the new cfdev only support macOS at this time, again bad notice for my Linux. I will install PCF Dev on my mac laptop with VirtualBox 5.0.3

Regards

**Comment by mustafakamil12** [comment]
Hello masalinas, did VirtualBox 5.0.3 solve the issue ??

**Comment by masalinas** [comment]
Hello @mustafakamil12 Yes under mac, resolve the problem. 
Regards
