### ISSUE TITLE
Cannot start dev: Error -5640 in supR3HardenedWinReSpawn

### ISSUE THREAD

**Issue by paul-stanley** [vmware-archive/pcfdev#327]
**Environment:**
VirtualBox 5.2.10
Windows 10 host
pcfdev-v0.30.0+PCF1.11.0

Issuing the command: **cf dev start** fails with:  

Error: failed to start VM: failed to execute 'C:\Program Files\Oracle\VirtualBox\VBoxManage startvm pcfdev-v0.549.0 --type headless': exit status 1: Waiting for VM "pcfdev-v0.549.0" to power on...
VBoxManage.exe: error: The virtual machine 'pcfdev-v0.549.0' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\paul.stanley\.pcfdev\vms\pcfdev-v0.549.0\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

The VBoxHardening.log contains this:

92c.730: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox'
92c.730: Calling main()
92c.730: SUPR3HardenedMain: pszProgName=VBoxHeadless fFlags=0x0
92c.730: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox'
92c.730: '\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe' has no imports
92c.730: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe)
92c.730: SUPR3HardenedMain: Respawn #2
92c.730: Error (rc=-5640):
92c.730: More than one thread in process
92c.730: Error -5640 in supR3HardenedWinReSpawn! (enmWhat=1)
92c.730: More than one thread in process
c5c.fd0: supR3HardNtChildWaitFor[1]: Quitting: ExitCode=0x1 (rcNtWait=0x0, rcNt1=0x0, rcNt2=0x103, rcNt3=0x103, 21 ms, the end);

This looks similar to #188, but there is no resolution given for that issue.

**Comment by sclevine** [comment]
Seems like your installation of Virtualbox is broken. Can you uninstall Virtualbox and try it with the latest Virtualbox 5.1.x? (**not 5.2**).

Also see: https://stackoverflow.com/questions/34778147/cannot-boot-windows-guest-in-virtualbox-without-kernel-module-error

**Comment by sshankjha** [comment]
I was able to solve this by downgrading to 4.3.0. 

Found the suggestion from following link:

https://stackoverflow.com/questions/30837998/oracle-virtualbox-terminated-unexpectedly-with-exit-code-1073741819-0xc000000

"VirtualBox 4.14 has new "hardened" security on Windows, and it doesn't play nice with anything that hooks dll's into Windows, mainly 3rd-party antivirus packages, but also any other 3rd-party program that "intercepts" Windows dll calls."
