### ISSUE TITLE
PCFDev Trusted https certificate

### ISSUE THREAD

**Issue by amitoj** [vmware-archive/pcfdev#328]
Can I install SSL/TLS certificate issued by a trusted authority to my pcfdev (v0.30.0 for PCF 1.11.0) environment running on Mac OSX (High Sierra).

Is there a published process that I can follow?

I tried this blog but my pcfdev installation stopped working because of certificate error  - http://dmalone.io/2016/05/17/modifying-the-ssl-certificates-used-by-pcfdev/ 

I want to understand this process and would appreciate any help in that direction.

Regards,
Amitoj

**Comment by sclevine** [comment]
This should be possible via BOSH in the latest release for macOS on PivNet.

However, 0.30.0 does offer a `cf dev trust` command and `-k` option to start that adds the PCF Dev certificate CA to the host certificate store (after destroying the CA private key, for security).

(If you're trying to accomplish this to host PCF Dev in a network with untrusted hosts (such as the internet), I would strongly recommend against that. PCF Dev has many default credentials in unexpected places.)

**Comment by amitoj** [comment]
Thanks, I’ll try with the new release.
