### ISSUE TITLE
pcf-dev vm ssh userid and password

### ISSUE THREAD

**Issue by zsaleem123** [vmware-archive/pcfdev#329]
What is the userid and password for pcf-dev vm when ssh into the vm?

Thank you.

**Comment by amitoj** [comment]
Hi @zsaleem123,
I'm not sure about the default password for `vcap` user but you can set it to whatever you want by opening `root` shell using `sudo su -` command.
I've never had a need to change the password so not sure if changing `vcap` password breaks pcfdev operations.

**Comment by sclevine** [comment]
Use `cf dev ssh` to get SSH access to the VM as the vcap user. If you want to use the OpenSSH client directly, the key is somewhere in `~/.pcfdev`.
