### ISSUE TITLE
pcfdev custom domain requirements 

### ISSUE THREAD

**Issue by amitoj** [vmware-archive/pcfdev#330]
What are the requirements for setting custom domain name in pcfdev?

I've created a new wildcard domain with GoDaddy where `*.amitoj.co.uk` points to 192.168.11.11

But when i start pcfdev with `cf dev start -d amitoj.co.uk` the error message I get is
> FAILED
> Error: amitoj.co.uk is not one of the allowed PCF Dev domains.

I can pinpoint the the logic in https://github.com/pivotal-cf/pcfdev-cli/blob/master/address/address.go
It seems there is a restricted list of domains allowed.

**Comment by sclevine** [comment]
Can you try manually specifying the IP as well (with `-i`)?

**Comment by amitoj** [comment]
Closing this because I've migrated to cfdev. Will try this on cfdev when custom domain option becomes available.
