### ISSUE TITLE
PCF LOGIN ISSUE

### ISSUE THREAD

**Issue by MdKamranUddin** [vmware-archive/pcfdev#331]
When I am trying to login to cf cli, I am getting the below error:
Error performing request: Get https://api.run.pivotal.io/v2/info: read tcp 10.159.116.73:56349->52.205.108.189:443: wsarecv: An existing connection was forcibly closed by the remote host.

Can somebody assist immediately

**Comment by sclevine** [comment]
The address `api.run.pivotal.io` is PWS, not PCF Dev.
Are you using the latest alpha release, or v0.30.0?

**Comment by MdKamranUddin** [comment]
I am working on PWS only not PCF dev, and the cf cli i have installed is latest version also but still I am getting this error. Can you please help

**Comment by sclevine** [comment]
This issue tracker is for issues related to PCF Dev, not PWS or the cf CLI. 

PWS support: https://support.pivotal.io/
Issue tracker for the cf CLI: https://github.com/cloudfoundry/cli/issues

Judging by the error though, it looks like you require an HTTP proxy to make external connections and haven't set the `http_proxy`, `https_proxy`, and/or `no_proxy` environment variables.

**Comment by MdKamranUddin** [comment]
One question Stephen, I am not using any proxy server in my proxy settings so if I set the above variables, will it work?
