### ISSUE TITLE
I Can't download pcfdev from Pivotal network.

### ISSUE THREAD

**Issue by CoaCao** [vmware-archive/pcfdev#337]
I tried download pcfdev from Pivotal network and receive message : "Unfortunately, we are unable to provide you with access to download software at this time. Please contact export@pivotal.io for assistance."

I also tried send email to export@pivotal.io but not have rely. How I contact to download ?

**Comment by sclevine** [comment]
This is a PivNet compliance issue that can only be resolved by emailing export@pivotal.io.
