### ISSUE TITLE
pcf dev 2.1 start fails at deploying mysql stage - while starting container process

### ISSUE THREAD

**Issue by silomare** [vmware-archive/pcfdev#338]
I haven't been able to start pcfdev 2.1.0 in my macbook pro so far, I'm stuck with this issue every time I try to start pcfdev 

$ PIVNET_TOKEN=.... -r cf dev start -f /vm/pcfdev-pas.v.2.1.0-build.0.8.0.dev -m 8096
Installing networking components (requires root privileges)
Password:
Starting VPNKit ...
Starting the VM...
Waiting for Garden...
Deploying the BOSH Director...
Deploying CF...
  Uploading Releases
Deploying Mysql...
  Uploading ReleasesFAILED
cf dev start: Failed to deploy mysql: hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:296: starting container process caused \"exec: \\\"/usr/bin/deploy-mysql\\\": stat /usr/bin/deploy-mysql: no such file or directory\"\n","Handle":"","ProcessID":""}

**Comment by ssisil** [comment]
hi @silomare - there is a bug in the latest release of the CF Dev plugin. Please use v 0.0.5 instead.  We will be deploying a new version to fix this issue in the coming weeks.

Link to [v0.0.5](http://d3p1cc0zb2wjno.cloudfront.net/cfdev/cfdev-v0.0.5-darwin)

**Comment by silomare** [comment]
thank you very much, I was able to start it successfully by applying these steps

cf uninstall-plugin cfdev
cf install-plugin ./cfdev-v0.0.5-darwin
PIVNET_TOKEN=.... -r cf dev start -f /vm/pcfdev-pas.v.2.1.0-build.0.8.0.dev -m 8096
