### ISSUE TITLE
Install PCF Dev in Mac - Mysql Issue Deployment

### ISSUE THREAD

**Issue by lhmoraes** [vmware-archive/pcfdev#339]
Hi team, I'm trying do install PCF Dev in my laptop, but I'm getting the error below. I couldn't find any help on Google from that, please someone:

➜ cf dev start -f pcfdev-pas.v.2.1.0-build.0.8.0.dev -m 8096
Starting VPNKit ...============>| 100.0%
Starting the VM...
Waiting for Garden...
Deploying the BOSH Director...
Deploying CF...
  Uploading ReleasesDeploying Mysql...
  Uploading ReleasesFAILED
### _**cf dev start: Failed to deploy mysql: hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:296: starting container process caused \"exec: \\\"/usr/bin/deploy-mysql\\\": stat /usr/bin/deploy-mysql: no such file or directory\"\n","Handle":"","ProcessID":""}**_

➜ Mac version:
macOS Hight Sierra
Version: 10.13.3

➜ Sudo Version:
Sudo version 1.8.17p1
Sudoers policy plugin version 1.8.17p1
Sudoers file grammar version 45
Sudoers I/O plugin version 1.8.17p1

**Comment by sclevine** [comment]
There's an issue with the latest CF Dev plugin that affects compatible with the PAS iso. Apologies for the trouble. Everything should work if you downgrade your CF Dev plugin to v0.0.5.

**Comment by lhmoraes** [comment]
No problem, thanks @sclevine I will try it
