### ISSUE TITLE
Error setting API endpoint

### ISSUE THREAD

**Issue by echurchm** [vmware-archive/pcfdev#34]
I got MicroPcf up and running.  I can ssh into the instance and run the cf command fine but from my host machine it fails.  Here is the error I am getting:

xxxx@kubuntu-laptop:/tmp$ export MICROPCF_IP=10.0.2.15
xxxx@kubuntu-laptop:/tmp$ cf api api.local.micropcf.io --skip-ssl-validation
Setting api endpoint to api.local.micropcf.io...
FAILED
Error performing request: Get http://api.local.micropcf.io/v2/info: dial tcp 192.168.11.11:80: i/o timeout

I am running VirtualBox 5.0.14 on Kubuntu 15.10.  The IP address in virtual box defaulted to 10.0.2.15 so I set the variable as described.  

 could not figure out where it was getting 192.168.11.11. 

 I also tried: 
     cf api 10.0.2.15 --skip-ssl-validation

but get no route to host error.

Any help appreciated.
Thanks Ed.

**Comment by sclevine** [comment]
Hi @echurchm,

Short version: Unless you cannot use 192.168.11.11 for the MicroPCF guest VM, do not set `MICROPCF_IP`.

Long version:

The local.micropcf.io domain will always resolve to 192.168.11.11 outside of the MicroPCF VM. The `MICROPCF_IP` and `MICROPCF_DOMAIN` environment variables exist for situations where 192.168.11.11 is unavailable. For instance, running `MICROPCF_IP=192.168.22.11 vagrant up` would configure the MicroPCF guest VM to use the address 192.168.22.11 with Cloud Controller available at api.192.168.22.11.xip.io. Running `MICROPCF_DOMAIN=local2.micropcf.io MICROPCF_IP=192.168.22.11 vagrant up` would configure the MicroPCF guest VM to use the address 192.168.22.11 with Cloud Controller available at api.local2.micropcf.io (another domain we provide for convenience).

MicroPCF uses the standard Virtualbox NAT address (10.0.2.15) separately for external internet access. Setting `MICROPCF_IP` to this will result in an unusable VM.

**Comment by echurchm** [comment]
Thanks.  I started over and it worked as documented.  For some reason  the first time through it did not seem to work so I went down the different IP path.  I must have done something wrong.
