### ISSUE TITLE
Creating of SCS

### ISSUE THREAD

**Issue by fullydead** [vmware-archive/pcfdev#342]
Using : v0.30, Virtualbox 5.1
Issue : cf dev start (Able to create)
Windows 10

Failure for below:
cf dev start -m 102400 -s scs
cf dev start -m 102400 -s all

provision.log
cf start spring-cloud-broker
Starting app spring-cloud-broker in org system / space p-spring-cloud-services as admin...
Downloading dotnet-core_buildpack...
Downloading java_buildpack...
Downloading ruby_buildpack...
Downloading nodejs_buildpack...
Downloading go_buildpack...
Downloaded nodejs_buildpack (78.6M)
Downloading python_buildpack...
Downloading java_buildpack failed
Downloading php_buildpack...
Downloading ruby_buildpack failed
Downloading staticfile_buildpack...
Destroying container
Successfully destroyed container

**Comment by sclevine** [comment]
Could you provide the full output of `cf dev start -s all`, and give us your system specs (total memory, CPU info, etc.)?

**Comment by fullydead** [comment]
![spec](https://user-images.githubusercontent.com/1572574/44972300-3e93f900-af8b-11e8-9bdd-d985345cac64.png)
[dev_start_all.txt](https://github.com/pivotal-cf/pcfdev/files/2344530/dev_start_all.txt)

**Comment by fullydead** [comment]
Pls see attached

**Comment by fullydead** [comment]
[dev_start_all.txt](https://github.com/pivotal-cf/pcfdev/files/2344534/dev_start_all.txt)
![spec](https://user-images.githubusercontent.com/1572574/44972398-992d5500-af8b-11e8-949e-08931a65bf0d.png)

**Comment by fullydead** [comment]
Problem still exist. Not sure why issue was closed

**Comment by aemengo** [comment]
Closing as this has been addressed in multiple other discussions. CF Dev failing to start on your workstation (especially with `-s scs`) is usually due to resource constraints: usually memory limits or slow disk speeds.

https://github.com/cloudfoundry-incubator/cfdev/issues/72#issuecomment-461796608
