### ISSUE TITLE
error on pcfdev install - "version is too old"

### ISSUE THREAD

**Issue by duderdice** [vmware-archive/pcfdev#344]
I have the latest (I believe) pcf cli installed (v6.38.0)
```
$> cf -v
cf.exe version 6.38.0+7ddf0aadd.2018-08-07

```
but when I try to install pcfdev package, I get the following error:
```
$> .\pcfdev-v0.30.0+PCF1.11.0-windows.exe
Your cf CLI version is too old. Please install the latest cf CLI.
```
I am on Windows 10, and used chocolatey to install pcf-cli, and it appears to be installed correctly.  Did a reboot and everything else seems to work correctly.  I am running this from PowerShell prompt (v6.1.0-rc1).  I tried using both an elevated shell and regular user shell; same result.  Any suggestions?

**Comment by ssisil** [comment]
Hi Darryl - have you tried using the latest version. cf dev -
https://github.com/cloudfoundry-incubator/cfdev
and the latest version of PCF Dev instead - the one that is an .iso file
you run with cf dev?

We now support windows 10 with that version instead of the legacy version
you are trying to use.

-Scott

**Comment by duderdice** [comment]
Success.  Thank you.

FYI - I was following the instructions in the [PCF Getting Started Guide](https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry-dev/install-pcf-dev
), which presumably needs updating.  Thanks again!

**Comment by ssisil** [comment]
Yes - it is out of date- we are in the process of updating.

Thanks

**Comment by andrelohmann** [comment]
Hi there, I was following the same installation instructions on my linux box and got the same error (Your cf CLI version is too old. Please install the latest cf CLI.), even if I'm allready on the latest cf cli (6.40.1).

Can you help me out with this too? Is anyone working on that problem? the regular cfdev plugin seems to be only available on macOS (and Windows, as I can see in this issue request).
