### ISSUE TITLE
PCF Dev fails to start at deploying BOSH director on restricting RAM to 6GB

### ISSUE THREAD

**Issue by coderookie1994** [vmware-archive/pcfdev#348]
Hi,
My system configuration is Windows 10 with total memory of 8GB. I was trying to start cf dev locally using this command 
cf dev start -m 6144  -f .\pcfdev-pas.v.2.0.20.0-build.0.82.0.iso
As u can see im trying to restrict memory to 6GB, because Windows is taking about 1.9GB minimally.
Everytime it fails at 
this
![new bitmap image 5](https://user-images.githubusercontent.com/15284156/45446830-83d2cc00-b6eb-11e8-8fdd-d7e8dacc903e.jpg)

So my question is can I disable some other services like RabbitMQ, Redis ?
So my bare bones VM at least starts up ?
Here are the log messages from cf dev logs

creating loop devices...
Deployment manifest: '/var/vcap/director/director.yml'
Deployment state: '/var/vcap/director/state.json'

Started validating
  Validating release 'bosh'... Finished (00:00:01)
  Validating release 'os-conf'... Finished (00:00:00)
  Validating release 'garden-runc'... Finished (00:00:02)
  Validating release 'grootfs'... Finished (00:00:02)
  Validating release 'bosh-warden-cpi'... Finished (00:00:10)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:30)
Finished validating (00:00:48)

Started installing CPI
  Compiling package 'golang-1.8-linux/a96c82386c30ac6ca67bcde2ee7b8ed8d9e5116a'... Finished (00:00:00)
  Compiling package 'warden_cpi/ca55fd1c340ede61944c9c2718d09fb6251a694f'... Finished (00:00:00)
  Installing packages... Finished (00:00:04)
  Rendering job templates... Finished (00:00:00)
  Installing job 'warden_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:05)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.55'... Finished (00:00:55)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell '8c507d71-e9e8-4b04-5190-265656b126c2'... Finished (00:01:42)
  Waiting for the agent on VM '7cc52b49-d4a3-40aa-5eaa-93ce4a474b8f' to be ready... Finished (00:00:08)
  Creating disk... Finished (00:00:02)
  Attaching disk 'de68b48e-8f32-4423-5b3d-f10e9c463af2' to VM '7cc52b49-d4a3-40aa-5eaa-93ce4a474b8f'... Finished (00:00:00)
  Rendering job templates... Finished (00:00:06)
  Compiling package 'autoconf/109f4668f1888e315e841d8f8396685dca2f9cb8fe9551d325d23500db0caa5f'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'pkg-config/59f8293a0c355f6ac26fbe6d185ed8d07ad6514e44efdbee45cb03f83b8ba748'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'libtool/16bb03d3ebe2c7b7bb4136b1ed49e518f278faf6481124adc4a0b40f4a912378'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'automake/b8f992f578de548311f62b9358cdba7dd97ec5b19145494e39484542cbdb27d4'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'ruby-2.4-r3/8471dec5da9ecc321686b8990a5ad2cc84529254'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'zlib/293e16abf1e1c72bcde0ece39b87310ccb5b4b5678390d1c91b9ed0b066aa1c9'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'util-linux/6310f68e8294c980de62481bced2fc915f449e3a2cc2d13a7a2a49c4a612d825'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'lzo/7ec718ef29da337d56f08e90534f561c138c2c88b576dc5da5185d85fdd42b20'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'golang/d0d1b2a5863243f82a949288cef9a3d5fc9d000e9be2904aea6d04650a0149b0'... Skipped [Package already compiled] (00:00:01)
  Compiling package 'mysql/b7e73acc0bfe05f1c6cbfd97bf92d39b0d3155d5'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'libpq/3afb51e921e950abb31e5d039d2144591a41482d'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'golang/ddeb4f6006c24bb49954212837b8f94b7aaf105648e968e6c04db57a083453eb'... Skipped [Package already compiled] (00:00:04)
  Compiling package 'golang-1.8-linux/a96c82386c30ac6ca67bcde2ee7b8ed8d9e5116a'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'apparmor/3789c10fa8ef4349f58badae51723eec7855d59b9bb6c1bb7ee21a264fae1dbb'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'libseccomp/0594acc533fd2801a347d6b725d0db9f3591c583d06f1e53201e701b12e09824'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'health_monitor/a0b5a680f1cbfda4a17b2fedff93cc9b9d9d959c'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'xfs-progs/6ce014f88e05f358621a25ce48ee036d78bdb1a935a8eb556974d3de26c8614d'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'guardian/d6db6a35ccdab8f813b3aabde4bc09400aef1a994879a65e8d67299ab720b87e'... Skipped [Package already compiled] (00:00:03)
  Compiling package 'bosh-gcscli/fce60f2d82653ea7e08c768f077c9c4a738d0c39'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'busybox/eab1896633e23c0eea7e07b91b27c2c090d16efd7fe07de1adbd8e5a1b16578e'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'director/0d042598ac5a6964d7de6b19b38a0d625386a8d6'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'idmapper/3319d2c98b73bb9d8b080aec2469b8b6018f56ea0aeac528f6f2c2a6f078b655'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'davcli/2672d0a96a775f5252fef6ac7bbab3928aa41599'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'garden-idmapper/557e57eeae91fc614b4d4e2ccf2440a93e725ed0b6a895a35fe8d94d2c764fa2'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'warden_cpi/ca55fd1c340ede61944c9c2718d09fb6251a694f'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'iptables/85ef0fef60ac079fb75b36d0693cce704a662b23b0727c824f15d58713476f13'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'postgres-9.4/52b3a31d7b0282d342aa7a0d62d8b419358c6b6b'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'nginx/3518a530de39c41ec65abf1194c27aadae23b711'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'grootfs/721259296fa06a6a237d691551deeed3af28e6105563a3893ee9ab2b2d02c4c0'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'gonats/73ec55f11c24dd7c02288cdffa24446023678cc2'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'runc/0de96bc356b3bb61592a2a4bddcfe1123086b589708e0b2b8f609e1b10066e90'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'tar/1de08f190630baf01c0741c86773a02f7c88c2786db1f219152e46e8853f1ccc'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'verify_multidigest/8fc5d654cebad7725c34bb08b3f60b912db7094a'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'btrfs-progs/935a56352911ed5fcf6ff10bce206ded409510f7661a464524abe24fff0c9070'... Skipped [Package already compiled] (00:00:01)
  Compiling package 's3cli/b6e38c619dd5575e16ea9fcabc4b7c500effdd26'... Skipped [Package already compiled] (00:00:00)
  Updating instance 'bosh/0'... Finished (00:01:32)
  Waiting for instance 'bosh/0' to be running... Failed (00:05:05)
Failed deploying (00:09:00)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Received non-running job state: 'failing'

Exit code 1

**Comment by sclevine** [comment]
Sorry for the delay here. The latest release lets you select which services you'd like to use with the `-s` flag. Additionally, the next version of PCF Dev should have greatly reduced start-up time and memory footprint. (Early testing shows 8 min starts and 4 GB base footprint!)

**Comment by coderookie1994** [comment]
Oh thanks, good to know.

**Comment by dkadam77** [comment]
Sorry but with this pcfdev-pas.v.2.0.22.0-build.0.101.0.iso version as well I am facing the same issue. Can you please help to resolve this issue?

**Comment by dkadam77** [comment]
Anyone addressing my issue please?

**Comment by coderookie1994** [comment]
Maybe you should open a new issue, because this is old and is closed
