### ISSUE TITLE
unable to run 'cf dev start -s scs'

### ISSUE THREAD

**Issue by dclaverty** [vmware-archive/pcfdev#349]
I get the following

FAILED
unknown shorthand flag: 's' in -s

I believe I am missing instruction on how to get the scs plugin integrated into the pcf dev plugin.

I am on MacOs
cf dev version is 0.0.10

**Comment by aemengo** [comment]
@dclaverty You will only have access to MySQL service. We do not currently support SCS.

Apps Manager, Redis, and RabbitMQ are available when you start in PCF Dev mode - which is `cf dev start -f <path to .iso>`. You should be able to download the .iso file from the PCF Dev page on network.pivotal.io. Additionally, please refrain from opening issues in this repository, as it is no longer maintained. The active cfdev repository can now be found: https://github.com/cloudfoundry-incubator/cfdev

**Comment by dclaverty** [comment]
Confused since this repo is full of -s examples.  Is it just not working on the Mac?  Also we use pivotal cloud foundry, not the open source Cloud Foundry, so why would I not continue here to ask questions about pcfdev vs cfdev ?
