### ISSUE TITLE
Just started pcf dev iso no services in marketplace, nor Apps Manager available

### ISSUE THREAD

**Issue by alberto-riggi** [vmware-archive/pcfdev#350]
Hi,

I started cf dev and received an error but seems like there are no services in marketplace and Apps Manager is not available neither. I also tried to push a sample app but cannot access it, even if it says it's running.
What am I missing? 

Following the error and some outputs

This is the error I received when starting cf dev:
cf dev start -f "C:\pcfdevHome\pcfdev-pas.v.2.0.20.0-build.0.82.0.iso" -m 8192
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Creating the VM...=============>| 100.0%
Starting VPNKit...
Starting the VM...
Waiting for Garden...
Deploying the BOSH Director...
Deploying CF...
  Uploading ReleasesFAILED
cf dev start: Failed to deploy services: unable to parse bosh config: yaml: line 2: mapping values are not allowed in this context

cf login -a https://api.dev.cfdev.sh --skip-ssl-validation
API endpoint: https://api.dev.cfdev.sh

Email> admin

Password>
Authenticating...
OK

Select an org (or press enter to skip):
1. cfdev-org
2. system

Org> cfdev-org
Targeted org cfdev-org

Targeted space cfdev-space

API endpoint:   https://api.dev.cfdev.sh (API version: 2.98.0)
User:           admin
Org:            cfdev-org
Space:          cfdev-space

cf marketplace
Getting services from marketplace in org cfdev-org / space cfdev-space as admin...
OK

No service offerings found

cf dev version
CLI: 0.0.10

cf apps
Getting apps in org cfdev-org / space cfdev-space as user...
OK

name    requested state   instances   memory   disk   urls
cloud   started           1/1         256M     1G     cloud.dev.cfdev.sh

**Comment by aemengo** [comment]
It looks like the start procedure failed for you midway, due to a bug that has already been resolved.
