### ISSUE TITLE
Internal miniport create failed

### ISSUE THREAD

**Issue by TallenOwen-zz** [vmware-archive/pcfdev#351]
I am trying to install PCF Dev and getting the following error
![pcfdevinstallerror](https://user-images.githubusercontent.com/27459252/46767670-8862b400-cc9a-11e8-8a41-dbe6a4afb67e.PNG)

Anyone able to help?

**Comment by aemengo** [comment]
Please re-open if you are still facing these concerns with the latest version. If you had recently enabled Hyper-V on your machine, I suspect that a reboot was in order.
