### ISSUE TITLE
pcfdev-pas.v.2.0.20.0-build.0.82.0.iso is not compatible with CF Dev.

### ISSUE THREAD

**Issue by teespoon** [vmware-archive/pcfdev#352]
This...
`cf dev start -f pcfdev-pas.v.2.0.20.0-build.0.82.0.iso`
...results in this...
`cf dev start: pcfdev-pas.v.2.0.20.0-build.0.82.0.iso is not compatible with CF Dev. Please use a compatible file`

The instructions here...
[https://docs.pivotal.io/pcf-dev/install-windows.html](url)
...suggest that the latest of both cf dev and .iso should be used, but it appears they are incompatible.  The issue may be the compatibility version.

pcfdev-pas.v.2.0.20.0-build.0.82.0.iso  METADATA.YML
`compatibility_version: "v1"`
...vs...
cfdev/cmd/start/start.go  line 144
`const compatibilityVersion = "v2"`

**Comment by teespoon** [comment]
Additional info...

```
> cf dev version
CLI: 0.0.11
cf: v4.5.0
cf-mysql: 36.15.0

> cf version
cf.exe version 6.40.0+07673feb9.2018-10-08

```

**Comment by morrisdand** [comment]
I'm having the exact same issue.  My versions are the same too.  Anyone try a previous version of PCFDev?  Curious if that would have the same compatibility problem...

**Comment by sclevine** [comment]
Apologies, see https://github.com/cloudfoundry-incubator/cfdev/issues/53

**Comment by morrisdand** [comment]
Thank you!  That appears to be working just fine!

**Comment by ssisil** [comment]
Latest release of PCF Dev - https://network.pivotal.io/products/pcfdev#/releases/216556
is compatible with CF Dev plugin v0.0.12 or higher.
