### ISSUE TITLE
 cf dev start -s scs  unknown shorthand flag: 's' in -s

### ISSUE THREAD

**Issue by wiZzwise** [vmware-archive/pcfdev#353]
cf dev start failed with scs flag : 

cf dev start -s scs
[31;1mFAILED[0m
unknown shorthand flag: 's' in -s

cf dev version
CLI: 0.0.10
cf: v4.3.0
cf-mysql: 36.15.0

cf version
cf.exe version 6.40.0+07673feb9.2018-10-08

**Comment by ssisil** [comment]
hi @faissalwise - Spring Cloud Services requires the CF Dev cli plugin v 0.0.12 or higher and the PCF Dev-PAS .iso to run. Please run `cf install-plugin cfdev` to upgrade to the latest version of the CLI plugin. Additionally, the PCF Dev PAS .iso file is available on Pivnet - here https://network.pivotal.io/products/pcfdev#/releases/216556.
