### ISSUE TITLE
no redis on pcfdev scs mode?

### ISSUE THREAD

**Issue by exzine** [vmware-archive/pcfdev#355]
no redis on pcfdev scs mode? v2.0.22
I can't push scdf without redis.

**Comment by ssisil** [comment]
@exzine - pass in `-s scs,redis` - this should include redis along with spring cloud services

**Comment by exzine** [comment]
thanks ssisil, after I pass in -s scs,redis the vm failed to start saying 'scs,redis' is not supported. I also tried put space in between "scs, redis", but the redis service won't be loaded. I do get things worked out by pass in "-s all", but someone might want to take a look at why "scs,redis" doesn't work.

**Comment by ssisil** [comment]
Ok - yeah this may be a bug - let me try to reproduce

**Comment by aemengo** [comment]
@exzine Our newest release **v.0.0.13** is out which addresses this issue by allowing multiple services to be specified with the `-s` flag. Please try it with the newest compatible pcf artifacts and let us know if this fixes your issue.

**Comment by sdawson-pivotal** [comment]
@exzine would you mind sharing a bit about your use case? We are looking to better understand how people are using CF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1
