### ISSUE TITLE
Can I run pcfdev-pas.v.2.0.22 on Windows 7?

### ISSUE THREAD

**Issue by Kairys** [vmware-archive/pcfdev#356]
I have downloaded pcfdev-pas.v.2.0.22.0-build.0.101.0.iso and the cf installer and followed the instructions to install the cfdev plugin. Following the instructions for Windows 7 I have also installed VirtualBox.
When I try the command "cf dev start -f ...iso" it fails at "checking whether hyperv is enabled". Of course HyperV is not available on Windows 7.

Returning to the instructions for Windows 7 I see they are really for the older releases of PCF-Dev such as pcfdev-v0.30.0+PCF1.11.0. Is it possible that pcfdev-pas.v.2.0.22.0 rquires Windows 10 and cannot be run on Windows 7?

**Comment by ssisil** [comment]
@Kairys - Correct the latest version of PCF Dev only supports Windows 10.  We are interested in hearing from users who are using earlier version of 10.  

Would you mind sharing your PCF Dev use case and what type of system you are running?

**Comment by Kairys** [comment]
I am a developer for SL Corporation <http://www.sl.com/> . We make products for monitoring middleware, including TIBCO BusinessWorks. We have a solution for monitoring BusinessWorks applications deployed in PCF containers. I have been developing and testing this solution using PCF-Dev.

**Comment by sdawson-pivotal** [comment]
@Kairys would you mind sharing a bit more about your use case? We are looking to better understand how people are using CF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1
