### ISSUE TITLE
Want to store Secrets on PCF for Dotnet Core

### ISSUE THREAD

**Issue by tpardhu561** [vmware-archive/pcfdev#357]
I've .Net core services to be deployed on PCF and I'm able to do this.
We have a requirement where we need to store DB Connection strings, Passwords on PCF and should be accessible thru Environment Variables(values should be encrypted).

Looking for suggestions.

**Comment by sclevine** [comment]
This seems like a general question about Cloud Foundry that's not specific to PCF Dev.

PCF ships with CredHub for this use case: https://docs.pivotal.io/pivotalcf/2-3/credhub/index.html

If you're a PCF customer in need of support, please reach out via support@pivotal.io.
