### ISSUE TITLE
Prompt not displaying correctly in PowerShell/CMD on Windows 10

### ISSUE THREAD

**Issue by stephendotcarter** [vmware-archive/pcfdev#358]
The color codes for BASH prompt are not rendering correctly in PowerShell/CMD on Windows 10:
![pcfdev_prompt](https://user-images.githubusercontent.com/4451181/48475770-6a3a2780-e7f5-11e8-984b-d862ffe4e8c9.png)

**Comment by mgreene-atx** [comment]
Thanks, @stephendotcarter !

**Comment by aemengo** [comment]
This issue is no longer applicable to the current iteration of [CF Dev](https://github.com/cloudfoundry-incubator/cfdev).
