### ISSUE TITLE
I am unable to install pcf dev. cf cli in the last version but the installer says is too old. 

### ISSUE THREAD

**Issue by llyorshch** [vmware-archive/pcfdev#359]
This is what happens:

```
localhost:Downloads jorge$ cf update-cli
You are using the latest version of cf cli (v6.40.1)
localhost:Downloads jorge$ cf --version
cf versión 6.40.1+85d04488a.2018-10-31
localhost:Downloads jorge$ ./pcfdev-v0.30.0+PCF1.11.0-osx
Your cf CLI version is too old. Please install the latest cf CLI.
localhost:Downloads jorge$ 
```

How is it possible?

**Comment by dcmoeller** [comment]
I'm facing this problem, too:
```
$ ./pcfdev-v0.30.0+PCF1.11.0-linux 
Your cf CLI version is too old. Please install the latest cf CLI.

$ cf update-cli
You are using the latest version of cf cli (v6.40.1)
```

**Comment by ssisil** [comment]
@dcmoeller @llyorshch - You are using the legacy version of PCF Dev, I would recommend using our new version - https://network.pivotal.io/products/pcfdev

If you run into system or memory constraints - I would recommend the OSS version - CF Dev - https://github.com/cloudfoundry-incubator/cfdev only.  It has a smaller footprint and requires less resources.

**Comment by dcmoeller** [comment]
This does not work for me:
```
$ cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.101.0.iso
'dev' ist kein registrierter Befehl. Siehe 'cf help -a'

$ cf install-plugin -r CF-Community "cfdev"
CF-Community nach Plug-in cfdev durchsuchen...
Das angeforderte Plug-in verfügt über keine Binärdatei für Ihre Plattform.
FEHLGESCHLAGEN
```

**Comment by dcmoeller** [comment]
```
$ cf install-plugin cfdev
CF-Community nach Plug-in cfdev durchsuchen...
Das angeforderte Plug-in verfügt über keine Binärdatei für Ihre Plattform.
FEHLGESCHLAGEN
```

**Comment by dcmoeller** [comment]
Cited from https://github.com/cloudfoundry-incubator/cfdev:

> Please note CF Dev only supports macOS at this time

**Comment by ssisil** [comment]
@dcmoeller - That is slightly out of date - ive updated it - as we support MacOS and Windows 10 at this time.  Linux support is on our roadmap.

**Comment by sclevine** [comment]
@llyorshch @dcmoeller could you try installing 0.30.0 via `cf install-plugin` instead of by executing it directly? Like this:
```
cf install-plugin ./pcfdev-v0.30.0+PCF1.11.0-linux 
```

**Comment by dcmoeller** [comment]
@sclevine OK, thank you, it seems to work now:

> Downloading VM ...

:-)
