### ISSUE TITLE
pcfdev-pas.v.2.0.22.0: cf dev start fails at step 6 of 14

### ISSUE THREAD

**Issue by Kairys** [vmware-archive/pcfdev#360]
Windows 10.1803. Running cf dev start fails consistently as follows:

cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.101.0.iso
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Creating the VM...=============>| 100.0%
Starting VPNKit...
Starting the VM...
Waiting for Garden...
Deploying the BOSH Director...
Deploying CF...
  Progress: 6 of 14 (1h23m53s)FAILED
cf dev start: Failed to deploy the Cloud Foundry: process exited with status 1

I followed a [suggestion in the support community](https://community.pivotal.io/s/question/0D50e00005DVj6FCAT/error-while-starting-pcfdev-getting-error) that I install bosh and look at recent tasks, and at the top of the list I see:

100  error  Tue Dec  4 02:07:52 UTC 2018  Tue Dec  4 02:50:05 UTC 2018  admin      cf          create deployment    Action Failed get_task: Task 51192c0e-eba1-4821-54b8-a3b474b210ab result: 1 of 7 pre-start scripts failed. Failed Jobs:...
99   done   Tue Dec  4 02:07:47 UTC 2018  Tue Dec  4 02:07:50 UTC 2018  admin      -           create release       Created release 'routing/0.168.12'
98   done   Tue Dec  4 02:07:44 UTC 2018  Tue Dec  4 02:07:46 UTC 2018  admin      -           create release       Created release 'cf-mysql/36.11.0'
97   done   Tue Dec  4 02:07:36 UTC 2018  Tue Dec  4 02:07:36 UTC 2018  admin      -           create release       Created release 'uaa/52.10'

Please advise...

**Comment by aemengo** [comment]
@Kairys More than likely, your machine unfortunately does not have enough free RAM to support the start process. If it is possible, please shut down any memory intensive programs and try again.

Moreover, the engineering team is working very hard to trim down the resources consumed by CF Dev. Our next release should fair far better.

**Comment by jsfranko** [comment]
my cf-cli (cf version 6.41.0+dd4c76cdd.2018-11-28) install via brew on macOS Mojave 10.14.2, doesn't have the -f switch on cf dev start:
```
USAGE:
   cf dev SUBCOMMAND

SUBCOMMANDS:
   start                             Start the PCF Dev VM. When creating a VM, http proxy env vars are respected.
      [-c number-of-cores]           Number of processor cores used by VM. Default: number of physical cores.
      [-d domain]                    Specify the domain that the PCF Dev VM will occupy.
      [-i ip-address]                Specify the IP Address that the PCF Dev VM will occupy.
      [-k]                           Import VM certificates into host's trusted certificate store.
      [-m memory-in-mb]              Memory to allocate for VM. Default: half of total memory, max 4 GB, max 8 GB with SCS.
      [-r registry1,registry2,...]   Docker registries that PCF Dev will use without SSL validation. Specify in 'host:port' format.
      [-s service1,service2]         Specify the services started with PCF Dev.
                                        Options: redis, rabbitmq, spring-cloud-services (scs), default, all, none
                                        Default: redis, rabbitmq
                                        (MySQL is always available and cannot be disabled.)
      [-t]                           Perform a CF login to PCF Dev after starting, as the 'user' user.
   stop                              Shutdown the PCF Dev VM. All data is preserved.

**Comment by aemengo** [comment]
@jsfranko You have a deprecated version of cfdev. Please re-install the following way:

```bash
$ cf dev stop
$ cf uninstall-plugin cfdev
$ cf install-plugin cfdev
$ cf dev version
CLI: 0.0.12

**Comment by jsfranko** [comment]
So cfdev replaces pcfdev?  After installing the plugin, cfdev is taking forever as root, to install BOSH Directgory and CF Router.  Is this normal?

**Comment by aemengo** [comment]
@jsfranko Unfortunately the current iteration does take a bit of time. But we will release a more performant update, that starts up much more quickly, soon.

**Comment by jsfranko** [comment]
One final comment.  The update to cfdev from pcfdev took up quite a lot of disk space for me.  I had about 60GB free and it consumed all of it.  I had to clear my maven repo to reclaim some space when the install got my drive down to below 100mb.  Making it a little leaner would be great.  Slow install, apps run slow on it  (I’m getting the 1 second timeout on health check bug), and consuming too much disk space.  

Thanks for taking the time to comment!  Very much appreciated!

**Comment by aemengo** [comment]
@jsfranko  Our newest release **v.0.0.13** is out, with major performance updates! Please give this a try and let us know if your issue is fixed.

```powershell
$ cf dev stop
$ Remove-Item -Recurse -Force ~/.cfdev
$ cf install-plugin -r CF-Community "cfdev"
$ cf dev start
```

**Comment by jsfranko** [comment]
Installed .13, still very slow, no more oracle virtual box, now hyperkit takes up between 80% an 120% of my cpu while idling. Ssh’d to my api and it shws about 4% in top. Can’t use the health actuator, it takes longer than 1 second to repond. Api only stays up if I change the health check to port. It takes around 13 minutes for the cf dev start. Push take about 3 mins

**Comment by jsfranko** [comment]
Also not getting the apps manager url st startup or login, and apps.dev.cdev.ssh is not working

**Comment by aemengo** [comment]
@jsfranko In regards to the apps manager issue, are you using the `-f` flag? PCF components are only accessible when you perform `cf dev start -f <path-to-pcf-artifacts.tgz>`. You can retrieve those here: https://network.pivotal.io/products/pcfdev

**Comment by sdawson-pivotal** [comment]
@jsfranko would you mind sharing a bit about your use case for PCF Dev? I appreciate the feedback re start time and resource needs. Wanting to better understand your usage to make sure we can support your needs.

**Comment by jsfranko** [comment]
My needs are just development/learning, on a mac. The company i work for sets up an official space for our apps. Right now I’m just pushing a spring boot generated config server pointing to a gitlab config repo. I’m using what i learn to help set up a ci pipeline in jenkins.
