### ISSUE TITLE
PCF DEV didn't install (Windows 10)

### ISSUE THREAD

**Issue by arittner** [vmware-archive/pcfdev#361]
Hello together!

We tried it several times, but it fails and currently I'm unsure, if the alpha release is deployable at all. It was possible to create a cf-dev system on two different Windows 10 notebooks (16GB and 32 GB physical RAM). Now we tried to install pcf dev with scs. We tried different memory setting (default 8GB, 10GB and our latest try: 16GB). We disabled virus protection, disabled sleep mode for hard-drives. Nothing is working.

CF CLI is installed successfully, old cfdev VM was destroyed (verified with VM comamnds via powershell). .cfdev folder was deleted. 

This is the latest try:

```
PS C:\WINDOWS\system32> cf dev start -m 16384 -f $env:userprofile/downloads/pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz -s scs
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...

Pivotal Telemetry

The Pivotal Telemetry program (“Pivotal Telemetry”) provides Pivotal Software, Inc. (“Pivotal”) with information that enables us to improve our products and services, fix problems, and advise you on how best to deploy and use our products. As part of Pivotal Telemetry, Pivotal collects technical information about your organization’s use of our products and services on a regular basis. Information collected under Pivotal Telemetry does not personally identify any individual.

Additional information regarding the data collected through Pivotal Telemetry and the purposes for which it is used by Pivotal is available on the Pivotal Telemetry page at https://pivotal.io/legal/telemetry.

By opting into the Pivotal Telemetry program, you understand and agree to the collection of product usage data in accordance with the program description at https://pivotal.io/legal/telemetry. If you prefer not to participate in Pivotal Telemetry, you should not join. You may join or leave Pivotal Telemetry at any time.

Are you ok with PCF Dev periodically capturing anonymized telemetry [y/N]?
> n
Creating the VM...
Starting VPNKit...
Starting the VM...
Waiting for the VM...
Deploying the BOSH Director...
Deploying CF...
  Done (22m40s)
Deploying Apps-Manager...
  Done (4m7s)
Deploying Spring Cloud Services...
  Uploaded Releases: 51 (9m38s)FAILED
cf dev start: Failed to deploy services: Failed to deploy Spring Cloud Services: exit status 1
```

The latest log lines from scs deploy:
```
Task 766 | 15:35:20 | Updating instance rmq: rmq/8238651f-7b47-4ed9-b80e-00deaabc5af9 (0) (canary) (00:01:43)
Task 766 | 15:35:37 | Error: Action Failed get_task: Task 9a43b417-3df7-47c3-7730-2d788400cbfa result: 1 of 1 post-deploy scripts failed. Failed Jobs: rabbitmq-server.

Task 766 Started  Thu Jan 10 15:33:09 UTC 2019
Task 766 Finished Thu Jan 10 15:35:37 UTC 2019
Task 766 Duration 00:02:28
Task 766 error

Updating deployment:
  Expected task '766' to succeed but state is 'error'

Exit code 1

```

I don't know how to check other logs (inside the VM?). Troubleshooting guides are talking about using BOSH. But this is not installed and it would be appreciated if someone can give me some hints how to find out what is going wrong.

About the versions:
cf.exe version 6.41.0+dd4c76cdd.2018-11-28

CLI: 0.0.13
pas: 2.0.22.0
cf: v1.15.0
cf-mysql: 36.15.0
pcf-rabbitmq: 1.12.6
pcf-redis: 1.12.1
spring cloud services: 1.5.8

**Comment by arittner** [comment]
Btw., I'm not alone with the troubles:
https://github.com/cloudfoundry-incubator/cfdev/issues/66

**Comment by aemengo** [comment]
Hey @arittner, I'm under the impression that this is an issue with resource limitations. We've worked hard to reduce the system requirements of CF Dev with this current version, but a local deployment of Spring Cloud Services might still be taxing for a local laptop. What is especially telling is your `Deploying CF...` step taking twice as long as it should.

That being said, we're able to deploy with the default settings (`8GB`, `-s scs`) repeatedly on our Windows 10 test environments. However this are full desktop machines, _not laptops_. Given that laptops are typically have less power than their desktop counterparts, it might be worth trying to run the same setup on a windows desktop machine while we investigate further.

**Comment by arittner** [comment]
Hello Anthony!

Thank you for your fast response. Yes I guess, this is the main issue. Not only the memory. With less CPU power some deployments run a long time and maybe some timeouts breaks the whole installation.

A dual core (4 threads) i5-6300U with 2.5GHz; 32GB RAM; SSD; is not the latest technology ;) 

Ok, we should think about a hardware upgrade for our team. Or we need a PCF local system on a workstation to check our development on this instance. We have a bunch of microservices (Spring boot/cloud (1.5, 2.0)). I'm pretty sure, this services on top will beat the scs deployment many times :-D
Currently we deploy natively (this means, Spring cloud native with own Auth. GW, registry and config server, on Linux or Windows with own scripts), or we deploy into Azure cloud with Docker/Kubernetes. But a very big customer goes to PCF and forces us to support this in a short time. This is not a problem for us. We have tested it and it works fine. But we need a development and maintenance strategy for our teams.

Anyway, thank you for your clarification. It helps us to plan the next steps. :-)

br, Josh.
