### ISSUE TITLE
Steeltoe in PCF Dev PAS 2.0.22.0

### ISSUE THREAD

**Issue by dlane771** [vmware-archive/pcfdev#364]
We are unable to see any Steeltoe integration with  PCF Dev PAS 2.0.22.0.

We are deploying .NET Core applications which leverage the SteelToe 2.0 libraries. Specifically,  we are using the management endpoints which integrate with the PCF Apps Manager. The health management endpoint does not appear to be integrated. Typically we see an "APP HEALTH" column on the instances table when viewed in the Pivotal Apps Manager.

![pcfhealthappsmanager](https://user-images.githubusercontent.com/30055913/52664098-90e42900-2ede-11e9-919d-bba1bed6ef97.PNG)

Note the picture is from a production version of PCF. We don't see this in PCF Dev.

Thank you.

**Comment by aemengo** [comment]
@dlane771 After discussing the issue with the appropriate team, it seems likely that the primary issue is that CF Dev uses a self-signed certificate. Getting CF Dev to use a valid certificate is currently out of scope for the team. But if you can get your machine to trust the CA, perhaps it might work.
