### ISSUE TITLE
cf dev start: adding aliases: failed to add network alias: vEthernet (cfdev)  The object already exists

### ISSUE THREAD

**Issue by kunal-aggarwal** [vmware-archive/pcfdev#366]
On running cf dev start -f on windows 10 with pcfdev-v0.30.0+PCF1.11.0-windows.zip get an error that -"failed to add network alias: vEthernet (cfdev) The object already exists"
For some reason I see a progress bar showing an attempt to add an network alias twice. In first attempt it shows 0% progress and in 2nd it shows 80% and then it fails with the error.
I'm using 8 GB RAM machine with i5 (2.5GHz) so think it's enough horse power.

**Comment by kunalkeane** [comment]
On running cf dev start -f on windows 10 with pcfdev-v0.30.0+PCF1.11.0-windows.zip get an error that -"failed to add network alias: vEthernet (cfdev) The object already exists"
For some reason I see a progress bar showing an attempt to add an network alias twice. In first attempt it shows 0% progress and in 2nd it shows 80% and then it fails with the error.
I'm using 8 GB RAM machine with i5 (2.5GHz) so think it's enough horse power.

**Comment by aemengo** [comment]
@kunalkeane Could you please try `cf dev stop` (to clean up leftover resources) and then execute the start command again?

Moreover, you're using outdated versions of CF Dev. Please consider upgrading the plugin to `CLI: 0.0.13` and the windows artifact to: `pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz`.

Lastly, depending on what else is running on your machine, 8GB is cutting it close  😬

**Comment by kunal-aggarwal** [comment]
Thanks for your response.  I took latest pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz but No luck! I already have latest CLI 0.0.13.
D:\DEV\PCF>cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
FAILED
cf dev start: adding aliases: failed to add network alias: vEthernet (cfdev), <ip>, exit status 1, The object already exists.

**Comment by aemengo** [comment]
@kunalkeane Very odd. Could you please try `Remove-VMSwitch -Name cfdev -force` in an Administrator powershell window and see if that helps?

**Comment by kunal-aggarwal** [comment]
PS D:\dev\pcf> Remove-VMSwitch -Name cfdev -force
PS D:\dev\pcf> cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
[31;1mFAILED [0m
cf dev start: adding aliases: failed to add network alias: vEthernet (cfdev),  exit status 1, The object already exists.

One observation-
In HKLM\SYSTEM\CurrentControlSet\Services\VMSMP\Parameters\NicList .. I can see 3 entries for cfdev
 then in HKLM\SYSTEM\CurrentControlSet\Services\VMSMP\Parameters\SwitchList ..  there is 1 entry for cfdev as expected.

BTW about which object it complains that it already exists?

**Comment by aemengo** [comment]
@kunalkeane I think I understand now.

Are you intentionally omitting part of the error message? The code that is failing to execute is here: https://github.com/cloudfoundry-incubator/cfdev/blob/v0.0.13/network/ip_aliaser_windows.go#L53. It is trying to add an IP address to the `VM-Switch` that it just created. You can execute it yourself here:
```
netsh interface ip add address "vEthernet (cfdev)" <ip-address> 255.255.255.255
```
This command failing more than likely means that the IP address already being occupied by another network interface. Could you please check the contents of `ipconfig`. If you see the IP _already_ there but on another interface (that can be removed), please remove it.

The provisioning step is trying to get to a state where the IP address is on the interface named: `Ethernet adapter vEthernet (cfdev):`

**Comment by kunal-aggarwal** [comment]
No! I'm not omitting any error 'intentionally'. Copied here whatever I'm seeing on console. Is there any other log gets generated?
I ran "netsh interface ip add address "vEthernet (cfdev)" <ip-address> 255.255.255.255" at home it didn't work. But then I tried to run 'cf dev start -f <file>'  again in corporate network then it moved ahead. The IP range it was trying to assign to vEthernet was actually my office IP range.
Then when I ran this on 8 GB machine it failed because of memory allocation error.

After that I tried it on 16 GM machine-
```
D:\kunal\pcf>cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...
Creating the VM...
Starting VPNKit...
Starting the VM...
FAILED
cf dev start: starting the vm: start-vm: failed to execute: powershell.exe -Command "Start-VM -Name cfdev": exit status 1: Start-VM : 'cfdev' failed to start. (Virtual machine ID 392AAF44-82FA-442E-BEA2-5BE58AF55170)
'cfdev' failed to start worker process: %3228369022 (0xC06D007E). (Virtual machine ID 392AAF44-82FA-442E-BEA2-5BE58AF55170)
At line:1 char:1
+ Start-VM -Name cfdev
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM
```

**Comment by aemengo** [comment]
@kunalkeane Interesting... If you're saying that you're now trying a `cf dev start` on a company machine, it maybe be locked down in some way. After reading the attached link, I'm thinking that it might be due to some kind of antivirus software. Perhaps talk to your system administrator and see if you're allowed to start _any_ Hyper-V virtual machines on your company's machines.

https://support.microsoft.com/en-ie/help/4052082/hyper-v-cannot-start-vm-after-you-upgrade-to-windows-10

**Comment by kunal-aggarwal** [comment]
I can run docker for windows on the same machine which actually uses hyper-V without using virtual box.

Now I'm trying on another machine at home. cf dev start created a vEthernet Adpter but could not assign any IP to it. Just shows a message identifying on network connections page.
cf dev start again failed with object exists error.
