### ISSUE TITLE
pcf dev stuck on 55

### ISSUE THREAD

**Issue by mustafakamil12** [vmware-archive/pcfdev#367]
Hi,
I have issue with pcf dev, am using mac os Mojave 10.14 with PCF Dev version 0.30.0 (CLI: 850ae45, OVA: 0.549.0), i tried with virtual box v 6.0.4 and it's stuck in the same step then i downgrade it to (5.2.26) and face the same issue. I also tried to use -m 8192 and also face the same issue, 

could you please advise if there's any solution to this problem, btw i tried to download and run virtual box 5.0.3 but it's failed coz the system couldn't recognize kext .

cf dev start
Using existing image.
Allocating 4096 MB out of 16384 MB total system memory (7212 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
7 out of 58 running
19 out of 58 running
33 out of 58 running
48 out of 58 running
48 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running
55 out of 58 running

**Comment by pho-enix** [comment]
I have the same issue. I found that there is some internal certs expired:

/var/vcap/sys/log/metron_agent/metron.log:
```
2019/02/27 08:13:55 Could not use GRPC creds for client: x509: certificate has expired or is not yet valid
2019/02/27 08:17:32 Could not use GRPC creds for client: x509: certificate has expired or is not yet valid
2019/02/27 08:19:23 Could not use GRPC creds for client: x509: certificate has expired or is not yet valid
2019/02/27 08:21:03 Could not use GRPC creds for client: x509: certificate has expired or is not yet valid
```

/var/vcap/jobs/loggregator_trafficcontroller/config/certs/trafficcontroller.crt:
```
        Validity
            Not Before: Feb 10 23:20:45 2017 GMT
            Not After : Feb 10 23:20:45 2019 GMT
```

**Comment by aemengo** [comment]
@pho-enix `v0.30.1 for PCF1.11.0` available at https://network.pivotal.io/products/pcfdev#/releases/312110 was recently released as a patch for this. Does this address your concerns?

https://github.com/pivotal-cf/pcfdev/issues/365#issuecomment-467647907

**Comment by mustafakamil12** [comment]
yes version 0.30.1 resolve the issue, thank u guys appreciate
