### ISSUE TITLE
How to push any app using pcf dev - pas 2.0.22.0

### ISSUE THREAD

**Issue by mustafakamil12** [vmware-archive/pcfdev#368]
Hi, 

Could you please advise how to use push command in pcf dev - pas 2.0.22.0

Start and stop a single vm CF deployment running on your workstation

Usage:
  cf dev [command]

Available Commands:
  bosh
  catalog
  download
  help        Help about any command
  start
  stop
  telemetry   Show status for collecting anonymous usage telemetry
  version

**Comment by aemengo** [comment]
CF Dev is only a CF plugin that stands up an local environment which you can push applications to. To push applications, you use `cf` itself in the following way:

```bash
$ cf login -a api.dev.cfdev.sh --skip-ssl-validation # Use the credentials in the splash message to log in
$ cd </path/to/application>
$ cf push <push-args>
```

You can find out more about the workflow [here](https://docs.cloudfoundry.org/cf-cli/getting-started.html#push)

**Comment by mustafakamil12** [comment]
appreciate
