### ISSUE TITLE
Log streams for apps not working in 0.30.1

### ISSUE THREAD

**Issue by kdvolder** [vmware-archive/pcfdev#369]
The 0.30.1 update fixed https://github.com/pivotal-cf/pcfdev/issues/365 but there still seems to be some sort of issue with apps log streaming. Commands like `cf push` or `cf logs` never display any log output from the app.

Some more details here: https://github.com/pivotal-cf/pcfdev/issues/365#issuecomment-468360804

**Comment by aemengo** [comment]
@kdvolder Appreciate you raising an issue about this and keeping us honest. You're definitely correct that there is a bug in that last release and getting it resolved is a high priority. Expect the fix to come very, very soon.

**Comment by aemengo** [comment]
We've made another patch release for this issue `v0.30.2 for PCF1.11.0`, which can be retrieved here: https://network.pivotal.io/products/pcfdev#/releases/314093. Please give it a go and do not hesitate to let us know if there are any problems.

We completely apologize as we cannot guarantee the same level of quality in our deprecated offering as we can in the new [CF Dev](https://github.com/cloudfoundry-incubator/cfdev)

**Comment by kdvolder** [comment]
> We completely apologize as we cannot guarantee the same level of quality in our deprecated offering as we can in the new CF Dev

FWIW: I think you are doing a great Job :-) Very grateful for all the feedback and these quick patches. I'll try this out shortly.
