### ISSUE TITLE
Proper method to shutdown virtualbox

### ISSUE THREAD

**Issue by tonybasile** [vmware-archive/pcfdev#37]
This is a request to include a little more documentation that explains among other things the proper method for shutting down the vm in virtualbox.  I am unable to ascertain the credentials for logging into the virtual machine to issue a shutdown command.

**Comment by sclevine** [comment]
Hi @tonybasile,

Thanks for trying out MicroPCF! You can shutdown the VM by running `vagrant halt`.

You can login to the VM using `vagrant ssh`, but rebooting the VM manually from the CLI will result in an unusable CF installation with no services running when it starts again.

We're actively working on documentation to make this more clear.

-Stephen

**Comment by tonybasile** [comment]
Thank you!
