### ISSUE TITLE
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.168.11.11:443: i/o timeout

### ISSUE THREAD

**Issue by ghost** [vmware-archive/pcfdev#370]
Hi ,
I had to prepare presentation for PCF and have the exact errors above irrelevant whether I run it on Centos or local MS-Windows toy it gives the same error:
```
[root@svmgmlo001:~/sandbox/spring-music]# cf login -a api.local.pcfdev.io --skip-ssl-validation
API endpoint: api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.168.11.11:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
```
I can access the internet no worries and have updated the no_proxy var but no luck.

Then I started to do Public cloud deployment and that crashed too. Throwing out many errors.
As a result:
![54272362-d9e1d880-4583-11e9-8ef4-0c623d5316f8](https://user-images.githubusercontent.com/34564819/54272711-7e641a80-4584-11e9-8d05-5399f83dce53.png)
![54270920-bd906c80-4580-11e9-9f2f-1f697390ba38](https://user-images.githubusercontent.com/34564819/54272715-802dde00-4584-11e9-9aaa-75548a0bf9a6.png)

So basically the 15 Minutes app deployment failed in both cases.
One would not expect to troubleshoot so much for a simple example.
This does not look good!

**Comment by aemengo** [comment]
@fabwolvie I suspect that there's some misinformation here. The `api.dev.cfdev.sh` domain points to a local Cloud Foundry environment that you must explicitly stand up. Did you first perform that operation with `cf dev start`? 

Secondly, this issue tracker is not the correct place to report unsuccessful application deployments to Pivotal Web Services. More than likely the `push` invocation or the application itself was malformed.

**Comment by ghost** [comment]
@aemengo 
Yes I have done both local and web deployments.

I have attached both of the error messages above respectively by deploying into:
1-  "local dev", by issuing:  cf login -a api.local.pcfdev.io --skip-ssl-validation
and 
2- "Pivotal Cloud" by issuing: cf login -a https://api.run.pivotal.io

Perhaps the Pivotal Cloud web error is not related to Cloudfoudry and I need to register it with them, but I thought it could be somehow related.

**Comment by aemengo** [comment]
@fabwolvie It doesn't seem like you're referring to our product here. To use `CF Dev`, please perform the following (note the domain change):

```
$ cf install-plugin -r CF-Community "cfdev"
$ cf dev start
...
$ cf login -a api.dev.cfdev.sh --skip-ssl-validation
```
