### ISSUE TITLE
PCF dev startup failure - Windows 10 Professional version 1809 - 64 bit

### ISSUE THREAD

**Issue by ranadeep-sh** [vmware-archive/pcfdev#371]
Downloaded specified version.
![Capture](https://user-images.githubusercontent.com/19390028/55522907-da3a3480-5654-11e9-88aa-abce893bdbb8.JPG)

![Pcf_dev_startup_failure_](https://user-images.githubusercontent.com/19390028/55522586-8d099300-5653-11e9-9ea8-a838515113dd.JPG)

As seen in screenshot, installed PCF Dev . Failed at step# 9 of 14 after taking around 21 hours.
Attempt to start again prompts that PCF Dev is already running.
Then, trying to connect prompts that no API endpoint is set.
Trying to forcefully set the endpoint fails.

Please guide to resolution of said issue.

**Comment by aemengo** [comment]
@ranadeep-sh Looks like something went wrong during the first start. To restart, you can run:

```sh
cf dev stop # To cleanup leftover resources 
cf dev start
```

**But before** you do so, it might be worth looking at `~/.cfdev/log/deploy-cf.log` to see if this failure was caused by anything deterministic.
More than likely, this was due to resource constraints on the machine that CF Dev is running on.

**Comment by ranadeep-sh** [comment]
Hi @aemengo ,

I have upgraded my physical RAM to 16 GB.
My laptop is an HP Envy model with Intel i7 processor.

I observed there's no update to the mentioned logs, since a long time, although I have been trying out almost every alternate day.
![Capture](https://user-images.githubusercontent.com/19390028/55599133-4df74280-5724-11e9-870c-35fb261c4a50.JPG)

I did stop and restarted fresh, but the progress steps numbers keeping flipping from 7 to 11, back and forth. I am not sure what's really going on.
![cf_dev_start_error](https://user-images.githubusercontent.com/19390028/55599228-bb0ad800-5724-11e9-8957-8455e7719ecf.JPG)

Kindly suggest alternative ways to trouble-shoot.

**Comment by aemengo** [comment]
Does your HP Envy model come with the following hard drive specification: `1 TB 7200 rpm SATA`? If so, please note that CF Dev is a very disk I/O intensive process and no less than flash (SSD) storage is recommended: https://github.com/cloudfoundry-incubator/cfdev#recommended-system-requirements.

I'm afraid that CF Dev may never start on your machine - as is. I'm not sure what your use case is, but if you simply need an environment to push applications and view them via a url, then Pivotal Web Services is a great alternative: https://run.pivotal.io/

**Comment by ranadeep-sh** [comment]
Yes. Here's my hard drive details - 1TB HDD 5400RPM SATA RAW HYBRID 8GB

So, are you absolutely sure that adding a SSD drive would resolve my current issue?
If so, does it also mean that my host Windows 10 OS also needs to be moved to this SSD drive ?

I have decided to go for a PCF Developer certification exam, this year. But, I am new to PCF and would like to explore as much as possible **with the lowest possible expenses**. So, having the whole setup in my control and knowledge is a must.

Thanks.

**Comment by aemengo** [comment]
@ranadeep-sh 

> Does it also mean that my host Windows 10 OS also needs to be moved to this SSD drive ?

No, the OS does not need to be moved. The CF Dev VM simply needs to run from the drive, which can be configured using the `$env:CFDEV_HOME` variable.

> So, are you absolutely sure that adding a SSD drive would resolve my current issue?

I'm sure that it will _help_ the current issue that you're facing. To be perfectly frank, your laptop seems to barely meet the specifications and you also seem intent on using the more resource intensive PCF artifiacts from Pivotal Network (using the `-f` flag). CF Dev might start up, but I'm not confident that your laptop will be able to do much else. If you could pursue another solution such as deploying CF to a cloud provider, or trying CF Dev on a more performant _full Desktop_ machine - I'd be much more optimistic.

That being said here's a post to similar SSD advice that I've given in the past. https://github.com/cloudfoundry-incubator/cfdev/issues/72#issuecomment-461796608.
Please let me know how things work out for you regarding this.

**Comment by ranadeep-sh** [comment]
Hi @aemengo ,

This is very informative.
I am getting one such drive today. I will try out and get back.
Thanks.

**Comment by ranadeep-sh** [comment]
@aemengo 

Bought a Portable SSD T5 and tried the same steps to start the TAR file.
No success yet. I am not sure where we are heading to.

**Comment by ranadeep-sh** [comment]
Found the trick that nobody told me.

Started PCF-Dev in **PowerShell Integrated Scripting Environment (ISE)** successfully, even without the SSD.

For deployment and other normal activities, the non-ISE Powershell can be used.

![PCF-Dev-started](https://user-images.githubusercontent.com/19390028/61988748-a44e0100-aff3-11e9-8427-16842eb09a43.JPG)
