### ISSUE TITLE
cf dev start fails

### ISSUE THREAD

**Issue by martin-schaefer** [vmware-archive/pcfdev#374]
I tried several times to start pcfdev on my Windows 10 Machine, but it always fails with an exit code 1. There is no obvious reason why. Any ideas what I can do? My machine runs Win 10 Pro on a Intel Core i7 2600k with 16GB Ram.

Outpout from PowerShell running as admin:
```
PS C:\users\Max\pcfdev> cf help
cf.exe version 6.43.0+815ea2f3d.2019-02-20, Cloud Foundry command line tool

PS C:\users\Max\pcfdev> cf dev start .\pcfdev-v1.2.0-windows.tgz
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...
Creating the VM...
Starting VPNKit...
Starting the VM...
Waiting for the VM...
Deploying the BOSH Director...
Deploying CF...
  Progress: 2 of 15 (1m21s)FAILED
cf dev start: Failed to deploy services: Failed to deploy CF: exit status 1
```

**Comment by aemengo** [comment]
Does the following post pertain to you?

https://github.com/cloudfoundry-incubator/cfdev/blob/master/FAQ.md#cf-dev-start-failed-while-deploying-it-got-stuck-at-progress-x-of-15-55m10s

**Comment by martin-schaefer** [comment]
I run pcf-dev on an Intel Core i7 2600K with 4 cores (8 virtual) @ 4.2 GHz max, 16GB Ram and 500 GB of free SSD space. Should be enough power, or not?
Is there probably a log file which could tell more about the problem?

**Comment by aemengo** [comment]
You're right, it should be enough power.

The log files are present at `~\.cfdev\log`. In this case, you might want `~\.cfdev\log\deploy-cf.log`. Could you please print out the output of that file?

On an unrelated note, I believe that you are not on the latest version of the CF Dev plugin. You can use `cf dev version` to check that it reports `v0.0.16`

**Comment by martin-schaefer** [comment]
Thanks for the hint. I therefore just realized I was using pcfdev (which "is our previous, deprecated offering" according to the website) and switched now to cfdev and it works! Thx for your support.
