### ISSUE TITLE
pcf dev start issues

### ISSUE THREAD

**Issue by pakro** [vmware-archive/pcfdev#375]
In our project we again can't start the pcf dev vm. It hangs on 55/58 started services and times out after 1 hour. Is there again a certificate issue?

We are still using pcfdev-v0.30.2+PCF1.11.0-linux

**Comment by aemengo** [comment]
@pakro Please consider the replacement for this project: CF Dev - which now supports Ubuntu

https://github.com/cloudfoundry-incubator/cfdev
