### ISSUE TITLE
Enabling nfs-volumes on PCF-DEV and / or PWS

### ISSUE THREAD

**Issue by sikosi** [vmware-archive/pcfdev#377]
**Enabling nfs-volumes on PCF-DEV and / or PWS**

I am using the PCF-DEV Version 1.20 for Windows downloaded from https://network.pivotal.io/products/pcfdev/
As far as I understood, the NFS-Volume Service is included by default in the Marketplace of PCF-DEV, but I don't see this when I `cf marketplace`

I switched to my trial account of Pivotal Web Services, but could not find the nfs service there either.

So my question is, how do I get the NFS Service on PCF-DEV or on PWS? Or do I need to do extra work?

Thank you for your support!

**Comment by aemengo** [comment]
I'm sorry but NFS/local-volume services are not provided on any of the latest assets of CF Dev.

The main reason is that at close to `~20GB`, these assets are already large in size and thus we're being very particular about what services that we are bundling in.

If you're familiar with the BOSH ecosystem, your best option is to follow the instructions here to deploy manually: https://github.com/cloudfoundry/local-volume-release

This is not the correct place to receive support about PWS.

**Comment by sikosi** [comment]
Hi alright!
Your answer clarified my issue at stake, thanks
