### ISSUE TITLE
Unable to register service broker with self-signed certificate

### ISSUE THREAD

**Issue by some-ibmer** [vmware-archive/pcfdev#378]
This isn't so much a bug necessarily, but a question.  Trying to register a service broker that implements the OSB API.  It currently uses a self-signed certificate, and I can't find a way to get PCF Dev to accept it.  Using `pcfdev-v1.2.0-linux.tgz`.  Currently see the following:

```console
cf create-service-broker zoscb <user> <pass> <host>:<port>/api
Creating service broker zoscb as admin...
Unexpected Response
Response code: 500
CC code:       0
CC error code:
Request ID:    ffeb9515-b7e4-4808-66fc-a94825e677fa::45f76f1a-80ac-49d0-937f-74db5de5c200
Description:   {
  "description": "SSL_connect returned=1 errno=0 state=error: certificate verify failed",
  "error_code": "CF-HttpRequestError",
  "code": 10001,
  "http": {
    "uri": "<host>:<port>/api/v2/catalog",
    "method": "GET"
  }
}
```

Been trying to find a way to get the pcf dev setup to trust this self-signed certificate without much luck.

**Comment by aemengo** [comment]
CF Dev doesn't have the ability to trust arbitrary certificates
