### ISSUE TITLE
PCF-DEV and DELL ECS

### ISSUE THREAD

**Issue by sikosi** [vmware-archive/pcfdev#379]
Hello!
Is it possible to integrate the PCF-DEV  with the DELL ECS Service Broker? And if yes, what are the steps please.
Thanks

**Comment by aemengo** [comment]
If you're using the newest CF Dev found here: https://github.com/cloudfoundry-incubator/cfdev, then you have access to a functional BOSH Director that you can deploy a service broker with - using the BOSH workflow: https://bosh.io/docs/deploying/

**Comment by sikosi** [comment]
Hello!
Yes I have the newest CF Dev Version. 
I also checked the BOSH link supplied, but I can't see or I don't understand where or how to use the Director to deploy the service Broker. Could you elaborate a little please, with may be a sample service breoker deployment using BOSH?
Thank you sir!
