### ISSUE TITLE
"no available version" error when doing `vagrant up`

### ISSUE THREAD

**Issue by billimek** [vmware-archive/pcfdev#38]
At least with the virtualbox provider,

```
 ❯ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'micropcf/base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 0
==> default: Loading metadata for box 'micropcf/base'
    default: URL: https://atlas.hashicorp.com/micropcf/base
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constriants.

Box: micropcf/base
Address: https://atlas.hashicorp.com/micropcf/base
Constraints: 0
Available versions: 0.0.1, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.38.0, 0.39.0, 0.40.0, 0.41.0, 0.42.0, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0, 0.53.0, 0.54.0, 0.55.0, 0.56.0, 0.57.0
```

`config.vm.box_version = "0"` inside Vagrantfile may be at issue.  Editing this and hard-coding one of the versions (e.g. `config.vm.box_version = "0.57.0"`) gets past this.

If I find a generic way to handle it, I'll fork and submit a pull request.

**Comment by sclevine** [comment]
Hi @billimek, thanks for checking out microPCF!

The Vagrantfile at the root of the repository should only be used to run locally-built development boxes (explicitly versioned `v0`) corresponding to the same commit. The latest box version may not work with that Vagrantfile. Please use a Vagrantfile from the available [Releases](https://github.com/pivotal-cf/micropcf/releases) or [Nightly Builds](https://micropcf.s3.amazonaws.com/nightly/index.html), as mentioned in the README.

-Stephen
