### ISSUE TITLE
Timed out waiting for the VM: rpc error

### ISSUE THREAD

**Issue by MatthiasLakaemper** [vmware-archive/pcfdev#380]
Hi,

i have problems, starting cfdev.

System Windows 10 Enterprise
```
cf version: cf.exe version 6.46.0+29d6257f1.2019-07-09
```
i am using: pcfdev-v1.2.0-windows.tgz

could you please help

Regards, Matthias

```
-----Start-Protocol---------------------------------------------------------
cf dev start -f C:\Develop\CloudFoundry\pdfdev/pcfdev-v1.2.0-windows.tgz

cf dev start -f C:\Develop\CloudFoundry\pdfdev/pcfdev-v1.2.0-windows.tgz
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...

Pivotal Telemetry
...
Are you ok with PCF Dev periodically capturing anonymized telemetry [y/N]?
> y
Creating the VM...
Starting VPNKit...
Starting the VM...
Waiting for the VM...
FAILED
cf dev start: Timed out waiting for the VM: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9999: connectex: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte."
```

**Comment by MatthiasLakaemper** [comment]
Hi,
what does that mean, how can i get a solution?

Regards, Matthias

**Comment by aemengo** [comment]
Could you please provide the log files present in `~/.cfdev/logs`?
Those might provide clues as to what error you're seeing.

**Comment by MatthiasLakaemper** [comment]
Hi,

here the log-files.

best Regards, Matthias

[org.cloudfoundry.cfdev.vpnkit.err.log](https://github.com/pivotal-cf/pcfdev/files/3534742/org.cloudfoundry.cfdev.vpnkit.err.log)

[org.cloudfoundry.cfdev.vpnkit.wrapper.log](https://github.com/pivotal-cf/pcfdev/files/3534743/org.cloudfoundry.cfdev.vpnkit.wrapper.log)

**Comment by aemengo** [comment]
There doesn't seem to be anything wrong in the logs that you've sent.

Does your machine meet the recommended system requirements here? https://github.com/cloudfoundry-incubator/cfdev#recommended-system-requirements

**Comment by MatthiasLakaemper** [comment]
Hi,

i have checked the requirements. I see, that i have no bosh installed...
Is that necessary?

I only find a amd64.exe.  (bosh-cli-6.0.0-windows-amd64.exe) do download,

This doesn´t start on my Intel-System...

Any idea?

best Regards, Matthias

**Comment by aemengo** [comment]
No, installing BOSH is not necessary.

I was referring to the system requirements:
> CPU: 2 Cores or more
> Memory: 8 Gigabytes _available_ memory
> Disk: 60GB _flash_ storage

**Comment by MatthiasLakaemper** [comment]
4 CPUs 
32 GB Ram
After complete Installation 40 GB remaining free... (is that not enough)

**Comment by aemengo** [comment]
@MatthiasLakaemper What about the disk storage? Are you using a Solid-State-Drive or Hard-Disk-Drive? Are you able to discern?

**Comment by MatthiasLakaemper** [comment]
Hi,

its a Hard-Disk. See Screenshot.



[DiskInfo.docx](https://github.com/pivotal-cf/pcfdev/files/3535002/DiskInfo.docx)

**Comment by MatthiasLakaemper** [comment]
Hi,

i increased the space to 89 GB

sam error.

-------------------
Waiting for the VM...
FAILED
cf dev start: Timed out waiting for the VM: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9999: connectex: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte."

**Comment by MatthiasLakaemper** [comment]
Hi,

i get it run directly in Windows10.

But when i try to run it on a Windows10 via VMWare-Workstation it doesnt work. 
   -> my Problems...

Because of the hyper-v - problem 
     (bcdedit /set hypervisorlaunchtype on -> reboot.)
it is obviously not possible to run cf-dev and work with VmwareWorkstation side by side.

best Regards, Matthias

**Comment by aemengo** [comment]
CF Dev spins up a VM on your local machine. This is a fairly intensive process and attempting perform the start process inside _another_ VM is not recommended nor supported.
