### ISSUE TITLE
cf dev start fails

### ISSUE THREAD

**Issue by diazoscuros** [vmware-archive/pcfdev#382]
Hi,
cf start fails after waiting for services to start. Is there a pcf dev version compatible with VirtualBoxVersion 5.2.22 r126460 (Qt5.6.3) or above? Unfortunately on this MacOs Mojave 10.14.6 (18G95) (Memory 16GB)I cannot run older VirtualBox versions.

Here all the versions I am trying to use, no nested VM:
cf version 6.46.1+4934877ec.2019-08-23
PCF Dev version 0.30.2 (CLI: 850ae45, OVA: 0.551.0)

Thank you.

**Comment by diazoscuros** [comment]
Pasting the error:

55 out of 58 running
Timed out after 3600 seconds.
FAILED
Error: failed to provision VM: Process exited with: 1. Reason was:  ().

**Comment by diazoscuros** [comment]
***********
/var/pcfdev/provision.log

+ started=17
+ [[ 17 -lt 58 ]]
+ counter=297
+ [[ 57 = 0 ]]
+ sleep 1
++ started_service_count
++ started_services
++ monit_summary
++ wc -l
++ grep -E '(running|accessible|Timestamp changed|PID changed)'
+++ /var/vcap/bosh/bin/monit summary
++ tr -d \'
++ awk '{print $2}'
++ output='The Monit daemon 5.2.5 uptime: 7m

Process '\''pcfdev-api'\''                running
Process '\''pcfdev-nginx'\''              running
Process '\''vxlan-policy-agent'\''        Execution failed

**********
/var/vcap/monit/monit.log

[UTC Sep 11 17:38:18] error    : 'vxlan-policy-agent' process is not running
[UTC Sep 11 17:38:18] info     : 'vxlan-policy-agent' trying to restart
[UTC Sep 11 17:38:18] info     : 'vxlan-policy-agent' start: /var/vcap/jobs/vxlan-policy-agent/bin/vxlan-policy-agent_ctl
[UTC Sep 11 17:38:48] error    : 'vxlan-policy-agent' failed to start
[UTC Sep 11 17:38:48] error    : 'silk-daemon' process is not running
[UTC Sep 11 17:38:48] info     : 'silk-daemon' trying to restart
[UTC Sep 11 17:38:48] info     : 'silk-daemon' start: /var/vcap/jobs/silk-daemon/bin/silk-daemon_ctl
[UTC Sep 11 17:39:18] error    : 'silk-daemon' failed to start
[UTC Sep 11 17:39:18] error    : 'rep' process is not running
[UTC Sep 11 17:39:18] info     : 'rep' trying to restart
[UTC Sep 11 17:39:18] info     : 'rep' start: /var/vcap/jobs/rep/bin/rep_ctl
[UTC Sep 11 17:39:19] error    : 'process-destroyer' process is not running
[UTC Sep 11 17:39:19] info     : 'process-destroyer' trying to restart
[UTC Sep 11 17:39:19] info     : 'process-watcher' stop: /var/vcap/jobs/cf-redis-broker/bin/process-watcher_ctl
[UTC Sep 11 17:39:20] info     : 'process-destroyer' start: /var/vcap/jobs/cf-redis-broker/bin/process-destroyer_ctl
[UTC Sep 11 17:39:20] info     : 'process-watcher' start: /var/vcap/jobs/cf-redis-broker/bin/process-watcher_ctl
[UTC Sep 11 17:39:31] error    : 'vxlan-policy-agent' process is not running


*******
/var/vcap/sys/log/vxlan-policy-agent/vxlan-policy-agent_ctl.err.log

/var/vcap/packages/ctl-utils/ctl_util.sh: line 95: kill: (15857) - No such process


*******

/var/vcap/sys/log/vxlan-policy-agent/vxlan-policy-agent_ctl.out.log 

Wed Sep 11 14:51:21 UTC 2019: checking for processes listening on port 44151
Wed Sep 11 14:51:21 UTC 2019: no processes found listening on port 44151

**Comment by diazoscuros** [comment]
*********

/var/vcap/sys/log/silk-daemon/silk-daemon_ctl.err.log 

/var/vcap/packages/ctl-utils/ctl_util.sh: line 95: kill: (17185) - No such process


**********

/var/vcap/sys/log/silk-daemon/silk-daemon_ctl.out.log 

Mon Sep  9 04:28:39 UTC 2019: checking for processes listening on port 23954
Mon Sep  9 04:28:39 UTC 2019: no processes found listening on port 23954


**********


/var/vcap/sys/log/silk-daemon/silk-daemon.stderr.log 

2019/09/09 04:28:39 silk-daemon error: acquire subnet lease: http client do: Put https://silk-controller.service.cf.internal:4103/leases/acquire: dial tcp 127.0.0.1:4103: getsockopt: connection refused
2019/09/09 04:33:00 silk-daemon error: acquire subnet lease: http client do: Put https://silk-controller.service.cf.internal:4103/leases/acquire: x509: certificate has expired or is not yet valid

***********

**Comment by diazoscuros** [comment]
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            6e:ff:c1:92:e6:38:56:61:21:4e:f5:45:1c:44:c9:93
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=cf-networking-ca
        Validity
            Not Before: May 25 18:24:42 2017 GMT
            Not After : May 25 18:24:42 2019 GMT
        Subject: CN=silk-daemon
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)

**Comment by aemengo** [comment]
You are using the unsupported, deprecated version of CF Dev. Please consider trying our newer version:

https://github.com/cloudfoundry-incubator/cfdev#install

**Comment by diazoscuros** [comment]
Thank you @aemengo . CF Dev is running now.
