### ISSUE TITLE
unable run the pcf dev -f filepath giving new object error in power shell

### ISSUE THREAD

**Issue by phanivasana** [vmware-archive/pcfdev#392]
Hi Folks,

I am using Windows 10 VDI with 2 cores and 16GB RAM and trying to install the pcf dev.

1. Installed cf  command line of version "cf.exe version 6.51.0+2acd15650.2020-04-07".
2. Installed cfdev plugin using cf install-plugin filepath where i downloaded plugin from "https://plugins.cloudfoundry.org/".
3. Result of command plugin cf plugins is "cfdev    0.0.17    dev            Start and stop a single vm CF deployment running on your workstation". (working fine)
4. Result of command cf dev version is "CLI: 0.0.17 BUILD: 14 (b36c82e)" (working fine)
5. I downloaded the file "pcfdev-v1.2.0-windows".
6. finally running the cf dev start -f pcfdev-v1.2.0-windows.tgz getting below error. 

FAILED
cf dev start: checking for admin privileges: failed to execute: powershell.exe -Command "(New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)": exit status 1: New-Object : The term 'New-Object' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+ (New-Object Security.Principal.WindowsPrincipal([Security.Principal.W ...
+  ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-Object:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Please provide the solution for this it is a show stopper.

**Comment by aemengo** [comment]
Closing because your issue is not a problem with CF Dev. CF Dev has not begun to start executing in your example. Thus this is out of scope for this repository.
