### ISSUE TITLE
Download of PCF Dev v1.3.0 for PAS 2.5.7 not possible

### ISSUE THREAD

**Issue by jeksopra** [vmware-archive/pcfdev#395]
Hello folks, 

unfortunately, trying to download the packages of the recently released PCF Dev v1.3.0 fails for all platform packages with the following error notice:

```
ERROR
The request could not be satisfied.

Generated Fri, 03 Jul 2020 05:32:23 GMT
Request ID: 8Voezj28edrO9XY9R4Jn0j6zIP8QaeWUEFIn3ObyuxSxlxDSaxk1LQ==

```
Could you please have a look? Seems to be an error in the Cloudfront settings:
This is one sample of the dead links:
`https://d13k9s5899twdr.cloudfront.net/product_files/pcfdev/359fb30e-1ac7-46de-af54-3092e1835a90?Expires=1593841146&Signature=ZnNfyB82ZlTFevQexf01ka72GaZ-djIssySgCLZe-Ja45Ehlz3HC7ZGp08zauEg3RxUNABr9lTvVE6dfBeDihYHk4jquqHpE3UwhJv0jggWgdVIFw2wvkp8pIp48VoYYiCrFyndWXPj1bdGZTVge4qpVVOcJ0KQLZN-htZf%7EU11iiUAITJT6cA6yO79omDP6-tpjUoYhcjo3nKvr1gTQD96Ecm5WzNGUZ43gm7R-rfQATA2QsPhoVZEICKogMs%7ELJSbvpgmFOkWv2aGdjyi0KFlYwwk2arIA8EXv2NUcz1pCBTHy7oPbglnrblTZWgrK4hKRcopwqWTXUu4F8L3aOw__&Key-Pair-Id=APKAIOIREZ2UWYGOZQDA&filename=359fb30e-1ac7-46de-af54-3092e1835a90
`

Thanks in advance!

**Comment by aemengo** [comment]
Apologies once more. We've finally come across a version that is too big to serve at once. What we have done is serve the same files in **v1.3.1** but broken up into 2 parts per platform. The workflow is exactly before but the files must be combined before use with the plugin.

```
# Windows
copy /b .\pcfdev-v1.3.1-windows.tgz-aa + .\pcfdev-v1.3.1-windows.tgz-ab .\pcfdev-v1.3.1-windows.tgz

# Unix
cat pcfdev-v1.3.1-darwin.tgz-aa pcfdev-v1.3.1-darwin.tgz-ab > pcfdev-v1.3.1-darwin.tgz
```

Please give the following a try:

- ~~**v1.3.0** (Service Assets) - https://network.pivotal.io/products/pcfdev/#/releases/685614~~
- **v1.3.1** (Service Assets) - https://network.pivotal.io/products/pcfdev#/releases/690049

**Comment by jeksopra** [comment]
Hi @aemengo,

thanks a lot for your support and the very quick workaround solution for the new PCF Dev release. I now was able to download the packages, forging the two package parts together by the windows copy command and finally starting the PCF Dev environment including the Spring Cloud Services on my local workstation (Laptop). So I can begin with my app deployment that are using the Spring Cloud Services.

Best regards!
