### ISSUE TITLE
Setting up the micropcf development env, git clone failed

### ISSUE THREAD

**Issue by amitoj** [vmware-archive/pcfdev#40]
Following the guide micropcf/DEVELOP.md, git clone operation fails with error message

> Submodule 'assets/rabbit-example-app' (https://github.com/pivotal-cf/rabbit-example-app.git) registered for path 'assets/rabbit-example-app'
> Cloning into 'assets/rabbit-example-app'...
> remote: Counting objects: 115, done.
> remote: Total 115 (delta 0), reused 0 (delta 0), pack-reused 115
> Receiving objects: 100% (115/115), 1.90 MiB | 1.72 MiB/s, done.
> Resolving deltas: 100% (43/43), done.
> Checking connectivity... done.
> Submodule path 'test/src/github.com/pivotal-cf/cf-rabbitmq-smoke-tests/assets/rabbit-example-app': checked out '55b12318c9fb9677e06e10255b84c1e3da13553f'
> Failed to recurse into submodule path 'releases/cf-mysql-release'
> Unable to checkout 'dc571470ca621d3e919e47fb9538277452b2b1ab' in submodule path 'test/src/github.com/mdelillo/cf-mysql-acceptance-tests'

Navigating directly to [github.com/mdelillo/cf-mysql-acceptance-tests](https://github.com/mdelillo/cf-mysql-acceptance-tests) I can see the module but not sure why is it failing to checkout

Also noticed another error message towards the beginning, but this one doesn't interrupt the git clone operation

> remote: Repository not found.
> fatal: repository 'https://github.com/fraenkel/candiedyaml/' not found
> Clone of 'https://github.com/fraenkel/candiedyaml' into submodule path 'src/github.com/fraenkel/candiedyaml' failed

Thanks

**Comment by sclevine** [comment]
This should be fixed on master. Feel free to re-open if you're still having issues.

Thanks!
Stephen
