### ISSUE TITLE
Cloud lattice vs pcfdev - which one to use and for what usecase?

### ISSUE THREAD

**Issue by volivattam77** [vmware-archive/pcfdev#46]
Hi,

In what way is pcfdev different from cloud lattice.

Seems like both have same objectives.

I am not clear which one would be better to install and explore cloud foundary features locally with a laptop.

I was planning to install cloud lattice after googling about a way to explore cloud foundary locally.

Can you help in clarifying the scope of 2 products and the usecases in which pcfdev would be better.

Thanks,
Volivattam

**Comment by sclevine** [comment]
Hi @volivattam77,

PCF Dev and Lattice are two different products with two different goals.

Lattice, which is no longer actively maintained, was essentially a demo of the Diego app scheduler. Lattice could not be used with the `cf` CLI and didn't support many Cloud Foundry features such as marketplace services. Lattice could be deployed to a single local VM (like PCF Dev), but it could also be deployed with many cell VMs to a number of different cloud infrastructures.

PCF Dev is a small replica of a full PCF installation. You can use PCF Dev to try out your CF apps before locally before you deploy them to production, or evaluate PCF features. PCF Dev is provided as a single, local VM for Virtualbox.  

Does this make sense?

Thanks,
Stephen
