### ISSUE TITLE
Support for VMware Fusion

### ISSUE THREAD

**Issue by mreider** [vmware-archive/pcfdev#47]
Would be nice to use getopt in the start-osx script to set a flag --provider=vmware_fusion

**Comment by sclevine** [comment]
Hi @mreider,

Although we are still building VMware boxes that should function properly, we don't officially support it. We have very few users who run VMware Fusion / Workstation and are willing to purchase the Vagant VMware plugin. We may officially support VMware after we switch from Vagrant to a customer `cf dev` plugin that we're working on.

Thanks,
Stephen

**Comment by qzi** [comment]
## Vmware is important platform ya !!!

[**_@localhost pcf]# ./pcfdev-v0.20.0+PCF1.8.0-linux 
Plugin successfully installed. Current version: 0.20.0. For more info run: cf dev help
[**_@localhost pcf]# cf dev start
FAILED
Error: failed to execute 'VBoxManage --version': exec: "VBoxManage": executable file not found in $PATH: .
panic: This shouldn't print anything
