### ISSUE TITLE
MongoDB / Cassandra / BOSH support

### ISSUE THREAD

**Issue by amitoj** [vmware-archive/pcfdev#48]
Any plans for including NoSQL databases such as MongoDB and Cassandra in the near future releases of pcfdev?
I'm considering using cups command to provide MongoDB access.
But would like to get a default MongoDB database available as a service in marketplace with pcfdev.

Also, when are we going to see the access to bosh shell or bosh director?
I want to create my own bosh scripts for setting up 'Spring Cloud Services' in pcfdev.

**Comment by sclevine** [comment]
Hi @amitoj,

There are currently no plans to integrate MongoDB or Cassandra. If we get more feedback requesting them, or hear that many enterprise PCF installations have them available, we will certainly consider it. Spring Cloud Services, however, is on our roadmap and will likely be available in several months.

PCF Dev does not include a BOSH director. We use a tool called bosh-provisioner to deploy BOSH releases to PCF Dev, but we do not support deploying additional BOSH releases to official releases of PCF Dev. 

-Stephen

**Comment by amitoj** [comment]
Thanks

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
+1 MongoDB

**Comment by Turbots** [comment]
+1 Cassandra since I would like to play around with Spinnaker on PCFDEV (one of the Spinnaker microservices uses Cassandra as backing store)

**Comment by andifalk** [comment]
+1 MongoDB

**Comment by luckyabhishek** [comment]
+1 MongoDB

**Comment by altfatterz** [comment]
+1 MongoDB

**Comment by andreas-schilling** [comment]
+1 MongoDB

**Comment by KrishnaT08** [comment]
+1 MongoDB

**Comment by ghisvail** [comment]
+1 for MongoDB / Cassandra
