### ISSUE TITLE
Cannot start - issue on download

### ISSUE THREAD

**Issue by alexvasseur** [vmware-archive/pcfdev#49]
Trying v0.14.0 - I have the below error (I tried from 2 networks) - after around 1 hour of download

==> default: Adding box 'pcfdev/pcfdev' (v0.54.0) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/pcfdev/boxes/pcfdev/versions/0.54.0/providers/vmware_desktop.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
SSL read: error:00000000:lib(0):func(0):reason(0), errno 54

**Comment by Turbots** [comment]
I just downloaded pcfdev yesterday on my Macbook Pro and it worked flawlessly, it booted up perfectly and everything works like a charm. You should try again, the connection was probably interrupted while downloading

**Comment by sclevine** [comment]
@avasseur-pivotal Are you still having trouble downloading the latest version (0.15.0)?

**Comment by alexvasseur** [comment]
Thank you - I am closing this - as I could download 0.14.0 today successfully.
