### ISSUE TITLE
Proper command to start pcfdev with AWS provider

### ISSUE THREAD

**Issue by mdcarlson** [vmware-archive/pcfdev#51]
What is the recommended way to initialize and start pcfdev  using AWS as the provider.

I can obviously modify `start-osx.sh` to use the `--provider=aws` argument on the `vagrant up` command, but wonder if that is the preferred approach.

I attempted to use `./start-osx --provider=aws` but that resulted in using the virtualbox provider.

I have been successful in starting pcfdev using AWS as provider so far only by modifying the `.start-osx` script and populating the environment variables needed by the AWS section of the `Vagrantfile`.

--M

**Comment by sclevine** [comment]
Hi @mdcarlson,

We do not support running PCF Dev on AWS. We publish an AWS Vagrant box for use with our own CI systems only. We may stop publishing AWS boxes in the future. That said, AWS will work as long as you **do not use the provided scripts (such as `start-osx.sh`)**. With your AWS credentials set in your shell environment, run:

```
vagrant up --provider=aws
```

Note that resolution for the `X.X.X.X.xip.io` domain is flakey for us, and occasionally results in errors. To get around this, we run dnsmasq on our CI boxes.

(This also answers issue #52. Please avoid opening multiple issues for the question.)

**Comment by mdcarlson** [comment]
I think this would make an excellent addition to the FAQ.

> We do not support running PCF Dev on AWS. We publish an AWS Vagrant box for use with our own CI systems only. We may stop publishing AWS boxes in the future.
