### ISSUE TITLE
pcfdev fails to start all services with AWS provider

### ISSUE THREAD

**Issue by mdcarlson** [vmware-archive/pcfdev#52]
Started pcfdev using start-osx script after modifying the start command to specify `--provider=aws` and confirming required environment variables were populated.

VM is created successfully and provisioning script is started.

46 of 48 services are started successfully, but after hours, the remaining two have not started.
Command `cf api <public DNS name> --skip-ssl-validation` fails with a 404 error

Gist:  https://gist.github.com/mdcarlson/ff9fb0cadc665271c6cb703a2491dfab#file-pcfdev-console-log-txt 

Monit summary on the AWS pcfdev instance shows that `cf-mysql-broker` and `quota-enforcer` were in a `not monitored` state.  MySQL appears to be failing to start due to an error attempting to connect to the mysql-_broker at `mysql.local.pcfdev.io` in the `mysql-broker-dbcreate` and `mysql-broker-dbmigrate` scripts.

**Comment by sclevine** [comment]
Addressed in #51.
