### ISSUE TITLE
Redis Service

### ISSUE THREAD

**Issue by ryanjbaxter** [vmware-archive/pcfdev#54]
Is there a limit to the number of connections that can be made to the Redis service in PCFDev?  If so is this configurable?

**Comment by sclevine** [comment]
The maximum number of connected clients (`maxclients`) is 10,000.

While we don't officially support changing this, it should be configurable in `/var/vcap/jobs/cf-redis-broker/config/redis.conf` in the VM. You can login to the VM with `vagrant ssh`.

**Comment by ryanjbaxter** [comment]
@sclevine thanks.  I was seeing one client connect and the other fail, I will have to investigate further.
