### ISSUE TITLE
Linux - Number of CPUs used is inefficient

### ISSUE THREAD

**Issue by lummie** [vmware-archive/pcfdev#55]
uniq removes sequentially duplicated lines, therefore input needs sorting first to achieve a unique count. 
Optimum vcpu number in vm should not include hyperthread cpu therefore calculation should be physical cpus \* cores on each cpu 
e.g. I have 2 x 8 core CPUs (hyperthreaded too) currently returns 32, should be 16.

**Comment by sclevine** [comment]
This makes sense, we intended to exclude hyperthreaded CPUs with the `uniq` logic. Let's discuss this in #56.
