### ISSUE TITLE
Not able to login in PCF Dev.  Server error, status code: 403, error code: 0,

### ISSUE THREAD

**Issue by periz** [vmware-archive/pcfdev#58]
PCF Dev has reserved 3 GB out of 7 GB total system memory.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'pcfdev/pcfdev' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Waiting for services to start...
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 38 out of 48 running
==> default: 48 out of 48 running
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
PS C:\00PCE5COB\PCF\pcfdev-v0.15.0> cf api api.local.pcfdev.io --skip-ssl-validation
Setting api endpoint to api.local.pcfdev.io...
FAILED
Server error, status code: 403, error code: 0, message:

**Comment by sclevine** [comment]
Hi @periz,

Looks like the VM failed to start successfully:

```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Can you `vagrant ssh` into the machine and provide us the contents of `/var/pcfdev/run.log`?
We recommend running PCF Dev with at least 4 GB of free memory. Can you tear down your VM, free up 4 GB of memory, and run the following before starting it again:

```
>> $env:VM_MEMORY = 4096
```

Other questions:
1. Do you require a proxy to access the internet?
2. Are you attempting to start PCF Dev without an internet connection?
3. Does api.local.pcfdev.io resolve to `192.168.11.11` for you?

**Comment by periz** [comment]
I resolved this issue. It is a issue with the DNS. I run PCF Dev ofline.

**Comment by sclevine** [comment]
(Resolved)

**Comment by periz** [comment]
hi @sclevine,
If i run behind corporate proxy still i am getting the error. Help me to resolve it.
