### ISSUE TITLE
No service offerings found

### ISSUE THREAD

**Issue by p-r-o-m-e-t-h-e-u-s** [vmware-archive/pcfdev#59]
When I use `cf marketplace` i get `No service offerings found`. Same issue with `cf services`.

I expect to have rabbitmq, mysql and redis running - the processes for this services are all running and the ports are also opened / working.

The only problem I see i that pcfdev is not offering this as a service. Any idea?

> I'm using version 0.15.0 from pivotal.io

**Comment by sclevine** [comment]
Hi @real-prometheus,

`cf marketplace` should definitely show those services. `cf services` only shows service instances (which you have to create from the marketplace services).

Can you provide the output of the start script / `vagrant up`?

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
Hi @sclevine,

sure - `cf push` works pretty much, despite the facts that it couldn't complete the script. How can I send you the verbose output? It would extend the comment area here.

By the way, I got the same issue on OS X and Windows.

> PCF Dev has reserved 4 GB out of 16 GB total system memory.
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Checking if box 'pcfdev/pcfdev' is up to date...
> ==> default: Clearing any previously set forwarded ports...
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
>     default: Adapter 2: hostly
> ==> default: Forwarding ports...
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: vagrant
>     default: SSH auth method: private key
> ==> default: Machine booted and ready!
> ==> default: Checking for guest additions in VM...
> ==> default: Configuring and enabling network interfaces...
> ==> default: Configuring proxy for Apt...
> ==> default: Configuring proxy environment variables...
> ==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
> ==> default: flag to force provisioning. Provisioners marked to run always will still run.
> ==> default: Running provisioner: shell...
>     default: Running: inline script
> ==> default: stdin: is not a tty
> ==> default: Waiting for services to start...
> ==> default: 0 out of 48 running
> ==> default: 0 out of 48 running
> ==> default: 0 out of 48 running
> ==> default: 0 out of 48 running
> ==> default: 32 out of 48 running
> ==> default: 48 out of 48 running
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
Here is the last part of the --debug output.

> .....
> ==> default: 48 out of 48 running
> DEBUG ssh: Sending SSH keep-alive...
> DEBUG ssh: Exit status: 1
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Calling recover: #VagrantPlugins::ProxyConf::Action::OnlyOnce:0x00000102b10938
>  INFO warden: Beginning recovery process...
>  INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x0000010216b478
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Recovery complete.
>  INFO warden: Calling recover: #Vagrant::Action::Builtin::HandleForwardedPortCollisions:0x00000102bba028
>  INFO warden: Calling recover: #VagrantPlugins::ProxyConf::Action::OnlyOnce:0x00000102bba0a0
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x000001019cbd30
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x00000100a7a2a0
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x00000101ac2680
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x0000010293c418
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x0000010293c490
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
> ERROR warden: Error occurred: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO warden: Beginning recovery process...
>  INFO warden: Recovery complete.
>  INFO environment: Released process lock: machine-action-a11de5a7a17f03f44d04644e64ca1092
>  INFO environment: Running hook: environment_unload
>  INFO runner: Preparing hooks for middleware sequence...
>  INFO runner: 2 hooks defined.
>  INFO runner: Running action: environment_unload #Vagrant::Action::Builder:0x00000101c865e8
> ERROR vagrant: Vagrant experienced an error! Details:
> ERROR vagrant: #<Vagrant::Errors::VagrantError: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.>
> ERROR vagrant: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
> ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:236:in `execute'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/shell/provisioner.rb:86:in`block (2 levels) in provision_ssh'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/shell/provisioner.rb:60:in `tap'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/shell/provisioner.rb:60:in`block in provision_ssh'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/shell/provisioner.rb:220:in `with_script_file'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/shell/provisioner.rb:58:in`provision_ssh'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/shell/provisioner.rb:24:in `provision'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:133:in`run_provisioner'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in`block in finalize_action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in`block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in`run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:473:in `hook'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:121:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:121:in `block in call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:103:in`each'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:103:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/set_name.rb:19:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in`busy'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in`block in finalize_action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in`block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in`run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in`busy'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_check_outdated.rb:78:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in`block in finalize_action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in`busy'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in`block in finalize_action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in`busy'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in`call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in`busy'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in`action_raw'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in`lock'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in`action'
> /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
>  INFO interface: error: The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**Comment by sclevine** [comment]
Looks like the VM failed to start successfully:

```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Can you `vagrant ssh` into the machine and provide us with the contents of `/var/pcfdev/run.log`?

Do you require a proxy to access the internet? I see references to the vagrant-proxyconf plugin in the debug output. If you have `HTTP_PROXY` or `HTTPS_PROXY` set, the VM will attempt to use them.

Are you attempting to start PCF Dev without an internet connection?

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
Yes - I'm behind a company proxy. Therefore I'm running CNTLM locally (cascading) on my Mac to access the internet. The proxy is on localhost 3128. 

The VM has also set 

> declare -x http_proxy="http://localhost:3128/"
> declare -x https_proxy="http://localhost:3128/"

but I guess the proxy config in the Vagrant file is not set! Therefore the internet connection won't work.
This may be the issue. Last statement in`/var/pcfdev/run.log` is

> Creating security group http_proxy as admin
> FAILED
> Server error, status code: 400, error code: 300001, message: The security group is invalid: rules rule number 1 contains invalid destination

**Comment by sclevine** [comment]
You only need to set those in the shell you use to start the VM. You shouldn't need to modify the Vagrantfile. See http://docs.pivotal.io/pcf-dev/proxy.html.

That said, you're `localhost` proxy is probably not going to work, because it will refer to the VM inside of the VM. Instead, use `host.pcfdev.io`.

Also, is there any related output above that statement in `run.log`?

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
Ok, I had a look inside the Vagrant file and now I understand the problem...

But from my view, this is an issue in the proxy configuration in the vagrant file. My host shell points to the outgoing proxy `localhost:3128`. This is required to provide internet connection for all command line tools like wget, curl, ...

The Vagrant file has the following proxy settings

> config.proxy.http = ENV["HTTP_PROXY"] || ENV["http_proxy"]
> config.proxy.https = ENV["HTTPS_PROXY"] || ENV["https_proxy"]

These settings are exposed to the vm, what is wrong. The http_proxy / https_proxy is only relevant for the host, not the guest system. Therefor the proxy calls inside the guest must be rooted to the host-settings.

I guess - your idea was, use the same proxy settings for host and guest, what is wrong by using the proxy plugin. The plugin exposes the port automatically and injects the env variable.

The simple solution is using

> config.proxy.http = ENV["PCFDEV_IP"] || "192.168.11.11"
> config.proxy.https = ENV["PCFDEV_IP"] || "192.168.11.11"

which should work under all circumstances (and works now on my system under OS X and Windows).

What do you think?

**Comment by sclevine** [comment]
> The http_proxy / https_proxy is only relevant for the host, not the guest system. 

This is actually not true. The guest VM needs to use the same HTTP proxy settings as the host (for example, so that apps can make outbound connections to HTTP services, or for Garden to pull Docker images).

> The simple solution is using
> 
> > config.proxy.http = ENV["PCFDEV_IP"] || "192.168.11.11"
> > config.proxy.https = ENV["PCFDEV_IP"] || "192.168.11.11"

This would set the proxy to the guest VM IP address, which is not running a proxy. This will prevent various applications running inside the guest VM from accessing HTTP services. You'll be able to start the guest VM successfully (because the security group it creates on boot doesn't have `localhost` in it like it did before), but a number of things will be broken.

The real issue is that it is not possible for the guest VM to access services bound to the localhost interface on the host. The localhost interface on the host is actually entirely un-routable from the guest VM. There is no way for processes running in the guest VM to connect to `localhost:3128`.

To get around this, make sure your proxy is listening on all interfaces (including `192.168.11.1`), and set your proxy settings as such before you start the VM:

```
export http_proxy="http://host.pcfdev.io:3128/"
export https_proxy="http://host.pcfdev.io:3128/"
```

(`host.pcfdev.io` conveniently resolves to 192.168.11.1 for exactly this type of issue.)

If this prevents you from downloading the box the first time you start the VM (because Virtualbox hasn't created the `192.168.11.1` subnet yet), you could use the following instead:

```
export http_proxy="http://<your-workstation-ip>:3128/"
export https_proxy="http://<your-workstation-ip>:3128/"
```

(as your workstation's IP address should always be routable from both the VM and the host)

Hope this helps!

-Stephen

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
Hi Stephen,

you're right - settings to http_proxy to "_192.168.11.11_" won't work if you doesn't have a local proxy running, but it works pretty good when I'm running **cntlm** or **fiddler**. The daemon is listing on all interfaces.

This would work....

```
export http_proxy="http://<your-workstation-ip>:3128/"
export https_proxy="http://<your-workstation-ip>:3128/"
```

... but it looks like a workaround, because usually the users get their ip's via dhcp and the ip may change. Therefore **localhost** is more suitable.

Don't get me wrong, thankfully it works now on my machine. I just wonder whether there is a more generic solution to prevent other people running into this. In an enterprise network infrastructure it's very common to have very restricted policies, which the users try to simplify by running a local proxy instead for their tools.

An idea could be to check the http(s)_proxy variable at the start script for a string like **localhost** or **127.0.0.1** and change it to **host.pcfdev.io**.

**Comment by sclevine** [comment]
Again, `192.168.11.11` is the IP of the guest VM, so unless you're running cntlm or fiddler inside the guest VM itself, your apps are not going to be able to make outbound HTTP requests, and you won't be able to pull Docker images. For example:

```
cf push test-app -o cloudfoundry/lattice-app
```

probably won't work for you.

(We'll eventually have a solution soon that will translate `localhost` to `host.pcfdev.io` and setup the `192.168.11.1` subnet before downloading the OVA.)

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
I guess it works flawless (see output below).

I've set the proxy to my internal host ip - not to the guest vm. This ip is only available inside the guest VM.

Sorry for creating confusion.

Guest VM shows:

```
declare -x http_proxy="http://10.0.2.2:3128"
declare -x https_proxy="http://10.0.2.2:3128"
```

So **localhost** should be somehow translate to the internal host IP provided by vagrant.
Glad to hear that you are working on a solution.

**Output:**

> cf push test-app -o cloudfoundry/lattice-app

```
vagrant@agent-id-pcfdev-0:~$ cf push test-app -o cloudfoundry/lattice-app
Updating app test-app in org pcfdev-org / space pcfdev-space as admin...
OK


Starting app test-app in org pcfdev-org / space pcfdev-space as admin...
Creating container
Successfully created container
Staging...
Staging process started ...
Staging process finished
Exit status 0
Staging Complete

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App test-app was started using this command `/lattice-app `

Showing health and status for app test-app in org pcfdev-org / space pcfdev-space as admin...
OK

requested state: started
instances: 1/1
usage: 256M x 1 instances
urls: test-app.local.pcfdev.io
last uploaded: Thu May 12 16:50:52 UTC 2016
stack: unknown
buildpack: unknown

     state     since                    cpu    memory      disk        details
#0   running   2016-05-12 04:51:36 PM   0.0%   0 of 256M   0 of 512M
```

**Comment by jurjevic** [comment]
+1 Thx. This thread helped me out!
