### ISSUE TITLE
Not able to access the https://api.local.pcfdev.io/ in browser. Shows the below responce.

### ISSUE THREAD

**Issue by periz** [vmware-archive/pcfdev#60]
{
  "code": 10000,
  "description": "Unknown request",
  "error_code": "CF-NotFound"
}

**Comment by Turbots** [comment]
Mmm strange, how much Memory do you have? You need 4Gb of **free ram** to be safe...

Can you `vagrant ssh` into the machine and provide us the contents of `/var/pcfdev/run.log`?

**Comment by sclevine** [comment]
@periz,

Were you able to resolve issue #58 then?

The output you're providing is the expected response from Cloud Controller when you hit it with a browser. If you're looking for Apps Manager, we do not yet provide it with PCF Dev. You must use the `cf` CLI to manage your apps and services.

-Stephen

**Comment by periz** [comment]
Thanks stephen.
