### ISSUE TITLE
DEVELOP.md

### ISSUE THREAD

**Issue by lummie** [vmware-archive/pcfdev#61]
Can you please add 
- Go (and the min version) 
- jq (and the min version) 
  to the dependencies for building.

Also aws is required (even if you are not building for AWS e.g. build -only=virtualbox-iso)

**Comment by sclevine** [comment]
Hi @lummie,

Sorry for the delay. This will get merged in from [here](https://github.com/pivotal-cf/pcfdev/blob/cli-docs-updates/DEVELOP.md) before the next release.
