### ISSUE TITLE
Support an offline mode

### ISSUE THREAD

**Issue by mminella** [vmware-archive/pcfdev#63]
pcfDev is a great tool for development and testing against new PCF features.  However, the requirement for an internet connection can be cumbersome at times (demos at client sites/conferences for example).  I'm open to setting up a local DNS (I believe lattice had that option) if documented.  However, the ability to use pcfDev in an offline mode would be extremely useful.

**Comment by sclevine** [comment]
Check out: https://docs.pivotal.io/pcf-dev/work-offline.html

Let me know if that works for you!

-Stephen

**Comment by sergiubodiu** [comment]
To send only .local.pcfdev.io queries to Dnsmasq you need to make changes to resolver

sudo tee /etc/resolver/io.pcfdev.local >/dev/null <<EOF
nameserver 127.0.0.1
EOF
