### ISSUE TITLE
Error performing request: Get http://local.pcfdev.io/v2/info: dial tcp 192.168.11.11:80: getsockopt: connection refused

### ISSUE THREAD

**Issue by jaikanthm** [vmware-archive/pcfdev#65]
Am using a windows machine and I am currently in a corporate network. I downloaded the pcfdev vagrant box directly and deployed using windows shell script and vagrant up. I am able to putty inside the box ip 192.168.11.11 . But am unable to do a CF Login and set the end point either to local.pcfdev.io or api.local.pcfdev.io...
I even tried using acrylic but no go...
CF Cli version - 6.18
CF version - cf version 6.16.1+924508c-2016-02-26
API endpoint> local.pcfdev.io
FAILED
Error performing request: Get http://local.pcfdev.io/v2/info: dial tcp 192.168.11.11:80: getsockopt: connection refused
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

**Comment by sclevine** [comment]
Hi @jaikanthm,

You must use the Vagrantfile from the [Pivotal Network](https://network.pivotal.io/) to use the PCF Dev box on Atlas. It will not work without it.

-Stephen

**Comment by jaikanthm** [comment]
Hi @sclevine 
Thnks for the response. Am using the vagrant file from pivotal netwrk only. I have edited only the below lines in the vagrant file rest everything is the same.

config.vm.box = "pcfdev"
  config.vm.box_url = ["file:///C:/Users/mjt5kor/Documents/pcfdev-v0.15.0/pcfdev-virtualbox-0.80.0.box"]
  config.vm.synced_folder ".", "/vagrant", disabled: true

**Comment by jaikanthm** [comment]
When i run the powershell script below is the output i get. 
Strange that i use the same vagrant file that i downloaded along with the pcfdev zip. 
The only line modified was the "
  config.vm.box = "pcfdev" so that the base box will be imported from my local system

PS C:\Users\mjt5kor\Documents\pcfdev-v0.15.0\pcfdev-v0.15.0(2)\pcfdev-v0.15.0> .\start-windows.ps1
PCF Dev has reserved 3 GB out of 7 GB total system memory.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'pcfdev'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: pcfdev-v0150_default_1464073271961_76578
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Please use a Vagrantfile from PivNet to start the commercial version of PCF Dev.

**Comment by sclevine** [comment]
Hi @jaikanthm,

You are attempting to use a newer, un-released version of PCF Dev. Please use the unmodified Vagrantfile from PivNet.

Not all box versions published to Atlas work -- they are only candidates for release. We understand that this is confusing for some users who might assume the latest release on Atlas is an official release of PCF Dev. We are moving off of Atlas entirely very soon.

-Stephen

**Comment by jaikanthm** [comment]
Hi @sclevine 
That is one of the things am doing wrongly instead of pcfdev 0.66 I was trying to use pcfdev 0.80 thinking that it was latest version. Since am in a corporate network i am unable to do a vagrant up using the vagrant file from Pivnet as it errors out "The box 'pcfdev/pcfdev' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas"... But i am able to download using the link https://atlas.hashicorp.com/pcfdev/boxes/pcfdev/versions/0.66.0/providers/virtualbox.box... Can i point the vagrant file to use the downloaded 0.66 box locally

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'pcfdev/pcfdev' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 0.66.0
The box 'pcfdev/pcfdev' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

**Comment by sclevine** [comment]
Hi @jaikanthm,

If you're behind a corporate proxy, you can set your environment up to allow Vagrant to download the box. If you don't do this, a number of features that require internet access from inside the VM (such as pushing Docker images) will not work. See: http://docs.pivotal.io/pcf-dev/proxy.html

If you really want to use the box you've already downloaded, set

``` ruby
config.vm.box_version = "0"
```

and add the box with

``` ruby
$ vagrant box add --force <path-to-box-file> --name pcfdev/pcfdev
```

**Comment by warmchang** [comment]
@jaikanthm  A few days ago I met this problem, and finally solved it.

The steps are as follows:

1.modify the Vagrantfile as follow:

```
  config.vm.box = "pcfdev"
  # config.vm.box_version = "0.66.0"
```

2.add the box (the final official release is pcfdev-v0.15.0, and be sure you download the pcfdev box version is 0.66.0, you can download it from https://atlas.hashicorp.com/pcfdev/boxes/pcfdev/versions/0.60.0/providers/virtualbox.box):

```
vagrant box add pcfdev pcfdev-virtualbox-0.66.0.box
```

3.check success added the box: 

```
PS C:\cf\pcfdev-v0.15.0> vagrant box list
pcfdev  (virtualbox, 0)
```

4.run the powershell script:

```
PS C:\cf\pcfdev-v0.15.0> .\start-windows.ps1
```

or run vagrant up directlly, then you can see:

```
...
==> default: Waiting for services to start...
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 3 out of 48 running
==> default: 48 out of 48 running
==> default: PCF Dev is now running.
==> default: To begin using PCF Dev, please run:
==> default:    cf login -a api.local.pcfdev.io --skip-ssl-validation
==> default: Email: admin
==> default: Password: admin
PS C:\cf\pcfdev-v0.15.0>
```

**Comment by jaikanthm** [comment]
Thanks @sclevine and @warmchang  issue is resolved

**Comment by gsainagendraprasad** [comment]
@sclevine  , 

i am getting this similar issue:
C:\Users\SGUNTURU>cf dev start
Using existing image.
Starting VM...
←[31;1mFAILED←[0m
Error: failed to start VM: failed to execute 'C:\Work\CloudPOC\VBoxManage startv
m pcfdev-v0.461.0 --type headless': exit status 1: Waiting for VM "pcfdev-v0.461
.0" to power on...
VM "pcfdev-v0.461.0" has been successfully started.

C:\Users\SGUNTURU>cf login -a api.local.pcfdev.io --skip-ssl-validation
API endpoint: api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.
168.11.11:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_pr
oxy environment variable is correctly set. Else, check your network connection.
