### ISSUE TITLE
SSL Read Error on box download after running start-osx

### ISSUE THREAD

**Issue by gregsimons** [vmware-archive/pcfdev#66]
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
SSL read: error:00000000:lib(0):func(0):reason(0), errno 60

The above error message was reported during download of the box image. Is there an alternative to swap to http or command line args? Perhaps an additional configuration option for start-osx?

This is also on a mac with el captain and the latest updates installed.

**Comment by Turbots** [comment]
Have you tried it a second time already? The box can take a while to download and if it gets interrupted, it gets handled poorly atm, but if your network is fine and stable enough, it should work when you try again. Can't help you much beyond that, @sclevine might have a better answer for you ✌️

**Comment by gregsimons** [comment]
yea on third attempt it was successful as I suspected it was network problems.

I did also attempt downloading the box separately and adding to vagrant but it still attempted a new download.

I think perhaps the network interruption handing was perhaps the main reason for my issue report.

**Comment by sclevine** [comment]
This is one of many issues that will be addressed when we release our cf CLI plugin to replace Vagrant. Feel free to re-open if you're still having issues.
