### ISSUE TITLE
STOMP Plugin is not enabled on RabbitMQ

### ISSUE THREAD

**Issue by daveburnsLIT** [vmware-archive/pcfdev#67]
I've been trying to setup the Spring websocket broker in PCF dev but only the amqp ports seem to work. I need STOMP enabled but from the service JSON it doesn't seem to be there (only amqp/5672 and http to management 15672) Is there a way to manually do this? 

Also tried ssh to vagrant and logging in as vcap but couldn't run the rabbitmq-plugin enabled stomp command as the env wasn't set correctly (could find a profile to fix this).

**Comment by mdelillo** [comment]
Hi @daveburnsLIT,

STOMP is not enabled by default but you are correct that you can use the `rabbitmq-plugins` command to enable it from inside of the VM. You can log in as root and run the following:

```
root@agent-id-pcfdev-0:~# export PATH=/var/vcap/packages/erlang/bin:/var/vcap/packages/rabbitmq-server/bin:$PATH
root@agent-id-pcfdev-0:~# rabbitmq-plugins enable <plugin>
```

I haven't tested it out, but you'll probably need to enable `rabbitmq_stomp` and/or `rabbitmq_web_stomp`.

**Comment by sclevine** [comment]
@daveburnsLIT Did this address your issue?

**Comment by sclevine** [comment]
Closing for now, feel free to re-open if this doesn't fix your issue. We've prioritized a story about enabling default PCF RabbitMQ plugins on boot.
