### ISSUE TITLE
enabling private docker registries on pcfdev

### ISSUE THREAD

**Issue by jyidiego** [vmware-archive/pcfdev#69]
How do I enable private docker registries on pcfdev?

**Comment by sclevine** [comment]
Hi @jyidiego,

Sorry for the delay. We do not yet support private docker registries, but we expect to soon.

In the meantime, if you `vagrant ssh` to the VM and get root access with `sudo su -`, you can modify `/var/vcap/jobs/garden/bin/garden_ctl` to pass `-insecureDockerRegistry` to garden for each registry you want to allow. See https://github.com/cloudfoundry-incubator/garden-linux-release/blob/develop/jobs/garden/templates/garden_ctl.erb#L159.

Hope this helps,
Stephen

**Comment by jyidiego** [comment]
Hi Stephen,

Thanks for that. Always interesting to see how the sausage is made.

John
