### ISSUE TITLE
ssh false

### ISSUE THREAD

**Issue by thesynapses** [vmware-archive/pcfdev#71]
Vagrant file might need additional line:
config.ssh.insert_key = false

**Comment by sclevine** [comment]
Hi @thesynapses,

Why is this necessary for you? Do you get an error message without it? `config.ssh.insert_key` replaces the default Vagrant SSH key with a more secure key when you `vagrant up`.

-Stephen

**Comment by thesynapses** [comment]
Yes. When I tried to run PCF DEV it threw up ssh errors. Once I put this
line in, the ssh error stopped and vagrant could login to PCF..

tx.

-Sureel

On Wed, Jun 8, 2016 at 10:13 AM, Stephen Levine notifications@github.com
wrote:

> Hi @thesynapses https://github.com/thesynapses,
> 
> Why is this necessary for you? Do you get an error message without it?
> config.ssh.insert_key replaces the default Vagrant SSH key with a more
> secure key when you vagrant up.
> 
> -Stephen
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/pivotal-cf/pcfdev/issues/71#issuecomment-224602150,
> or mute the thread
> https://github.com/notifications/unsubscribe/AH9Asrz1IiMRobrUotI3iOPZlm8hM0Zjks5qJs4ngaJpZM4IujXy
> .

## 

----------*-----------
This email and any attachments are confidential and intended only for the 
individual(s) named. If you are not the named addressee or have received 
this email by mistake, please (a) notify the sender, and (b) delete this 
email immediately without distributing or retaining.
The sender does not accept liability for any errors or omissions in the 
contents of this message, which arise as a result of e-mail transmission.

Any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of the organization. Our 
employees, contractors & students are expressly required not to infringe on 
copyright or any other law. Any such communication is contrary to company 
policy and outside the scope of his/her engagement with the company. iLEAD, 
Crinis or Synapse will not accept any liability in respect of such 
communication, and he/she will be personally responsible and liable for any 
damages.

**Comment by sclevine** [comment]
Could you provide the errors that you see, along with the rest of the output from running the distribution script for you platform? No one else has reported this issue.

**Comment by thesynapses** [comment]
I ran again and it works. Must have been some corruption in my key. I will keep an eye out. If it occurs again will report. 
ThanksSureel

On Wed, Jun 8, 2016 at 1:58 PM -0400, "Stephen Levine" notifications@github.com wrote:

Could you provide the errors that you see, along with the rest of the output from running the distribution script for you platform? No one else has reported this issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

## 

----------*-----------
This email and any attachments are confidential and intended only for the 
individual(s) named. If you are not the named addressee or have received 
this email by mistake, please (a) notify the sender, and (b) delete this 
email immediately without distributing or retaining.
The sender does not accept liability for any errors or omissions in the 
contents of this message, which arise as a result of e-mail transmission.

Any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of the organization. Our 
employees, contractors & students are expressly required not to infringe on 
copyright or any other law. Any such communication is contrary to company 
policy and outside the scope of his/her engagement with the company. iLEAD, 
Crinis or Synapse will not accept any liability in respect of such 
communication, and he/she will be personally responsible and liable for any 
damages.

**Comment by sclevine** [comment]
Thanks @thesynapses, feel free to re-open if you see it again.
