### ISSUE TITLE
cf login return server error 504

### ISSUE THREAD

**Issue by xtrycatchx** [vmware-archive/pcfdev#73]
Environment is Windows 7 64bit

Executing .\start-windows.ps1 returns this:

```
PCF Dev has reserved 4 GB out of 15 GB total system memory.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'pcfdev/pcfdev'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'pcfdev/pcfdev' is up to date...
==> default: Setting the name of the VM: pcfdev-v0150_default_1465524584063_15746
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Waiting for services to start...
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 0 out of 48 running
==> default: 20 out of 48 running
==> default: 30 out of 48 running
==> default: 48 out of 48 running
==> default: PCF Dev is now running.
==> default: To begin using PCF Dev, please run:
==> default:    cf login -a api.local.pcfdev.io --skip-ssl-validation
==> default: Email: admin
==> default: Password: admin
```

however, doing a cf login, i encountered server error 504

```
  cf login -a api.local.pcfdev.io --skip-ssl-validation
  API endpoint: api.local.pcfdev.io
  FAILED
  Server error, status code: 504, error code: 0, message:
```

FACTS:
i started pcfdev in powershell
i executed cf login in command prompt
can SSH to pcfdev

Feel free to let me know what else is needed. Thanks

**Comment by sclevine** [comment]
Hi @xtrycatchx,

What version of the cf CLI are you running? (run: `cf version`)

**Comment by xtrycatchx** [comment]
hi @sclevine , my apologies for the late reply (went offgrid over the weekend)
anyways, my CLI version is `cf version 6.16.1+924508c-2016-02-26`

**Comment by sclevine** [comment]
Do you require an HTTP/HTTPS proxy to access the internet?
Also, could you try out PCF Dev 0.16.0, and report if this error persists?

**Comment by xtrycatchx** [comment]
hi @sclevine, yes I need HTTP/HTTPS proxy to access internet. 

With regards to PCF Dev 0.16.0, may i know what is needed for me to run the windows installer? The release packaging seems different from previous 0.15.0 which has the guide i followed

**Comment by sclevine** [comment]
Installation instructions, as well as instructions for running PCF Dev if you require an HTTP/HTTPS proxy to access the internet, are available here: https://docs.pivotal.io/pcf-dev/

**Comment by xtrycatchx** [comment]
thanks @sclevine , unfortunately after i tried cf dev start i encountered this error:

> Using existing image
> Allocating 4096 MB out of 16270 MB total system memory (9879 MB free).
> Importing VM...
> Starting VM...
> Provisioning VM...
> Waiting for services to start...
> 8 out of 49 running
> 8 out of 49 running
> 49 out of 49 running
> FAILED
> Error: failed to provision VM: Process exited with: 1. Reason was:  ()

**Comment by sclevine** [comment]
Can you describe how you've set your proxy environment variables (with the specific domain/ip redacted)?

Also, could you run `ssh vcap@ssh.local.pcfdev.io` (password is `vcap`) and provide the output of `cat /var/pcfdev/run.log`? Please redact any sensitive information about your environment from this output.

**Comment by sclevine** [comment]
Hi @xtrycatchx,

Are you still experiencing these issues? Have you tried 0.17.0?

Thanks,
Stephen

**Comment by xtrycatchx** [comment]
hi @sclevine sorry for the my late reply. We switched to using bosh-lite for now and its working fine. I havent tried back using pcfdev again. maybe we can close the issue and reopen it or i'll create a new once i encounter the same problem? thanks a lot.

**Comment by sclevine** [comment]
0.18.0 likely fixes this issue. Closing for now, but feel free to re-open if you try out PCF Dev again and continue to experience this issue.
