### ISSUE TITLE
pcfdev setup fails under Windows 7

### ISSUE THREAD

**Issue by mrumpf** [vmware-archive/pcfdev#77]
When I run the binary distribution from Pivotal network under Windows 7 I get the following error:

```
C:\Users\mrumpf\Downloads\pcfdev-v0.16.0-windows>pcfdev-v0.16.0-windows.exe
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x93a720, 0xc082002040)
        /usr/local/go/src/runtime/panic.go:481 +0x3f4
github.com/pivotal-cf/pcfdev-cli/vendor/github.com/cloudfoundry/cli/plugin.Start
(0x33a5098, 0xc08206b200)
        /ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/vendor/github.com/cloudfo
undry/cli/plugin/plugin_shim.go:16 +0x494
main.main()
        /ext-go/1/src/github.com/pivotal-cf/pcfdev-cli/main.go:76 +0xd51
```

PCFDev 0.15 setup was working fine.

**Comment by sclevine** [comment]
Hi @mrumpf,

PCF Dev is now a cf CLI plugin. You need to install it with `cf install-plugin pcfdev-v0.16.0-windows.exe`.

See the getting started tutorial: https://pivotal.io/platform/pcf-tutorials/getting-started-with-pivotal-cloud-foundry-dev/install-pcf-dev
Or the docs: https://docs.pivotal.io/pcf-dev/

(We will eventually run `cf install-plugin` for you when you run the plugin directly, to reduce confusion.)

**Comment by mrumpf** [comment]
Hm, I was confused by the extenions "exe"...

Here is what I get now:

```
{ pcfdev-v0.16.0-windows }  » cf install-plugin ./pcfdev-v0.16.0-windows.exe

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin ./pcfdev-v0.16.0-windows.exe? (y or n)> y

Installing plugin pcfdev-v0.16.0-windows.exe...
OK
Plugin pcfdev v0.0.0 successfully installed.
{ pcfdev-v0.16.0-windows }  » cf dev start
Please retrieve your Pivotal Network API from:
https://network.pivotal.io/users/dashboard/edit-profile
FAILED
Error: invalid Pivotal Network API token
```

I think that is a corporate proxy issue. I have the proxyies in my environment:

```
{ pcfdev-v0.16.0-windows }  » echo $http_proxy
http://10.206.246.20:8080
{ pcfdev-v0.16.0-windows }  » echo $https_proxy
http://10.206.246.20:8080
```

I have the proxy configured like described here:
https://docs.cloudfoundry.org/cf-cli/http-proxy.html

**Comment by sclevine** [comment]
Did you copy and paste your API token from PivNet? The `Invalid Pivotal Network API token` error implies a successful connection to PivNet with an invalid token.  We've seen occasional issues with the Windows DOS command line and cf CLI password-type prompts, so use PowerShell if you aren't already.

**Comment by mrumpf** [comment]
ok. It seems to work under PowerShell: I was using Cygwin bash before.

```
PS C:\Users\mrumpf\Downloads\pcfdev-v0.16.0-windows> cf install-plugin pcfdev-v0.16.0-windows.exe

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.*
*

Do you want to install the plugin pcfdev-v0.16.0-windows.exe? (y or n)> y

Installing plugin pcfdev-v0.16.0-windows.exe...
OK
Plugin pcfdev v0.0.0 successfully installed.
PS C:\Users\mrumpf\Downloads\pcfdev-v0.16.0-windows> cf dev start
Please retrieve your Pivotal Network API from:
https://network.pivotal.io/users/dashboard/edit-profile

API token>
BETA SOFTWARE END USER LICENSE AGREEMENT
...
Last Updated: April 14th, 2014

Accept (yes/no):> yes
Downloading VM...
Progress: |=>                   | 1%
```

You could reduce confusion if you mention
- that under Windows PowerShell should be used
- Where to find the API token
