### ISSUE TITLE
Can't find source for Cloud Foundry CLI Plugin

### ISSUE THREAD

**Issue by mar1ged** [vmware-archive/pcfdev#84]
I wanted to learn more about this plugin in order to perhaps find either the reason for [another issue](https://github.com/pivotal-cf/pcfdev/issues/82) or at least learn something.

But unfortunately I did not find the go sourcecode although I even downloaded the whole project and searched offline. Is the plugin part of the pommercial part of pcf dev and closed source ?

**Comment by sclevine** [comment]
Hi @mar1ged,

The source code for the CLI plugin will be released soon. We're currently adding support for running OSS builds of PCF Dev using the plugin, and we plan to open source it as soon as we get that working.

Thanks,
Stephen

**Comment by mar1ged** [comment]
Thanks a lot, now I know that I was not blind ;-)
