### ISSUE TITLE
Add 'cf dev ssh' subcommand to plugin

### ISSUE THREAD

**Issue by tgreenyc** [vmware-archive/pcfdev#89]
Today it is possible to ssh directly to the VM using 192.168.11.11 with normal vagrant credentials, but it would make sense to add this directly to the plugin as well.

**Comment by sclevine** [comment]
Hi @tgreenyc,

This is on the roadmap, but it's a bit complicated because we can't rely on the presence of an OpenSSH client on Windows.

-Stephen

**Comment by tgreenyc** [comment]
I was thinking 'cf dev ssh' would give you access to the VM running the ERT.  Wouldn't you only have to worry about cross platform support on traditional 'cf ssh' subcommand (for AIs)?

**Comment by sclevine** [comment]
In either situation, you need a local client to make the SSH connection. On Windows, that local client may not be present. It's not hard to implement the local client in Go, but it's more work than shelling out to the OpenSSH client that's ubiquitous on Unix systems.

**Comment by tgreenyc** [comment]
Ahh ok, I see what you are saying now.  Thanks!

**Comment by sclevine** [comment]
This feature is now on the roadmap for 0.19.0.
