### ISSUE TITLE
I can't start pcfdev on my colleagues computer..

### ISSUE THREAD

**Issue by raptus93** [vmware-archive/pcfdev#90]
..and guys, I'm some kind of desperate.

The setup:
- VirtualBox 5.0.24
- behind a proxy
- Windows 7
- cf version 6.19.0
- pcfdev v0.17.0

What I do (in PowerShell, non-admin):

```
.\cf.exe
.\pcfdev-v0.17.0+PCF1.7.0-windows.exe
$env:HTTP_PROXY = "http://localhost:myPort"
$env:HTTPS_PROXY = "http://localhost:myPort"
.\cf dev start
```

What I get:

> Using existing image
> Allocating 4096 MB out of [trillions] MB total system memory ([trillions-4096] MB free).
> Importing VM...
> [here I get a uac prompt]
> FAILED
> PCF Dev is in an invalid state. Please run 'cf dev destroy'.

I can't find a way to get any more output or logs of what happened.
If I execute
`Test-Connection www.google.de`
I see, that my PowerShell can connect to the internet.

The strange thing is, that I have PCF Dev up and running the same way on my machine. So there must be a filthy little bug somewhere, I ran out of ideas what else I could check.

I'd appreciate any help!
Greets, Bob

**Comment by aemengo** [comment]
Hey @raptus93 We're a little unsure of your steps taken to reach this state. Have you attempted to run `cf dev destroy` as the prompt instructs? And then running `cf dev start` once more? If so, perhaps the full console output will help us debug further.

**Comment by sclevine** [comment]
Hi @raptus93,

Actually, the issue is that `localhost` (in reference to the host) cannot be used as an HTTP proxy from inside of the VM. Processes in the VM are attempting to connect to `myPort` on the VM itself, not the host.

To fix this, confirm that your local proxy is listening on all interfaces (or at least the appropriate `vboxnet` interface), and set your HTTP proxy settings to:

```
$env:HTTP_PROXY = "http://host.pcfdev.io:myPort"
$env:HTTPS_PROXY = "http://host.pcfdev.io:myPort"
```

(You could also use any routable IP that corresponds to the host. You may need to use `host2.pcfdev.io` if your VM is running on `local2.pcfdev.io`.)

**Comment by raptus93** [comment]
Hi @aemengo & @sclevine !

Sorry, but I bearly have any more details about "the full console output", because I already delivered all the output I got. I tried the cf dev destroy & cf dev start multiple times, but "turning off and turning on again" didn't work for me in this case.

@sclevine That is a great hint, thanks a lot! Setting the environment variables still does not work, I get the exact same 

> FAILED

response as above. I've tried to set both variables to:

> "http://host2.pcfdev.io:myPort"

and 

> The IP address of my ethernet adapter for LAN (the only non-192.168... if I ipconfig)

but that does not work either.

I have to admit that I do not fully understand what you are saying about the local proxy that is listening on all interfaces. I have Fiddler running, listening on myPort. That works perfectly for all my other applications. What else can I do? Do you have any idea to get any more output? The most random thing about this is: How on earth can pcfdev start properly on my machine (I mentioned, I'm working on my colleagues one right now) with the same setup (Proxy as localhost:3128). (I could login after deleting the EnvVars).

**Comment by sclevine** [comment]
I see, the `[here I get a uac prompt]` is Windows asking for some extra permissions.

I no longer think that your issue is proxy related. Can you provide the Virtualbox logs for the `pcfdev-*` VM? If you open Virtualbox, you can right-click on the VM and select `Show Log...`.

-Stephen

**Comment by raptus93** [comment]
Hey Stephen!

VirtualBox doesn't provide any logs for this VM (it searches in C:/Users/raptus93/.pcfdev/vms/pcfdev-v.0.136.0/Logs, but cannot find any).

**Comment by sclevine** [comment]
Are you able to use Virtualbox to start other (non-PCF Dev) VM?

**Comment by raptus93** [comment]
Hey Stephen!

I could start vagrant boxes, and therefore I thought, nothing could be wrong about my VirtualBox. Because of your hint I researched a little deeper in that direction, and found out, that VirtualBox behaved strange. After uninstalling and installing again VirtualBox (this times v.5.0.24) the cf dev start command finally works.

Conclusion: Try re-installing Virtual Box, if cf dev start fails after Importing VM...

Thanks a lot for the help!
