### ISSUE TITLE
cf dev start gets stuck at 48 services out of 50

### ISSUE THREAD

**Issue by MarcSolde** [vmware-archive/pcfdev#91]
So I'm working with a machine with 8 GB of RAM (which I think should be enough to run pcf dev) and I'm getting stucked at "48 out of 50 running" at the "Waiting for services to start..." stage. Is it supposed for the services to take longer than an hour to start?
I am, in theory, not behind any kind of proxy and I'm using the 5.0.20 version of Virtualbox and the lastest version of the CF CLI. 

Could you give me a helping hand?

Thanks,
Marc

EDIT: If I take a look at the VM, it's showing a login screen. Also, sorry if I make any kind of gramatical mistakes, since english is not my first language.
EDIT 2: I'm using Windows 10 64bits

**Comment by aemengo** [comment]
Hey @MarcSolde 

It definitely is not supposed to take a hour to start, or even more than 20 minutes.

We have reason to believe that you might have ran into a race condition with the VM starting. Please cancel the operation if not already, please run `cf dev destroy` and then `cf dev start` and tell us if this issue resurfaces. If it does, we can use more advanced troubleshooting methods.

**Comment by sclevine** [comment]
Hi @MarcSolde, 

Can you provide the full output of running `cf dev start` as well?

**Comment by MarcSolde** [comment]
@aemengo I already did that a couple of times before, but I tried once again and it worked. Since I've changed the network, maybe there was something wrong with the original one, I don't know.

@sclevine Now it works, so I don't really think it matters anymore :smile: . Anyway, thanks you both for the help!

EDIT: You can close the issue :+1:
