### ISSUE TITLE
Error dialing traffic controller server when starting a docker image

### ISSUE THREAD

**Issue by luckyabhishek** [vmware-archive/pcfdev#94]
I started a pcf dev instance using 0.17 plugin. 
After logging in using cf login I enabled the feature flag for docker 

`cf enable-feature-flag diego_docker`

I then try to start the lattice app using 
`cf push my-app -o cloudfoundry/lattice-app`
however this ends up in a wiered error 

```
Creating app my-app in org pcfdev-org / space pcfdev-space as admin...
OK

Creating route my-app.local.pcfdev.io...
OK

Binding my-app.local.pcfdev.io to my-app...
OK


Warning: error tailing logs
Error dialing traffic controller server: read tcp 192.168.11.1:64273->192.168.11.11:443: i/o timeout.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.local.pcfdev.io:443).
Starting app my-app in org pcfdev-org / space pcfdev-space as admin...

FAILED
Error restarting application: StagingError

TIP: use 'cf logs my-app --recent' for more information
```

I am behind a corporate proxy with all the proxy variables set correctly. From inside the VM I am able to curl any URL. So not really sure what's the IO timeout about. 

BTW the cf dev start didn't really return and is stuck at 

```
Please retrieve your Pivotal Network API from:
https://network.pivotal.io/users/dashboard/edit-profile

API token> 
Downloading VM...
Progress: |====================>| 100%
VM downloaded
Allocating 4096 MB out of 16384 MB total system memory (8294 MB free).
Importing VM...
Starting VM...
Provisioning VM...
Waiting for services to start...
9 out of 50 running
50 out of 50 running
```

This is being followed in issue #79

**Comment by sclevine** [comment]
Hi @luckyabhishek,

A number of important things happen after the services are started, so I'm not surprised that things are broken. Let's address issue #79 first, and you can re-open this once you have a working VM.

-Stephen
