### ISSUE TITLE
Cant start pcf dev

### ISSUE THREAD

**Issue by MohanBunny** [vmware-archive/pcfdev#95]
Hi,
Iam new to pcf.
Today i have installed pcf dev 7 as well as virtual box 5.0 in centos7.
Successfully done with installation, but i got an issue,
i.e
 cf dev start command error
output:
        Please retrieve your Pivotal Network API from:
https://network.pivotal.io/users/dashboard/edit-profile

API token> 
FAILED
Error: failed to reach Pivotal Network: Post https://network.pivotal.io/api/v2/products/pcfdev/releases/1622/product_files/5095/download: read tcp ip:46077->52.1.70.252:443: read: connection reset by peer
i have regenerated the token and retried it.but didn't worked.
I think when we use this cf dev start command it creates a vm.
Can i know that how much disk space it requires for vm creation.
B'coz when i checked pcf dev vm is not created.

any help

any help.

**Comment by sclevine** [comment]
Hi @MohanBunny,

PCF Dev does not create a VM until it successfully downloads an OVA from PivNet. The error you're receiving seems to indicate that the cf CLI plugin cannot talk to PivNet. Do you require an HTTP proxy to browse the web? Are you able to `curl https://network.pivotal.io` from the same terminal successfully?

-Stephen

**Comment by MohanBunny** [comment]
Thanks for your reply.
I am using proxy as well as no proxy.
I tried the command that you have provided on both types.
And I am unable to run the command.
Output as
               curl: (35) TCP connection reset by peer.
And may I know what is OVA, as I said that I'm new to pcf so.

-Mohan.V

**Comment by MohanBunny** [comment]
And I did r&d on it, after that i found another command i.e curl -v
i tried to run the command, it given me error as
- About to connect() to network.pivotal.io port 443 (#0)
-   Trying 52.1.70.252...
- Connected to network.pivotal.io (52.1.70.252) port 443 (#0)
- Initializing NSS with certpath: sql:/etc/pki/nssdb
-   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
- NSS error -5961 (PR_CONNECT_RESET_ERROR)
- TCP connection reset by peer
- Closing connection 0
  curl: (35) TCP connection reset by peer

I think there is problem with host if I am not wrong.

-Mohan.V

**Comment by sclevine** [comment]
It seems to me like you don't have `https_proxy` set properly. Do you have that environment variable set to a valid proxy server and exported?

**Comment by MohanBunny** [comment]
Hi @sclevine 
Thanks for your reply.
We are using automatic proxy configuration URL.
I believe that the environment variable set to a valid proxy server and exported.
But still facing the same issue.

**Comment by sclevine** [comment]
If both the PCF Dev CLI plugin and `curl` cannot connect to `https://network.pivotal.io`, it is likely that you don't have `https_proxy` set to a usable proxy server. Can you `curl https://example.com` successfully?

**Comment by MohanBunny** [comment]
thanks for U'r guide @sclevine.

Yes it is b'cause of not given full access of internet(firewall blocking) as per company policy.
Will try to get the permissions and do the same.

thank you.
Mohan.V

**Comment by sclevine** [comment]
That makes sense. Please re-open this issue if you still have trouble downloading the OVA after adjusting your company firewall.
