### ISSUE TITLE
Is their a way to customize PCFDEV to run on machine with 4GB ram.

### ISSUE THREAD

**Issue by amitshukla30** [vmware-archive/pcfdev#96]
Hi,

Minimum requirement of RAM for PCFDEV is 3072Mb and most of the dev machines will not have so much of free space of RAM. 

Is their some way to reduce the number of features of PCF Dev Cloud Foundary so that It can run on a Laptop with 4 GB of RAM?

I would like to customize it with reduced features like no redis service, light mysql servce reduced default memory allocation for VM and reduced size of droplets and number of programs it runs(55) at the beginning.

It wont be called cloud foundry in that case because of reduced fetaure but atleast developer can run along with other enterprise applications and build a prototype to showcase to the client.

Regards
Amit Shukla

**Comment by sclevine** [comment]
Hi Amit,

The next release of PCF Dev will allow you to disable Redis and RabbitMQ, which reduces the base system memory usage down to around 2.2GB. This doesn't include user apps, so we don't plan to reduce the minimum memory requirement of 3GB.

What other CF components would you leave out to reduce memory usage? The two largest non-essential components for running containers (Cloud Controller and UAA) are necessary to use the cf CLI. MySQL is necessary to provide a DB for Cloud Controller and UAA. We've already tuned the UAA JVM to be as small as possible.

Thanks,
Stephen

**Comment by amitshukla30** [comment]
Thanks for the info Stephen.
