### ISSUE TITLE
cf login FAILED

### ISSUE THREAD

**Issue by ShwetaD1** [vmware-archive/pcfdev#98]
Hi,
I am new to PCF.
I have installed **pcf dev as well as virtualbox and cf cli** in my local machine and i successfully did it.
When i am trying to login, getting failed error.
that is 
     $ **cf login -a api.local.pcfdev.io --skip-ssl-validation
API endpoint: api.local.pcfdev.io
FAILED
Server error, status code: 502, error code: 0, message:** 
![screenshot from 2016-07-08 14-28-06](https://cloud.githubusercontent.com/assets/20353637/16682947/c7b0d0ba-451a-11e6-840a-d566984bc2de.png)

Any Help

-Shweta

**Comment by sclevine** [comment]
Hi @ShwetaD1,

You cannot login because your VM did not start successfully. Are you running PCF Dev 0.17.0? (0.17.0 should have 50 services, not 49.)

-Stephen

**Comment by ShwetaD1** [comment]
Hi Stephen,

Thanks for the reply.
But I am running PCF Dev 0.16.0.

-Shweta

**Comment by sclevine** [comment]
Can you upgrade to 0.17.0 and see if the VM starts successfully?

**Comment by ShwetaD1** [comment]
Hi @sclevine,
thanks for the reply.
May I know why it is not working on 0.16.0 .
-Shweta

**Comment by sclevine** [comment]
There are a number of reasons why you might receive that error. The 0.17.0 release provides the same PCF components as 0.16.0 and includes bug fixes that might fix your issue.

**Comment by sclevine** [comment]
Closing. Feel free to re-open if you experience the same issue on 0.17.0 (or newer).

**Comment by parthasarathi204** [comment]
same issue .
cf dev start
Using existing image.
Starting VM...
Provisioning VM...
Waiting for services to start...
8 out of 56 running
8 out of 56 running
8 out of 56 running
8 out of 56 running
39 out of 56 running
56 out of 56 running
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
is now running.
To begin using PCF Dev, please run:
   cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass
partha@partha-Latitude-E7440:[~/Downloads/dhiraj/pcfdev] $ cf login -a https://api.local.pcfdev.io --skip-ssl-validation
API endpoint: https://api.local.pcfdev.io
FAILED
Server error, status code: 502, error code: 0, message: 
partha@partha-Latitude-E7440:[~/Downloads/dhiraj/pcfdev] $ cf login -a https://api.local.pcfdev.io --skip-ssl-validation
API endpoint: https://api.local.pcfdev.io
FAILED
Server error, status code: 502, error code: 0, message: 
partha@partha-Latitude-E7440:[~/Downloads/dhiraj/pcfdev] $ cf login -a https://api.local.pcfdev.io 
API endpoint: https://api.local.pcfdev.io

**Comment by parthasarathi204** [comment]
sudo /var/vcap/bosh/bin/monit summary
The Monit daemon 5.2.5 uptime: 19m 

Process 'pcfdev-api'                running
Process 'pcfdev-nginx'              running
Process 'uaa'                       running
Process 'tps_listener'              running
Process 'tps_watcher'               running
Process 'tcp_router'                running
Process 'tcp_emitter'               running
Process 'syslog_drain_binder'       running
Process 'syslog-configurator'       running
Process 'stager'                    running
Process 'ssh_proxy'                 running
Process 'routing-api'               running
Process 'route_registrar'           running
Process 'route_emitter'             running
Process 'rep'                       running
Process 'rabbitmq-server'           running
Process 'rabbitmq-broker'           running
Process 'rabbitmq-broker-route-registrar' running
Process 'rabbitmq-management-route-registrar' running
Process 'nsync_listener'            running
Process 'nsync_bulker'              running
Process 'nats'                      running
Process 'mariadb_ctrl'              running
Process 'galera-healthcheck'        running
Process 'gra-log-purger-executable' running
Process 'cluster_health_logger'     running
Process 'metron_agent'              running
Process 'loggregator_trafficcontroller' running
Process 'localdriver'               running
Process 'localbroker'               running
Process 'gorouter'                  running
Process 'garden'                    running
Process 'file_server'               running
Process 'etcd'                      running
Process 'etcd_consistency_checker'  running
Process 'doppler'                   running
Process 'consul_agent'              running
Process 'cloud_controller_worker_1' running
Process 'cloud_controller_ng'       running
Process 'cloud_controller_worker_local_1' running
Process 'cloud_controller_worker_local_2' running
Process 'nginx_cc'                  running
Process 'cloud_controller_clock'    running
Process 'process-watcher'           running
Process 'process-destroyer'         running
Process 'cf-redis-broker'           running
Process 'broker-nginx'              running
Process 'cf-mysql-broker'           running
Process 'cf-mysql-route-registrar'  running
Process 'quota-enforcer'            running
Process 'cc_uploader'               running
Process 'blobstore_nginx'           running
Process 'blobstore_url_signer'      running
Process 'bbs'                       running
Process 'auctioneer'                running
System 'system_localhost'           running

**Comment by aemengo** [comment]
Inside of the PCF Dev VM, could you run 'tail /var/pcfdev/provision.log' and submit the output?

**Comment by sclevine** [comment]
Are you behind a corporate HTTP proxy? Have you followed these steps?
https://docs.pivotal.io/pcf-dev/proxy.html
